export const awsAdvancedQuestions = [
  // ─── EASY THEORY ───────────────────────────────────────────────────────────
  {
    topicSlug: \'aws-advanced\',
    difficulty: \'EASY\' as const,
    type: \'THEORY\' as const,
    question: \'What is the primary difference between RDS Multi-AZ and Read Replicas?',
    options: [
      \'Multi-AZ provides synchronous replication for high availability; Read Replicas provide asynchronous replication for read scalability\',
      \'Multi-AZ is cheaper than Read Replicas\',
      \'Read Replicas provide automatic failover; Multi-AZ does not\',
      \'Multi-AZ can be in different regions; Read Replicas cannot\',
    ],
    correctIndex: 0,
    explanation: \'RDS Multi-AZ deployments provide high availability and durability through synchronous replication to a standby instance in a different Availability Zone. In case of infrastructure failure, RDS automatically fails over to the standby. This happens transparently with no manual intervention, typically within 60-120 seconds. Read Replicas, on the other hand, use asynchronous replication and are designed to offload read traffic from the primary database. They can be in the same region or cross-region. Read Replicas do not provide automatic failover — they are primarily for scaling read operations. Multi-AZ costs roughly double because you pay for the standby instance, but it is essential for production workloads requiring high availability. Read Replicas can be promoted to standalone databases manually if needed.',
    tags: [\'aws\', \'rds\', \'multi-az\', \'read-replica\', \'high-availability\'],
  },
  {
    topicSlug: \'aws-advanced\',
    difficulty: \'EASY\' as const,
    type: \'THEORY\' as const,
    question: \'What triggers an AWS Lambda function execution?',
    options: [
      \'Event sources such as S3, API Gateway, DynamoDB Streams, SNS, SQS, EventBridge, or direct invocation\',
      \'Only HTTP requests via API Gateway\',
      \'Only scheduled CloudWatch Events\',
      \'Lambda functions run continuously like EC2 instances\',
    ],
    correctIndex: 0,
    explanation: \'AWS Lambda is an event-driven compute service that executes code in response to triggers from various AWS services. Common event sources include: S3 (object creation/deletion), API Gateway (HTTP requests), DynamoDB Streams (table changes), SNS topics, SQS queues, EventBridge (scheduled or custom events), Kinesis streams, CloudWatch Logs, Cognito, IoT, Step Functions, and direct SDK/CLI invocation. Lambda functions are stateless and ephemeral — they do not run continuously. Each invocation starts a new execution environment (cold start) or reuses a warm one. The function runs only for the duration needed to process the event, and you pay only for compute time consumed. This makes Lambda ideal for sporadic workloads, microservices, and event-driven architectures. Understanding event source mappings is critical for serverless architecture design.',
    tags: [\'aws\', \'lambda\', \'serverless\', \'event-driven\', \'triggers\'],
  },
  {
    topicSlug: \'aws-advanced\',
    difficulty: \'EASY\' as const,
    type: \'THEORY\' as const,
    question: \'What is the purpose of Amazon CloudFront and how does it improve application performance?',
    options: [
      \'CloudFront is a CDN that caches content at edge locations worldwide, reducing latency for end users\',
      \'CloudFront is a load balancer for EC2 instances\',
      \'CloudFront is a DNS service like Route 53\',
      \'CloudFront is a database caching layer\',
    ],
    correctIndex: 0,
    explanation: \'Amazon CloudFront is a Content Delivery Network (CDN) with over 400 edge locations globally. It caches copies of your content (static files, videos, API responses) at these edge locations, bringing data closer to end users geographically. When a user requests content, CloudFront routes the request to the nearest edge location. If the content is cached (cache hit), it is served immediately with low latency. If not (cache miss), CloudFront fetches it from the origin (S3, ELB, or custom HTTP server), caches it, and serves it. CloudFront significantly reduces latency, decreases load on your origin servers, and provides DDoS protection via AWS Shield. It also supports SSL/TLS encryption, custom domain names, and Lambda@Edge for edge computing. Typical use cases: serving static website assets, streaming video content, accelerating APIs.',
    tags: [\'aws\', \'cloudfront\', \'cdn\', \'edge\', \'performance\'],
  },
  {
    topicSlug: \'aws-advanced\',
    difficulty: \'EASY\' as const,
    type: \'THEORY\' as const,
    question: \'What is Amazon EKS and why would you choose it over self-managed Kubernetes on EC2?',
    options: [
      \'EKS is a managed Kubernetes service; AWS handles control plane upgrades, patching, and high availability\',
      \'EKS is cheaper than self-managed Kubernetes\',
      \'EKS does not require any EC2 instances\',
      \'EKS only works with AWS services and cannot run standard Kubernetes workloads\',
    ],
    correctIndex: 0,
    explanation: \'Amazon Elastic Kubernetes Service (EKS) is a fully managed Kubernetes service where AWS operates and maintains the Kubernetes control plane (API server, etcd, scheduler, controller manager). You deploy worker nodes (EC2 instances or Fargate pods) but AWS handles control plane scaling, patching, and multi-AZ redundancy. Benefits: reduced operational overhead, automatic Kubernetes version upgrades, integrated AWS security (IAM for RBAC), deep integration with VPC networking, ELB, CloudWatch, and IAM Roles for Service Accounts (IRSA). EKS runs upstream Kubernetes, so all standard Kubernetes manifests, Helm charts, and tooling work without modification. The trade-off: EKS control plane costs $0.10/hour per cluster (~$73/month) regardless of usage. For production workloads, EKS is preferred because self-managing Kubernetes control planes is complex and error-prone.',
    tags: [\'aws\', \'eks\', \'kubernetes\', \'managed-service\', \'containers\'],
  },
  {
    topicSlug: \'aws-advanced\',
    difficulty: \'EASY\' as const,
    type: \'SCENARIO\' as const,
    question: \'Your web application experiences a sudden traffic spike. The RDS database becomes a bottleneck with read queries taking over 10 seconds. What is the quickest solution to offload read traffic?',
    options: [
      \'Create an RDS Read Replica and direct read traffic to it via a read endpoint\',
      \'Upgrade the RDS instance to a larger instance type\',
      \'Enable RDS Multi-AZ for better performance\',
      \'Switch to DynamoDB immediately\',
    ],
    correctIndex: 0,
    explanation: \'Creating an RDS Read Replica is the fastest and most cost-effective way to scale read-heavy workloads. A Read Replica is an asynchronous copy of the database that handles SELECT queries, offloading traffic from the primary instance. You can create a replica in minutes and immediately route read traffic to it using its endpoint. Your application must be configured to use different endpoints for reads and writes (this is often done via database connection pooling or a proxy like ProxySQL). Upgrading the instance type (B) requires downtime and may not fully resolve the issue if reads overwhelm a single instance. Multi-AZ (C) does not improve performance — it is for high availability only, and the standby is not accessible for reads. Migrating to DynamoDB (D) is a massive architectural change requiring code rewrites. Read Replicas can also be used for disaster recovery, analytics workloads, and cross-region replication.',
    tags: [\'aws\', \'rds\', \'read-replica\', \'scalability\', \'performance\'],
  },
  {
    topicSlug: \'aws-advanced\',
    difficulty: \'EASY\' as const,
    type: \'SCENARIO\' as const,
    question: \'Your Lambda function is timing out when processing large S3 files. The default timeout is 3 seconds. What should you do?',
    options: [
      \'Increase the Lambda timeout configuration (max 15 minutes) and allocate more memory if needed\',
      \'Lambda cannot process large files; use EC2 instead\',
      \'Split the S3 file into smaller chunks before uploading\',
      \'Lambda automatically scales timeout based on file size\',
    ],
    correctIndex: 0,
    explanation: \'AWS Lambda allows you to configure the timeout from 1 second to 15 minutes (900 seconds). If your function is timing out, the first step is to increase the timeout value in the Lambda configuration. Additionally, Lambda memory allocation affects CPU performance — Lambda allocates proportional CPU power based on memory. If you allocate 128 MB, you get minimal CPU; if you allocate 1792 MB (the maximum), you get approximately 1 full vCPU. For CPU-intensive tasks like file parsing or image processing, increasing memory improves execution speed. If processing still exceeds 15 minutes, you should redesign using Step Functions to orchestrate multiple Lambda invocations, or use ECS/Fargate for long-running tasks. Lambda is not inherently unsuitable for large files (B is wrong) — it depends on the processing complexity. Splitting files (C) may help but is not always necessary. Lambda does not auto-adjust timeout (D).',
    tags: [\'aws\', \'lambda\', \'timeout\', \'performance\', \'troubleshooting\'],
  },
  {
    topicSlug: \'aws-advanced\',
    difficulty: \'EASY\' as const,
    type: \'SCENARIO\' as const,
    question: \'You need to serve a static website hosted on S3 with a custom domain and HTTPS. What AWS services do you need?',
    options: [
      \'S3 for hosting, CloudFront for CDN and HTTPS, Route 53 for DNS, ACM for SSL certificate\',
      \'S3 and Route 53 only (S3 supports HTTPS natively)',
      \'EC2 with Nginx, Route 53, and ACM\',
      \'S3, API Gateway, and ACM\',
    ],
    correctIndex: 0,
    explanation: \'To serve a static website with a custom domain and HTTPS, you need: (1) S3 bucket configured for static website hosting (contains HTML/CSS/JS files), (2) CloudFront distribution pointing to the S3 bucket as the origin (CloudFront provides HTTPS and global edge caching), (3) AWS Certificate Manager (ACM) certificate for your domain (free SSL/TLS certificate, must be in us-east-1 region for CloudFront), (4) Route 53 hosted zone with an A record (alias) pointing to the CloudFront distribution. S3 alone does not support custom domains with HTTPS (B is incorrect) — S3 website endpoints do not support HTTPS. EC2 with Nginx (C) is overkill and introduces unnecessary operational complexity. API Gateway (D) is for APIs, not static websites. This architecture is extremely common for modern web applications and is a standard interview question.',
    tags: [\'aws\', \'s3\', \'cloudfront\', \'route53\', \'acm\', \'static-website\'],
  },

  // ─── MEDIUM THEORY ─────────────────────────────────────────────────────────
  {
    topicSlug: \'aws-advanced\',
    difficulty: \'MEDIUM\' as const,
    type: \'THEORY\' as const,
    question: \'What are Lambda cold starts and how can you minimize their impact?',
    options: [
      \'Cold starts occur when Lambda initializes a new execution environment; mitigate with Provisioned Concurrency, smaller deployment packages, and keeping functions warm\',
      \'Cold starts are network delays; use VPC endpoints to fix them\',
      \'Cold starts happen only with interpreted languages like Python; use compiled languages like Go\',
      \'Cold starts are unavoidable and cannot be mitigated\',
    ],
    correctIndex: 0,
    explanation: \'A cold start occurs when AWS Lambda must initialize a new execution environment because no warm environment is available. This involves: (1) downloading your deployment package, (2) starting a runtime (Node.js, Python, etc.), (3) executing initialization code outside the handler (imports, connections). Cold starts add 100ms-3s latency depending on package size, runtime, and whether the function is in a VPC. Mitigation strategies: (1) Provisioned Concurrency — keeps N execution environments initialized and warm, eliminating cold starts for those invocations (costs ~$0.015/hour per provisioned instance), (2) reduce deployment package size (tree-shake dependencies, use Webpack/esbuild), (3) avoid VPCs unless necessary (VPC ENI setup adds latency), (4) use lighter runtimes (Node.js/Python are faster to start than Java/.NET), (5) keep functions "warm" with scheduled pings (not recommended by AWS anymore). Compiled languages (C) do not eliminate cold starts, though they may reduce initialization time slightly. Cold starts are inherent to serverless but can be managed.',
    tags: [\'aws\', \'lambda\', \'cold-start\', \'performance\', \'provisioned-concurrency\'],
  },
  {
    topicSlug: \'aws-advanced\',
    difficulty: \'MEDIUM\' as const,
    type: \'THEORY\' as const,
    question: \'What is Amazon Aurora Serverless and when should you use it over standard Aurora?',
    options: [
      \'Aurora Serverless auto-scales capacity based on demand and pauses during inactivity; ideal for intermittent or unpredictable workloads\',
      \'Aurora Serverless is cheaper than standard Aurora for all workloads\',
      \'Aurora Serverless provides higher performance than standard Aurora\',
      \'Aurora Serverless does not require a VPC\',
    ],
    correctIndex: 0,
    explanation: \'Amazon Aurora Serverless is an on-demand, auto-scaling configuration for Aurora (PostgreSQL or MySQL). Instead of provisioning fixed instance sizes (db.r5.large, etc.), you define capacity in Aurora Capacity Units (ACUs). Aurora automatically scales compute and memory from min to max ACU settings based on load. When there is no activity, Aurora can pause the database entirely, and you pay only for storage. This is ideal for: (1) development/test databases (pause during nights/weekends), (2) infrequent or unpredictable workloads (e.g., internal tools used sporadically), (3) applications with variable traffic. However, Aurora Serverless has limitations: higher latency during scaling events (5-15 seconds), no read replicas, no cross-region replication, not suitable for consistently high-traffic production workloads. For steady, predictable production workloads, standard Aurora with fixed instance sizes is more cost-effective and performant. Aurora Serverless v2 (released 2022) improves scaling speed but costs more per ACU.',
    tags: [\'aws\', \'aurora\', \'serverless\', \'auto-scaling\', \'rds\'],
  },
  {
    topicSlug: \'aws-advanced\',
    difficulty: \'MEDIUM\' as const,
    type: \'THEORY\' as const,
    question: \'How do CloudFront signed URLs differ from signed cookies, and when would you use each?',
    options: [
      \'Signed URLs restrict access to individual files; signed cookies restrict access to multiple files or patterns (e.g., all files in /premium/)',
      \'Signed URLs are for public content; signed cookies are for private content\',
      \'Signed URLs use S3 pre-signed URLs; signed cookies use CloudFront\',
      \'Signed URLs expire after 1 hour; signed cookies never expire\',
    ],
    correctIndex: 0,
    explanation: \'CloudFront signed URLs and signed cookies both provide temporary, secure access to private content served via CloudFront. Signed URLs embed access permissions and expiration directly in the URL query string (e.g., ?Expires=...&Signature=...). Use signed URLs when: (1) you want to restrict access to a single file (e.g., download a paid PDF), (2) users cannot handle cookies (RTMP streaming), (3) the URL is embedded in an email or third-party app. Signed cookies store access permissions in HTTP cookies set by your application. Use signed cookies when: (1) you want to provide access to multiple files (e.g., all videos in a premium course directory), (2) you want to avoid changing URLs, (3) the application manages sessions (e.g., after user login, set a signed cookie for /premium/*). Both require a trusted signer (CloudFront key pair or AWS Secrets Manager). Signed URLs and cookies are not related to S3 pre-signed URLs (C is wrong) — those are generated by S3 directly and bypass CloudFront.',
    tags: [\'aws\', \'cloudfront\', \'signed-urls\', \'signed-cookies\', \'security\'],
  },
  {
    topicSlug: \'aws-advanced\',
    difficulty: \'MEDIUM\' as const,
    type: \'THEORY\' as const,
    question: \'What is the purpose of RDS Proxy and how does it improve database connections?',
    options: [
      \'RDS Proxy pools and reuses database connections, reducing connection overhead and improving scalability for serverless architectures\',
      \'RDS Proxy provides a public endpoint for private RDS databases\',
      \'RDS Proxy caches query results to improve performance\',
      \'RDS Proxy automatically backs up the database\',
    ],
    correctIndex: 0,
    explanation: \'Amazon RDS Proxy is a fully managed database proxy that sits between your application and RDS/Aurora database. It maintains a pool of established database connections and multiplexes application connections to this pool. Benefits: (1) reduces database connection overhead — Lambda functions and other serverless apps create thousands of short-lived connections, overwhelming the database; RDS Proxy reuses connections efficiently, (2) improves failover times — during RDS Multi-AZ failover, RDS Proxy preserves connections and automatically routes traffic to the new primary, reducing failover from 60s to 20s, (3) enforces IAM authentication for database access without embedding credentials. RDS Proxy does NOT provide public endpoints (B) — you still need secure networking (VPC, security groups). It does NOT cache query results (C) — for that, use ElastiCache. It does NOT handle backups (D). RDS Proxy is particularly valuable for Lambda-to-RDS architectures where connection storms can exhaust database connections. It costs ~$0.015/hour per vCPU plus data transfer.',
    tags: [\'aws\', \'rds-proxy\', \'lambda\', \'connection-pooling\', \'database\'],
  },
  {
    topicSlug: \'aws-advanced\',
    difficulty: \'MEDIUM\' as const,
    type: \'SCENARIO\' as const,
    question: \'Your EKS cluster node group needs to scale based on pending pods that cannot be scheduled due to insufficient resources. What AWS feature should you use?',
    options: [
      \'Cluster Autoscaler, which watches for unschedulable pods and automatically scales the node group\',
      \'Horizontal Pod Autoscaler (HPA), which scales pods based on CPU/memory\',
      \'Auto Scaling Groups with target tracking based on cluster CPU\',
      \'Karpenter, which provisions nodes dynamically\',
    ],
    correctIndex: 0,
    explanation: \'The Cluster Autoscaler is a Kubernetes component that automatically adjusts the number of nodes in an EKS node group (backed by an EC2 Auto Scaling Group) based on pod scheduling needs. It watches for: (1) pods that cannot be scheduled due to insufficient resources (CPU/memory/GPU), (2) nodes that are underutilized and can be scaled down. When unschedulable pods are detected, Cluster Autoscaler increases the desired capacity of the ASG. When nodes are idle, it scales down. Cluster Autoscaler respects pod disruption budgets and node selectors. HPA (B) scales the number of pod replicas, not nodes. ASG target tracking (C) scales based on metrics like CPU but is not pod-aware. Karpenter (D) is an alternative to Cluster Autoscaler — it is a newer AWS-native autoscaler that provisions nodes more intelligently and efficiently, bypassing ASGs entirely. Karpenter is recommended for modern EKS setups but requires explicit adoption. Cluster Autoscaler is the default solution.',
    tags: [\'aws\', \'eks\', \'kubernetes\', \'cluster-autoscaler\', \'auto-scaling\'],
  },
  {
    topicSlug: \'aws-advanced\',
    difficulty: \'MEDIUM\' as const,
    type: \'SCENARIO\' as const,
    question: \'Your Lambda function accesses RDS in a private subnet. After deployment, the function times out when trying to connect to the database. What is likely wrong?',
    options: [
      \'Lambda in a VPC requires a NAT Gateway or VPC endpoints for AWS service calls, and the security group must allow outbound traffic to RDS\',
      \'Lambda cannot access RDS in a private subnet\',
      \'You must enable Lambda Enhanced Networking\',
      \'RDS must be in a public subnet for Lambda to access it\',
    ],
    correctIndex: 0,
    explanation: \'When a Lambda function is configured to run inside a VPC (to access private resources like RDS), it loses direct internet access. If the Lambda function needs to call AWS services (e.g., Secrets Manager to get DB credentials, or CloudWatch for logs), it must either: (1) have a route to a NAT Gateway in a public subnet, or (2) use VPC endpoints for AWS services (recommended for cost and performance). Additionally, the Lambda function security group must allow outbound traffic to the RDS security group on the database port (e.g., 3306 for MySQL, 5432 for PostgreSQL), and the RDS security group must allow inbound traffic from the Lambda security group. Common mistake: Lambda function is attached to a private subnet with no NAT Gateway, so it cannot initialize (cannot reach S3 for code download, cannot send logs to CloudWatch). Lambda CAN access RDS in private subnets (B is wrong). Enhanced Networking (C) is for EC2 high-throughput workloads. RDS should remain private (D is a security anti-pattern).',
    tags: [\'aws\', \'lambda\', \'vpc\', \'rds\', \'networking\', \'troubleshooting\'],
  },
  {
    topicSlug: \'aws-advanced\',
    difficulty: \'MEDIUM\' as const,
    type: \'SCENARIO\' as const,
    question: \'You want to deploy a web application on EKS with a public-facing load balancer. Which Kubernetes Service type and AWS integration should you use?',
    options: [
      \'Service type LoadBalancer with AWS Load Balancer Controller to provision an Application Load Balancer (ALB) or Network Load Balancer (NLB)',
      \'Service type NodePort and expose nodes directly to the internet\',
      \'Service type ClusterIP and manually configure Route 53\',
      \'Use Ingress only without any Service\',
    ],
    correctIndex: 0,
    explanation: \'For public-facing applications on EKS, you should use Kubernetes Service type LoadBalancer, which integrates with the AWS Load Balancer Controller (formerly ALB Ingress Controller). When you create a Service with type: LoadBalancer, the controller automatically provisions an AWS NLB (Network Load Balancer) or ALB (Application Load Balancer) depending on annotations. For HTTP/HTTPS traffic, use an Ingress resource with the ALB controller — it creates an ALB with target groups pointing to your pods. The controller manages ALB lifecycle, security groups, and listener rules. NodePort (B) exposes services on a static port on every node, requiring you to manually manage load balancing and security — not recommended for production. ClusterIP (C) is internal-only; external traffic cannot reach it without additional networking. Ingress alone (D) still requires a Service backend. Proper EKS load balancing architecture: Ingress (ALB) → Service (ClusterIP or NodePort) → Pods.',
    tags: [\'aws\', \'eks\', \'kubernetes\', \'load-balancer\', \'alb\', \'ingress\'],
  },

  // ─── HARD THEORY ───────────────────────────────────────────────────────────
  {
    topicSlug: \'aws-advanced\',
    difficulty: \'HARD\' as const,
    type: \'THEORY\' as const,
    question: \'What is Lambda@Edge and how does it differ from CloudFront Functions?',
    options: [
      \'Lambda@Edge runs Node.js/Python at edge locations with full Lambda capabilities; CloudFront Functions runs lightweight JavaScript with sub-millisecond latency but limited functionality\',
      \'Lambda@Edge is for S3 origins; CloudFront Functions is for custom origins\',
      \'Lambda@Edge runs on the origin server; CloudFront Functions runs at edge locations\',
      \'Lambda@Edge is deprecated; use CloudFront Functions for all edge computing\',
    ],
    correctIndex: 0,
    explanation: \'Both Lambda@Edge and CloudFront Functions enable edge computing — running code at CloudFront edge locations before requests reach the origin. Key differences: (1) Runtime: Lambda@Edge supports Node.js and Python with full AWS SDK access; CloudFront Functions only supports a restricted JavaScript subset. (2) Execution time: Lambda@Edge allows up to 5 seconds for viewer/origin requests; CloudFront Functions executes in under 1ms. (3) Use cases: Lambda@Edge is for complex logic (A/B testing with DynamoDB lookups, image resizing, auth token validation); CloudFront Functions is for simple, high-scale transformations (URL rewrites, header manipulation, request normalization). (4) Triggering events: Lambda@Edge supports viewer request/response + origin request/response; CloudFront Functions only supports viewer request/response. (5) Cost: CloudFront Functions is 1/6th the price. Neither is deprecated (D). Choose based on complexity: simple transformations → CloudFront Functions; complex logic or AWS service integration → Lambda@Edge.',
    tags: [\'aws\', \'lambda-edge\', \'cloudfront-functions\', \'edge-computing\', \'cdn\'],
  },
  {
    topicSlug: \'aws-advanced\',
    difficulty: \'HARD\' as const,
    type: \'THEORY\' as const,
    question: \'How does Aurora Global Database provide cross-region disaster recovery, and what are the RPO/RTO characteristics?',
    options: [
      \'Aurora Global Database replicates data asynchronously across regions with typical replication lag <1 second; RPO ~1 second, RTO <1 minute via manual promotion\',
      \'Aurora Global Database uses synchronous replication; RPO and RTO are both zero\',
      \'Aurora Global Database requires manual backup and restore; RPO and RTO depend on backup schedule\',
      \'Aurora Global Database is for read scaling only and does not support failover\',
    ],
    correctIndex: 0,
    explanation: \'Aurora Global Database spans multiple AWS regions with one primary region (read-write) and up to five secondary regions (read-only). Physical replication occurs at the storage layer with typical lag under 1 second. In a disaster scenario where the primary region fails, you promote a secondary region to become the new primary. RPO (Recovery Point Objective) is typically ~1 second because replication lag is minimal. RTO (Recovery Time Objective) is under 1 minute for promotion, though application failover (DNS updates, connection rerouting) adds overhead. Synchronous cross-region replication (B) is impossible due to physics (speed of light latency between regions). Aurora Global does NOT require manual backup/restore (C) — it is real-time replication. It CAN be used for disaster recovery via promotion (D is incorrect) — secondary regions are not just for read scaling. Aurora Global is expensive (~2-3x the cost of single-region Aurora) but provides the best cross-region DR for RDS. Use cases: global applications, compliance (data residency), disaster recovery for critical databases.',
    tags: [\'aws\', \'aurora\', \'global-database\', \'disaster-recovery\', \'rpo\', \'rto\'],
  },
  {
    topicSlug: \'aws-advanced\',
    difficulty: \'HARD\' as const,
    type: \'THEORY\' as const,
    question: \'What is the purpose of EKS IAM Roles for Service Accounts (IRSA) and how does it improve security?',
    options: [
      \'IRSA maps Kubernetes service accounts to IAM roles, allowing pods to assume IAM permissions without sharing instance roles or storing credentials\',
      \'IRSA provides SSH access to EKS worker nodes\',
      \'IRSA encrypts secrets in etcd\',
      \'IRSA is a replacement for Kubernetes RBAC\',
    ],
    correctIndex: 0,
    explanation: \'EKS IAM Roles for Service Accounts (IRSA) allows fine-grained IAM permissions for individual Kubernetes pods by mapping a Kubernetes ServiceAccount to an AWS IAM role. Without IRSA, all pods on a node share the IAM role attached to the EC2 instance, violating the principle of least privilege. With IRSA: (1) each pod can have its own IAM role, (2) pods obtain temporary credentials via the IAM OpenID Connect (OIDC) provider associated with the EKS cluster, (3) credentials are automatically rotated and injected via environment variables (AWS_ROLE_ARN, AWS_WEB_IDENTITY_TOKEN_FILE). This eliminates the need to store AWS credentials in Kubernetes Secrets or ConfigMaps. Example: a pod running an application that writes to S3 can assume an IAM role with s3:PutObject permissions, while another pod on the same node has no S3 access. IRSA does NOT provide SSH access (B), does NOT encrypt secrets in etcd (C) — use KMS encryption for that, and does NOT replace RBAC (D) — IRSA handles AWS permissions, RBAC handles Kubernetes permissions.',
    tags: [\'aws\', \'eks\', \'irsa\', \'iam\', \'service-accounts\', \'security\'],
  },
  {
    topicSlug: \'aws-advanced\',
    difficulty: \'HARD\' as const,
    type: \'THEORY\' as const,
    question: \'How does RDS Performance Insights help diagnose database performance issues, and what is a "wait event"?',
    options: [
      \'Performance Insights visualizes database load and identifies bottlenecks by showing wait events — the resources (CPU, I/O, locks) that queries are waiting for\',
      \'Performance Insights automatically optimizes slow queries\',
      \'Performance Insights is a log aggregation tool for RDS error logs\',
      \'Performance Insights provides real-time alerts for high CPU usage\',
    ],
    correctIndex: 0,
    explanation: \'RDS Performance Insights is a database performance monitoring tool that shows database load over time, broken down by wait events. A "wait event" is a point in query execution where the database engine must wait for a resource before proceeding. Common wait events: (1) CPU — query execution is CPU-bound, (2) IO:XactSync — waiting for transaction commit to flush to disk (high fsync latency), (3) Lock:transactionid — waiting for a row-level lock held by another transaction, (4) IO:DataFileRead — waiting for disk reads (missing indexes or cold cache). Performance Insights displays: (1) Database Load graph (Average Active Sessions over time), (2) Top SQL queries contributing to load, (3) Wait events for each query, (4) Dimensions (users, hosts, databases). It does NOT auto-optimize queries (B) — that requires manual tuning or AWS Trusted Advisor. It does NOT aggregate logs (C). It does NOT send alerts (D) — use CloudWatch Alarms for that. Performance Insights is critical for diagnosing sudden performance degradation.',
    tags: [\'aws\', \'rds\', \'performance-insights\', \'wait-events\', \'database\', \'monitoring\'],
  },
  {
    topicSlug: \'aws-advanced\',
    difficulty: \'HARD\' as const,
    type: \'SCENARIO\' as const,
    question: \'Your EKS cluster is experiencing intermittent pod scheduling failures with "Insufficient CPU" errors, but cluster CPU utilization is only 40%. What could be the cause?',
    options: [
      \'Pods have high CPU requests (not limits), causing resource fragmentation; nodes cannot fit new pods even though overall cluster utilization is low\',
      \'EKS has a bug; restart the cluster\',
      \'Kubernetes always shows incorrect CPU metrics\',
      \'The Cluster Autoscaler is disabled\',
    ],
    correctIndex: 0,
    explanation: \'This is a classic resource fragmentation problem caused by improper pod resource requests and limits. Kubernetes schedules pods based on resource requests (not limits). If pods have very high CPU/memory requests but low actual usage, nodes may appear underutilized but cannot fit additional pods because their allocatable resources are "reserved" by existing pod requests. Example: 4-core node with 3.5 cores allocatable. If 5 pods each request 1 core but use only 0.2 cores, the node shows 60% utilization but cannot schedule a new pod requesting 1 core (only 0.5 cores remain allocatable). Solutions: (1) right-size pod requests to match actual usage (use Vertical Pod Autoscaler or metrics analysis), (2) use Cluster Autoscaler to add nodes when scheduling fails, (3) use Descheduler to rebalance pods, (4) enable bin-packing node scoring. Restarting the cluster (B) does nothing. Kubernetes metrics are accurate (C is wrong). Cluster Autoscaler (D) would help but does not address the root cause. This question tests deep understanding of Kubernetes scheduling.',
    tags: [\'aws\', \'eks\', \'kubernetes\', \'resource-requests\', \'scheduling\', \'troubleshooting\'],
  },
  {
    topicSlug: \'aws-advanced\',
    difficulty: \'HARD\' as const,
    type: \'SCENARIO\' as const,
    question: \'You are implementing a blue-green deployment for an EKS application using two separate Kubernetes Deployments. How can you switch traffic between blue and green versions with zero downtime?',
    options: [
      \'Update the Kubernetes Service selector to point to the green Deployment labels, then delete the blue Deployment after validation\',
      \'Delete the blue Deployment and immediately create the green Deployment\',
      \'Use kubectl rolling-update command\',
      \'Change the Docker image tag in the blue Deployment\',
    ],
    correctIndex: 0,
    explanation: \'Blue-green deployment in Kubernetes involves running two separate Deployments (blue and green) with different label selectors. A Kubernetes Service routes traffic based on its selector. Initial state: Service selector matches blue Deployment (app=myapp, version=blue). To switch: (1) Deploy green Deployment (app=myapp, version=green) with the new version. (2) Validate green Deployment is healthy (all pods running, health checks passing). (3) Update Service selector to match green (kubectl patch service myapp -p '{"spec":{"selector":{"version":"green"}}}') — traffic instantly switches with zero dropped connections. (4) Monitor green in production. (5) If issues occur, rollback by patching the Service selector back to blue. (6) Once confident, delete blue Deployment. This provides instant switchover and easy rollback. Deleting blue before green is ready (B) causes downtime. kubectl rolling-update (C) is deprecated and does not apply here. Changing the image tag (D) is a rolling update, not blue-green. This pattern is common in production CI/CD pipelines.',
    tags: [\'aws\', \'eks\', \'kubernetes\', \'blue-green\', \'deployment\', \'zero-downtime\'],
  },
  {
    topicSlug: \'aws-advanced\',
    difficulty: \'HARD\' as const,
    type: \'SCENARIO\' as const,
    question: \'Your Aurora database experiences a sudden 10x increase in IOPS due to a batch analytics job, causing production queries to slow down. How can you isolate the analytics workload?',
    options: [
      \'Create an Aurora Read Replica with a custom endpoint and direct analytics queries there; use query priorities or separate connections\',
      \'Increase Aurora instance size to handle both workloads\',
      \'Enable Aurora Multi-AZ to distribute load\',
      \'Use RDS Proxy to throttle the analytics queries\',
    ],
    correctIndex: 0,
    explanation: \'Aurora Read Replicas can be used for workload isolation. Create a dedicated Read Replica (or multiple replicas) and configure your analytics application to use the replica endpoint. This offloads heavy read IOPS from the primary instance, protecting production write and latency-sensitive read traffic. Aurora also supports Custom Endpoints — you can group multiple replicas into a custom endpoint and route specific workload types (e.g., analytics vs. application queries) to different endpoints. Additionally, you can use Aurora priority queues (connection-level session priorities) to deprioritize low-priority queries when the database is under load. Increasing instance size (B) is expensive and does not isolate workloads — both still compete for resources. Multi-AZ (C) is for high availability, not performance isolation. RDS Proxy (D) does connection pooling but does not throttle or prioritize queries. Proper workload isolation is a critical pattern for production databases serving multiple use cases (OLTP + OLAP).',
    tags: [\'aws\', \'aurora\', \'read-replica\', \'workload-isolation\', \'performance\', \'database\'],
  },
  {
    topicSlug: \'aws-advanced\',
    difficulty: \'HARD\' as const,
    type: \'SCENARIO\' as const,
    question: \'Your Lambda function processes images uploaded to S3. During peak hours, thousands of images are uploaded simultaneously, causing Lambda throttling errors. What is the best solution?',
    options: [
      \'Use an SQS queue between S3 and Lambda; configure S3 to send events to SQS, then trigger Lambda from SQS with controlled concurrency\',
      \'Increase Lambda reserved concurrency to handle all requests\',
      \'Use Step Functions to orchestrate Lambda invocations\',
      \'Switch to EC2 instances for image processing\',
    ],
    correctIndex: 0,
    explanation: \'Lambda concurrent execution limits are per region (default 1000, can be increased via quota request). If your S3 bucket receives 5000 uploads simultaneously and triggers Lambda directly, you will hit throttling errors (TooManyRequestsException). The best solution is to decouple S3 and Lambda using an SQS queue: (1) Configure S3 Event Notifications to send ObjectCreated events to SQS, (2) Configure Lambda to poll SQS with a controlled batch size (e.g., 10 messages per invocation) and reserved concurrency (e.g., 100 concurrent Lambda executions), (3) Lambda processes images from the queue at a controlled rate. SQS buffers bursts and Lambda processes messages as capacity allows. This prevents throttling, provides retry logic via SQS visibility timeout, and enables DLQ for failed messages. Increasing reserved concurrency (B) is not scalable and may exhaust account-level concurrency. Step Functions (C) is for orchestration, not burst buffering. Switching to EC2 (D) increases operational complexity. SQS as a buffer is a standard serverless pattern.',
    tags: [\'aws\', \'lambda\', \'sqs\', \'throttling\', \'s3\', \'event-driven\', \'queue\'],
  },
];
