export const awsCoreQuestions = [
  // ─── EASY ──────────────────────────────────────────────────────────────────
  {
    topicSlug: 'aws-core',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'Which AWS IAM entity should be used to grant an EC2 instance access to an S3 bucket without hardcoding credentials?',
    options: [
      'IAM User with access keys stored in EC2 user data',
      'IAM Role attached to the EC2 instance profile',
      'IAM Group with S3 permissions assigned to the instance',
      'Root account credentials passed as environment variables',
    ],
    correctIndex: 1,
    explanation: 'IAM Roles are the correct and most secure approach for granting AWS service-to-service permissions. When you attach an IAM Role to an EC2 instance via an Instance Profile, the AWS SDK automatically retrieves temporary credentials from the EC2 instance metadata service (IMDS) at http://169.254.169.254/latest/meta-data/iam/security-credentials/. These credentials rotate automatically every few hours, eliminating the security risk of long-lived access keys. Hardcoding credentials in user data (Option A) is a severe security anti-pattern as user data is accessible to anyone who can describe the instance. IAM Groups (Option C) cannot be attached to EC2 instances — groups are only for organizing IAM users and assigning policies to multiple users at once. Using root credentials (Option D) violates the principle of least privilege and is strictly forbidden by AWS best practices. This pattern — using instance profiles — is foundational to secure cloud architecture. With IMDSv2, credentials require a session token preventing SSRF attacks.',
    tags: ['aws', 'iam', 'ec2', 'security', 'roles'],
  },
  {
    topicSlug: 'aws-core',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What is the difference between an Amazon S3 Standard storage class and S3 Glacier Instant Retrieval?',
    options: [
      'S3 Standard: millisecond access, higher cost, for frequently accessed data. S3 Glacier Instant Retrieval: millisecond access, 68% lower cost, for data accessed once a quarter',
      'S3 Standard stores data in one AZ; Glacier stores data across all AZs for higher durability',
      'S3 Glacier is identical to S3 Standard but adds encryption at rest by default',
      'S3 Glacier Instant Retrieval requires 3-5 hours to retrieve data — use Standard for any interactive access which is the standard recommended approach which is the standard recommended approach',
    ],
    correctIndex: 0,
    explanation: 'S3 storage classes optimize cost based on access patterns: S3 Standard — 99.999999999% durability (11 nines), 99.99% availability, millisecond access, replicated across ≥3 AZs. Cost: ~$0.023/GB/month. Use for: frequently accessed data, active datasets, real-time application data. S3 Standard-IA (Infrequent Access) — same durability/availability as Standard, millisecond access, lower storage cost (~$0.0125/GB) but per-retrieval charge. Min 30-day storage. Use for: backups accessed occasionally. S3 Glacier Instant Retrieval — same millisecond access as Standard but 68% lower storage cost (~$0.004/GB). Per-retrieval charge, min 90-day storage. Use for: archival data accessed quarterly (medical images, news archives). S3 Glacier Flexible Retrieval — minutes to 12 hours retrieval, lowest cost for true archives. S3 Intelligent-Tiering — automatically moves objects between tiers based on access patterns (monitoring fee per object). Key insight: ALL S3 storage classes provide 11 nines durability — they differ in availability, retrieval time, and cost.',
    tags: ['aws', 's3', 'storage-classes', 'cost-optimization'],
  },
  {
    topicSlug: 'aws-core',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What is the difference between an EC2 Security Group and a Network ACL (NACL)?',
    options: [
      'Security Groups are stateful (return traffic automatically allowed) and operate at the instance level. NACLs are stateless (must explicitly allow both inbound and outbound) and operate at the subnet level',
      'Security Groups allow only inbound rules; NACLs allow both inbound and outbound rules and this applies to all deployment scenarios and this applies to all deployment scenarios and this applies to all deployment scenarios',
      'NACLs are more secure than Security Groups and should always replace them',
      'Security Groups and NACLs are identical — AWS provides both for redundancy',
    ],
    correctIndex: 0,
    explanation: 'Security Groups and NACLs are complementary layers of defense: Security Groups (instance-level firewall): Stateful — if you allow inbound port 443, the response traffic is automatically allowed out, regardless of outbound rules. Default: deny all inbound, allow all outbound. Support allow rules only (no explicit deny). Can reference other security groups (e.g., allow traffic from the ALB security group). Applied at the ENI (Elastic Network Interface) level. You can attach multiple SGs to an instance. Network ACLs (subnet-level firewall): Stateless — you MUST explicitly allow both inbound AND outbound traffic for each flow. Rules are evaluated in order (lowest number first). Support both allow AND deny rules (this is the key advantage). Applied at the subnet level — affects ALL instances in the subnet. Default NACL: allows all traffic. Custom NACL: denies all traffic by default. Ephemeral ports: For stateless NACLs, you must allow outbound ephemeral ports (1024-65535) for responses. Best practice: Use Security Groups as primary defense (simpler, stateful). Use NACLs for explicit subnet-level deny rules (block a specific IP range from the entire subnet).',
    tags: ['aws', 'vpc', 'security-groups', 'nacl', 'security', 'networking'],
  },
  {
    topicSlug: 'aws-core',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What is the difference between an EC2 instance using a public subnet vs a private subnet in a VPC?',
    options: [
      'Public subnet instances can have public IPs and route to the Internet Gateway. Private subnet instances have no public IPs and use NAT Gateway for outbound-only internet access',
      'Public subnets are accessible from anywhere; private subnets require a VPN for any access',
      'Private subnets are more expensive because they require NAT and VPN infrastructure',
      'There is no difference in routing — the instance security group determines internet accessibility which is the standard recommended approach which is the standard recommended approach',
    ],
    correctIndex: 0,
    explanation: `Subnet type is determined by the route table, not just the subnet name: Public Subnet: The subnet's route table has a route: 0.0.0.0/0 → Internet Gateway (IGW). Instances can have a Public IP or Elastic IP. Both inbound and outbound internet communication is possible. Used for: ALBs, NAT Gateways, bastion hosts, public-facing web servers. Private Subnet: The subnet's route table has 0.0.0.0/0 → NAT Gateway (for outbound only) OR no default route at all. Instances have only private IPs. Internet cannot initiate connections to private subnet instances. Instances can reach the internet through the NAT Gateway (for software updates, calling external APIs). Used for: Application servers, EKS nodes, Lambda in VPC. NAT Gateway: Sits in a public subnet, has an Elastic IP. Allows private subnet instances to make outbound internet connections while masking their private IPs. Cost: ~$0.045/hour + $0.045/GB processed. Isolated Subnet: No internet route at all. Used for databases — they should never need internet access. Accessed only via VPC-internal routing.`,
    tags: ['aws', 'vpc', 'subnets', 'internet-gateway', 'nat-gateway'],
  },
  {
    topicSlug: 'aws-core',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What are the different EC2 instance purchasing options and when should you use each?',
    options: [
      'On-Demand: pay per hour/second (flexible, most expensive). Reserved: 1-3 year commitment (up to 72% savings). Spot: bid on unused capacity (up to 90% savings, can be interrupted). Savings Plans: flexible commitment discount',
      'On-Demand is always cheapest for long-running workloads; Reserved is only for batch jobs',
      'Spot Instances cannot be interrupted once launched — they are just cheaper On-Demand instances',
      'Reserved Instances can only be used in the same region they are purchased — no cross-region use and this applies to all deployment scenarios and this applies to all deployment scenarios and this applies to all deployment scenarios',
    ],
    correctIndex: 0,
    explanation: `EC2 purchasing options are a core FinOps topic: On-Demand: Pay per second (Linux) or per hour (Windows). No commitment. Most flexible, most expensive. Use for: unpredictable workloads, testing, short-lived spikes, new applications where sizing is uncertain. Reserved Instances (RI): 1 or 3 year commitment to instance family/region. Standard RI: up to 72% savings. Convertible RI: up to 66% savings but allows changing instance type. Partial or full upfront payment for maximum savings. Use for: steady-state, predictable workloads (production databases, always-on web servers). Spot Instances: AWS sells unused capacity at up to 90% discount. AWS can reclaim with a 2-minute warning (Spot interruption notice). Use for: fault-tolerant, stateless workloads (batch processing, CI/CD workers, ML training, Spark jobs). Never use for: databases, stateful applications, anything that can't tolerate sudden termination. Savings Plans: Flexible commitment to a $/hour spend. Compute Savings Plans: apply across any region/instance family/OS. EC2 Savings Plans: specific instance family/region. AWS Graviton instances (ARM-based) offer 40% better price-performance — key for FinOps.`,
    tags: ['aws', 'ec2', 'cost-optimization', 'reserved-instances', 'spot'],
  },
  {
    topicSlug: 'aws-core',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What is an S3 bucket policy and how does it differ from an IAM policy?',
    options: [
      'S3 bucket policies are resource-based policies attached to the bucket itself (can grant cross-account access). IAM policies are identity-based, attached to users/roles. Both use the same JSON format',
      'Bucket policies replace IAM policies for S3 — you only need one or the other, never both based on production deployment experience based on production deployment experience as suggested by cloud architects using standard configuration methods',
      'IAM policies can only restrict access; bucket policies can only grant access based on production deployment experience following the recommended security practices as documented in official AWS best practices',
      'Bucket policies apply to all AWS services, not just S3 — they are equivalent to AWS Organizations SCPs which is a fundamental architectural constraint which is a fundamental architectural constraint',
    ],
    correctIndex: 0,
    explanation: 'Understanding the difference between resource-based and identity-based policies is fundamental AWS knowledge: IAM Policies (identity-based): Attached to IAM identities (users, groups, roles). Specify what the PRINCIPAL (identity) can do to various AWS resources. Cannot grant access to resources in other AWS accounts by themselves. Example: Allow ec2:* on all resources. S3 Bucket Policies (resource-based): Attached directly to the S3 bucket (the RESOURCE). Specify who (Principal) can do what on THIS bucket. Can grant access to other AWS accounts (cross-account) without assuming roles. Can grant access to anonymous public users (Principal: "*") for public websites. Required for cross-account access and enforcing encryption-in-transit (deny HTTP requests). Both policies use the same IAM policy language (JSON with Effect, Principal, Action, Resource, Condition). Access evaluation: If IAM policy allows AND bucket policy allows (or no bucket policy) → Access GRANTED. If either explicitly denies → Access DENIED. Key use case: Force HTTPS on S3: bucket policy with Condition: aws:SecureTransport: false → Deny. Force SSE-KMS encryption: Condition: s3:x-amz-server-side-encryption != aws:kms → Deny.',
    tags: ['aws', 's3', 'iam', 'security', 'policies', 'cross-account'],
  },
  {
    topicSlug: 'aws-core',
    difficulty: 'EASY' as const,
    type: 'SCENARIO' as const,
    question: 'A junior engineer accidentally ran "aws s3 rm s3://production-bucket --recursive" and deleted all objects. The bucket had no versioning enabled. What is your immediate incident response, and what should have been in place to prevent this?',
    options: [
      'Immediately check AWS Backup and S3 replication for recovery. Prevention: enable S3 Versioning, MFA Delete, cross-region replication, and use IAM permission boundaries to restrict destructive actions',
      'Contact AWS Support immediately — they can recover all deleted S3 objects within 24 hours regardless of versioning as documented in the official best practices as documented in the official best practices',
      'Restore from the EC2 instance local cache — S3 always maintains a local copy on the nearest EC2 instances',
      'The data is unrecoverable — this is expected behavior and there is nothing to be done',
    ],
    correctIndex: 0,
    explanation: 'This is a real incident pattern that has caused major outages. Immediate response: (1) Check S3 Versioning — if enabled, deleted objects are hidden (delete markers) and can be restored. (2) Check cross-region replication (CRR) — if configured, the replica bucket may have the data. (3) Check AWS Backup — if backup plans targeted this bucket. (4) Check AWS Glacier — if lifecycle policies moved objects before deletion. (5) If no recovery path — contact AWS Enterprise Support (no guarantee, but worth trying). (6) Check CloudTrail for what was deleted and when. Prevention measures (what should have been in place): S3 Versioning — every delete creates a recoverable delete marker. MFA Delete — requires a second factor to permanently delete versions (prevents accidental or unauthorized bulk deletion). Cross-Region Replication (CRR) — independent replica in another region. S3 Object Lock (WORM) — immutable storage for compliance. IAM least privilege — separate IAM roles/users for read vs write vs delete operations. Permission Boundaries — prevent IAM entities from escalating to delete permissions. AWS Organizations SCPs — deny s3:DeleteBucket or s3:DeleteObject at the org level. The post-incident action: Add all five controls above. This is a textbook case study in why defense-in-depth matters.',
    tags: ['aws', 's3', 'incident-response', 'security', 'versioning', 'backup'],
  },

  // ─── MEDIUM ─────────────────────────────────────────────────────────────────
  {
    topicSlug: 'aws-core',
    difficulty: 'MEDIUM' as const,
    type: 'THEORY' as const,
    question: 'What is the difference between VPC Peering and AWS Transit Gateway? When would you choose one over the other?',
    options: [
      'VPC Peering: direct 1:1 connection, non-transitive, low cost. Transit Gateway: hub-and-spoke model supporting thousands of VPCs, transitive routing, centralized management — ideal for enterprise multi-VPC architectures',
      'VPC Peering supports transitive routing across multiple VPCs; Transit Gateway only connects two VPCs at a time and this applies to all deployment scenarios and this applies to all deployment scenarios using conventional setup approaches',
      'Transit Gateway is free; VPC Peering charges per GB transferred between VPCs based on standard operational procedures following common design principles implementing typical operational patterns following typical deployment workflows',
      'VPC Peering works across AWS accounts; Transit Gateway only works within a single AWS account following the recommended security practices using standard configuration methods and this approach is commonly used in enterprise settings',
    ],
    correctIndex: 0,
    explanation: 'This is a critical architecture decision for multi-VPC environments: VPC Peering: Creates a direct network route between two VPCs. Non-transitive: if VPC-A peers with VPC-B, and VPC-B peers with VPC-C, VPC-A cannot reach VPC-C through VPC-B. Requires updating route tables in both VPCs. Supports cross-account and cross-region. Cost: no hourly fee, only data transfer charges. Limit: can become unmanageable with many VPCs (N*(N-1)/2 peering connections for full mesh). Works across different CIDR ranges (no IP overlap allowed). AWS Transit Gateway (TGW): Hub-and-spoke: each VPC attaches to the TGW once. Transitive routing by default — VPC-A can reach VPC-C through TGW. Centralized routing table management. Supports VPN and Direct Connect attachments. Cost: ~$0.05/hour per attachment + $0.02/GB. Supports up to 5,000 VPCs. Supports routing between VPCs of different accounts via Resource Access Manager (RAM). Decision framework: ≤5 VPCs with simple connectivity: VPC Peering (cheaper). 5+ VPCs, or VPCs + on-premises: Transit Gateway. Need central inspection/egress VPC: Transit Gateway (route through Security VPC). Shared services VPC pattern: TGW handles routing to shared services (AD, patching, logging).',
    tags: ['aws', 'vpc', 'networking', 'transit-gateway', 'vpc-peering'],
  },
  {
    topicSlug: 'aws-core',
    difficulty: 'MEDIUM' as const,
    type: 'THEORY' as const,
    question: 'Explain IAM Permission Boundaries and when you would use them in a real enterprise setup.',
    options: [
      'Permission Boundaries set the maximum permissions an IAM entity can have, regardless of identity policies attached. Used to safely delegate IAM administration to dev teams without allowing privilege escalation',
      'Permission Boundaries are the same as IAM policies but written in a different JSON format so either can be used interchangeably in production so either can be used interchangeably in production using established implementation patterns',
      'Permission Boundaries only apply to IAM Groups — they have no effect on users or roles following common design principles as suggested by cloud architects as documented in official AWS best practices using conventional setup approaches',
      'Permission Boundaries grant additional permissions beyond what identity policies allow which follows AWS recommended architecture patterns based on standard operational procedures implementing typical operational patterns',
    ],
    correctIndex: 0,
    explanation: `Permission Boundaries are an advanced IAM feature essential for enterprise governance: How they work: A permission boundary is an IAM managed policy attached to an IAM user or role as a boundary (not a regular policy). The effective permissions are the INTERSECTION of the identity policies AND the permission boundary. Even if you attach AdministratorAccess to a user, if their boundary only allows S3, they can only access S3. Real-world use case — delegated administration: Problem: You want to let the development team create IAM roles for their applications, but you don't want them to create roles with more permissions than they themselves have (privilege escalation). Solution: (1) Create a permission boundary policy that limits what permissions the dev team can grant (e.g., only S3, EC2, Lambda). (2) Allow the dev team to create roles ONLY IF they attach this boundary: iam:CreateRole with Condition iam:PermissionsBoundary = arn:aws:iam::ACCOUNT:policy/DevBoundary. (3) Dev team can now create application roles, but those roles are capped by the boundary. This pattern appears in AWS Organizations setups, multi-team environments, and compliance frameworks (SOC2, PCI-DSS) that require preventing privilege escalation.`,
    tags: ['aws', 'iam', 'security', 'governance', 'permission-boundaries', 'enterprise'],
  },
  {
    topicSlug: 'aws-core',
    difficulty: 'MEDIUM' as const,
    type: 'THEORY' as const,
    question: 'What is S3 Transfer Acceleration and how does it work? When is it beneficial?',
    options: [
      'It routes uploads through CloudFront edge locations using the AWS backbone network instead of the public internet, reducing latency for geographically distant uploads',
      'Transfer Acceleration increases download speeds for all S3 operations by caching data at edge locations based on production deployment experience based on standard operational procedures',
      'Transfer Acceleration is an S3 encryption feature that reduces the overhead of encrypting large files based on standard operational procedures implementing typical operational patterns',
      'It splits large files into parallel chunks and uploads them simultaneously — equivalent to S3 Multipart Upload as documented in the official best practices using standard configuration methods',
    ],
    correctIndex: 0,
    explanation: `S3 Transfer Acceleration addresses a real performance problem: uploading large files from distant geographic locations over the public internet has high latency and inconsistent throughput due to TCP slow start and routing inefficiencies. How it works: Instead of uploading directly to the S3 bucket endpoint (s3.amazonaws.com), you upload to a special accelerated endpoint (bucket.s3-accelerate.amazonaws.com). The upload first hits the nearest CloudFront edge location (400+ worldwide). Data is then transferred over AWS's dedicated, optimized global backbone network to the S3 bucket region. The backbone has optimized TCP settings, dedicated capacity, and avoids the congested public internet. Performance benefit: Can be 50-500% faster for cross-continental uploads. Minimal benefit for uploads from the same region (no edge location helps). Cost: Additional $0.04-0.08 per GB on top of regular S3 pricing. When to use: Mobile apps with global users uploading media. IoT devices in remote locations. Disaster recovery uploads from distant data centers. When NOT to use: If client is in the same region as the bucket (overhead with no benefit). Use the S3 Transfer Acceleration Speed Comparison Tool to measure improvement before enabling. Combine with Multipart Upload for large files.`,
    tags: ['aws', 's3', 'performance', 'cloudfront', 'transfer-acceleration'],
  },
  {
    topicSlug: 'aws-core',
    difficulty: 'MEDIUM' as const,
    type: 'SCENARIO' as const,
    question: 'Your EC2 Auto Scaling group is not scaling out despite CPU utilization hitting 95%. The scaling policy is correctly defined. What are the possible causes?',
    options: [
      'Cooldown period active, instance limits (service quotas) reached, insufficient capacity in AZ, launch template/configuration errors causing unhealthy instance launches',
      'Auto Scaling only scales when CPU exceeds 100% — 95% is intentionally below the threshold and this applies to all deployment scenarios and this applies to all deployment scenarios',
      'Auto Scaling requires manual approval for each scale-out event in production',
      'Auto Scaling will not trigger if the EC2 instances are running in private subnets',
    ],
    correctIndex: 0,
    explanation: `When Auto Scaling fails to scale despite high metrics, diagnose systematically: (1) Cooldown Period — default 300 seconds. After a scaling activity, no new scaling occurs during cooldown. Check in ASG Activity History in console. Fix: reduce default cooldown, or use target tracking policies (they have built-in warmup settings). (2) EC2 Service Quotas — there is a limit on running On-Demand instances per region per instance family. Check Service Quotas console. Symptom: Activity History shows "EC2 QUOTA EXCEEDED". Fix: request quota increase. (3) Insufficient Capacity (InsufficientInstanceCapacity) — AWS doesn't have the requested instance type in your target AZ. Fix: configure multiple instance types (capacity-optimized Spot, or use multiple On-Demand types). Enable multi-AZ. (4) Launch Template/Configuration errors — if the new instance fails health checks, ASG terminates it and tries again, but scaling never "succeeds". Check Instance Refresh events and EC2 console for failed instances. Common causes: AMI no longer exists, incorrect subnet, security group missing, IAM role lacking permissions. (5) Max capacity reached — ASG max capacity setting prevents scaling beyond a limit. (6) SNS/CloudWatch Alarm in INSUFFICIENT_DATA state — alarm not firing. Check alarm history. Always check Activity History tab in the ASG console — it shows exactly what happened and why.`,
    tags: ['aws', 'ec2', 'auto-scaling', 'troubleshooting', 'scaling'],
  },
  {
    topicSlug: 'aws-core',
    difficulty: 'MEDIUM' as const,
    type: 'THEORY' as const,
    question: 'What are S3 lifecycle policies and give an example of a cost-optimized multi-tier storage configuration for application logs?',
    options: [
      'Lifecycle policies automatically transition or expire objects based on age. Example: Standard (0-30 days) → Standard-IA (31-90 days) → Glacier Instant Retrieval (91-180 days) → Delete (after 365 days)',
      'Lifecycle policies automatically replicate objects to another region after a configured time period',
      'Lifecycle policies only work with versioned buckets and only manage previous object versions',
      'Lifecycle policies change the storage class in real time based on current access patterns, similar to Intelligent-Tiering which is the standard recommended approach which is the standard recommended approach',
    ],
    correctIndex: 0,
    explanation: 'S3 Lifecycle policies are a core FinOps tool for managing storage costs over time. Configuration: Rules specify transitions (change storage class) or expirations (delete objects) based on object age or prefix. Cost-optimized log configuration: Days 0-30 (Hot): S3 Standard — logs actively queried for debugging, incident response. Days 31-90 (Warm): S3 Standard-IA — logs occasionally accessed for audits. 60% cost savings vs Standard. Days 91-180 (Cold): S3 Glacier Instant Retrieval — accessed for compliance reviews. 80% cost savings vs Standard. Days 181-365 (Archive): S3 Glacier Deep Archive — accessed only for legal holds. 95% cost savings. After 365 days: Delete — no compliance requirement to retain. Additional features: Multipart upload cleanup — rule to abort incomplete multipart uploads after 7 days (prevents orphaned storage charges). Noncurrent version expiration — for versioned buckets, delete old versions after 30 days. Delete expired delete markers — cleanup for versioned buckets. Prefix filtering — apply different policies to logs/, backups/, archives/. Real cost impact: A company storing 10TB/month of logs saves ~$15,000/year with proper lifecycle vs keeping everything in Standard.',
    tags: ['aws', 's3', 'lifecycle', 'cost-optimization', 'storage'],
  },

  // ─── HARD ──────────────────────────────────────────────────────────────────
  {
    topicSlug: 'aws-core',
    difficulty: 'HARD' as const,
    type: 'THEORY' as const,
    question: 'Explain EC2 placement groups: Cluster, Spread, and Partition. What are the trade-offs and when would you use each for HPC workloads?',
    options: [
      'Cluster: all instances in same AZ/rack for lowest latency 10Gbps+ networking (HPC, ML training). Spread: each instance on separate hardware (max 7 per AZ, for critical HA). Partition: groups of instances on separate racks (Hadoop, Cassandra, HDFS)',
      'Cluster placement gives the highest availability by distributing instances across all AZs automatically as documented in the official best practices as documented in the official best practices as documented in the official best practices which follows AWS recommended architecture patterns',
      'Spread placement groups put all instances on the same physical server for better CPU cache sharing using standard configuration methods following the recommended security practices using standard configuration methods using conventional setup approaches which follows AWS recommended architecture patterns',
      'Placement groups are only available for GPU instances and have no effect on CPU instance performance implementing typical operational patterns as documented in official AWS best practices using conventional setup approaches as documented in official AWS best practices',
    ],
    correctIndex: 0,
    explanation: 'EC2 Placement Groups control the physical placement of instances within AWS infrastructure: Cluster Placement Group: All instances placed in the same Availability Zone, often on the same physical host or nearby hosts connected via high-bandwidth, low-latency networking. Achieves up to 10 Gbps network throughput between instances (vs 5 Gbps normally). Lowest possible network latency within AWS. Trade-off: if the underlying hardware fails, all instances are affected. Single AZ only. Use cases: High Performance Computing (HPC) with MPI, machine learning training jobs requiring fast inter-node gradient synchronization (NCCL), financial trading systems needing microsecond inter-service latency. Spread Placement Group: Each instance is placed on distinct underlying hardware (different racks, different power sources). Maximum 7 instances per AZ per placement group. Can span multiple AZs. Use cases: Critical application components where simultaneous hardware failure would cause outage — primary/standby databases, ZooKeeper quorum nodes. Trade-off: limited to 7 instances per AZ. Partition Placement Group: Instances divided into logical partitions (up to 7 per AZ), each partition on separate rack/power/networking. Hundreds of instances per partition. Instances in different partitions never share underlying hardware. Use cases: Hadoop, Cassandra, HDFS, HBase — frameworks with rack-awareness where you want replicas on different racks for fault tolerance.',
    tags: ['aws', 'ec2', 'placement-groups', 'hpc', 'high-availability'],
  },
  {
    topicSlug: 'aws-core',
    difficulty: 'HARD' as const,
    type: 'THEORY' as const,
    question: 'What is IAM Attribute-Based Access Control (ABAC) and how does it scale better than traditional RBAC in AWS?',
    options: [
      'ABAC uses tags on both IAM principals and AWS resources to grant permissions dynamically. One IAM policy covers thousands of resources via tag matching, eliminating the need to update policies when new resources are created',
      'ABAC is an AWS Organizations feature that automatically generates IAM policies based on cost allocation tags as documented in the official best practices as documented in the official best practices as documented in the official best practices',
      'ABAC replaces IAM roles entirely — you define attributes on users and AWS computes permissions automatically',
      'ABAC and RBAC are the same concept in AWS — "attributes" and "roles" refer to the same IAM construct',
    ],
    correctIndex: 0,
    explanation: `ABAC is a powerful IAM design pattern that solves a critical scaling problem: Traditional RBAC problem: In a large org, you might have 50 teams × 3 environments × 10 resource types = 1,500 IAM policies. Each new resource requires policy updates. ABAC solution: Tag your IAM principals: aws sts tag-session with Team=payments, Env=prod. Tag your resources: EC2 instances, S3 buckets, RDS get Team=payments, Env=prod tags. One ABAC policy covers everything: Condition: StringEquals: aws:ResourceTag/Team: \${aws:PrincipalTag/Team} AND aws:ResourceTag/Env: \${aws:PrincipalTag/Env}. This single policy allows engineers to access only resources tagged with their team and environment. Scale advantage: When the payments team creates a new EC2 instance and tags it Team=payments, Env=prod — it's immediately accessible to payments engineers without any policy changes. Add a new team: just add the tags. When to use: Large organizations with many teams. Environments where resource creation is frequent. SAML federated identities (tags from your IdP map to AWS tags). Real implementation: Use aws:PrincipalTag/\${TagKey} for the user's tag. Use aws:ResourceTag/\${TagKey} for the resource tag. Combine with permission boundaries for defense in depth.`,
    tags: ['aws', 'iam', 'abac', 'rbac', 'security', 'governance', 'scaling'],
  },
  {
    topicSlug: 'aws-core',
    difficulty: 'HARD' as const,
    type: 'SCENARIO' as const,
    question: 'You need to design an S3 cross-region replication setup for a compliance requirement where data must exist in both us-east-1 and eu-west-1, with conflict resolution when the same object is written in both regions simultaneously.',
    options: [
      'Use S3 Multi-Region Access Points with active-active replication (two-way replication) and S3 Replication Time Control. Enable S3 Object Lock with versioning to handle conflicts — latest version wins via timestamp; use event notifications for conflict detection',
      'S3 replication is one-directional only — you must pick one primary region and accept data loss in conflict scenarios and this applies to all deployment scenarios and this applies to all deployment scenarios and this applies to all deployment scenarios implementing typical operational patterns',
      'Use DynamoDB Global Tables instead of S3 for any data that requires conflict resolution using standard configuration methods based on production deployment experience using established implementation patterns using established implementation patterns implementing typical operational patterns',
      'AWS automatically resolves S3 replication conflicts using a consensus algorithm similar to Raft following common design principles based on standard operational procedures based on standard operational procedures following common design principles which follows AWS recommended architecture patterns',
    ],
    correctIndex: 0,
    explanation: 'This is an advanced architecture scenario testing deep S3 and compliance knowledge: Setup: Enable versioning on BOTH buckets (required for CRR). Configure two-way replication rules (us-east-1 → eu-west-1 AND eu-west-1 → us-east-1). Enable S3 Replication Time Control (RTC) for the compliance SLA — guarantees 99.99% of objects replicated within 15 minutes (with CloudWatch metrics). Use S3 Multi-Region Access Points (MRAP) — single global endpoint that routes to the nearest region, with built-in failover. Conflict resolution strategy: S3 uses "last writer wins" based on object version timestamp. When the same key is written simultaneously in both regions, both writes create a version — replication then creates a second version in each bucket. The application must implement application-level conflict resolution using S3 Object Tags or custom metadata (e.g., a vector clock implementation). Use S3 Event Notifications (→ SQS → Lambda) to detect when replication creates conflicting versions and trigger reconciliation logic. S3 Object Lock (Write-Once-Read-Many) prevents modification of objects within the retention period — use Governance mode for flexibility, Compliance mode for immutable records. Replication metrics in CloudWatch: aws:s3:ReplicationLatency, aws:s3:BytesPendingReplication for monitoring.',
    tags: ['aws', 's3', 'replication', 'cross-region', 'compliance', 'conflict-resolution'],
  },
  {
    topicSlug: 'aws-core',
    difficulty: 'HARD' as const,
    type: 'THEORY' as const,
    question: 'Explain VPC endpoints (Gateway vs Interface) and how PrivateLink works to expose services without internet connectivity.',
    options: [
      'Gateway endpoints are free, route-table-based endpoints for S3/DynamoDB. Interface endpoints use ENIs with private IPs for all other AWS services via PrivateLink, billed per hour + data. PrivateLink allows SaaS providers to expose services into customer VPCs',
      'Gateway and Interface endpoints are identical — the choice is purely cosmetic as suggested by cloud architects as suggested by cloud architects as suggested by cloud architects and this approach is commonly used in enterprise settings following typical deployment workflows',
      'VPC endpoints require VPN or Direct Connect to function — they cannot be used with internet-connected VPCs using conventional setup approaches implementing typical operational patterns following the recommended security practices based on standard operational procedures',
      'Interface endpoints work only for services in the same AWS account — cross-account requires Gateway endpoints and this applies to all deployment scenarios and this applies to all deployment scenarios and this applies to all deployment scenarios as suggested by cloud architects',
    ],
    correctIndex: 0,
    explanation: 'VPC Endpoints enable private connectivity to AWS services without internet: Gateway Endpoints: Free. Work by modifying route tables (add route: prefix list for S3/DynamoDB → vpce-xxxx). Only support S3 and DynamoDB. Traffic stays within AWS network but routes through AWS endpoints. Policy-based access control. No DNS changes needed. Interface Endpoints (Powered by PrivateLink): Create an Elastic Network Interface (ENI) in your subnet with a private IP address. Support 100+ AWS services (CloudWatch, SQS, SNS, ECR, Secrets Manager, KMS, etc.) and custom services. DNS: creates private DNS names that resolve to the ENI IP within the VPC. Cost: ~$0.01/hour per AZ + $0.01/GB. You can enable private DNS to override the public service endpoint with the private one. AWS PrivateLink custom services: A service provider (or another team/account) can create a Network Load Balancer in their VPC, register it as a VPC Endpoint Service. Consumers create Interface Endpoints pointing to this service. Traffic flows from consumer VPC → ENI → NLB → service provider VPC, entirely within AWS backbone. Use cases: SaaS vendors exposing services to enterprise customers without public internet exposure. Sharing microservices between AWS accounts without VPC peering. Security benefit: no public IP, no internet route, no NAT Gateway needed for AWS API calls.',
    tags: ['aws', 'vpc', 'privatelink', 'vpc-endpoints', 'security', 'networking'],
  },
  {
    topicSlug: 'aws-core',
    difficulty: 'MEDIUM' as const,
    type: 'SCENARIO' as const,
    question: 'Your team needs to allow 200 developers read-only access to S3 in production for debugging, but you want to avoid creating 200 IAM users. What is the scalable solution?',
    options: [
      'Use IAM Identity Center (SSO) with permission sets. Sync from your corporate IdP (Active Directory/Okta) — developers authenticate via SSO and assume roles with S3 read-only permissions without individual IAM users',
      'Create one shared IAM user with S3 read-only access and share the credentials across the team following typical deployment workflows as documented in official AWS best practices which follows AWS recommended architecture patterns',
      'Grant everyone temporary root account access with a password that rotates daily based on standard operational procedures based on standard operational procedures according to industry standard guidelines based on production deployment experience',
      'Create a single EC2 bastion host with S3 access and require all developers to SSH into it for S3 operations as documented in the official best practices as documented in the official best practices and this approach is commonly used in enterprise settings',
    ],
    correctIndex: 0,
    explanation: `This is the modern, enterprise-grade solution for workforce identity: IAM Identity Center (formerly AWS SSO) is the correct answer: Integration with IdP: Connect to your corporate identity provider (Okta, Azure AD, Google Workspace, or Active Directory via AD Connector). Users are automatically provisioned/deprovisioned based on IdP groups. No 200 individual IAM users. Permission Sets: Define a "S3ReadOnly-Production" permission set using the AWS managed policy AmazonS3ReadOnlyAccess or a custom policy. Assign this permission set to the Developer group in IAM Identity Center for the production account. User experience: Developer logs into the SSO portal (your-domain.awsapps.com/start). They see "Production - S3 Read" tile. Click → they get temporary credentials (STS AssumeRoleWithSAML) valid for 1-8 hours. CLI: aws configure sso runs through the browser flow once; after that aws sso login refreshes credentials. Audit: CloudTrail records all API calls with the user's SSO identity, not a shared IAM user. Least privilege: Each developer gets individual temporary credentials tied to their identity. Off-boarding: When someone leaves, disable in IdP → immediately loses AWS access. This pattern scales to thousands of employees across hundreds of AWS accounts and is the architecture AWS recommends for enterprise.`,
    tags: ['aws', 'iam', 'sso', 'identity-center', 'governance', 'security'],
  },
  {
    topicSlug: 'aws-core',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What is the AWS shared responsibility model?',
    options: [
      'AWS is responsible for security OF the cloud (hardware, facilities, hypervisor, managed service patches). Customer is responsible for security IN the cloud (OS patching, application security, data, IAM, network config)',
      'AWS is responsible for all security — customers have no security responsibilities in the cloud based on production deployment experience based on standard operational procedures implementing typical operational patterns implementing typical operational patterns',
      'Customers are fully responsible for all security including the physical data center and hardware using standard configuration methods according to industry standard guidelines based on production deployment experience following typical deployment workflows',
      'The shared responsibility model only applies to PCI-DSS compliance — for other workloads, AWS handles everything and this applies to all deployment scenarios and this applies to all deployment scenarios using established implementation patterns',
    ],
    correctIndex: 0,
    explanation: 'The AWS Shared Responsibility Model is foundational to cloud security architecture and appears in every cloud certification and interview. AWS responsibility (Security OF the cloud): Physical data center security and access. Hardware (servers, networking equipment, storage). Hypervisor and virtualization layer. AWS managed service patches and maintenance (e.g., RDS: AWS patches the database engine). Global infrastructure (Regions, AZs, Edge Locations). Customer responsibility (Security IN the cloud): EC2: Guest OS patching, application code, data. IAM: Managing users, roles, policies, MFA enforcement. Network: Security groups, NACLs, VPC configuration. Data: Encryption at rest and in transit, key management. Application: Code vulnerabilities, dependency updates. Compliance: Ensuring configurations meet regulatory requirements. Shared responsibilities: Patch management (AWS patches RDS, customer patches EC2). Configuration management. Awareness and training. The model shifts for managed services: With RDS, AWS manages OS and DB engine patches. With Lambda, AWS manages everything except function code and execution role. This model is why "cloud is insecure" is a misconception — cloud security is a partnership.',
    tags: ['aws', 'security', 'shared-responsibility', 'compliance', 'fundamentals'],
  },

  // ─── ADDITIONAL AWS CORE QUESTIONS ───────────────────────────────────────────
  {
    topicSlug: 'aws-core',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What is the difference between Security Groups and Network ACLs in AWS?',
    options: [
      'Security Groups are stateful (return traffic auto-allowed), instance-level, allow-only rules. NACLs are stateless (must allow both directions), subnet-level, support allow and deny rules',
      'Security Groups and NACLs are identical',
      'NACLs are stateful while Security Groups are stateless',
      'Security Groups only apply to EC2, not to RDS or Lambda and this applies to all deployment scenarios and this applies to all deployment scenarios and this applies to all deployment scenarios',
    ],
    correctIndex: 0,
    explanation: 'Security Groups: (1) Stateful: if you allow inbound traffic, the return traffic is automatically allowed (no outbound rule needed for response). (2) Instance-level: attached to ENIs, can be shared across instances. (3) Allow-only: you define what to allow; everything else is denied. (4) No explicit deny rules. (5) All rules evaluated before decision. (6) Default: deny all inbound, allow all outbound. Network ACLs (NACLs): (1) Stateless: you must allow both inbound and outbound traffic separately. (2) Subnet-level: applies to all resources in the subnet. (3) Support allow AND deny rules. (4) Rules evaluated in order (lowest number first). (5) Default: allow all traffic. Use Security Groups for application-level security (allow port 443 from ALB). Use NACLs for subnet-level security (block known malicious IPs). They are different (B). Security Groups are stateful (C). Security Groups apply to all resources with ENIs (D).',
    tags: ['aws', 'security-groups', 'nacl', 'networking', 'vpc', 'security'],
  },
  {
    topicSlug: 'aws-core',
    difficulty: 'MEDIUM' as const,
    type: 'THEORY' as const,
    question: 'What is the difference between Application Load Balancer (ALB), Network Load Balancer (NLB), and Classic Load Balancer (CLB)?',
    options: [
      'ALB operates at Layer 7 (HTTP/HTTPS routing), NLB at Layer 4 (TCP/UDP, ultra-low latency), CLB at both layers but is legacy. Use ALB for web apps, NLB for high-performance TCP',
      'All three load balancers are identical in functionality so either can be used interchangeably in production so either can be used interchangeably in production so either can be used interchangeably in production',
      'NLB is more expensive than ALB in all cases',
      'CLB is the newest and most feature-rich option',
    ],
    correctIndex: 0,
    explanation: 'Application Load Balancer (ALB): Layer 7 (HTTP/HTTPS). Features: path-based routing (/api → backend), host-based routing (api.example.com → API service), authentication (Cognito, OIDC), WebSocket support, HTTP/2, request tracing. Best for: microservices, containerized apps, API gateways. Network Load Balancer (NLB): Layer 4 (TCP/UDP/TLS). Features: ultra-low latency (millions of requests/second), static IP per AZ, preserves source IP, supports UDP. Best for: high-performance workloads, gaming, IoT, real-time streaming, non-HTTP protocols. Classic Load Balancer (CLB): Layer 4 and 7 (limited). Legacy — predates ALB/NLB. Lacks advanced routing, no native container support. Not recommended for new applications. Migration: AWS provides tools to migrate from CLB to ALB/NLB. Gateway Load Balancer (GWLB): Layer 3. For network appliances (firewalls, IDS). They are different (B). NLB pricing depends on usage patterns (C). CLB is legacy (D).',
    tags: ['aws', 'elb', 'alb', 'nlb', 'load-balancing', 'networking'],
  },
  {
    topicSlug: 'aws-core',
    difficulty: 'MEDIUM' as const,
    type: 'SCENARIO' as const,
    question: 'Your EC2 instances in a private subnet need to download software updates from the internet. What AWS service should you use?',
    options: [
      'Deploy a NAT Gateway in a public subnet; update the private subnet route table to route 0.0.0.0/0 through the NAT Gateway',
      'Attach an Internet Gateway directly to the private subnet which is the standard recommended approach which is the standard recommended approach',
      'Use a VPC Peering connection',
      'Private subnets cannot have internet access',
    ],
    correctIndex: 0,
    explanation: 'NAT Gateway enables outbound internet access for private subnets: Architecture: (1) NAT Gateway deployed in a public subnet (has route to Internet Gateway). (2) Private subnet route table: 0.0.0.0/0 → NAT Gateway. (3) EC2 in private subnet → NAT Gateway → Internet Gateway → Internet. NAT Gateway features: (1) Managed by AWS (no patching, HA within AZ). (2) Scales automatically to 45 Gbps. (3) One-way: allows outbound connections, blocks unsolicited inbound. (4) Billed per hour + per GB processed. High availability: deploy NAT Gateway in each AZ to avoid cross-AZ traffic and single points of failure. Alternative: NAT Instance (EC2 running NAT) — cheaper for low traffic but requires management. Internet Gateway alone (B) does not provide NAT for private subnets. VPC Peering (C) is for VPC-to-VPC connectivity. Private subnets can have outbound internet via NAT (D).',
    tags: ['aws', 'nat-gateway', 'vpc', 'networking', 'private-subnet'],
  },
  {
    topicSlug: 'aws-core',
    difficulty: 'HARD' as const,
    type: 'SCENARIO' as const,
    question: 'You need to design a multi-region active-active architecture for a global application. Which AWS services would you use for database and routing?',
    options: [
      'Use Amazon Aurora Global Database for multi-region replication, Route 53 latency-based routing to direct users to the nearest region, and DynamoDB Global Tables as an alternative',
      'Use RDS Multi-AZ for multi-region',
      'Multi-region active-active is not supported by AWS',
      'Use a single-region database with global CloudFront distribution which is the standard recommended approach which is the standard recommended approach which is the standard recommended approach',
    ],
    correctIndex: 0,
    explanation: 'Multi-region active-active architecture: Database options: (1) Aurora Global Database: primary region for writes, up to 5 secondary regions with read replicas. Replication lag < 1 second. Failover promotes secondary to primary. (2) DynamoDB Global Tables: fully active-active with multi-region writes. Last-writer-wins conflict resolution. Sub-second replication. (3) ElastiCache Global Datastore: Redis replication across regions. Routing: (1) Route 53 latency-based routing: directs users to the AWS region with lowest latency. (2) Route 53 geolocation routing: directs users based on geographic location. (3) Global Accelerator: anycast IPs route traffic to optimal regional endpoint. Additional components: (1) S3 Cross-Region Replication for static assets. (2) CloudFront for edge caching. (3) Regional API Gateways or ALBs. RDS Multi-AZ (B) is single-region HA. Multi-region is supported (C). A single-region database (D) becomes a bottleneck and single point of failure.',
    tags: ['aws', 'multi-region', 'aurora', 'dynamodb', 'route53', 'global', 'architecture'],
  },
  {
    topicSlug: 'aws-core',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What is AWS CloudTrail and why is it important for security?',
    options: [
      'CloudTrail records all API calls made in your AWS account, providing an audit trail for security analysis, compliance, and troubleshooting',
      'CloudTrail is a CDN service as documented in official AWS best practices using standard configuration methods using standard configuration methods following typical deployment workflows',
      'CloudTrail only tracks EC2 instance launches and this applies to all deployment scenarios and this applies to all deployment scenarios following typical deployment workflows',
      'CloudTrail is the same as CloudWatch as recommended for high availability and this approach is commonly used in enterprise settings implementing typical operational patterns',
    ],
    correctIndex: 0,
    explanation: 'AWS CloudTrail is a governance, compliance, and auditing service: What it records: (1) Every API call (who made it, when, from where, what parameters). (2) Console sign-ins. (3) SDK and CLI calls. (4) Service-to-service calls. Key features: (1) Event history: 90 days of management events viewable in console (free). (2) Trail: configure to log to S3 for long-term retention. (3) CloudWatch Logs integration: stream events for real-time alerting. (4) Event types: management events (API calls), data events (S3 object access, Lambda invocations), insights events (unusual activity). Security use cases: (1) Audit trail for compliance (PCI, HIPAA, SOC 2). (2) Detect unauthorized access (failed logins, privilege escalation). (3) Investigate security incidents (who deleted that S3 bucket?). (4) Monitor for anomalies with CloudTrail Insights. Best practice: enable CloudTrail in all regions, log to a secured S3 bucket with versioning and MFA delete. CloudTrail is not a CDN (B). It tracks all API calls (C). CloudWatch is for metrics/logs (D).',
    tags: ['aws', 'cloudtrail', 'security', 'audit', 'compliance', 'governance'],
  },
  {
    topicSlug: 'aws-core',
    difficulty: 'MEDIUM' as const,
    type: 'THEORY' as const,
    question: 'What is AWS Systems Manager and how can it help manage EC2 instances without SSH?',
    options: [
      'Systems Manager provides agentless management features including Session Manager for secure shell access, Run Command for executing scripts, and Patch Manager for automated patching',
      'Systems Manager is only for monitoring',
      'Systems Manager requires SSH to be enabled',
      'Systems Manager only works with Windows instances and this applies to all deployment scenarios and this applies to all deployment scenarios and this applies to all deployment scenarios',
    ],
    correctIndex: 0,
    explanation: 'AWS Systems Manager (SSM) is a collection of operational tools: Session Manager: (1) Browser-based or CLI shell access to instances. (2) No SSH ports needed (no security group rules for port 22). (3) No bastion hosts needed. (4) Full audit trail in CloudTrail. (5) IAM-based access control. Run Command: execute scripts on multiple instances simultaneously (install software, run health checks). Patch Manager: (1) Define patch baselines. (2) Scan instances for missing patches. (3) Automatically apply patches on schedule. (4) Compliance reporting. Other features: (1) Parameter Store: secure storage for configuration and secrets. (2) State Manager: maintain consistent configurations. (3) Inventory: collect software and configuration inventory. (4) Automation: orchestrate complex operational tasks. Requirements: SSM Agent installed (pre-installed on Amazon Linux, Windows), instance profile with AmazonSSMManagedInstanceCore policy. SSM is not monitoring-only (B). It works without SSH (C). It supports Linux and Windows (D).',
    tags: ['aws', 'systems-manager', 'ssm', 'session-manager', 'patch-manager', 'operations'],
  },

  // ─── ADDITIONAL EC2 QUESTIONS ─────────────────────────────────────────────────
  {
    topicSlug: 'aws-core',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What are EC2 instance types and how do you choose the right one?',
    options: [
      'Instance families optimized for different workloads: t3 (general), c6i (compute), r6i (memory), i3 (storage)',
      'All instance types have identical performance and the choice is purely based on cost according to industry standard guidelines',
      'Instance types only differ in network speed following the recommended security practices following common design principles',
      'You cannot change instance type after launch as recommended for high availability using standard configuration methods',
    ],
    correctIndex: 0,
    explanation: 'EC2 instance families: (1) T3/T3a: burstable general purpose, good for variable workloads, dev/test. (2) M6i/M5: balanced compute, memory, networking. General purpose production. (3) C6i/C5: compute optimized, high CPU. Batch processing, gaming, ML inference. (4) R6i/R5: memory optimized. Databases, in-memory caching. (5) I3/D2: storage optimized. High sequential I/O, data warehousing. (6) P4/G5: GPU instances. ML training, graphics rendering. (7) Graviton (g suffix): ARM-based, 40% better price-performance. Choose based on: CPU vs memory vs storage vs GPU needs, and cost efficiency.',
    tags: ['aws', 'ec2', 'instance-types', 'sizing'],
  },
  {
    topicSlug: 'aws-core',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What is an AMI and how do you create a custom one?',
    options: [
      'AMI is a template containing OS, software, and config. Create from running instance via console or CLI',
      'AMI is a networking configuration that cannot be customized by users according to industry standard guidelines following common design principles',
      'AMIs can only be created by AWS using established implementation patterns which follows AWS recommended architecture patterns',
      'AMI is the same as an EBS snapshot based on production deployment experience and this approach is commonly used in enterprise settings',
    ],
    correctIndex: 0,
    explanation: 'Amazon Machine Image (AMI) is a template used to launch EC2 instances. Contains: (1) Root volume snapshot (OS, installed software). (2) Launch permissions. (3) Block device mapping. Create custom AMI: (1) Launch instance from base AMI. (2) Install and configure software. (3) Create image: Console → Actions → Image → Create Image, or aws ec2 create-image. (4) AMI appears in your account, can be shared across accounts/regions. Use cases: golden images with security hardening, pre-installed applications for faster scaling. AMIs are regional; copy to other regions for multi-region deployment.',
    tags: ['aws', 'ec2', 'ami', 'image', 'customization'],
  },
  {
    topicSlug: 'aws-core',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What is EC2 user data and when does it run?',
    options: [
      'Bootstrap script that runs once at first boot as root; used to install software, configure instance',
      'User data runs every time the instance starts after reboot following typical deployment workflows which follows AWS recommended architecture patterns',
      'User data is encrypted storage for user credentials and this approach is commonly used in enterprise settings',
      'User data is the instance metadata service using conventional setup approaches using standard configuration methods',
    ],
    correctIndex: 0,
    explanation: 'EC2 user data is a bootstrap mechanism: (1) Script (bash, PowerShell) passed at launch time. (2) Runs as root/Administrator on first boot only (by default). (3) Accessed at http://169.254.169.254/latest/user-data. (4) Max 16KB. Use cases: (1) Install packages (yum install, apt-get). (2) Download application code. (3) Configure services. (4) Register with configuration management (Chef, Puppet). (5) Join domain/cluster. Logs: /var/log/cloud-init-output.log (Linux). To run on every boot, use cloud-init per-boot scripts or configure mime multi-part user data.',
    tags: ['aws', 'ec2', 'user-data', 'bootstrap', 'automation'],
  },
  {
    topicSlug: 'aws-core',
    difficulty: 'MEDIUM' as const,
    type: 'THEORY' as const,
    question: 'What is EC2 instance metadata and how do applications use it?',
    options: [
      'Data about the instance available via HTTP at 169.254.169.254; used to get instance ID, region, IAM credentials',
      'Metadata is configuration stored in EBS volumes following common design principles as documented in official AWS best practices',
      'Metadata is only accessible from AWS Console implementing typical operational patterns using established implementation patterns',
      'Metadata requires IAM permissions to access using conventional setup approaches following the recommended security practices',
    ],
    correctIndex: 0,
    explanation: 'Instance Metadata Service (IMDS): (1) Available at http://169.254.169.254/latest/meta-data/. (2) No authentication required from within instance. (3) Provides: instance-id, ami-id, hostname, public-ip, local-ip, placement/availability-zone, iam/security-credentials/<role-name>. (4) IMDSv2 (recommended): requires session token for security (PUT request first). (5) Used by AWS SDKs to automatically retrieve IAM role credentials. (6) Also provides user-data at /latest/user-data. Security: use IMDSv2 to prevent SSRF attacks, or disable IMDS if not needed.',
    tags: ['aws', 'ec2', 'metadata', 'imds', 'credentials'],
  },
  {
    topicSlug: 'aws-core',
    difficulty: 'MEDIUM' as const,
    type: 'SCENARIO' as const,
    question: 'How do you connect to an EC2 instance in a private subnet without a public IP?',
    options: [
      'Use SSM Session Manager, bastion host, or VPN/Direct Connect',
      'Private subnet instances are completely inaccessible',
      'Assign a public IP to the private instance temporarily for access',
      'Use Route 53 for private instance access',
    ],
    correctIndex: 0,
    explanation: 'Access private EC2 instances: (1) SSM Session Manager (recommended): no bastion, no open ports, IAM-based access, audit trail. Requires SSM agent and instance role. (2) Bastion host/jump box: EC2 in public subnet, SSH through it to private instances. (3) VPN: AWS Client VPN or Site-to-Site VPN for secure tunnel. (4) Direct Connect: dedicated network connection for on-prem access. (5) EC2 Instance Connect Endpoint: newer option, SSH/RDP without bastion. SSM is preferred for most use cases — eliminates bastion host management, provides better security and auditing.',
    tags: ['aws', 'ec2', 'private-subnet', 'ssm', 'bastion', 'access'],
  },
  {
    topicSlug: 'aws-core',
    difficulty: 'MEDIUM' as const,
    type: 'SCENARIO' as const,
    question: 'Your EC2 instance is unreachable via SSH. How do you troubleshoot?',
    options: [
      'Check: security group (port 22), NACL, route table, instance state, key pair, SSM as alternative',
      'The instance must be terminated and recreated since SSH issues cannot be fixed as suggested by cloud architects',
      'Only AWS support can diagnose SSH issues following common design principles as recommended for high availability',
      'Reboot always fixes SSH issues using established implementation patterns using established implementation patterns',
    ],
    correctIndex: 0,
    explanation: 'EC2 SSH troubleshooting checklist: (1) Security Group: allow inbound TCP port 22 from your IP. (2) NACL: allow inbound 22 and outbound ephemeral ports. (3) Route table: instance has route to internet (if connecting over internet). (4) Public IP/EIP: instance has public IP if connecting from internet. (5) Instance state: running (not stopped/terminated). (6) Key pair: using correct private key for the instance. (7) OS firewall: iptables/ufw not blocking. (8) SSH service: sshd running. (9) Disk full: can prevent login. Debug: use EC2 Serial Console or SSM Session Manager to access instance without SSH. Check system logs in EC2 Console.',
    tags: ['aws', 'ec2', 'ssh', 'troubleshooting', 'connectivity'],
  },
  {
    topicSlug: 'aws-core',
    difficulty: 'HARD' as const,
    type: 'THEORY' as const,
    question: 'What is the difference between EBS-backed and instance store-backed EC2 instances?',
    options: [
      'EBS-backed: persistent root volume, can stop/start. Instance store: ephemeral, data lost on stop, higher I/O',
      'They are identical in behavior and performance and this approach is commonly used in enterprise settings as recommended for high availability',
      'Instance store is more expensive than EBS implementing typical operational patterns which follows AWS recommended architecture patterns',
      'EBS-backed instances cannot be terminated and this approach is commonly used in enterprise settings based on production deployment experience',
    ],
    correctIndex: 0,
    explanation: 'EBS-backed vs Instance Store: (1) EBS-backed: root volume is EBS. Data persists after stop. Can stop/start/terminate. Can detach and reattach volume. Supports snapshots and AMIs. Most common choice. (2) Instance store (ephemeral): directly attached disk to host. Data lost on stop/terminate/hardware failure. Cannot stop instance (only terminate). Higher I/O performance (local NVMe). Use for: temporary data, caches, buffers. Instance types like i3, d2 have instance store. Best practice: use EBS for persistence, instance store for scratch data with replication or regeneration capability.',
    tags: ['aws', 'ec2', 'ebs', 'instance-store', 'storage'],
  },

  // ─── ADDITIONAL RDS QUESTIONS ─────────────────────────────────────────────────
  {
    topicSlug: 'aws-core',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What database engines does Amazon RDS support?',
    options: [
      'MySQL, PostgreSQL, MariaDB, Oracle, SQL Server, and Amazon Aurora',
      'Only MySQL and PostgreSQL are supported',
      'RDS only supports NoSQL databases',
      'RDS requires you to bring your own database engine license for all engines',
    ],
    correctIndex: 0,
    explanation: 'RDS supported engines: (1) MySQL: open source, widely used. (2) PostgreSQL: open source, advanced features. (3) MariaDB: MySQL fork. (4) Oracle: enterprise, license included or BYOL. (5) SQL Server: Microsoft, license included or BYOL. (6) Aurora: AWS cloud-native, MySQL/PostgreSQL compatible, 5x performance. All engines get managed features: automated backups, patching, Multi-AZ, Read Replicas (engine dependent), monitoring. Choose based on: existing expertise, application compatibility, licensing costs, performance requirements.',
    tags: ['aws', 'rds', 'database', 'engines'],
  },
  {
    topicSlug: 'aws-core',
    difficulty: 'MEDIUM' as const,
    type: 'THEORY' as const,
    question: 'How does RDS automated backup and point-in-time recovery work?',
    options: [
      'Daily snapshots plus transaction logs enable restore to any second within retention period',
      'RDS only supports manual backups as documented in official AWS best practices as documented in official AWS best practices',
      'Point-in-time recovery requires manual snapshot before each change using established implementation patterns',
      'Backups are stored on the RDS instance itself following typical deployment workflows and this approach is commonly used in enterprise settings',
    ],
    correctIndex: 0,
    explanation: 'RDS automated backups: (1) Daily automated snapshots during backup window. (2) Transaction logs captured every 5 minutes to S3. (3) Retention: 0-35 days (0 disables). (4) Point-in-time recovery: restore to any second within retention period. Creates new DB instance. (5) Backups are stored in S3 (managed by AWS, not visible in your S3). (6) Multi-AZ: backups taken from standby (no I/O impact on primary). Manual snapshots: user-initiated, retained until deleted, for long-term retention. Restore always creates new instance; cannot restore in-place.',
    tags: ['aws', 'rds', 'backup', 'point-in-time-recovery', 'snapshots'],
  },
  {
    topicSlug: 'aws-core',
    difficulty: 'HARD' as const,
    type: 'SCENARIO' as const,
    question: 'How do you encrypt an existing unencrypted RDS instance?',
    options: [
      'Create encrypted snapshot from unencrypted snapshot, then restore to new encrypted instance',
      'Enable encryption toggle on existing instance without migration using conventional setup approaches based on production deployment experience',
      'Unencrypted instances cannot be encrypted following typical deployment workflows as documented in official AWS best practices',
      'Delete and recreate the database which follows AWS recommended architecture patterns as suggested by cloud architects',
    ],
    correctIndex: 0,
    explanation: 'Encrypting existing RDS instance: (1) Create snapshot of unencrypted instance. (2) Copy snapshot with encryption enabled (specify KMS key). (3) Restore new instance from encrypted snapshot. (4) Update application connection string to new endpoint. (5) Verify data, then delete old instance. Encryption: uses AES-256, KMS keys (AWS managed or customer managed). Once encrypted: snapshots, replicas, logs all encrypted. Cannot convert encrypted to unencrypted. Best practice: enable encryption at creation. Encryption has minimal performance impact.',
    tags: ['aws', 'rds', 'encryption', 'migration', 'kms'],
  },
  {
    topicSlug: 'aws-core',
    difficulty: 'HARD' as const,
    type: 'SCENARIO' as const,
    question: 'Your RDS instance CPU is consistently at 100%. What are your options?',
    options: [
      'Scale up instance type, add Read Replicas for read traffic, optimize queries, enable Performance Insights',
      'CPU issues cannot be resolved and require database migration according to industry standard guidelines which follows AWS recommended architecture patterns',
      'Restart the RDS instance which follows AWS recommended architecture patterns based on production deployment experience',
      'Add more storage to reduce CPU following typical deployment workflows following typical deployment workflows as suggested by cloud architects',
    ],
    correctIndex: 0,
    explanation: 'RDS high CPU troubleshooting: (1) Scale vertically: increase instance type (db.r5.large → db.r5.xlarge). Requires brief downtime. (2) Read Replicas: offload read queries to replicas if read-heavy. (3) Query optimization: use Performance Insights to identify expensive queries. Add indexes, rewrite queries. (4) Connection pooling: reduce connection overhead with RDS Proxy or PgBouncer. (5) Caching: use ElastiCache for frequently accessed data. (6) Aurora: consider migration for better performance/scaling. (7) Check for: missing indexes, full table scans, lock contention, inefficient joins.',
    tags: ['aws', 'rds', 'cpu', 'performance', 'scaling', 'optimization'],
  },

  // ─── ADDITIONAL CLOUDFRONT QUESTIONS ──────────────────────────────────────────
  {
    topicSlug: 'aws-core',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What is Origin Access Control (OAC) in CloudFront and why use it?',
    options: [
      'OAC restricts S3 bucket access to only CloudFront, blocking direct S3 URL access',
      'OAC is a firewall for CloudFront edge locations according to industry standard guidelines following the recommended security practices',
      'OAC controls which users can access CloudFront based on production deployment experience based on standard operational procedures',
      'OAC is for CloudFront logging only following typical deployment workflows as suggested by cloud architects',
    ],
    correctIndex: 0,
    explanation: 'Origin Access Control (OAC) secures S3 origins: (1) CloudFront signs requests to S3 using OAC identity. (2) S3 bucket policy allows only that OAC identity. (3) Direct S3 URL access blocked (forces users through CloudFront). (4) OAC replaces older Origin Access Identity (OAI). Benefits: enforce CloudFront caching, apply CloudFront security (WAF, signed URLs), hide S3 bucket from public. Setup: create OAC, associate with CloudFront distribution origin, update S3 bucket policy to allow CloudFront principal.',
    tags: ['aws', 'cloudfront', 'oac', 's3', 'security'],
  },
  {
    topicSlug: 'aws-core',
    difficulty: 'MEDIUM' as const,
    type: 'THEORY' as const,
    question: 'How does CloudFront cache invalidation work?',
    options: [
      'Invalidation removes objects from edge caches before TTL expires; charged per path, use versioned URLs instead',
      'Invalidation is instant and free according to industry standard guidelines implementing typical operational patterns based on standard operational procedures',
      'CloudFront caches cannot be invalidated based on production deployment experience based on production deployment experience',
      'Invalidation automatically happens every hour using conventional setup approaches based on standard operational procedures',
    ],
    correctIndex: 0,
    explanation: 'CloudFront cache invalidation: (1) Removes cached objects from all edge locations. (2) Create invalidation request with paths: /images/*, /index.html. (3) Takes 10-15 minutes to complete globally. (4) First 1,000 paths/month free, then $0.005 per path. (5) Wildcard (*) counts as one path. Better alternative: versioned URLs (style.v2.css) — instant "invalidation" by changing URL, better caching, no cost. Use invalidation for: emergency fixes, when versioning not possible. Monitor via CloudFront console or API.',
    tags: ['aws', 'cloudfront', 'cache', 'invalidation', 'cdn'],
  },
  {
    topicSlug: 'aws-core',
    difficulty: 'MEDIUM' as const,
    type: 'SCENARIO' as const,
    question: 'CloudFront is serving stale content after you updated files in S3. How do you fix it?',
    options: [
      'Create cache invalidation for updated paths, or use versioned filenames for instant updates',
      'CloudFront always serves real-time content so this cannot happen using conventional setup approaches as suggested by cloud architects',
      'Delete and recreate the CloudFront distribution as suggested by cloud architects which follows AWS recommended architecture patterns',
      'Disable caching entirely following the recommended security practices following typical deployment workflows',
    ],
    correctIndex: 0,
    explanation: 'Stale content fix: (1) Immediate: create invalidation for affected paths (/* for all). (2) Long-term: use versioned URLs (app.v2.js) or content hashes (app.a1b2c3.js). Webpack, build tools generate hashes automatically. (3) Adjust TTL: reduce Cache-Control max-age for frequently changing content. (4) Check behaviors: ensure correct cache behavior settings. (5) Origin shield: if enabled, may add caching layer. Prevention: implement cache-busting strategy (versioned URLs), set appropriate TTLs based on content update frequency.',
    tags: ['aws', 'cloudfront', 'cache', 'stale-content', 'troubleshooting'],
  },
  {
    topicSlug: 'aws-core',
    difficulty: 'HARD' as const,
    type: 'SCENARIO' as const,
    question: 'How do you set up CloudFront in front of an ALB with HTTPS end-to-end encryption?',
    options: [
      'HTTPS viewer to CloudFront (ACM cert), HTTPS CloudFront to ALB origin (ALB cert), configure origin protocol policy',
      'CloudFront automatically handles all encryption without configuration following typical deployment workflows using standard configuration methods',
      'HTTPS between CloudFront and ALB is not possible following typical deployment workflows and this approach is commonly used in enterprise settings',
      'Only HTTP can be used for ALB origins as suggested by cloud architects using conventional setup approaches which follows AWS recommended architecture patterns',
    ],
    correctIndex: 0,
    explanation: 'CloudFront + ALB HTTPS setup: (1) Viewer to CloudFront: ACM certificate in us-east-1 on CloudFront. (2) CloudFront to ALB: configure origin with HTTPS protocol, ALB must have certificate (can be same domain or ALB domain). (3) Origin protocol policy: "HTTPS Only" for full encryption. (4) ALB security group: allow CloudFront IPs (use AWS managed prefix list). (5) Match host header: forward Host header to ALB if using same domain certificate. (6) Origin SSL protocols: TLSv1.2 recommended. This ensures encryption in transit from browser through CloudFront to ALB to application.',
    tags: ['aws', 'cloudfront', 'alb', 'https', 'ssl', 'encryption'],
  },
];
