export const cicdQuestions = [
  // ─── EASY THEORY ───────────────────────────────────────────────────────────
  {
    topicSlug: 'cicd',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What is the difference between Continuous Integration (CI) and Continuous Deployment (CD)?',
    options: [
      'CI automatically builds and tests code on every commit; CD automatically deploys passing builds to production',
      'CI is for development environments; CD is for production',
      'CI and CD are the same thing',
      'CI is manual; CD is automated',
    ],
    correctIndex: 0,
    explanation: 'Continuous Integration (CI) is the practice of automatically building, testing, and validating code changes whenever developers commit to the repository. CI catches integration issues early by running automated tests (unit, integration, linting) on every commit. Benefits: fast feedback, reduced merge conflicts, higher code quality. Continuous Delivery (CD) extends CI by automatically deploying passing builds to staging/pre-production environments, ready for manual promotion to production. Continuous Deployment (also CD) goes further by automatically deploying every passing build directly to production without manual intervention. Modern CI/CD pipelines typically include: (1) Source code commit triggers pipeline, (2) Build: compile code, create artifacts (Docker images, JARs, binaries), (3) Test: run automated test suites, (4) Security scan: SAST, dependency scanning, (5) Deploy to staging, (6) Integration/smoke tests, (7) Deploy to production (manual or automatic). CI is not environment-specific (B). CI and CD are complementary, not the same (C). CI is automated, not manual (D).',
    tags: ['cicd', 'continuous-integration', 'continuous-deployment', 'devops', 'automation'],
  },
  {
    topicSlug: 'cicd',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What is a CI/CD pipeline artifact and why is it important?',
    options: [
      'An artifact is the output of a build (Docker image, JAR, binary) that is versioned, stored, and deployed to environments',
      'An artifact is a log file from the pipeline',
      'An artifact is the source code repository',
      'An artifact is the CI/CD configuration file',
    ],
    correctIndex: 0,
    explanation: 'A CI/CD artifact is the deployable output of a build process: compiled binaries, Docker images, JAR/WAR files, ZIP archives, NPM packages, or Helm charts. Artifacts are immutable and versioned (tagged with Git commit SHA, semantic version, or build number). Best practices: (1) Build once, deploy many times: the same artifact is promoted through environments (dev → staging → prod) without rebuilding, ensuring consistency. (2) Store artifacts in registries: Docker images in Docker Hub/ECR, binaries in Artifactory/Nexus, packages in npm/PyPI. (3) Artifact metadata: include build timestamp, Git commit, branch, and test results for traceability. (4) Sign artifacts: use GPG signing or Docker Content Trust to ensure authenticity. (5) Artifact retention: automatically delete old artifacts to save storage costs while preserving recent versions and releases. Artifacts are not logs (B), source code (C), or config files (D) — they are the deployable result of building source code. Proper artifact management is critical for reliable deployments.',
    tags: ['cicd', 'artifacts', 'build', 'deployment', 'versioning'],
  },
  {
    topicSlug: 'cicd',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What is the purpose of automated testing in a CI/CD pipeline?',
    options: [
      'Automated tests catch bugs early, ensure code quality, and provide confidence that changes do not break existing functionality',
      'Automated tests replace manual code reviews',
      'Automated tests are only for frontend applications',
      'Automated tests slow down deployments and should be avoided',
    ],
    correctIndex: 0,
    explanation: 'Automated testing is the backbone of CI/CD, providing fast feedback on code quality. Types of automated tests: (1) Unit tests: test individual functions/classes in isolation (fast, run on every commit). (2) Integration tests: test interactions between components (databases, APIs, services). (3) End-to-end tests: test the entire application flow from user perspective (slower, run less frequently). (4) Performance tests: measure response time, throughput, and resource usage. (5) Security tests: SAST (static analysis), DAST (dynamic analysis), dependency scanning. Test pyramid: many unit tests (fast, cheap), fewer integration tests (moderate speed/cost), few e2e tests (slow, expensive). CI pipeline typically fails if tests do not pass, preventing broken code from reaching production. Code coverage metrics (e.g., 80% line coverage) ensure adequate test coverage. Automated tests do NOT replace code reviews (B) — both are complementary. Tests apply to all application types (C). Well-designed tests accelerate deployments by catching issues early (D is wrong).',
    tags: ['cicd', 'testing', 'automation', 'quality-assurance', 'test-pyramid'],
  },
  {
    topicSlug: 'cicd',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What are Git branching strategies and why do they matter for CI/CD?',
    options: [
      'Branching strategies (trunk-based, GitFlow, GitHub Flow) define how developers collaborate on code and when deployments occur',
      'Branching strategies are only for large teams; small teams do not need them',
      'Branching strategies are unrelated to CI/CD',
      'All branching strategies are the same',
    ],
    correctIndex: 0,
    explanation: 'Git branching strategies define workflows for feature development, testing, and deployment. Common strategies: (1) Trunk-Based Development: developers commit frequently to the main branch (trunk). Feature flags control incomplete features. CI/CD deploys trunk continuously. Best for: fast-moving teams with strong test automation. (2) GitHub Flow: create feature branches, open pull requests, merge to main after review and CI passing, deploy main immediately. Best for: web applications with continuous deployment. (3) GitFlow: long-lived branches (main, develop) + feature/release/hotfix branches. Releases are tagged and deployed. Best for: versioned releases (libraries, mobile apps). CI/CD integration: (1) CI runs on every branch push and pull request. (2) CD deploys from specific branches (main, release/*). (3) Branch protection rules enforce CI passing and code review before merge. Branching strategies apply to all team sizes (B). They are tightly coupled with CI/CD (C). Strategies have different trade-offs (D).',
    tags: ['cicd', 'git', 'branching', 'trunk-based', 'gitflow', 'workflow'],
  },
  {
    topicSlug: 'cicd',
    difficulty: 'EASY' as const,
    type: 'SCENARIO' as const,
    question: 'Your CI pipeline fails with "npm ERR! 404 Not Found - GET https://registry.npmjs.org/package". What is the likely cause?',
    options: [
      'A dependency in package.json does not exist or was removed from the npm registry, or there is a typo in the package name/version',
      'The CI server does not have internet access',
      'npm is not installed on the CI server',
      'The package.json file is corrupted',
    ],
    correctIndex: 0,
    explanation: `This error occurs when npm cannot find a package during 'npm install'. Common causes: (1) Typo in package name or version in package.json (e.g., "expresss" instead of "express", or version "^99.0.0" which does not exist). (2) Package was unpublished from npm registry (rare but happens when authors remove packages). (3) Private package misconfiguration: you are trying to install a private package but npm is not authenticated (missing .npmrc with auth token). (4) Transitive dependency issue: a dependency of your dependency has a broken version. Troubleshooting: (1) Check package.json for typos. (2) Try installing locally: 'npm install' on your machine. (3) Check npm registry: visit https://www.npmjs.com/package/<package-name>. (4) Review package-lock.json for the specific package causing issues. (5) Authenticate with private registries if needed. If the CI server lacks internet access (B), you would see connection timeout errors, not 404. Missing npm (C) would cause "command not found". Corrupted package.json (D) would cause JSON parse errors.`,
    tags: ['cicd', 'npm', 'dependencies', 'troubleshooting', 'package-management'],
  },
  {
    topicSlug: 'cicd',
    difficulty: 'EASY' as const,
    type: 'SCENARIO' as const,
    question: 'You want to deploy automatically to production only when code is merged to the "main" branch. How do you configure this in a CI/CD pipeline?',
    options: [
      'Use branch filters or conditional logic to trigger the deployment job only when the branch is "main"',
      'Manually trigger deployments after every merge',
      'CI/CD cannot filter by branch',
      'Deploy from all branches and let production handle the filtering',
    ],
    correctIndex: 0,
    explanation: `All modern CI/CD platforms support branch-based triggers and conditions. Examples: GitHub Actions: 'on: push: branches: [main]' triggers workflow only on pushes to main. GitLab CI: 'only: refs: - main' or 'rules: - if: $CI_COMMIT_BRANCH == "main"'. Jenkins: when { branch "main" }. CircleCI: 'filters: branches: only: main'. Best practice: (1) Run CI (build, test, lint) on all branches and pull requests to catch issues early. (2) Run CD (deployment to production) only from main or release branches. (3) Use separate pipelines/jobs for different environments: feature branches → deploy to ephemeral preview environments, main → deploy to staging, tags → deploy to production. (4) Add approval gates for production deployments (manual approval step) if required by compliance/policy. Manual triggering (B) defeats the purpose of automation. Branch filtering is standard (C). Deploying from all branches (D) is a security and stability risk.`,
    tags: ['cicd', 'branching', 'deployment', 'automation', 'triggers', 'conditional'],
  },
  {
    topicSlug: 'cicd',
    difficulty: 'EASY' as const,
    type: 'SCENARIO' as const,
    question: 'Your Docker image build in CI takes 15 minutes because it reinstalls all dependencies on every build. How can you speed it up?',
    options: [
      'Use layer caching in Dockerfile (copy package files first, run install, then copy code), enable CI caching for Docker layers or buildx cache',
      'Use a faster CI server',
      'Reduce the number of dependencies',
      'Docker builds cannot be optimized',
    ],
    correctIndex: 0,
    explanation: 'Docker layer caching is critical for fast CI builds. Optimize Dockerfile: (1) Order instructions from least to most frequently changed: FROM → system packages → dependency files (package.json, requirements.txt) → install dependencies → copy application code. (2) Split COPY and RUN: COPY package*.json ./, RUN npm ci, COPY . . This caches the npm install layer — changing app code does not invalidate it. (3) Use .dockerignore to exclude unnecessary files (node_modules, .git) from build context. Enable CI caching: (1) GitHub Actions: use docker/build-push-action with cache-from and cache-to. (2) GitLab CI: use docker:dind with DOCKER_BUILDKIT=1 and --cache-from. (3) CircleCI: use docker layer caching feature. (4) Use BuildKit: DOCKER_BUILDKIT=1 docker build enables parallel builds and improved caching. (5) Use multi-stage builds to separate build and runtime stages. A faster CI server (B) helps but does not address the root cause. Reducing dependencies (C) may not be feasible. Docker builds are highly optimizable (D is wrong).',
    tags: ['cicd', 'docker', 'caching', 'build-optimization', 'dockerfile', 'performance'],
  },

  // ─── MEDIUM THEORY ─────────────────────────────────────────────────────────
  {
    topicSlug: 'cicd',
    difficulty: 'MEDIUM' as const,
    type: 'THEORY' as const,
    question: 'What are blue-green and canary deployment strategies, and when should you use each?',
    options: [
      'Blue-green: run two identical environments, switch traffic instantly; Canary: gradually shift traffic from old to new version, monitor, and rollback if needed',
      'Blue-green is for frontend; canary is for backend',
      'Blue-green is cheaper than canary deployments',
      'Canary deployments require Kubernetes; blue-green does not',
    ],
    correctIndex: 0,
    explanation: 'Blue-Green Deployment: maintain two identical production environments (blue = current, green = new). Deploy new version to green, test it, then switch traffic from blue to green (via load balancer, DNS, or service mesh). If issues arise, instantly rollback by switching back to blue. Benefits: zero downtime, instant rollback, thorough testing before cutover. Drawbacks: requires 2x infrastructure, database migrations are complex. Canary Deployment: deploy new version to a small subset of users (e.g., 5% traffic), monitor metrics (error rate, latency, business KPIs), gradually increase traffic (10% → 25% → 50% → 100%) if healthy, or rollback if issues detected. Benefits: reduces blast radius of bugs, validates production behavior with real users. Drawbacks: requires traffic splitting infrastructure (Istio, AWS ALB weighted targets, Nginx), more complex rollback. Neither is frontend/backend specific (B). Blue-green requires 2x capacity, canary does not (C). Both can be implemented without Kubernetes (D) using load balancers or service meshes.',
    tags: ['cicd', 'blue-green', 'canary', 'deployment-strategies', 'rollback', 'zero-downtime'],
  },
  {
    topicSlug: 'cicd',
    difficulty: 'MEDIUM' as const,
    type: 'THEORY' as const,
    question: 'What is GitOps and how does it differ from traditional CI/CD?',
    options: [
      'GitOps uses Git as the single source of truth for infrastructure and application state; changes are pulled from Git by operators (ArgoCD, Flux) rather than pushed by CI',
      'GitOps is only for Kubernetes; traditional CI/CD is for VMs',
      'GitOps requires GitHub; traditional CI/CD works with any Git provider',
      'GitOps and traditional CI/CD are the same',
    ],
    correctIndex: 0,
    explanation: 'GitOps is a declarative deployment model where Git is the single source of truth. Principles: (1) Everything (infrastructure, Kubernetes manifests, configuration) is stored in Git. (2) Changes are made via Git commits (pull requests). (3) GitOps operators (ArgoCD, Flux) continuously watch Git and automatically sync the cluster state to match Git (pull model). (4) Rollback is as simple as reverting a Git commit. Traditional CI/CD uses a push model: CI pipeline builds artifacts and pushes them to environments using credentials (kubectl apply, SSH, AWS CLI). GitOps benefits: (1) Audit trail: Git history shows who deployed what and when. (2) Drift detection: operators detect manual changes and revert them. (3) Disaster recovery: entire cluster state can be recreated from Git. (4) Enhanced security: cluster credentials are not exposed to CI pipeline. GitOps is most popular with Kubernetes but applies to infrastructure (Terraform, CloudFormation) via tools like Atlantis. GitOps works with any Git provider (C). They are different paradigms (D).',
    tags: ['cicd', 'gitops', 'argocd', 'flux', 'kubernetes', 'deployment', 'pull-model'],
  },
  {
    topicSlug: 'cicd',
    difficulty: 'MEDIUM' as const,
    type: 'THEORY' as const,
    question: 'What are SAST and DAST security scanning, and when should each be used in a CI/CD pipeline?',
    options: [
      'SAST (Static Application Security Testing) analyzes source code for vulnerabilities during build; DAST (Dynamic Application Security Testing) tests running applications for vulnerabilities',
      'SAST is for frontend; DAST is for backend',
      'SAST and DAST are the same thing',
      'Security scanning is not part of CI/CD',
    ],
    correctIndex: 0,
    explanation: 'SAST (Static Application Security Testing) analyzes source code, bytecode, or binaries without executing the program. SAST tools detect: SQL injection, XSS, hardcoded secrets, insecure crypto, buffer overflows. Examples: SonarQube, Checkmarx, Semgrep, CodeQL. CI integration: run SAST after code checkout, before deployment. Benefits: fast, finds issues early in SDLC. Limitations: false positives, cannot detect runtime issues. DAST (Dynamic Application Security Testing) tests running applications by simulating attacks (black-box testing). DAST tools detect: auth bypasses, API vulnerabilities, misconfigured CORS, injection attacks. Examples: OWASP ZAP, Burp Suite, Acunetix. CI integration: run DAST against deployed test/staging environments. Benefits: detects runtime issues, fewer false positives. Limitations: slower, requires deployed application. Comprehensive pipelines use both: SAST early (commit/PR), DAST later (staging deployment). Dependency scanning (SCA) is also critical: detect vulnerable libraries (Snyk, Dependabot, Trivy). Security scanning is essential in modern CI/CD (D is wrong).',
    tags: ['cicd', 'sast', 'dast', 'security', 'vulnerability-scanning', 'devsecops'],
  },
  {
    topicSlug: 'cicd',
    difficulty: 'MEDIUM' as const,
    type: 'THEORY' as const,
    question: 'What is the purpose of a CI/CD pipeline approval gate and when should you use it?',
    options: [
      'An approval gate pauses the pipeline and requires manual approval before proceeding, typically used before production deployments for compliance or risk management',
      'Approval gates are used to slow down deployments intentionally',
      'Approval gates are only for failed pipelines',
      'Approval gates are deprecated in modern CI/CD',
    ],
    correctIndex: 0,
    explanation: 'Approval gates (manual approval steps) pause automated pipelines and require human intervention before proceeding. Common use cases: (1) Production deployments: require approval from QA, product owner, or SRE before deploying to prod (especially in regulated industries — finance, healthcare). (2) High-risk changes: database migrations, infrastructure changes, major version upgrades. (3) Change management compliance: ITIL processes require documented approvals for production changes. (4) Business alignment: ensure stakeholders are aware of deployment timing (e.g., avoid deployments during business-critical hours). Approval gates do NOT mean CI/CD is broken (B) — they balance automation with governance. They are not for failed pipelines (C) — those should fail and stop. They are not deprecated (D) — they are common in enterprise CI/CD. Approval gates should be minimized through strong automated testing, but are necessary in some contexts. Implementation: GitHub Actions (environment protection rules), GitLab CI (manual job), Jenkins (input step), ArgoCD (sync waves with manual promotion).',
    tags: ['cicd', 'approval-gates', 'manual-approval', 'compliance', 'change-management', 'governance'],
  },
  {
    topicSlug: 'cicd',
    difficulty: 'MEDIUM' as const,
    type: 'SCENARIO' as const,
    question: 'Your CI pipeline runs 3000 unit tests and takes 20 minutes. How can you reduce the test execution time?',
    options: [
      'Run tests in parallel across multiple workers/containers, use test sharding/splitting, cache dependencies, and optimize slow tests',
      'Skip tests to speed up the pipeline',
      'Run tests only on main branch, not on pull requests',
      'Test execution time cannot be reduced',
    ],
    correctIndex: 0,
    explanation: 'Long test execution times slow down feedback and deployments. Optimization strategies: (1) Parallel execution: split tests into chunks and run simultaneously on multiple CI workers (GitHub Actions matrix, GitLab parallel jobs, CircleCI parallelism). Example: split 3000 tests into 10 groups of 300, run in parallel → 10x faster. (2) Test sharding: tools like Jest, pytest-xdist, Go test -parallel support parallel test execution. (3) Selective test execution: use test impact analysis to run only tests affected by code changes (Bazel, Pants, NX). (4) Optimize slow tests: profile test execution, optimize database seeding, use mocking instead of real dependencies, avoid sleep/wait calls. (5) Cache dependencies: cache node_modules, pip packages, Go modules between CI runs. (6) Incremental testing: run fast smoke tests on every commit, full regression tests nightly. Skipping tests (B) defeats the purpose of CI. Running tests only on main (C) misses issues before merge. Test time is highly optimizable (D).',
    tags: ['cicd', 'testing', 'performance', 'parallelization', 'optimization', 'test-sharding'],
  },
  {
    topicSlug: 'cicd',
    difficulty: 'MEDIUM' as const,
    type: 'SCENARIO' as const,
    question: 'Your deployment pipeline should rollback automatically if the error rate exceeds 5% after deployment. How do you implement this?',
    options: [
      'Use progressive delivery tools (Flagger, Argo Rollouts) that monitor metrics (error rate, latency) and automatically rollback if thresholds are breached',
      'Manually monitor dashboards and rollback if needed',
      'Automatic rollback is not possible',
      'Use blue-green deployment without monitoring',
    ],
    correctIndex: 0,
    explanation: 'Automated rollback based on metrics requires progressive delivery tools that integrate with monitoring systems. Implementation: (1) Flagger (for Kubernetes): define a Canary resource with analysis metrics (success rate, latency percentiles) and thresholds. Flagger gradually shifts traffic (5% → 10% → 50% → 100%), queries Prometheus/Datadog for metrics at each step, and automatically rolls back if metrics fail. (2) Argo Rollouts: similar to Flagger, supports Canary and Blue-Green strategies with analysis templates. (3) Spinnaker: automated canary analysis with Kayenta, integrates with monitoring systems. (4) AWS CodeDeploy: supports automatic rollback based on CloudWatch alarms. (5) Custom scripts: deploy new version, monitor metrics via API (Prometheus, Datadog), trigger rollback if thresholds breached. Metrics to monitor: error rate, HTTP 5xx rate, latency (p50, p99), saturation (CPU, memory), business metrics (conversion rate, checkout success). Manual monitoring (B) is not scalable. Automatic rollback is possible (C). Blue-green without monitoring (D) cannot detect issues.',
    tags: ['cicd', 'rollback', 'progressive-delivery', 'canary', 'monitoring', 'flagger', 'argo-rollouts'],
  },
  {
    topicSlug: 'cicd',
    difficulty: 'MEDIUM' as const,
    type: 'SCENARIO' as const,
    question: 'Your team wants to deploy feature branches to temporary preview environments for testing. How do you implement this in CI/CD?',
    options: [
      'Create ephemeral environments per branch/PR using dynamic URLs, deploy on PR creation, and tear down on PR closure',
      'Share a single dev environment for all feature branches',
      'Preview environments are too complex and not worth implementing',
      'Preview environments require a separate production account',
    ],
    correctIndex: 0,
    explanation: 'Preview (ephemeral) environments provide isolated testing for feature branches without conflicts. Implementation: (1) Trigger: create environment on pull request open event. (2) Naming: generate unique environment identifier (PR number, branch name slug). Example: pr-123.preview.example.com. (3) Deployment: deploy application to Kubernetes namespace (pr-123), create Ingress with unique hostname. For non-k8s: deploy to separate AWS account/VPC, or use containerized setup (Docker Compose on unique ports). (4) Database: use a separate ephemeral database or database-per-PR (CloudSQL, RDS instance), or use seed data in shared dev database with isolated schema. (5) Cleanup: tear down environment on PR close/merge (delete namespace, database, DNS record). (6) Comment on PR: post preview URL as a PR comment for easy access. Tools: Vercel/Netlify (built-in preview deployments), Render, Heroku Review Apps, Kubernetes + ArgoCD/Flux, Terraform for infrastructure. Sharing dev environment (B) causes conflicts. Preview environments are valuable for QA and product testing (C).',
    tags: ['cicd', 'preview-environments', 'ephemeral-environments', 'pull-request', 'testing', 'automation'],
  },

  // ─── HARD THEORY ───────────────────────────────────────────────────────────
  {
    topicSlug: 'cicd',
    difficulty: 'HARD' as const,
    type: 'THEORY' as const,
    question: 'What is a multi-stage pipeline and how does it enable complex CI/CD workflows?',
    options: [
      'A multi-stage pipeline consists of sequential and parallel stages (build, test, security scan, deploy) with dependencies and artifacts passed between stages',
      'A multi-stage pipeline is only for monorepos',
      'Multi-stage pipelines are slower than single-stage pipelines',
      'Multi-stage pipelines are only supported by Jenkins',
    ],
    correctIndex: 0,
    explanation: 'Multi-stage pipelines model complex workflows as directed acyclic graphs (DAGs) of stages. Each stage represents a logical unit (build, test, scan, deploy) and can run sequentially or in parallel. Features: (1) Stage dependencies: test stage runs only after build succeeds. (2) Parallel execution: run unit tests, integration tests, and linting in parallel to save time. (3) Artifact passing: build stage produces a Docker image, subsequent stages use that image (not rebuilt). (4) Conditional execution: deploy-to-prod runs only if branch is main. (5) Manual gates: pause before production deployment for approval. (6) Stage-level caching: cache npm install results, reuse if package.json unchanged. (7) Visualization: UI shows pipeline progress, failed stages, and bottlenecks. Example pipeline: [Build] → [Unit Tests | Integration Tests | Lint] → [Security Scan] → [Deploy to Staging] → [Smoke Tests] → [Manual Approval] → [Deploy to Prod]. Multi-stage pipelines apply to all repos (B). They are faster when stages run in parallel (C). Most CI/CD platforms support them (D).',
    tags: ['cicd', 'multi-stage', 'pipeline', 'dag', 'parallel-execution', 'workflow'],
  },
  {
    topicSlug: 'cicd',
    difficulty: 'HARD' as const,
    type: 'THEORY' as const,
    question: 'What is a monorepo CI/CD strategy and how do you optimize pipelines for large monorepos?',
    options: [
      'Monorepo pipelines use affected-only builds (detect changed packages/services and build/test only those), caching, and dependency graph analysis to avoid rebuilding everything',
      'Monorepos always build and test everything on every commit',
      'Monorepos are not compatible with CI/CD',
      'Monorepos require separate pipelines for each service',
    ],
    correctIndex: 0,
    explanation: 'Monorepos (single repository for multiple services/packages) present CI/CD challenges: a small change in one service should not trigger full rebuild of 100 services. Optimization strategies: (1) Affected-only builds: tools like NX, Turborepo, Bazel, Pants analyze dependency graph and determine which packages are affected by changes. Only affected packages are built/tested. (2) Remote caching: cache build/test results across CI runs and developers. If service-a has not changed, reuse cached artifacts from previous builds. (3) Distributed task execution: split tasks (build, test) across multiple machines for parallelism. (4) Incremental builds: recompile only changed files (Bazel, Buck). (5) Selective deployments: deploy only services with changes to production. (6) Pipeline sharding: split tests for large services across multiple workers. Example: 10 services changed in commit → build/test those 10, skip remaining 90. Tools: NX (TypeScript), Bazel (language-agnostic), Turborepo (JavaScript), Pants (Python, Java, Go). Naive monorepo approach (B) is slow and wastes resources. Monorepos work great with CI/CD (C). Single pipeline with selective execution is optimal (D).',
    tags: ['cicd', 'monorepo', 'affected-builds', 'caching', 'optimization', 'nx', 'bazel'],
  },
  {
    topicSlug: 'cicd',
    difficulty: 'HARD' as const,
    type: 'THEORY' as const,
    question: 'What are immutable deployments and how do they improve reliability?',
    options: [
      'Immutable deployments replace entire infrastructure/containers on every deploy rather than modifying in-place, ensuring consistency and enabling easy rollback',
      'Immutable deployments mean you cannot deploy more than once',
      'Immutable deployments are only for databases',
      'Immutable deployments are slower than mutable deployments',
    ],
    correctIndex: 0,
    explanation: 'Immutable infrastructure/deployments treat servers/containers as disposable. Instead of SSH-ing to servers and running update scripts (mutable approach), immutable deployments: (1) Build a new artifact (Docker image, AMI, VM image) with updated code. (2) Deploy new instances with the new artifact. (3) Route traffic to new instances. (4) Terminate old instances. Benefits: (1) Consistency: all instances are identical, no configuration drift. (2) Rollback: keep old artifacts, redeploy them instantly if needed. (3) Testability: test exact artifact in staging that will run in prod. (4) Simplified operations: no manual server maintenance, no "works on my machine" issues. (5) Security: no SSH access needed, reducing attack surface. Patterns: (1) Kubernetes: deploy new Pods with new image, delete old Pods (rolling update). (2) AWS: create new Auto Scaling Group with new AMI, shift traffic via ALB, delete old ASG. (3) Blue-green: build green environment, switch traffic, delete blue. Immutable does not mean "cannot deploy again" (B). It applies to all infrastructure (C). Performance overhead is minimal (D).',
    tags: ['cicd', 'immutable-infrastructure', 'immutable-deployments', 'reliability', 'rollback', 'consistency'],
  },
  {
    topicSlug: 'cicd',
    difficulty: 'HARD' as const,
    type: 'THEORY' as const,
    question: 'What is semantic versioning (SemVer) and how should it be integrated into CI/CD pipelines?',
    options: [
      'SemVer uses MAJOR.MINOR.PATCH versioning (e.g., 2.5.3); CI/CD should automatically tag releases, update changelogs, and publish versioned artifacts',
      'SemVer is only for libraries, not applications',
      'SemVer means always using version 1.0.0',
      'SemVer is unrelated to CI/CD',
    ],
    correctIndex: 0,
    explanation: 'Semantic Versioning (SemVer) is a versioning scheme: MAJOR.MINOR.PATCH (e.g., 3.2.1). Rules: (1) MAJOR: increment for breaking API changes (v1 → v2). (2) MINOR: increment for backward-compatible new features (v2.0 → v2.1). (3) PATCH: increment for backward-compatible bug fixes (v2.1.0 → v2.1.1). Pre-release: 1.0.0-alpha, 1.0.0-beta.1. CI/CD integration: (1) Commit message conventions: use Conventional Commits (feat:, fix:, chore:, BREAKING CHANGE:) to automatically determine version bump. (2) Automated versioning: tools like semantic-release, standard-version, or GitVersion analyze commit history and compute next version. (3) Tagging: CI creates Git tags (v2.5.3) and GitHub releases. (4) Changelog generation: auto-generate changelog from commit messages. (5) Artifact versioning: Docker images, npm packages tagged with SemVer version. (6) Deployment: deploy specific versions to environments (staging: v2.5.3-rc.1, prod: v2.5.3). SemVer applies to applications, libraries, APIs (B). It is tightly integrated with CI/CD (D).',
    tags: ['cicd', 'semver', 'versioning', 'semantic-release', 'conventional-commits', 'automation'],
  },
  {
    topicSlug: 'cicd',
    difficulty: 'HARD' as const,
    type: 'SCENARIO' as const,
    question: 'Your CI/CD pipeline secrets (AWS keys, database passwords) are stored in plaintext in the pipeline configuration. What is the secure approach?',
    options: [
      'Use secret management services (AWS Secrets Manager, HashiCorp Vault, GitHub Secrets) and inject secrets at runtime without exposing them in logs or code',
      'Encrypt secrets with base64',
      'Store secrets in environment variables in CI configuration',
      'Email secrets to developers',
    ],
    correctIndex: 0,
    explanation: 'Hardcoding secrets in CI configuration is a critical security vulnerability. Secure secret management: (1) Use platform-native secret stores: GitHub Secrets (encrypted at rest), GitLab CI Variables (masked), CircleCI Contexts, AWS Secrets Manager, Azure Key Vault, GCP Secret Manager. (2) Inject secrets at runtime: CI platform fetches secrets and exposes them as environment variables during job execution. (3) Never log secrets: mask secrets in CI logs. Most platforms automatically mask registered secrets. (4) Least privilege: grant CI only the secrets it needs, rotate secrets regularly. (5) External secret management: use HashiCorp Vault or AWS Secrets Manager with dynamic credentials (short-lived tokens generated per CI run). (6) Audit: log secret access for compliance. (7) Do NOT commit secrets to Git: use pre-commit hooks (detect-secrets, git-secrets) to prevent accidental commits. Base64 (B) is encoding, not encryption. Environment variables in config (C) are still exposed. Emailing secrets (D) is insecure. Secret sprawl is a top cause of breaches.',
    tags: ['cicd', 'secrets-management', 'security', 'aws-secrets-manager', 'vault', 'devsecops'],
  },
  {
    topicSlug: 'cicd',
    difficulty: 'HARD' as const,
    type: 'SCENARIO' as const,
    question: 'You need to implement a CI/CD pipeline that deploys to 50 Kubernetes clusters across multiple regions. How do you design this efficiently?',
    options: [
      'Use a hub-and-spoke model with GitOps (ArgoCD, Flux): a central Git repo defines deployments, each cluster has an agent that pulls and applies manifests independently',
      'Run kubectl apply from CI to each cluster sequentially',
      'SSH into each cluster and deploy manually',
      'Multi-cluster deployments are not possible',
    ],
    correctIndex: 0,
    explanation: 'Deploying to many clusters requires a scalable, reliable approach. Recommended architecture: GitOps with ArgoCD or Flux. (1) Hub-and-spoke: Central Git repository (monorepo or multi-repo) contains Kubernetes manifests for all clusters, organized by cluster/region (clusters/us-east-1/, clusters/eu-west-1/). (2) Cluster agents: Each cluster runs an ArgoCD/Flux agent that watches the Git repo and syncs manifests for its cluster. (3) Declarative configuration: cluster-specific overlays using Kustomize or Helm values (cluster-us-east-1-values.yaml). (4) Progressive rollout: deploy to dev clusters first, then staging, then prod in waves (region-by-region). (5) Drift detection: agents detect manual changes and revert them or alert. (6) Secrets: use External Secrets Operator to sync secrets from AWS Secrets Manager/Vault to each cluster. (7) Disaster recovery: if a cluster is destroyed, recreate it and point agent to Git — full restore. Sequential kubectl (B) is slow and does not scale. Manual SSH (C) is error-prone. Multi-cluster deployments are common in enterprise environments (D).',
    tags: ['cicd', 'multi-cluster', 'kubernetes', 'gitops', 'argocd', 'flux', 'scalability'],
  },
  {
    topicSlug: 'cicd',
    difficulty: 'HARD' as const,
    type: 'SCENARIO' as const,
    question: 'Your deployment pipeline must comply with SOC 2 Type II: every production deployment must have an audit trail showing who approved it, when, and what changed. How do you implement this?',
    options: [
      'Use Git as the audit log (all changes via pull requests with approvals), integrate CI/CD with ticketing (Jira), sign commits/tags, and log deployments to immutable audit systems',
      'Keep deployment records in a spreadsheet',
      'Audit trails are not possible in automated CI/CD',
      'Only manual deployments can be audited',
    ],
    correctIndex: 0,
    explanation: 'Compliance-driven CI/CD requires comprehensive audit trails. Implementation: (1) Git as audit log: all production changes via pull requests. PRs include: code diff, commit author, timestamp, reviewer approvals (enforced via branch protection). (2) Commit signing: require GPG-signed commits to prove author identity. (3) Immutable tags: tag releases (v2.5.3) and protect tags from deletion. (4) CI/CD integration: link deployments to tickets (Jira issue ID in commit message). CI updates ticket status on deployment. (5) Deployment logging: log every deployment to an immutable audit system (AWS CloudTrail, Splunk, centralized logging). Include: timestamp, user, Git SHA, environment, approval ticket. (6) Approval gates: require manual approval from authorized personnel before production deployment (recorded in CI logs). (7) Change management: integrate with ITIL/ITSM systems for change requests. (8) Retention: retain audit logs for required period (7 years for SOC 2). Spreadsheets (B) are not auditable or tamper-proof. Automated pipelines are auditable (C). Manual deployments are less auditable than automated (D).',
    tags: ['cicd', 'compliance', 'audit-trail', 'soc2', 'security', 'governance', 'change-management'],
  },
  {
    topicSlug: 'cicd',
    difficulty: 'HARD' as const,
    type: 'SCENARIO' as const,
    question: 'Your CI pipeline builds and pushes Docker images to a registry. An attacker compromises the CI and pushes a backdoored image. How do you prevent this?',
    options: [
      'Use Docker Content Trust to sign images, enforce signature verification in production, use OIDC short-lived tokens instead of long-lived credentials, and enable audit logging',
      'Do not use Docker registries',
      'CI compromise cannot be prevented',
      'Only pull images from Docker Hub',
    ],
    correctIndex: 0,
    explanation: 'Supply chain security for container images requires multiple defenses: (1) Image signing (Docker Content Trust / Notary): sign images with a private key during CI push. In production, enable DCT (DOCKER_CONTENT_TRUST=1) to verify signatures before pulling — unsigned or tampered images are rejected. (2) Short-lived credentials: use OIDC tokens (GitHub Actions OIDC, GitLab CI JWT) to authenticate to registries instead of long-lived access keys. Tokens expire after the job, limiting compromise window. (3) Least privilege: CI should only have push access to specific registries/repositories, not full admin access. (4) Image scanning: scan images in CI for vulnerabilities (Trivy, Snyk, Aqua) and block deployment if critical CVEs detected. (5) Immutable tags: use content-addressable tags (SHA256 digests) instead of mutable tags like "latest". (6) Audit logging: log all registry pushes (who, when, from where). (7) Admission controllers: in Kubernetes, use OPA/Kyverno to enforce only signed images from trusted registries. Avoiding registries (B) is impractical. CI compromise can be mitigated (C). Docker Hub is not inherently more secure (D).',
    tags: ['cicd', 'supply-chain-security', 'docker', 'image-signing', 'content-trust', 'security', 'devsecops'],
  },

  // ─── ADDITIONAL CI/CD QUESTIONS ──────────────────────────────────────────────
  {
    topicSlug: 'cicd',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What is the difference between Continuous Delivery and Continuous Deployment?',
    options: [
      'Continuous Delivery means code is always ready to deploy (requires manual approval), while Continuous Deployment automatically deploys every change to production',
      'They are the same thing',
      'Continuous Deployment requires more manual testing',
      'Continuous Delivery is only for frontend applications',
    ],
    correctIndex: 0,
    explanation: 'Both are stages beyond Continuous Integration: Continuous Delivery (CD): code changes are automatically built, tested, and prepared for release. Deployment to production requires a manual approval step. The code is always in a deployable state, but humans decide when to release. Continuous Deployment: every code change that passes automated tests is automatically deployed to production without human intervention. No manual gates between merge and production. Requirements for Continuous Deployment: (1) Comprehensive automated testing (unit, integration, e2e). (2) Feature flags for incomplete features. (3) Robust monitoring and rollback capabilities. (4) High organizational trust in automation. Most companies start with Continuous Delivery and evolve to Continuous Deployment as their testing and monitoring mature. They are not the same (B). CD actually requires more automated testing (C). Both apply to all application types (D).',
    tags: ['cicd', 'continuous-delivery', 'continuous-deployment', 'devops', 'automation'],
  },
  {
    topicSlug: 'cicd',
    difficulty: 'MEDIUM' as const,
    type: 'THEORY' as const,
    question: 'What is trunk-based development and how does it differ from GitFlow?',
    options: [
      'Trunk-based development uses a single main branch with short-lived feature branches, enabling faster CI/CD; GitFlow uses multiple long-lived branches (develop, release, hotfix)',
      'Trunk-based development is the same as GitFlow',
      'GitFlow is better for continuous deployment',
      'Trunk-based development does not support feature branches',
    ],
    correctIndex: 0,
    explanation: 'Trunk-based development (TBD): (1) Single main branch (trunk/main). (2) Short-lived feature branches (< 1-2 days). (3) Frequent merges to main (multiple times per day). (4) Feature flags hide incomplete features. (5) Everyone commits to the same branch, reducing merge conflicts. Best for: CI/CD, continuous deployment, high release frequency. GitFlow: (1) Multiple long-lived branches: main, develop, feature/*, release/*, hotfix/*. (2) Features branch off develop, merge back when complete. (3) Release branches for stabilization. (4) Complex merge process. Best for: infrequent releases, strict versioning, regulated environments. Trade-offs: TBD enables faster deployment cycles but requires feature flags and robust testing. GitFlow provides more control but creates merge conflicts and slows deployment. Modern DevOps teams generally prefer TBD. They are different (B). TBD is better for continuous deployment (C). TBD supports short-lived feature branches (D).',
    tags: ['cicd', 'trunk-based-development', 'gitflow', 'branching', 'git', 'devops'],
  },
  {
    topicSlug: 'cicd',
    difficulty: 'MEDIUM' as const,
    type: 'THEORY' as const,
    question: 'What are GitHub Actions reusable workflows and composite actions, and when would you use each?',
    options: [
      'Reusable workflows are called as complete jobs from other workflows; composite actions combine multiple steps into a single action. Use reusable workflows for job-level reuse, composite actions for step-level reuse',
      'They are the same thing',
      'Composite actions can only contain shell scripts',
      'Reusable workflows cannot accept inputs',
    ],
    correctIndex: 0,
    explanation: 'GitHub Actions offers two reusability patterns: Reusable workflows: (1) Called from other workflows with uses: org/repo/.github/workflows/file.yml@main. (2) Run as separate jobs with their own runners. (3) Accept inputs and secrets. (4) Good for: standardizing CI/CD across repos (deploy workflow, security scan workflow). (5) Example: a central "deploy-to-k8s" workflow used by all microservices. Composite actions: (1) Bundle multiple steps into a single action. (2) Run in the same job as the caller. (3) Can mix shell scripts and other actions. (4) Defined in action.yml with runs: using: composite. (5) Good for: reusable step sequences (setup, build, test steps). (6) Example: a "setup-node-with-cache" action combining node setup and npm caching. Key difference: reusable workflows = job-level, composite actions = step-level. They solve different problems (B). Composite actions can include other actions (C). Reusable workflows accept inputs (D).',
    tags: ['cicd', 'github-actions', 'reusable-workflows', 'composite-actions', 'automation'],
  },
  {
    topicSlug: 'cicd',
    difficulty: 'MEDIUM' as const,
    type: 'SCENARIO' as const,
    question: 'Your CI pipeline takes 45 minutes to run, slowing down development. What strategies can you use to reduce the build time?',
    options: [
      'Parallelize independent jobs, use caching for dependencies, run only affected tests, use larger runners, and implement incremental builds',
      'Run fewer tests to save time',
      'Build times cannot be improved',
      'Skip CI for some commits',
    ],
    correctIndex: 0,
    explanation: 'CI pipeline optimization strategies: (1) Parallelization: split tests into parallel jobs. Use matrix builds (test on multiple node versions simultaneously). Run lint, unit tests, and e2e tests concurrently. (2) Caching: cache node_modules, pip packages, Docker layers. Example: actions/cache for npm. Saves minutes on every build. (3) Incremental testing: only run tests affected by changed files. Tools: jest --changedSince, nx affected:test. (4) Larger/faster runners: use GitHub larger runners (16 cores vs 2 cores), or self-hosted runners with more resources. (5) Docker layer caching: use BuildKit cache mounts, cache base images. (6) Test sharding: distribute tests across multiple runners (Playwright sharding, Jest projects). (7) Pre-built base images: do not install dependencies every build — use a base image with common tools pre-installed. (8) Skip unnecessary work: do not rebuild if only docs changed. Removing tests (B) reduces quality. Times are improvable (C). Skipping CI breaks the feedback loop (D).',
    tags: ['cicd', 'optimization', 'performance', 'caching', 'parallelization', 'build-time'],
  },
  {
    topicSlug: 'cicd',
    difficulty: 'HARD' as const,
    type: 'THEORY' as const,
    question: 'What is SLSA (Supply chain Levels for Software Artifacts) and how does it apply to CI/CD pipelines?',
    options: [
      'SLSA is a security framework defining levels of supply chain integrity, from basic build provenance (Level 1) to fully hermetic, reproducible builds with signed attestations (Level 4)',
      'SLSA is a logging framework for CI/CD',
      'SLSA is only relevant for open-source projects',
      'SLSA replaces all CI/CD testing',
    ],
    correctIndex: 0,
    explanation: 'SLSA (pronounced "salsa") is a security framework for software supply chain integrity, developed by Google. Levels: Level 1: Build process is documented, producing provenance (metadata about how artifacts were built). Level 2: Builds run on a hosted service, provenance is signed, source and build are tamper-resistant. Level 3: Build process is hardened with isolated builds, provenance is unforgeable, dependencies are tracked. Level 4: Hermetic, reproducible builds with two-party review, full dependency graph, maximum tamper resistance. Implementation in CI/CD: (1) Generate SLSA provenance during builds (slsa-github-generator, sigstore). (2) Sign provenance with Sigstore/cosign. (3) Verify provenance before deployment. (4) Store provenance alongside artifacts. Benefits: (1) Detect tampered artifacts. (2) Prove where/how artifacts were built. (3) Meet compliance requirements. (4) Respond to supply chain attacks (like SolarWinds). SLSA is not logging (B). It applies to all software (C). It complements, not replaces, testing (D).',
    tags: ['cicd', 'slsa', 'supply-chain-security', 'provenance', 'sigstore', 'security'],
  },
  {
    topicSlug: 'cicd',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What is a CI/CD artifact and why is artifact versioning important?',
    options: [
      'Artifacts are build outputs (Docker images, JAR files, binaries) stored for deployment; versioning enables traceability, rollback, and ensures the same artifact is deployed across environments',
      'Artifacts are source code files',
      'Artifacts should be rebuilt for each environment',
      'Artifact versioning is only needed for production',
    ],
    correctIndex: 0,
    explanation: 'Artifacts are the output of the build process: Docker images, JAR/WAR files, npm packages, compiled binaries, Helm charts. Versioning importance: (1) Traceability: know exactly what code is running in production (git SHA, version tag). (2) Rollback: revert to a previous artifact if deployment fails. (3) Consistency: the same artifact deploys to dev, staging, prod — no "works on my machine" issues. (4) Auditing: compliance requires knowing what was deployed when. Best practices: (1) Immutable artifacts: once built, never modify. Tag with version or git SHA. (2) Single artifact per build: do not rebuild for each environment — same artifact, different config. (3) Store in artifact repository: Docker registry (ECR, Docker Hub), package registry (npm, Maven), object storage (S3). (4) Semantic versioning: major.minor.patch for releases. (5) Retention policy: keep artifacts for rollback period, then clean up. Artifacts are built outputs, not source (B). Never rebuild for different environments (C). Versioning is needed everywhere (D).',
    tags: ['cicd', 'artifacts', 'versioning', 'docker', 'deployment', 'traceability'],
  },
];
