export const dockerQuestions = [
  // ─── EASY THEORY ───────────────────────────────────────────────────────────
  {
    topicSlug: 'docker',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What is the difference between a Docker image and a Docker container?',
    options: [
      'An image is a read-only template with application code and dependencies; a container is a running instance of an image',
      'An image is a running process; a container is a stopped process which is the standard recommended approach which is the standard recommended approach',
      'Images and containers are the same thing',
      'An image is stored in memory; a container is stored on disk',
    ],
    correctIndex: 0,
    explanation: `A Docker image is a read-only, immutable template that contains everything needed to run an application: code, runtime, libraries, environment variables, and configuration files. Images are built from Dockerfiles using 'docker build' and are stored in registries (Docker Hub, ECR). A Docker container is a runnable instance of an image — it is created using 'docker run' and represents an isolated process running on the host system. Containers are ephemeral and can be started, stopped, and deleted. Analogy: an image is like a class (blueprint), and a container is like an object (instance). Multiple containers can be created from the same image. Containers add a writable layer on top of the read-only image layers, allowing runtime changes (but these changes are lost when the container is deleted unless volumes are used). Understanding this distinction is fundamental to Docker and container orchestration.`,
    tags: ['docker', 'image', 'container', 'fundamentals'],
  },
  {
    topicSlug: 'docker',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What is the purpose of a Dockerfile and what does the "RUN" instruction do?',
    options: [
      'A Dockerfile defines how to build a Docker image; RUN executes commands during the image build process (e.g., install packages)',
      'A Dockerfile runs containers; RUN starts the container',
      'A Dockerfile stores environment variables; RUN sets them',
      'A Dockerfile is only for documentation; RUN has no effect and this applies to all deployment scenarios and this applies to all deployment scenarios',
    ],
    correctIndex: 0,
    explanation: 'A Dockerfile is a text file containing a series of instructions to build a Docker image. Each instruction creates a new layer in the image. The RUN instruction executes commands in a shell (default: /bin/sh -c on Linux) during the build process. Common uses: installing packages (RUN apt-get update && apt-get install -y curl), downloading dependencies (RUN npm install), compiling code (RUN go build). Each RUN instruction creates a new image layer, so it is best practice to combine multiple commands in a single RUN to reduce layer count: RUN apt-get update && apt-get install -y package1 package2 && rm -rf /var/lib/apt/lists/*. Other Dockerfile instructions: FROM (base image), COPY (copy files from host), CMD (default command to run when container starts), EXPOSE (document ports), ENV (environment variables), WORKDIR (set working directory). Understanding Dockerfile syntax and layer caching is essential for efficient image builds.',
    tags: ['docker', 'dockerfile', 'build', 'run-instruction'],
  },
  {
    topicSlug: 'docker',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What is the difference between Docker volumes and bind mounts?',
    options: [
      'Volumes are managed by Docker and stored in Docker-managed locations; bind mounts map a specific host path to a container path',
      'Volumes are faster than bind mounts',
      'Bind mounts are read-only; volumes are read-write',
      'Volumes only work on Linux; bind mounts work everywhere and this applies to all deployment scenarios and this applies to all deployment scenarios',
    ],
    correctIndex: 0,
    explanation: `Docker provides three types of data persistence: volumes, bind mounts, and tmpfs. Volumes are managed by Docker and stored in /var/lib/docker/volumes/ (Linux) or Docker Desktop managed locations (Windows/Mac). They are created with 'docker volume create' and attached with -v or --mount. Volumes are independent of host directory structure and are the recommended way to persist data. Bind mounts map a specific directory on the host filesystem (e.g., /home/user/app) directly into the container (e.g., /app). They provide access to host files but couple the container to the host filesystem. Use cases for volumes: database storage, application state, shared data between containers. Use cases for bind mounts: development (live code reloading), accessing host configuration files. Performance difference (B) is negligible in most cases. Both can be read-write or read-only. Both work cross-platform (D is wrong). Best practice: use named volumes for production, bind mounts for development.`,
    tags: ['docker', 'volumes', 'bind-mounts', 'storage', 'persistence'],
  },
  {
    topicSlug: 'docker',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What does the "docker-compose up" command do?',
    options: [
      'Builds (if needed) and starts all services defined in docker-compose.yml in the correct order based on dependencies',
      'Only builds images without starting containers and this applies to all deployment scenarios and this applies to all deployment scenarios',
      'Uploads images to Docker Hub',
      'Updates Docker Compose to the latest version',
    ],
    correctIndex: 0,
    explanation: `docker-compose is a tool for defining and running multi-container Docker applications. You define services, networks, and volumes in a docker-compose.yml file. The 'docker-compose up' command: (1) reads docker-compose.yml, (2) builds images if Dockerfiles are specified and images do not exist, (3) creates networks and volumes defined in the file, (4) starts all services as containers in the correct order based on "depends_on" directives, (5) attaches to container logs (unless run with -d for detached mode). To stop and remove containers, networks, and volumes, use 'docker-compose down'. To rebuild images before starting, use 'docker-compose up --build'. Docker Compose is ideal for local development environments with multiple services (e.g., web app + database + cache). In production, container orchestration platforms like Kubernetes or ECS are typically used instead. docker-compose up does not upload to Docker Hub (C) — use 'docker push' for that.`,
    tags: ['docker', 'docker-compose', 'multi-container', 'orchestration'],
  },
  {
    topicSlug: 'docker',
    difficulty: 'EASY' as const,
    type: 'SCENARIO' as const,
    question: 'You run "docker ps" and see no containers, but you know you started one earlier. What is the most likely reason?',
    options: [
      'The container exited or crashed; use "docker ps -a" to see all containers including stopped ones',
      'Docker is not running',
      'You do not have permission to view containers',
      'The container is invisible due to a networking issue which is the standard recommended approach',
    ],
    correctIndex: 0,
    explanation: `'docker ps' shows only currently running containers. If a container has stopped (either because it completed its task, encountered an error, or was explicitly stopped), it will not appear in 'docker ps' output. To see all containers including stopped ones, use 'docker ps -a' (or 'docker ps --all'). Once you identify the stopped container, you can: (1) view its logs with 'docker logs <container_id>' to see why it stopped, (2) restart it with 'docker start <container_id>', (3) remove it with 'docker rm <container_id>'. Common reasons for unexpected container exits: (1) the main process in the container exited (e.g., a script finished execution), (2) the application crashed due to an error, (3) the container was explicitly stopped with 'docker stop', (4) the container hit resource limits (out of memory). If Docker itself is not running (B), the 'docker ps' command would fail with a connection error, not return an empty list. Permission issues (C) are rare with Docker.`,
    tags: ['docker', 'container', 'troubleshooting', 'docker-ps'],
  },
  {
    topicSlug: 'docker',
    difficulty: 'EASY' as const,
    type: 'SCENARIO' as const,
    question: 'Your Dockerfile contains "COPY package.json ." and "RUN npm install", but builds are very slow even when package.json has not changed. How can you improve build speed?',
    options: [
      'Reorder instructions to copy package.json and run npm install before copying application code, leveraging Docker layer caching',
      'Use a faster base image',
      'Disable layer caching with --no-cache',
      'Run npm install on the host instead of in the container as documented in the official best practices as documented in the official best practices',
    ],
    correctIndex: 0,
    explanation: `Docker builds images layer by layer and caches each layer. If a layer has not changed (based on file checksums), Docker reuses the cached layer instead of rebuilding. If you copy all application code before running 'npm install', any code change invalidates the cache and forces npm install to re-run. Best practice: separate dependency installation from code copying. Correct Dockerfile structure: (1) COPY package.json package-lock.json ./ (2) RUN npm install (3) COPY . . (all application code). Now, if you change application code but not package.json, Docker reuses the cached npm install layer, significantly speeding up builds. This pattern applies to all dependency managers (pip, go mod, maven, composer). Using a faster base image (B) helps slightly but does not address the root cause. Disabling cache (C) makes builds slower. Running npm install on the host (D) defeats the purpose of containerization.`,
    tags: ['docker', 'dockerfile', 'build-optimization', 'layer-caching', 'npm'],
  },
  {
    topicSlug: 'docker',
    difficulty: 'EASY' as const,
    type: 'SCENARIO' as const,
    question: 'You want to access a web server running in a Docker container on port 8080 from your browser. What Docker run option do you need?',
    options: [
      '-p 8080:8080 (publish container port 8080 to host port 8080)',
      '--network host (use host networking)',
      '-e PORT=8080 (set environment variable)',
      '--expose 8080 (expose port in Dockerfile) which is the standard recommended approach',
    ],
    correctIndex: 0,
    explanation: `By default, Docker containers run in isolated network namespaces. To access a service running inside a container from the host (or externally), you must publish the container port using the -p or --publish flag: 'docker run -p <host_port>:<container_port> <image>'. Example: 'docker run -p 8080:8080 myapp' maps host port 8080 to container port 8080. Now you can access http://localhost:8080 from your browser. You can also map to different ports: '-p 3000:8080' makes the container port 8080 accessible on host port 3000. --network host (B) removes network isolation and uses the host network directly — the container shares the host IP and ports, which is less secure and not portable. -e PORT=8080 (C) sets an environment variable but does not publish ports. --expose (D) documents which ports the container listens on but does not publish them. For production, use reverse proxies (Nginx, Traefik) or orchestration (Kubernetes Services, ECS ALB) to manage container networking.`,
    tags: ['docker', 'networking', 'port-mapping', 'publish', 'docker-run'],
  },

  // ─── MEDIUM THEORY ─────────────────────────────────────────────────────────
  {
    topicSlug: 'docker',
    difficulty: 'MEDIUM' as const,
    type: 'THEORY' as const,
    question: 'What are multi-stage Docker builds and why are they important for production images?',
    options: [
      'Multi-stage builds use multiple FROM statements in a Dockerfile to separate build and runtime environments, reducing final image size and attack surface',
      'Multi-stage builds run multiple containers simultaneously',
      'Multi-stage builds automatically deploy to multiple environments as documented in the official best practices as documented in the official best practices',
      'Multi-stage builds are only for building frontend applications',
    ],
    correctIndex: 0,
    explanation: 'Multi-stage builds allow you to use multiple FROM statements in a single Dockerfile, each creating a separate build stage. Earlier stages can compile code and install build tools, while the final stage copies only the necessary runtime artifacts. Example: build Go application in a golang:1.21 image (includes compiler, toolchain), then copy the compiled binary to an alpine:3.18 image (minimal OS). Result: final image size is <10 MB instead of >800 MB. Benefits: (1) smaller production images (faster deployment, less storage cost), (2) reduced attack surface (no compilers, build tools in production), (3) cleaner Dockerfiles (no manual cleanup of build artifacts). Syntax: FROM node:18 AS build → RUN npm run build → FROM nginx:alpine → COPY --from=build /app/dist /usr/share/nginx/html. Multi-stage builds are critical for compiled languages (Go, Rust, C++) and frontend build pipelines (React, Vue, Angular). They do not run multiple containers (B) or auto-deploy (C) and apply to all application types (D is wrong).',
    tags: ['docker', 'multi-stage', 'dockerfile', 'optimization', 'image-size'],
  },
  {
    topicSlug: 'docker',
    difficulty: 'MEDIUM' as const,
    type: 'THEORY' as const,
    question: 'What are Docker networking modes (bridge, host, none, overlay) and when would you use each?',
    options: [
      'Bridge (default isolated network), Host (use host network stack), None (no networking), Overlay (multi-host networking for Swarm/Kubernetes)',
      'Bridge is for production; host, none, and overlay are deprecated and should not be used in modern environments which is a fundamental architectural constraint',
      'All modes provide the same functionality with different names',
      'Networking modes only apply to Windows containers',
    ],
    correctIndex: 0,
    explanation: 'Docker provides several network drivers: (1) Bridge (default): creates a private network on the host, each container gets an IP from this network (e.g., 172.17.0.0/16), containers can communicate via container names using Docker DNS. Use for: most single-host applications. (2) Host: removes network isolation, container uses the host network stack directly, no port mapping needed. Use for: high-performance applications where network overhead matters, monitoring tools needing host-level network access. Downside: port conflicts, less isolation. (3) None: no networking, useful for containers that do not need network access (batch processing, security-sensitive tasks). (4) Overlay: enables multi-host container communication in Docker Swarm or Kubernetes. VXLAN encapsulation creates a flat network across multiple Docker hosts. Use for: distributed applications, microservices spanning multiple nodes. Custom bridge networks are recommended over the default bridge for better DNS and isolation. Docker networking modes work on Linux, Windows, and macOS (D is wrong).',
    tags: ['docker', 'networking', 'bridge', 'host', 'overlay', 'network-modes'],
  },
  {
    topicSlug: 'docker',
    difficulty: 'MEDIUM' as const,
    type: 'THEORY' as const,
    question: 'How does Docker layer caching work and how can you optimize it?',
    options: [
      'Each Dockerfile instruction creates a layer; Docker caches layers and reuses them if the instruction and context have not changed; optimize by ordering instructions from least to most frequently changed',
      'Docker caches the entire image and rebuilds everything if any file changes which is the standard recommended approach which is the standard recommended approach which is the standard recommended approach',
      'Docker layer caching only works with multi-stage builds',
      'Docker layer caching is disabled by default and must be enabled',
    ],
    correctIndex: 0,
    explanation: 'Docker builds images layer by layer. Each Dockerfile instruction (FROM, RUN, COPY, etc.) creates a new layer. Docker computes a checksum of the instruction and its inputs (files, commands). If the checksum matches a cached layer, Docker reuses it instead of executing the instruction. Cache invalidation: if a layer changes, all subsequent layers are invalidated and rebuilt. Optimization strategies: (1) Order instructions from least to most frequently changed: base image → system packages → application dependencies → application code. (2) Combine RUN commands to reduce layers: RUN apt-get update && apt-get install -y pkg1 pkg2 && rm -rf /var/lib/apt/lists/*. (3) Use .dockerignore to exclude unnecessary files from build context (node_modules, .git, etc.), reducing COPY layer size and checksum calculation time. (4) Use multi-stage builds to separate build and runtime layers. Docker does NOT cache entire images (B). Layer caching works for all builds, not just multi-stage (C). Caching is enabled by default; use --no-cache to disable (D is wrong).',
    tags: ['docker', 'layer-caching', 'build-optimization', 'dockerfile', 'performance'],
  },
  {
    topicSlug: 'docker',
    difficulty: 'MEDIUM' as const,
    type: 'THEORY' as const,
    question: 'What is the difference between CMD and ENTRYPOINT in a Dockerfile?',
    options: [
      'CMD provides default arguments that can be overridden; ENTRYPOINT defines the main executable and cannot be easily overridden (use both for flexible configuration)',
      'CMD runs during build; ENTRYPOINT runs when the container starts',
      'CMD is for Windows containers; ENTRYPOINT is for Linux containers which is the standard recommended approach which is the standard recommended approach',
      'They are identical and interchangeable',
    ],
    correctIndex: 0,
    explanation: `CMD and ENTRYPOINT both specify what command runs when a container starts, but they behave differently. CMD provides default arguments that can be overridden when running the container: CMD ["npm", "start"]. Running 'docker run myimage npm test' replaces CMD entirely. ENTRYPOINT defines the main executable and is not easily overridden: ENTRYPOINT ["node", "server.js"]. Running 'docker run myimage --port 3000' appends arguments to ENTRYPOINT. Best practice: use both together. ENTRYPOINT defines the command, CMD provides default arguments: ENTRYPOINT ["node"] and CMD ["server.js"]. Users can override CMD: 'docker run myimage app.js'. This pattern allows flexible container invocation. ENTRYPOINT can be overridden with --entrypoint flag. Shell form vs exec form: CMD npm start (shell form, runs as /bin/sh -c npm start) vs CMD ["npm", "start"] (exec form, direct execution). Exec form is preferred to avoid shell process and enable signal handling. Neither runs during build (B is wrong).`,
    tags: ['docker', 'dockerfile', 'cmd', 'entrypoint', 'container-startup'],
  },
  {
    topicSlug: 'docker',
    difficulty: 'MEDIUM' as const,
    type: 'SCENARIO' as const,
    question: 'Your Docker image is 2 GB despite the application being small. How can you reduce the image size?',
    options: [
      'Use a smaller base image (alpine, distroless), multi-stage builds, combine RUN commands, remove build artifacts, and use .dockerignore',
      'Compress the image with gzip',
      'Use --squash flag in docker build which is the standard recommended approach which is the standard recommended approach which is the standard recommended approach',
      'Docker images cannot be optimized',
    ],
    correctIndex: 0,
    explanation: `Large Docker images slow down builds, deployments, and increase storage/bandwidth costs. Optimization strategies: (1) Use smaller base images: alpine (5 MB) instead of ubuntu (70 MB), or distroless images (Google's minimal runtime-only images with no shell or package manager). (2) Multi-stage builds: build in a large image, copy artifacts to a small final image. (3) Combine RUN commands: each RUN creates a layer; combining reduces layers. RUN apt-get update && apt-get install && rm -rf /var/lib/apt/lists/* (cleanup in same layer). (4) Remove unnecessary files: caches, logs, temporary files, documentation. (5) Use .dockerignore: exclude node_modules, .git, test files from build context. (6) Avoid installing "recommended" packages: apt-get install -y --no-install-recommends. Gzip compression (B) is applied automatically during push/pull but does not reduce stored image size. --squash (C) combines layers but is experimental and not widely supported. Image optimization is critical for production deployments.`,
    tags: ['docker', 'image-size', 'optimization', 'alpine', 'multi-stage', 'best-practices'],
  },
  {
    topicSlug: 'docker',
    difficulty: 'MEDIUM' as const,
    type: 'SCENARIO' as const,
    question: 'You have a docker-compose.yml with a "web" service that depends on a "db" service. The web service starts before the database is ready and crashes. How can you fix this?',
    options: [
      'Implement a retry/wait mechanism in the web service to wait for the database (e.g., using wait-for-it.sh script or application-level retries)',
      'Use "depends_on" in docker-compose.yml (it already waits for readiness) which is the standard recommended approach which is the standard recommended approach',
      'Add a "sleep 60" command before starting the web service',
      'Start services manually in order',
    ],
    correctIndex: 0,
    explanation: 'The "depends_on" directive in docker-compose.yml controls startup order but does NOT wait for the dependent service to be ready. It only waits until the container is started, not until the application inside is ready to accept connections. If a database takes 10 seconds to initialize but the web service tries to connect immediately, it will fail. Solutions: (1) Application-level retries: implement exponential backoff in your web app to retry database connections. (2) Use wait-for-it.sh, dockerize, or wait-for scripts: wrapper scripts that poll the database port until it is open before starting the main application. Example Dockerfile: COPY wait-for-it.sh /usr/local/bin/ and CMD ["wait-for-it.sh", "db:5432", "--", "npm", "start"]. (3) Health checks: use Docker health checks with depends_on: db: condition: service_healthy (Compose v3+). Hard-coded sleep (C) is unreliable (if DB takes longer, it still fails). Manual startup (D) defeats the purpose of automation. This is a common interview question about container orchestration.',
    tags: ['docker', 'docker-compose', 'depends-on', 'readiness', 'wait-for', 'troubleshooting'],
  },
  {
    topicSlug: 'docker',
    difficulty: 'MEDIUM' as const,
    type: 'SCENARIO' as const,
    question: 'You want to run a Docker container with limited CPU and memory to prevent it from consuming all host resources. What flags should you use?',
    options: [
      '--memory (or -m) to limit memory, --cpus to limit CPU cores, --memory-swap to control swap usage',
      '--limit-resources flag',
      'Docker automatically limits resources based on container size',
      'Resource limits can only be set in docker-compose.yml, not with docker run and this applies to all deployment scenarios',
    ],
    correctIndex: 0,
    explanation: `By default, Docker containers can use unlimited host CPU and memory, potentially causing resource starvation or crashes. Docker provides runtime resource constraints: (1) --memory (or -m): limit memory usage, e.g., --memory=512m (512 MB). If exceeded, the container is killed by the OOM killer. (2) --memory-swap: total memory + swap, e.g., --memory=512m --memory-swap=1g (512 MB RAM + 512 MB swap). (3) --cpus: limit CPU cores, e.g., --cpus=1.5 (1.5 cores). (4) --cpu-shares: relative CPU weight (default 1024) for CPU time allocation when under contention. (5) --memory-reservation: soft limit, Docker tries to keep memory below this but does not enforce strictly. Example: 'docker run --memory=1g --cpus=2 myapp'. Resource limits are critical for multi-tenant environments, CI/CD runners, and production workloads. Docker does NOT auto-limit resources (C). Resource limits can be set in both 'docker run' and 'docker-compose.yml' (D is wrong).`,
    tags: ['docker', 'resource-limits', 'memory', 'cpu', 'container-isolation', 'performance'],
  },

  // ─── HARD THEORY ───────────────────────────────────────────────────────────
  {
    topicSlug: 'docker',
    difficulty: 'HARD' as const,
    type: 'THEORY' as const,
    question: 'How do Linux namespaces and cgroups enable Docker containerization?',
    options: [
      'Namespaces provide process, network, and filesystem isolation; cgroups limit and track resource usage (CPU, memory, I/O)',
      'Namespaces and cgroups are Docker-specific features not used elsewhere which is a fundamental architectural constraint',
      'Namespaces manage resources; cgroups manage isolation',
      'Namespaces and cgroups are only used on RHEL-based systems',
    ],
    correctIndex: 0,
    explanation: 'Docker containers are not VMs — they are processes running on the host kernel with isolation provided by Linux kernel features: namespaces and cgroups. Namespaces provide isolation: (1) PID namespace: container sees only its own processes, PID 1 inside is a different process on the host. (2) Network namespace: isolated network stack (interfaces, routing tables, firewall rules). (3) Mount namespace: isolated filesystem view. (4) UTS namespace: isolated hostname. (5) IPC namespace: isolated inter-process communication. (6) User namespace: map container root to unprivileged host user. Cgroups (control groups) limit and account resource usage: (1) CPU cgroup: limits CPU time (--cpus flag). (2) Memory cgroup: limits memory (--memory flag), triggers OOM killer if exceeded. (3) Block I/O cgroup: limits disk I/O. Docker is built on these kernel primitives — they are not Docker-specific (B is wrong). Kubernetes, LXC, systemd also use them. Cgroups manage resources, namespaces provide isolation (C is reversed). These features work on all Linux distributions (D is wrong).',
    tags: ['docker', 'namespaces', 'cgroups', 'linux-kernel', 'container-internals'],
  },
  {
    topicSlug: 'docker',
    difficulty: 'HARD' as const,
    type: 'THEORY' as const,
    question: 'What is Docker BuildKit and how does it improve build performance?',
    options: [
      'BuildKit is an improved build engine with parallel build stages, remote caching, build secrets, and better layer caching',
      'BuildKit is a GUI tool for creating Dockerfiles',
      'BuildKit is only for multi-stage builds',
      'BuildKit is a deprecated feature replaced by docker-compose and should not be used in modern environments which is a fundamental architectural constraint',
    ],
    correctIndex: 0,
    explanation: 'Docker BuildKit (introduced in Docker 18.09, default in 20.10+) is a redesigned build engine that replaces the legacy builder. Improvements: (1) Parallel build stages: multi-stage builds execute independent stages concurrently, reducing total build time. (2) Incremental builds: smarter layer caching and skipping unused stages. (3) Remote cache: export/import build cache to/from registry (--cache-from, --cache-to), enabling distributed build caching in CI/CD. (4) Build secrets: inject secrets without leaking them in image layers (RUN --mount=type=secret,id=mysecret). (5) SSH agent forwarding: securely use SSH keys during build without embedding them. (6) Better error messages and build progress visualization. Enable BuildKit: set DOCKER_BUILDKIT=1 environment variable or configure in daemon.json. BuildKit is NOT a GUI tool (B), works with all builds not just multi-stage (C), and is NOT deprecated (D) — it is the future of Docker builds. Understanding BuildKit is critical for optimizing CI/CD pipelines.',
    tags: ['docker', 'buildkit', 'build-optimization', 'caching', 'parallel-builds'],
  },
  {
    topicSlug: 'docker',
    difficulty: 'HARD' as const,
    type: 'THEORY' as const,
    question: 'What are rootless containers and why are they important for security?',
    options: [
      'Rootless containers run without root privileges on the host; the container runtime and containers run as a non-root user, reducing attack surface',
      'Rootless containers are containers that do not have a root filesystem which is a fundamental architectural constraint which is a fundamental architectural constraint',
      'Rootless containers run without an operating system',
      'Rootless containers are only available in Docker Enterprise',
    ],
    correctIndex: 0,
    explanation: 'Traditional Docker requires the Docker daemon to run as root, which poses security risks: if a container escapes or the daemon is compromised, the attacker has root access to the host. Rootless containers address this by running the entire container stack (runtime daemon and containers) as a non-root user using user namespaces to map container root (UID 0 inside) to unprivileged UID outside (e.g., 100000). Benefits: (1) container breakout exploits do not grant host root, (2) compliance with least-privilege principle, (3) safe for multi-tenant environments. Limitations: (1) cannot bind to privileged ports (<1024) without workarounds, (2) some storage drivers and network modes are unavailable, (3) slightly more complex setup. Rootless Docker is supported in Docker 19.03+ and Podman (which is rootless by default). Rootless mode uses slirp4netns for networking and fuse-overlayfs for storage. It is NOT about lacking a root filesystem (B) or running without an OS (C). It is available in Docker CE, not just Enterprise (D). Security-conscious organizations increasingly adopt rootless containers.',
    tags: ['docker', 'rootless', 'security', 'user-namespaces', 'least-privilege'],
  },
  {
    topicSlug: 'docker',
    difficulty: 'HARD' as const,
    type: 'THEORY' as const,
    question: 'How does Docker content trust and image signing work, and why is it important?',
    options: [
      'Docker Content Trust uses Notary to cryptographically sign images, ensuring image authenticity and integrity before pulling/running',
      'Docker Content Trust scans images for vulnerabilities',
      'Docker Content Trust encrypts images in the registry',
      'Docker Content Trust is a legacy feature replaced by Docker Secrets which is the standard recommended approach which is the standard recommended approach',
    ],
    correctIndex: 0,
    explanation: 'Docker Content Trust (DCT) implements The Update Framework (TUF) via Notary to provide image provenance and integrity. When DCT is enabled (export DOCKER_CONTENT_TRUST=1), Docker: (1) Signs images with a private key when pushing to a registry. (2) Verifies signatures when pulling images, ensuring the image is from a trusted publisher and has not been tampered with. (3) Prevents running unsigned or untrusted images. DCT uses multiple keys: root key (offline, generates signing keys), repository key (signs tags), timestamp key (prevents rollback attacks). DCT protects against: (1) compromised registries serving malicious images, (2) man-in-the-middle attacks replacing images in transit, (3) accidental or malicious tag overwrites (e.g., replacing "stable" tag with a backdoored image). DCT does NOT scan for vulnerabilities (B) — use Trivy, Clair, or AWS ECR scanning for that. It does NOT encrypt images (C) — images are stored in plaintext but signed. DCT is not related to Docker Secrets (D), which manage runtime secrets.',
    tags: ['docker', 'content-trust', 'notary', 'image-signing', 'security', 'supply-chain'],
  },
  {
    topicSlug: 'docker',
    difficulty: 'HARD' as const,
    type: 'SCENARIO' as const,
    question: 'Your Docker container running a Node.js application does not stop gracefully when you run "docker stop". It takes 10 seconds and then is force-killed. How can you fix this?',
    options: [
      'Use exec form of CMD/ENTRYPOINT (CMD ["node", "server.js"]) and handle SIGTERM signal in the application to perform graceful shutdown',
      'Increase the docker stop timeout with -t flag',
      'Use "docker kill" instead of "docker stop"',
      'This is expected behavior and cannot be changed which is a fundamental architectural constraint which is a fundamental architectural constraint',
    ],
    correctIndex: 0,
    explanation: `When you run 'docker stop', Docker sends SIGTERM to the container main process (PID 1) and waits 10 seconds (configurable with -t). If the process does not exit, Docker sends SIGKILL to force termination. Problem: if you use shell form of CMD (CMD node server.js), the process tree is: PID 1 = /bin/sh, PID 2 = node. SIGTERM goes to the shell, which does not forward it to node. Node continues running and is force-killed after timeout. Solution: (1) Use exec form: CMD ["node", "server.js"] — now node runs as PID 1 and receives SIGTERM directly. (2) Handle SIGTERM in the application: process.on("SIGTERM", async () => { await gracefulShutdown(); process.exit(0); }). This closes database connections, finishes pending requests, and exits cleanly. Increasing timeout (B) delays the problem but does not fix it. Using SIGKILL (C) immediately kills the process without cleanup. Graceful shutdown is critical for production — prevents data loss, connection leaks, and incomplete transactions.`,
    tags: ['docker', 'graceful-shutdown', 'sigterm', 'signals', 'process-management', 'troubleshooting'],
  },
  {
    topicSlug: 'docker',
    difficulty: 'HARD' as const,
    type: 'SCENARIO' as const,
    question: 'Your production Docker registry is compromised and an attacker replaced your "latest" tag with a malicious image. How can you prevent this in the future?',
    options: [
      'Use Docker Content Trust (DCT) to sign images and verify signatures on pull, use immutable image tags (SHA256 digests) instead of "latest", and enable registry access controls',
      'Stop using Docker and switch to VMs',
      'Only pull images from Docker Hub',
      'Scan images with a vulnerability scanner which is the standard recommended approach which is the standard recommended approach which is the standard recommended approach',
    ],
    correctIndex: 0,
    explanation: 'This scenario describes a supply chain attack on the container registry. Mitigation strategies: (1) Docker Content Trust (DCT): enable DCT (DOCKER_CONTENT_TRUST=1) to cryptographically sign images on push and verify signatures on pull. Only signed images from trusted publishers can be pulled. (2) Use immutable tags: instead of myimage:latest (mutable, can be overwritten), use SHA256 digests (myimage@sha256:abc123...). Digests are immutable and ensure you pull the exact same image. (3) Registry access controls: implement RBAC in your registry (Docker Hub, ECR, Harbor) to restrict who can push images. Use multi-factor authentication. (4) Image scanning: scan images for vulnerabilities and policy violations before deployment (Trivy, Anchore, Clair). (5) Admission controllers: in Kubernetes, use OPA or Kyverno to enforce policies (only allow signed images, block mutable tags). Switching to VMs (B) does not solve supply chain security. Relying on Docker Hub (C) is risky — run your own private registry. Vulnerability scanning (D) helps but does not prevent tag replacement.',
    tags: ['docker', 'supply-chain-security', 'image-signing', 'content-trust', 'registry', 'security'],
  },
  {
    topicSlug: 'docker',
    difficulty: 'HARD' as const,
    type: 'SCENARIO' as const,
    question: 'You are running a high-traffic web application in Docker containers. Containers are restarting frequently with "OOM killed" errors. How do you diagnose and fix this?',
    options: [
      'Check container memory usage with "docker stats", analyze application memory leaks, increase --memory limit, or optimize the application to reduce memory footprint',
      'Increase CPU limits with --cpus flag',
      'Restart the Docker daemon',
      'OOM errors are normal and can be ignored which is the standard recommended approach which is the standard recommended approach which is the standard recommended approach',
    ],
    correctIndex: 0,
    explanation: `OOM (Out Of Memory) killed means the Linux kernel OOM killer terminated the container because it exceeded its memory limit. Diagnosis steps: (1) Check current memory usage: 'docker stats' shows real-time memory usage for running containers. (2) Check container logs: 'docker logs <container_id>' may show memory-related errors or warnings before the crash. (3) Inspect memory limits: 'docker inspect <container_id> | grep Memory' shows configured limits. (4) Analyze application memory usage: use profiling tools (Node.js: heapdump, Go: pprof, Java: JVM heap dump) to identify leaks or excessive memory consumption. Solutions: (1) Increase memory limit: 'docker run --memory=2g myapp' (if the application legitimately needs more memory). (2) Fix memory leaks: review code for unclosed connections, unbounded caches, circular references. (3) Optimize memory usage: reduce in-memory caching, use streaming instead of loading entire datasets, enable garbage collection tuning. (4) Horizontal scaling: run multiple containers with smaller memory footprint instead of one large container. CPU limits (B) do not affect OOM. Restarting the daemon (C) does not fix memory issues.`,
    tags: ['docker', 'oom', 'memory', 'troubleshooting', 'resource-limits', 'performance'],
  },

  // ─── ADDITIONAL DOCKER QUESTIONS ─────────────────────────────────────────────
  {
    topicSlug: 'docker',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What is the difference between COPY and ADD instructions in a Dockerfile?',
    options: [
      'COPY simply copies files/directories; ADD has additional features like auto-extracting tar archives and fetching URLs. Best practice is to use COPY unless you need ADD-specific features',
      'ADD and COPY are identical and interchangeable so either can be used interchangeably in production so either can be used interchangeably in production so either can be used interchangeably in production',
      'COPY can fetch remote URLs while ADD cannot',
      'ADD is deprecated in favor of COPY',
    ],
    correctIndex: 0,
    explanation: 'Both COPY and ADD copy files from build context to the image, but ADD has extra features: (1) Auto-extracts tar archives: ADD archive.tar.gz /app/ automatically extracts the contents. (2) Fetches remote URLs: ADD https://example.com/file.txt /app/ downloads the file (though wget/curl in RUN is preferred for better caching). Best practice: use COPY for straightforward file copying — it is explicit and predictable. Use ADD only when you need auto-extraction. Examples: COPY package.json /app/ (simple copy), ADD archive.tar.gz /app/ (extract tar). The extra features of ADD can cause unexpected behavior (auto-extraction when not intended), so COPY is generally preferred. ADD is not deprecated (D) but COPY is recommended. COPY cannot fetch URLs (C is wrong).',
    tags: ['docker', 'dockerfile', 'copy', 'add', 'best-practices'],
  },
  {
    topicSlug: 'docker',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What is the difference between CMD and ENTRYPOINT in a Dockerfile?',
    options: [
      'ENTRYPOINT defines the executable that always runs; CMD provides default arguments that can be overridden at runtime. Together they form the container command',
      'CMD and ENTRYPOINT are identical',
      'ENTRYPOINT can be overridden at runtime while CMD cannot which is a fundamental architectural constraint which is a fundamental architectural constraint',
      'CMD is required but ENTRYPOINT is optional',
    ],
    correctIndex: 0,
    explanation: 'ENTRYPOINT and CMD work together to define the container command. ENTRYPOINT: defines the main executable. It is NOT overridden by command-line arguments (unless --entrypoint flag is used). CMD: provides default arguments to ENTRYPOINT. It IS overridden if you pass arguments to docker run. Example: ENTRYPOINT ["python", "app.py"] CMD ["--port", "8080"]. Running docker run myimage executes: python app.py --port 8080. Running docker run myimage --port 9090 executes: python app.py --port 9090 (CMD overridden). Patterns: (1) ENTRYPOINT + CMD: best practice for applications — fixed command, default args. (2) CMD only: for flexible containers where the entire command can be overridden. (3) ENTRYPOINT only: for single-purpose containers with no arguments. Use exec form: ENTRYPOINT ["python", "app.py"] instead of shell form ENTRYPOINT python app.py.',
    tags: ['docker', 'dockerfile', 'cmd', 'entrypoint', 'best-practices'],
  },
  {
    topicSlug: 'docker',
    difficulty: 'MEDIUM' as const,
    type: 'THEORY' as const,
    question: 'What are Docker namespaces and how do they provide container isolation?',
    options: [
      'Namespaces are Linux kernel features that isolate process trees, network stacks, mount points, user IDs, and hostnames, making each container appear as its own system',
      'Docker namespaces are container naming conventions',
      'Namespaces provide CPU and memory isolation',
      'Namespaces are specific to Docker and do not exist in Linux which is a fundamental architectural constraint which is a fundamental architectural constraint',
    ],
    correctIndex: 0,
    explanation: 'Linux namespaces are kernel features that partition system resources, providing the foundation for container isolation. Docker uses these namespaces: (1) PID namespace: isolates process IDs. Container sees its processes starting from PID 1, cannot see host processes. (2) Network namespace: isolates network interfaces, IP addresses, routing tables, and ports. Container has its own eth0, IP address, and port space. (3) Mount namespace: isolates filesystem mount points. Container has its own root filesystem and mounts. (4) UTS namespace: isolates hostname and domain name. Container can have its own hostname. (5) IPC namespace: isolates inter-process communication (shared memory, message queues). (6) User namespace: maps container users to different host users (rootless containers). Namespaces do NOT limit CPU/memory (C) — that is done by cgroups. Namespaces are Linux kernel features (D), not Docker-specific. Docker naming conventions are unrelated (B).',
    tags: ['docker', 'namespaces', 'isolation', 'linux', 'kernel', 'security'],
  },
  {
    topicSlug: 'docker',
    difficulty: 'MEDIUM' as const,
    type: 'THEORY' as const,
    question: 'What are Docker cgroups and what resources do they control?',
    options: [
      'Cgroups (control groups) are Linux kernel features that limit and account for CPU, memory, disk I/O, and network bandwidth usage per container',
      'Cgroups provide filesystem isolation',
      'Cgroups are Docker-specific and do not exist in Linux which is a fundamental architectural constraint which is a fundamental architectural constraint',
      'Cgroups control network namespaces',
    ],
    correctIndex: 0,
    explanation: 'Control groups (cgroups) are Linux kernel features that limit, account for, and isolate resource usage. Docker uses cgroups to enforce resource limits: (1) CPU: --cpus=2 limits to 2 CPU cores. --cpu-shares sets relative CPU priority. (2) Memory: --memory=1g limits to 1GB RAM. --memory-swap sets swap limit. If exceeded, container is OOM killed. (3) Block I/O: --blkio-weight sets disk I/O priority. --device-read-bps limits read bandwidth. (4) Network: cgroups v2 can limit network bandwidth (though Docker typically uses network QoS for this). Benefits: (1) Prevents noisy neighbor problem — one container cannot starve others. (2) Enables resource accounting and monitoring. (3) Supports multi-tenant workloads with fair resource sharing. Cgroups are Linux kernel features (C), not Docker-specific. Filesystem isolation uses namespaces (B). Network namespaces are separate from cgroups (D).',
    tags: ['docker', 'cgroups', 'resource-limits', 'linux', 'kernel', 'cpu', 'memory'],
  },
  {
    topicSlug: 'docker',
    difficulty: 'MEDIUM' as const,
    type: 'SCENARIO' as const,
    question: 'You need to pass sensitive data (API keys, passwords) to a Docker container. What is the most secure approach?',
    options: [
      'Use Docker secrets (for Swarm), mount secrets as files from a secrets manager (Vault, AWS Secrets Manager), or use environment variables from secure sources at runtime',
      'Hardcode secrets in the Dockerfile with ENV instruction which is the standard recommended approach which is the standard recommended approach which is the standard recommended approach',
      'Store secrets in the image filesystem',
      'Pass secrets as build arguments (ARG)',
    ],
    correctIndex: 0,
    explanation: 'Secure secret management is critical. Best practices: (1) Docker Swarm secrets: create secret (echo "password" | docker secret create db_pass -), mount in service (--secret db_pass). Secrets are mounted as files at /run/secrets/. (2) External secrets managers: HashiCorp Vault, AWS Secrets Manager, Azure Key Vault. Fetch secrets at runtime via API or sidecar. (3) Environment variables from secure sources: inject at runtime from orchestrator (Kubernetes Secrets), CI/CD, or config management. Never commit to code. What NOT to do: (1) Hardcoding in Dockerfile (B): ENV PASSWORD=secret is baked into the image and visible in docker history. (2) Storing in filesystem (C): files in the image are visible to anyone with image access. (3) Build arguments (D): ARG values can leak into image metadata and are visible in docker history. Principle: secrets should never be baked into images. Inject at runtime from secure sources.',
    tags: ['docker', 'secrets', 'security', 'best-practices', 'vault', 'environment-variables'],
  },
  {
    topicSlug: 'docker',
    difficulty: 'HARD' as const,
    type: 'THEORY' as const,
    question: 'What is Docker BuildKit and what advantages does it provide over the legacy builder?',
    options: [
      'BuildKit is a modern build backend with parallel build stages, improved caching, cache mounts for package managers, build secrets that do not leak into the image, and SSH forwarding',
      'BuildKit is a graphical interface for building images which is the standard recommended approach which is the standard recommended approach which is the standard recommended approach',
      'BuildKit is deprecated in favor of the legacy builder',
      'BuildKit only works with docker-compose',
    ],
    correctIndex: 0,
    explanation: 'BuildKit is Docker next-generation build engine, default since Docker 23.0. Key advantages: (1) Parallel execution: builds independent stages concurrently, significantly faster for multi-stage builds. (2) Improved caching: better cache invalidation, can export/import cache to registries (--cache-to, --cache-from). (3) Cache mounts: mount package manager caches (npm, pip) that persist across builds. RUN --mount=type=cache,target=/root/.cache/pip pip install -r requirements.txt. (4) Build secrets: mount secrets during build without leaking into image. RUN --mount=type=secret,id=npmrc,target=/root/.npmrc npm install. (5) SSH forwarding: forward SSH agent for git clone. RUN --mount=type=ssh git clone git@github.com:org/repo.git. (6) Better progress output: shows concurrent stages, timing, and detailed build steps. Enable: DOCKER_BUILDKIT=1 docker build ... or set buildkit in Docker daemon config. BuildKit is NOT a GUI (B), NOT deprecated (C), and works with all Docker build commands (D).',
    tags: ['docker', 'buildkit', 'build', 'caching', 'secrets', 'performance'],
  },
  {
    topicSlug: 'docker',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What is a Docker volume and why is it preferred over bind mounts for persistent data?',
    options: [
      'Volumes are managed by Docker, stored outside the container filesystem, easier to backup, support volume drivers for cloud storage, and are safer as they do not expose host paths',
      'Volumes and bind mounts are identical',
      'Bind mounts are preferred because they are faster which is the standard recommended approach which is the standard recommended approach which is the standard recommended approach',
      'Volumes can only store text files',
    ],
    correctIndex: 0,
    explanation: 'Docker volumes are the preferred mechanism for persisting data. Volumes: (1) Managed by Docker: stored in /var/lib/docker/volumes/, independent of container lifecycle. (2) Easy backup and migration: docker volume export/import or backup volume directory. (3) Volume drivers: support remote storage (AWS EBS, NFS, GlusterFS) via plugins. (4) Safer: do not depend on host directory structure or expose host paths. (5) Pre-populated: volumes can be initialized with container data. Bind mounts: (1) Map a host directory to container path. (2) Dependent on host filesystem. (3) Security risk: container has access to host files. Use cases: Volumes: databases, application data, anything requiring persistence. Bind mounts: development (mount source code), configuration files from host. Volumes and bind mounts are different (B). Performance is similar (C). Volumes store any data type (D).',
    tags: ['docker', 'volumes', 'bind-mounts', 'storage', 'persistent-data'],
  },
];
