export const finopsQuestions = [
  // ─── EASY THEORY ───────────────────────────────────────────────────────────
  {
    topicSlug: 'finops',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What is FinOps and why is it important for cloud cost management?',
    options: [
      'FinOps is a cultural practice combining financial management and DevOps to optimize cloud costs through visibility, optimization, and accountability',
      'FinOps is a financial software tool',
      'FinOps is only for finance teams, not engineers',
      'FinOps means cutting cloud costs at all costs',
    ],
    correctIndex: 0,
    explanation: 'FinOps (Financial Operations) is a cultural practice and framework for managing cloud costs. Core principles: (1) Teams collaborate: engineering, finance, and business work together on cost decisions. (2) Everyone takes ownership: engineers own their costs, finance provides visibility, leadership sets budgets. (3) Centralized team drives FinOps: dedicated FinOps team provides tools, training, and governance. (4) Reports accessible to all: cost visibility for engineers (cost per service), product (cost per feature), finance (budget tracking). (5) Decisions are data-driven: use cost data to make architectural and business decisions. (6) Take advantage of variable cost model: right-size resources, use spot instances, scale down non-prod. FinOps lifecycle: Inform (visibility and allocation) → Optimize (reduce waste) → Operate (continuous improvement). FinOps is NOT a tool (B) — it is a practice supported by tools (CloudHealth, Kubecost, AWS Cost Explorer). FinOps involves all teams (C), especially engineers who make cost-impacting decisions. FinOps balances cost, speed, and quality (D) — it is not about minimizing cost at all costs.',
    tags: ['finops', 'cost-optimization', 'cloud-costs', 'accountability', 'culture'],
  },
  {
    topicSlug: 'finops',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What is the difference between AWS On-Demand, Reserved, and Spot instances?',
    options: [
      'On-Demand: pay per hour, no commitment; Reserved: 1-3 year commitment, 30-70% discount; Spot: bid on unused capacity, up to 90% discount but can be interrupted',
      'Reserved instances are always cheaper than Spot',
      'On-Demand instances are the cheapest',
      'Spot instances are guaranteed to run continuously',
    ],
    correctIndex: 0,
    explanation: 'AWS EC2 pricing models: On-Demand: (1) Pay-as-you-go: $0.10/hour for t3.medium (example). (2) No upfront commitment or contract. (3) Full control: start/stop anytime. (4) Use case: short-term workloads, unpredictable traffic, development/testing. Reserved Instances (RIs): (1) 1 or 3-year commitment. (2) Payment options: all upfront (biggest discount), partial upfront, no upfront. (3) Discount: 30-75% vs. On-Demand depending on term and payment. (4) Types: Standard (fixed instance type, 75% discount) or Convertible (change instance type, 54% discount). (5) Use case: steady-state workloads (databases, always-on web servers). Spot Instances: (1) Bid on unused EC2 capacity (supply/demand pricing). (2) Discount: 50-90% vs. On-Demand. (3) Interruption: AWS can reclaim instances with 2-minute warning when capacity is needed. (4) Use case: fault-tolerant workloads (batch processing, CI/CD runners, big data, rendering). Reserved is NOT always cheaper (B) — Spot is the cheapest. On-Demand is the most expensive (C). Spot instances CAN be interrupted (D). Mixing instance types optimizes cost: use Reserved for baseline capacity, Spot for burst capacity.',
    tags: ['finops', 'aws', 'ec2-pricing', 'reserved-instances', 'spot-instances', 'cost-optimization'],
  },
  {
    topicSlug: 'finops',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What is right-sizing and why is it a common cost optimization technique?',
    options: [
      'Right-sizing is matching instance types/sizes to actual workload requirements; many resources are over-provisioned, wasting money on unused capacity',
      'Right-sizing means using the largest instance types',
      'Right-sizing is only for EC2 instances',
      'Right-sizing is a one-time activity',
    ],
    correctIndex: 0,
    explanation: 'Right-sizing is the process of matching compute resources to actual utilization and performance requirements. Common waste: over-provisioning. Engineers often choose larger instances "to be safe" (t3.2xlarge when t3.medium suffices), leading to 50-80% idle CPU/memory. Right-sizing process: (1) Monitor utilization: use CloudWatch, Datadog, or Prometheus to track CPU, memory, network, disk. (2) Identify over-provisioned resources: instances with < 20% average CPU over 30 days. (3) Analyze performance requirements: does the workload need the current capacity? Check latency, throughput, error rates. (4) Downsize: change instance type (r5.2xlarge → r5.xlarge). (5) Test: validate performance in staging. (6) Repeat continuously: usage patterns change (launch → steady-state → growth). Tools: AWS Compute Optimizer (ML-based recommendations), CloudHealth, Kubecost (Kubernetes right-sizing). Right-sizing does NOT mean using the largest instances (B) — that is over-provisioning. Right-sizing applies to all resources (C): EC2, RDS, EBS volumes, Lambda memory. Right-sizing is continuous (D), not one-time.',
    tags: ['finops', 'right-sizing', 'cost-optimization', 'resource-utilization', 'waste-reduction'],
  },
  {
    topicSlug: 'finops',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What are tagging strategies for cloud resources and why are they important for cost management?',
    options: [
      'Tags are key-value metadata on resources (Environment, Team, Cost Center, Application); they enable cost allocation, chargebacks, and budgeting per team/project',
      'Tagging is only for organization, not cost management',
      'Tags increase cloud costs',
      'Tagging is optional and not widely used',
    ],
    correctIndex: 0,
    explanation: 'Cloud resource tagging is critical for cost visibility and accountability. Common tag keys: (1) Environment: dev, staging, prod (isolate non-prod costs). (2) Team: platform, frontend, data-engineering (chargeback/showback per team). (3) Cost Center / Department: sales, engineering, marketing (financial reporting). (4) Application / Service: api-gateway, user-service, analytics-pipeline (cost per service). (5) Owner: email of responsible engineer (accountability). (6) Project: project-alpha, project-beta (track project-specific spending). Use cases: (1) Cost allocation: "How much did the frontend team spend last month?" Filter by Team=frontend in AWS Cost Explorer. (2) Chargebacks: finance bills each team for their usage (infrastructure as an internal service). (3) Budget alerts: set budget for Environment=prod, alert if exceeded. (4) Resource lifecycle: delete resources tagged Environment=dev after hours. (5) Compliance: tag sensitive data resources for auditing. Tagging is NOT just for organization (B) — it is foundational for FinOps. Tags do NOT increase costs (C). Tagging is mandatory in mature FinOps organizations (D). Best practice: enforce tagging via IAM policies (block resource creation without required tags).',
    tags: ['finops', 'tagging', 'cost-allocation', 'chargeback', 'accountability', 'cloud-governance'],
  },
  {
    topicSlug: 'finops',
    difficulty: 'EASY' as const,
    type: 'SCENARIO' as const,
    question: 'Your AWS bill is $50,000/month, but you do not know which services or teams are responsible. What is the first step?',
    options: [
      'Enable cost allocation tags and use AWS Cost Explorer to break down costs by service, region, and tag (Team, Environment, Application)',
      'Shut down all resources',
      'Ignore it if the business is profitable',
      'AWS costs cannot be tracked',
    ],
    correctIndex: 0,
    explanation: 'Lack of cost visibility is the #1 FinOps problem. Without visibility, you cannot optimize. Steps to gain visibility: (1) Enable AWS Cost and Usage Reports (CUR): detailed billing data exported to S3 hourly. (2) Enable cost allocation tags: activate tags (Team, Environment, Application) in AWS Billing Console. (3) Tag resources: retroactively tag existing resources, enforce tagging for new resources. (4) Use AWS Cost Explorer: break down costs by service (EC2, S3, RDS), region, instance type, tag. Identify top spenders (e.g., EC2 = 60%, S3 = 20%, RDS = 15%). (5) Drill down: EC2 costs by instance type (r5.2xlarge = $20k, t3.medium = $5k), by tag (Team=data = $15k, Team=frontend = $10k). (6) Create dashboards: use QuickSight, Grafana, or CloudHealth for real-time cost visibility. (7) Set budgets: AWS Budgets alert when spending exceeds thresholds. Shutting down resources (B) is reckless. Ignoring costs (C) is irresponsible. Costs CAN be tracked (D). Cost visibility is the foundation of FinOps.',
    tags: ['finops', 'cost-visibility', 'aws-cost-explorer', 'billing', 'tagging', 'dashboards'],
  },
  {
    topicSlug: 'finops',
    difficulty: 'EASY' as const,
    type: 'SCENARIO' as const,
    question: 'You discover that your development environment costs as much as production ($10,000/month). What optimizations should you consider?',
    options: [
      'Shut down dev resources outside business hours, use smaller instance types, use Spot instances for dev workloads, and delete unused dev environments',
      'Keep dev environment running 24/7 at full capacity',
      'Development costs are unavoidable',
      'Merge dev and prod environments',
    ],
    correctIndex: 0,
    explanation: 'Non-production environments are prime targets for cost optimization. Dev/staging should cost 10-30% of production, not 100%. Optimizations: (1) Scheduled shutdowns: turn off dev/staging resources outside business hours (9 PM - 8 AM, weekends). Use AWS Instance Scheduler, Lambda functions, or Karpenter (Kubernetes). Savings: 70% (running 50 hours/week vs. 168 hours). (2) Right-size: use smaller instance types (t3.medium in dev, r5.2xlarge in prod). Savings: 50-80%. (3) Spot instances: use Spot for dev/test (interruptions are acceptable). Savings: 70-90%. (4) Delete unused resources: identify idle EC2 instances, unattached EBS volumes, empty S3 buckets. Use AWS Config or CloudCustodian for automated cleanup. (5) Shared dev environments: instead of per-developer environments, use shared dev cluster with namespaces. (6) Ephemeral environments: create preview environments on demand, delete after testing. Keeping dev at full capacity (B) wastes money. Dev costs CAN be reduced (C). Merging dev/prod (D) is dangerous (testing affects production). Dev/test cost optimization is low-hanging fruit.',
    tags: ['finops', 'cost-optimization', 'dev-environments', 'spot-instances', 'automation', 'scheduling'],
  },
  {
    topicSlug: 'finops',
    difficulty: 'EASY' as const,
    type: 'SCENARIO' as const,
    question: 'Your S3 bill is $5,000/month, and most data is rarely accessed. How can you reduce costs?',
    options: [
      'Use S3 lifecycle policies to transition old data to cheaper storage classes (S3 Infrequent Access, Glacier, Glacier Deep Archive)',
      'Delete all S3 data',
      'S3 costs are fixed and cannot be reduced',
      'Migrate to a different cloud provider',
    ],
    correctIndex: 0,
    explanation: 'S3 storage costs scale with volume and storage class. Storage classes (cost per GB/month): (1) S3 Standard: $0.023 (frequent access, low latency). (2) S3 Intelligent-Tiering: $0.023 + monitoring fee (auto-tiers between frequent/infrequent based on access patterns). (3) S3 Standard-IA (Infrequent Access): $0.0125 (accessed < 1x/month, retrieval fee). (4) S3 One Zone-IA: $0.01 (single AZ, cheaper, lower durability). (5) S3 Glacier Flexible Retrieval: $0.004 (archive, retrieval in minutes-hours). (6) S3 Glacier Deep Archive: $0.00099 (long-term archive, retrieval in 12 hours). Lifecycle policy example: (1) After 30 days → transition to S3 Standard-IA (50% savings). (2) After 90 days → transition to Glacier (80% savings). (3) After 365 days → transition to Glacier Deep Archive (95% savings). (4) After 7 years → delete (compliance retention). Additional optimizations: (1) Enable S3 Intelligent-Tiering for unknown access patterns. (2) Compress data before upload (gzip, zstd). (3) Delete incomplete multipart uploads (hidden cost). Deleting all data (B) is extreme. S3 costs CAN be reduced (C). Migration (D) is overkill.',
    tags: ['finops', 's3', 'storage-classes', 'lifecycle-policies', 'cost-optimization', 'archival'],
  },

  // ─── MEDIUM THEORY ─────────────────────────────────────────────────────────
  {
    topicSlug: 'finops',
    difficulty: 'MEDIUM' as const,
    type: 'THEORY' as const,
    question: 'What are AWS Savings Plans and how do they differ from Reserved Instances?',
    options: [
      'Savings Plans offer flexible commitment (compute usage, EC2 families) with automatic discounts; Reserved Instances lock specific instance types but offer higher discounts',
      'Savings Plans and Reserved Instances are the same',
      'Reserved Instances are always better',
      'Savings Plans are only for S3',
    ],
    correctIndex: 0,
    explanation: 'AWS Savings Plans (introduced 2019) are a flexible alternative to Reserved Instances. Types: (1) Compute Savings Plans: commit to a dollar amount of compute usage ($/hour) for 1 or 3 years. Apply to EC2, Lambda, Fargate across any instance family, size, region, OS. Discount: up to 66%. Example: commit to $10/hour. If you use t3.medium or r5.large or Lambda, all get the discount. (2) EC2 Instance Savings Plans: commit to specific instance family (e.g., m5) in a region. Discount: up to 72%. Flexibility: instance size, OS, tenancy. Reserved Instances: (1) Standard RIs: lock instance type, region, OS. Discount: up to 75%. No flexibility (cannot change instance type). (2) Convertible RIs: can change instance type. Discount: up to 54%. Less flexibility than Savings Plans. Comparison: Savings Plans = flexibility + good discounts. RIs = maximum discounts but rigid. Recommendations: (1) Use Compute Savings Plans for variable workloads (mix of EC2, Lambda, Fargate). (2) Use EC2 Instance Savings Plans for dedicated EC2 workloads. (3) Use Standard RIs for steady-state, unchanging workloads (databases). They are NOT the same (B). Neither is always better (C) — it depends. Savings Plans apply to compute, not S3 (D).',
    tags: ['finops', 'aws', 'savings-plans', 'reserved-instances', 'commitment-discounts', 'cost-optimization'],
  },
  {
    topicSlug: 'finops',
    difficulty: 'MEDIUM' as const,
    type: 'THEORY' as const,
    question: 'What is Kubernetes cost optimization and why is it challenging?',
    options: [
      'Kubernetes cost optimization involves right-sizing pods, using node autoscaling, and allocating costs per namespace/team; challenging due to bin-packing, resource requests vs. usage, and multi-tenancy',
      'Kubernetes is free and does not incur costs',
      'Kubernetes costs are the same as VM costs',
      'Cost optimization is not possible in Kubernetes',
    ],
    correctIndex: 0,
    explanation: 'Kubernetes (EKS, GKE, AKS) costs are opaque compared to VMs. Challenges: (1) Shared infrastructure: multiple teams/apps share nodes, making cost allocation difficult. (2) Resource requests vs. actual usage: pods reserve CPU/memory (requests) but may use less, wasting capacity. (3) Bin-packing: Kubernetes schedules pods to fit on nodes, but inefficient packing leaves unused capacity. (4) Auto-scaling complexity: over-provisioning (too many nodes) vs. under-provisioning (pods pending). Optimization strategies: (1) Right-size pod requests: set requests to match actual usage (use VPA - Vertical Pod Autoscaler - for recommendations). (2) Cluster Autoscaler: automatically add/remove nodes based on pending pods. (3) Karpenter: advanced autoscaler that provisions optimal instance types (faster, cheaper than Cluster Autoscaler). (4) Spot/preemptible nodes: use Spot for fault-tolerant workloads (batch jobs, dev/staging). Savings: 70-90%. (5) Cost allocation: use tools (Kubecost, OpenCost) to allocate costs by namespace, label, or team. (6) Idle resource detection: identify over-provisioned pods and resize them. Kubernetes is NOT free (B) — you pay for worker nodes. Costs are more complex than VMs (C). Optimization IS possible (D).',
    tags: ['finops', 'kubernetes', 'cost-optimization', 'autoscaling', 'kubecost', 'right-sizing'],
  },
  {
    topicSlug: 'finops',
    difficulty: 'MEDIUM' as const,
    type: 'THEORY' as const,
    question: 'What is the difference between chargeback and showback in FinOps?',
    options: [
      'Chargeback: teams are billed/invoiced for their cloud usage; showback: teams see their costs for visibility/awareness without actual billing',
      'Chargeback and showback are the same',
      'Chargeback is for external customers; showback is internal',
      'Showback is more advanced than chargeback',
    ],
    correctIndex: 0,
    explanation: 'Chargeback and showback are cost accountability models. Showback: (1) Informational: teams see their cloud costs in dashboards, reports. (2) No financial transaction: costs are informational, not billed to teams. (3) Goal: awareness, visibility, cost-consciousness. (4) Benefit: low friction, easy to implement, encourages cost optimization. (5) Drawback: no financial accountability, teams may not take costs seriously. Example: "Frontend team, you spent $10,000 last month (up 20% from last month)." Chargeback: (1) Financial transaction: teams are billed for their usage (internal invoice or budget deduction). (2) Full accountability: teams own their costs financially (reduces budget if they overspend). (3) Goal: enforce cost discipline, treat infrastructure as an internal service. (4) Benefit: strong accountability, teams optimize aggressively. (5) Drawback: requires billing infrastructure, can create friction, may discourage innovation if overly punitive. Example: "Frontend team, $10,000 is deducted from your quarterly budget." FinOps maturity: start with showback (build visibility), evolve to chargeback (enforce accountability). They are NOT the same (B). Both are internal (C). Neither is inherently better (D) — it depends on culture.',
    tags: ['finops', 'chargeback', 'showback', 'cost-allocation', 'accountability', 'budgeting'],
  },
  {
    topicSlug: 'finops',
    difficulty: 'MEDIUM' as const,
    type: 'THEORY' as const,
    question: 'What is the cost of data transfer in AWS and how can you minimize it?',
    options: [
      'Data transfer costs: free inbound, free within same AZ, $0.01-0.02/GB between AZs, $0.09/GB outbound to internet; minimize with CloudFront, VPC endpoints, S3 Transfer Acceleration',
      'Data transfer is always free in AWS',
      'Data transfer costs are negligible',
      'Data transfer costs cannot be optimized',
    ],
    correctIndex: 0,
    explanation: 'AWS data transfer pricing (often overlooked, can be 10-30% of bill): (1) Inbound: free (data into AWS). (2) Within same AZ: free (EC2 to EC2 in us-east-1a). (3) Between AZs: $0.01/GB each direction (us-east-1a to us-east-1b). (4) Between regions: $0.02/GB (us-east-1 to eu-west-1). (5) Outbound to internet: $0.09/GB for first 10 TB, $0.085/GB for 10-50 TB (decreases with volume). (6) CloudFront to internet: cheaper than direct S3/EC2 egress ($0.085/GB vs. $0.09/GB, plus caching benefits). Minimization strategies: (1) Use CloudFront: cache content at edge locations, reduce origin data transfer. (2) VPC endpoints: access S3/DynamoDB without traversing internet gateway (free, no NAT Gateway data processing fees). (3) S3 Transfer Acceleration: faster uploads via CloudFront edge locations (additional $0.04/GB). (4) Keep data in same AZ: deploy app and database in the same AZ if latency allows (avoid cross-AZ transfer). (5) Compress data: gzip HTTP responses, compress files before transfer. (6) Regional architecture: deploy applications in regions close to users (reduce inter-region transfer). Data transfer is NOT always free (B). It can be significant (C). It CAN be optimized (D).',
    tags: ['finops', 'data-transfer', 'aws', 'cloudfront', 'vpc-endpoints', 'cost-optimization'],
  },
  {
    topicSlug: 'finops',
    difficulty: 'MEDIUM' as const,
    type: 'SCENARIO' as const,
    question: 'Your team wants to purchase Reserved Instances but is unsure about commitment length (1 year vs. 3 years). How do you decide?',
    options: [
      'Analyze historical usage trends, growth forecasts, and business stability; use 1-year RIs for growth/uncertainty, 3-year RIs for steady-state workloads with long-term commitment',
      'Always buy 3-year RIs for maximum discount',
      'Never buy RIs because they lock you in',
      'RI commitment length does not matter',
    ],
    correctIndex: 0,
    explanation: 'RI commitment decision factors: (1) Historical usage: analyze 6-12 months of usage. If workload is steady (database running 24/7), RIs make sense. If usage is spiky or growing rapidly, RIs may not align. (2) Growth forecast: if workload is growing 50%/year, 3-year RI may be under-utilized initially (commit to baseline, use On-Demand/Spot for growth). (3) Business stability: is this a core long-term product (buy 3-year RIs) or an experimental project (use On-Demand or 1-year RIs)? (4) Discount vs. flexibility: 3-year RIs offer 70-75% discount vs. 1-year 30-50% discount. Is the extra discount worth the reduced flexibility? (5) Convertible vs. Standard: use Convertible RIs if you expect workload changes (instance type, region). Strategy: (1) Start with 1-year RIs to test RI management. (2) Use 3-year RIs for proven steady-state workloads (databases, core APIs). (3) Layer commitments: 60% 3-year RIs (baseline), 20% 1-year RIs (near-term growth), 20% On-Demand/Spot (burst). Always buying 3-year (B) risks over-commitment. Never buying RIs (C) wastes money. Commitment length matters significantly (D).',
    tags: ['finops', 'reserved-instances', 'commitment', 'decision-making', 'forecast', 'aws'],
  },
  {
    topicSlug: 'finops',
    difficulty: 'MEDIUM' as const,
    type: 'SCENARIO' as const,
    question: 'You notice a $2,000 unexpected charge for AWS NAT Gateway data processing. What is likely causing this and how do you fix it?',
    options: [
      'NAT Gateway charges $0.045/GB for data processing; high traffic from private subnets to internet (S3, APIs, package downloads) is expensive; use VPC endpoints or S3 Gateway endpoints to bypass NAT',
      'NAT Gateway charges are unavoidable',
      'Switch to a different cloud provider',
      'NAT Gateway is free',
    ],
    correctIndex: 0,
    explanation: 'NAT Gateway is a common hidden cost in AWS. Pricing: (1) Hourly charge: $0.045/hour (~$32/month). (2) Data processing: $0.045/GB processed (both inbound and outbound). Problem: if instances in private subnets download packages (npm install, apt-get update), call external APIs, or access S3 via internet, ALL traffic goes through NAT Gateway and incurs data processing fees. Example: 50 GB/day of traffic = 50 * 30 * $0.045 = $67.50/month (just data processing, not including hourly charge). Solutions: (1) VPC endpoints for AWS services: create VPC endpoints for S3, DynamoDB, ECR (interface or gateway endpoints). Traffic stays within AWS backbone (free, no NAT Gateway traversal). (2) S3 Gateway endpoint: free, allows private subnet instances to access S3 directly. (3) PrivateLink: access AWS services via VPC endpoints. (4) Optimize egress: reduce unnecessary external API calls, cache data, use CloudFront for static assets. (5) Consolidate NAT Gateways: use one NAT Gateway per AZ (instead of per subnet) if acceptable. NAT charges are NOT unavoidable (B). Migration (C) is overkill. NAT is NOT free (D). NAT Gateway costs surprise many teams.',
    tags: ['finops', 'nat-gateway', 'data-transfer', 'vpc-endpoints', 'aws', 'cost-optimization'],
  },
  {
    topicSlug: 'finops',
    difficulty: 'MEDIUM' as const,
    type: 'SCENARIO' as const,
    question: 'Your database RDS instance is oversized (db.r5.4xlarge, 128 GB RAM) but only uses 20 GB RAM. What are the risks and steps to right-size it?',
    options: [
      'Risks: downtime during resize, potential performance issues if under-sized; steps: monitor metrics, test in staging, schedule maintenance window, resize via modify-db-instance, validate performance',
      'Right-sizing databases is not possible',
      'Change instance type without testing',
      'Delete the database and recreate it',
    ],
    correctIndex: 0,
    explanation: 'RDS right-sizing is more complex than EC2 due to data persistence and availability requirements. Right-sizing process: (1) Monitor utilization: use CloudWatch metrics (DatabaseConnections, CPUUtilization, FreeableMemory, ReadIOPS, WriteIOPS) for 30+ days. Identify over-provisioning (20 GB RAM used vs. 128 GB capacity). (2) Determine target size: choose instance type with 1.5-2x actual usage (e.g., 20 GB * 2 = 40 GB → db.r5.xlarge). (3) Test in staging: resize staging database first, run load tests, validate query performance. (4) Schedule maintenance window: RDS resizing causes downtime (5-15 minutes for single-AZ, less for Multi-AZ). Notify stakeholders. (5) Modify instance: AWS Console or CLI (modify-db-instance --db-instance-class db.r5.xlarge --apply-immediately). (6) Monitor post-resize: watch CPU, memory, IOPS, latency for 7 days. If performance degrades, scale back up. (7) Iterate: repeat every quarter as usage changes. Risks: (1) Downtime (mitigated by Multi-AZ). (2) Performance degradation (mitigate with testing). (3) IOPS bottleneck (check provisioned IOPS). Right-sizing IS possible (B). Testing is mandatory (C). Recreating is overkill (D).',
    tags: ['finops', 'rds', 'right-sizing', 'database', 'cost-optimization', 'aws'],
  },

  // ─── HARD THEORY ───────────────────────────────────────────────────────────
  {
    topicSlug: 'finops',
    difficulty: 'HARD' as const,
    type: 'THEORY' as const,
    question: 'What is unit economics in FinOps and how do you calculate cost per customer or transaction?',
    options: [
      'Unit economics measure cost per unit of business value (cost per customer, transaction, API call); calculate by mapping cloud costs to business metrics using tagging and usage correlation',
      'Unit economics is only for SaaS companies',
      'Unit economics cannot be calculated for cloud costs',
      'Unit economics is the same as total cost',
    ],
    correctIndex: 0,
    explanation: 'Unit economics connect cloud costs to business outcomes. Instead of "we spent $100,000 on EC2 last month," ask "what does it cost us to serve one customer?" Calculation approach: (1) Define unit of value: customer, transaction, API request, video stream, etc. (2) Map costs to units: use tagging (Service=user-api, Service=video-transcoding) and usage metrics (CloudWatch, application logs). (3) Calculate cost per unit: Total cost / Total units. Example: user-api costs $20,000/month, serves 10 million requests → $0.002 per request. (4) Track over time: is cost per unit decreasing (economies of scale) or increasing (inefficiency)? Detailed example (SaaS product): (1) Total cloud cost: $500,000/month. (2) Active customers: 50,000. (3) Cost per customer: $500,000 / 50,000 = $10/customer/month. (4) Break down by service: user-api $5/customer, database $3/customer, storage $1/customer, other $1/customer. (5) Compare to revenue: if ARPU (average revenue per user) is $50/month, gross margin = ($50 - $10) / $50 = 80%. Unit economics apply to all businesses (B). They CAN be calculated (C) with proper instrumentation. Unit economics ≠ total cost (D). This is critical for product/business decisions.',
    tags: ['finops', 'unit-economics', 'cost-per-customer', 'business-metrics', 'cost-allocation'],
  },
  {
    topicSlug: 'finops',
    difficulty: 'HARD' as const,
    type: 'THEORY' as const,
    question: 'What is commitment-based discount optimization and how do FinOps teams balance coverage vs. flexibility?',
    options: [
      'Commitment optimization involves purchasing the right mix of Savings Plans, RIs, and Spot to maximize discounts while maintaining flexibility; target 70-80% commitment coverage for steady-state workloads',
      'Always buy 100% commitment-based discounts',
      'Commitment-based discounts are too risky',
      'On-Demand is always cheaper',
    ],
    correctIndex: 0,
    explanation: 'Commitment-based discount optimization is a core FinOps strategy. Goal: maximize savings while maintaining flexibility for growth and experimentation. Strategy: (1) Analyze usage patterns: identify steady-state baseline (always-on workloads) vs. variable usage (bursts, experiments). (2) Layer commitments: (a) 50-60% coverage with 3-year Savings Plans (maximum discount, long-term stability). (b) 10-20% coverage with 1-year Savings Plans (near-term growth). (c) 20-30% On-Demand (flexibility for spikes, new projects). (d) 10-20% Spot (fault-tolerant workloads). (3) Monitor coverage: AWS Cost Explorer shows Savings Plans coverage %, unutilized commitment, missed savings. Target: 70-80% coverage (balance savings vs. flexibility). (4) Iterative optimization: review quarterly, adjust commitments as usage patterns change. (5) Risk mitigation: avoid over-commitment (80% coverage leaves 20% room for growth); use Convertible RIs for flexibility. Purchasing 100% commitment (B) is risky (what if usage drops? or you need different instance types?). Commitments are NOT too risky (C) — they are proven to save 50-70%. On-Demand is most expensive (D). This tests strategic FinOps decision-making.',
    tags: ['finops', 'commitment-discounts', 'savings-plans', 'reserved-instances', 'coverage', 'optimization'],
  },
  {
    topicSlug: 'finops',
    difficulty: 'HARD' as const,
    type: 'THEORY' as const,
    question: 'What is the FinOps concept of "variable cost model" and how does it change infrastructure decision-making?',
    options: [
      'Variable cost model: pay only for what you use, aligning costs with business outcomes; enables trade-offs (pay more for speed, pay less for delay) that are impossible with fixed costs',
      'Variable cost model means unpredictable budgets',
      'Variable cost model is the same as on-premises costs',
      'Variable cost model only applies to compute',
    ],
    correctIndex: 0,
    explanation: `The variable cost model is cloud's fundamental economic advantage. Traditional on-premises: (1) Fixed costs: buy servers upfront, depreciate over 3-5 years. (2) Capacity planning: over-provision for peak (wasted capacity) or under-provision (cannot handle spikes). (3) Sunk costs: cannot repurpose hardware quickly. Cloud variable cost model: (1) Pay-per-use: scale up during demand, scale down when idle. (2) No upfront investment: convert CapEx to OpEx. (3) Speed vs. cost trade-offs: launch 100 instances for 1 hour ($10) vs. 1 instance for 100 hours ($10) — choose based on business urgency. (4) Granular optimization: optimize per workload (use Spot for batch, On-Demand for production). Architectural implications: (1) Auto-scaling: add capacity dynamically based on load (impossible with fixed costs). (2) Ephemeral environments: create test environments on-demand, delete after use. (3) Cost-aware architecture: use Lambda (pay per invocation) instead of always-on EC2 for intermittent workloads. (4) Right-sizing: continuously adjust instance sizes as usage changes. Variable does NOT mean unpredictable (B) — budgets can be forecasted with usage analysis. It is fundamentally different from on-prem (C). It applies to all resources (D).`,
    tags: ['finops', 'variable-cost', 'cloud-economics', 'elasticity', 'capex-opex', 'scalability'],
  },
  {
    topicSlug: 'finops',
    difficulty: 'HARD' as const,
    type: 'THEORY' as const,
    question: 'What is the role of anomaly detection in FinOps and how does it prevent cost surprises?',
    options: [
      'Anomaly detection uses ML to identify unexpected cost spikes (resource misconfiguration, runaway scaling, crypto mining) and alerts before costs escalate; critical for proactive cost management',
      'Anomaly detection is only for security',
      'Anomaly detection is not relevant to FinOps',
      'Anomaly detection is too slow to be useful',
    ],
    correctIndex: 0,
    explanation: 'Cost anomaly detection prevents surprise bills by identifying unusual spending patterns. Common anomalies: (1) Runaway auto-scaling: misconfigured auto-scaling launches 100 instances instead of 10 (cost spike from $1,000/day to $10,000/day). (2) Forgotten resources: EC2 instance left running after testing (steady $50/day increase). (3) Data transfer spike: misconfigured application downloads 10 TB of S3 data ($900 charge). (4) Compromised account: attacker launches EC2 instances for crypto mining (sudden spike in new regions). (5) Pricing change: AWS increases price for a service (gradual cost increase). Anomaly detection systems: (1) AWS Cost Anomaly Detection: ML-based, monitors spending, alerts via SNS/email. (2) CloudHealth, Datadog, Apptio: third-party tools with anomaly detection. (3) Custom thresholds: "alert if daily spend > $5,000 (vs. baseline $2,000)". Detection logic: (1) Baseline: average spend over 14-30 days. (2) Threshold: alert if actual spend > baseline + 2σ (standard deviations). (3) Contextual: account for expected growth (Black Friday traffic spike is not an anomaly). Anomaly detection is NOT just security (B). It is critical for FinOps (C). ML makes it real-time (D). Anomalies can cost thousands before human detection.',
    tags: ['finops', 'anomaly-detection', 'cost-alerts', 'ml', 'proactive-management', 'aws'],
  },
  {
    topicSlug: 'finops',
    difficulty: 'HARD' as const,
    type: 'SCENARIO' as const,
    question: 'Your organization has 100 AWS accounts across 20 teams. How do you implement centralized FinOps governance?',
    options: [
      'Use AWS Organizations with consolidated billing, SCPs for guardrails, centralized Cost and Usage Reports, tagging policies, and budgets per account/team with alerts',
      'Each team manages their own costs independently',
      'Consolidation is not possible with multiple accounts',
      'Use a single AWS account for all teams',
    ],
    correctIndex: 0,
    explanation: 'Multi-account FinOps governance is critical for large organizations. Architecture: (1) AWS Organizations: link all accounts to a master payer account. (2) Consolidated billing: single bill with per-account breakdown. (3) Cost and Usage Reports (CUR): centralized billing data exported to S3 (master account), analyzed with Athena/QuickSight. (4) Tagging policies: enforce mandatory tags (Team, Environment, CostCenter) using AWS Organizations tag policies. (5) Service Control Policies (SCPs): prevent costly actions (launching expensive instance types, creating resources in unauthorized regions). (6) Budgets: set budgets per account, per team (using tags), per service. Alert when 80% threshold reached. (7) Reserved Instance / Savings Plans sharing: RIs/SPs purchased in master account can be shared across all accounts (organization-wide discounts). (8) Cost allocation: use AWS Cost Categories to group accounts by team/department. (9) Chargeback: generate reports per team for internal billing. (10) FinOps tooling: deploy CloudHealth, Kubecost, or custom dashboards for centralized visibility. Independent management (B) leads to chaos. Consolidation IS possible (C) — it is AWS best practice. Single account (D) violates security/isolation principles. Multi-account is standard for enterprises.',
    tags: ['finops', 'aws-organizations', 'multi-account', 'governance', 'consolidated-billing', 'centralization'],
  },
  {
    topicSlug: 'finops',
    difficulty: 'HARD' as const,
    type: 'SCENARIO' as const,
    question: 'Your Spot instance fleet of 100 instances experiences frequent interruptions, causing job failures and costing more in retries than savings. How do you optimize?',
    options: [
      'Use Spot instance diversification (multiple instance types/AZs), implement checkpointing for fault tolerance, and mix Spot with On-Demand (80% Spot, 20% On-Demand base)',
      'Switch to 100% On-Demand instances',
      'Spot instances are not reliable and should not be used',
      'Interruptions cannot be mitigated',
    ],
    correctIndex: 0,
    explanation: 'Spot instances are 70-90% cheaper but can be interrupted when AWS needs capacity. Optimization for reliability: (1) Diversification: use multiple instance types (m5.large, m5a.large, m5n.large) and AZs. AWS is less likely to interrupt simultaneously across diverse types. (2) Spot Fleet / EC2 Fleet: automatically provisions from multiple pools (instance type + AZ combinations), replacing interrupted instances. (3) Fallback to On-Demand: configure Auto Scaling Group or EKS node group to launch On-Demand instances when Spot capacity is unavailable. (4) Capacity Rebalancing: EKS/ASG can proactively replace Spot instances at elevated interruption risk before interruption. (5) Checkpointing: design workloads to checkpoint progress (save state to S3) and resume after interruption. Example: batch job processes 10,000 files, checkpoints every 1,000 files. (6) Graceful shutdown: handle SIGTERM signal (2-minute warning before interruption), drain work, save progress. (7) Mix Spot + On-Demand: 80% Spot (cost savings) + 20% On-Demand (baseline stability). Switching to 100% On-Demand (B) wastes savings. Spot IS reliable with proper architecture (C). Interruptions CAN be mitigated (D).',
    tags: ['finops', 'spot-instances', 'reliability', 'fault-tolerance', 'cost-optimization', 'aws'],
  },
  {
    topicSlug: 'finops',
    difficulty: 'HARD' as const,
    type: 'SCENARIO' as const,
    question: 'Your FinOps team calculates that a new feature will cost $20,000/month to run. Product team expects $50,000/month revenue. How do you evaluate if this is a good investment?',
    options: [
      'Calculate contribution margin ($50k revenue - $20k cost = $30k margin, 60% margin); compare to company targets; consider growth (will cost decrease or revenue increase?); evaluate opportunity cost',
      'Always approve if revenue > cost',
      'Only approve if margin is > 90%',
      'Ignore costs and focus on revenue only',
    ],
    correctIndex: 0,
    explanation: 'FinOps enables data-driven product investment decisions. Evaluation framework: (1) Contribution margin: Revenue - Variable costs (cloud costs, payment processing, support). $50,000 - $20,000 = $30,000 margin (60%). (2) Benchmark: compare to company gross margin targets (SaaS: 70-80% is good, 60% is acceptable for new features, <50% is concerning). (3) Growth trajectory: is this margin improving or worsening over time? If cost decreases as usage scales (economies of scale) or revenue grows (customer adoption), margin improves. (4) Customer lifetime value (LTV): if feature increases LTV, even low margin may be justified. (5) Opportunity cost: could $20,000/month be better spent on other features? (6) Strategic value: does this feature enable market expansion, competitive differentiation, or customer retention? (7) Optimization potential: can costs be reduced? (use Spot, right-size, optimize queries). Decision: (a) 60% margin is acceptable for new feature. (b) Approve with quarterly review: monitor actual revenue/cost, optimize costs, reassess. (c) Set target: improve margin to 70% within 6 months. Always approving (B) ignores profitability. 90% margin (C) is unrealistic for infrastructure-heavy features. Ignoring costs (D) leads to unprofitable products. FinOps bridges engineering and business.',
    tags: ['finops', 'unit-economics', 'product-investment', 'contribution-margin', 'business-analysis', 'decision-making'],
  },
  {
    topicSlug: 'finops',
    difficulty: 'HARD' as const,
    type: 'SCENARIO' as const,
    question: 'Your company uses both AWS and Azure. AWS bills $80,000/month, Azure $30,000/month. Leadership wants a unified cost view. How do you implement multi-cloud FinOps?',
    options: [
      'Use a multi-cloud FinOps platform (CloudHealth, Apptio, Flexera) or build custom solution using AWS CUR, Azure Cost Management APIs, and centralized data warehouse (Snowflake, BigQuery) with dashboards',
      'Multi-cloud cost management is impossible',
      'Migrate everything to one cloud',
      'Manage AWS and Azure costs separately',
    ],
    correctIndex: 0,
    explanation: 'Multi-cloud FinOps is complex due to different pricing models, APIs, and terminology. Implementation approaches: (1) Multi-cloud FinOps platform: CloudHealth (by VMware), Apptio Cloudability, Flexera, or Spot.io provide unified views, recommendations, and automation for AWS, Azure, GCP, Kubernetes. Pros: turnkey solution, multi-cloud expertise. Cons: cost (~1-3% of cloud spend). (2) Build custom solution: (a) Data ingestion: use AWS Cost and Usage Reports (CUR) exported to S3, Azure Cost Management API to export billing data. (b) Data warehouse: load data into centralized warehouse (Snowflake, BigQuery, Redshift) with unified schema (normalize AWS and Azure metrics). (c) Dashboards: build dashboards (Tableau, Grafana, QuickSight) showing total spend, breakdown by cloud, service, team. (d) Tagging standardization: enforce consistent tags across clouds (Team, Environment, Application). (3) Challenges: (a) Different pricing models (AWS EC2 vs. Azure VMs, storage tiers). (b) Different discount mechanisms (AWS RIs vs. Azure RIs). (c) Currency and billing cycles. Multi-cloud IS manageable (B). Migration to single cloud (C) is often impractical (acquisitions, vendor diversity). Separate management (D) loses visibility. Multi-cloud FinOps is increasingly common.',
    tags: ['finops', 'multi-cloud', 'aws', 'azure', 'cost-management', 'data-warehouse', 'dashboards'],
  },

  // ─── ADDITIONAL FINOPS QUESTIONS ─────────────────────────────────────────────
  {
    topicSlug: 'finops',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What are the three pillars of FinOps?',
    options: [
      'Inform (visibility and allocation), Optimize (reduce waste and rates), and Operate (continuous improvement and governance)',
      'Build, Deploy, Monitor',
      'Plan, Execute, Review',
      'Spend, Track, Report',
    ],
    correctIndex: 0,
    explanation: 'FinOps (Cloud Financial Operations) is a cultural practice that brings financial accountability to cloud spending. The three pillars: (1) Inform: understand cloud usage and spending. Cost visibility, allocation, showback/chargeback, tagging, reporting. Questions answered: "Who is spending what? On what services?" (2) Optimize: reduce cloud costs. Right-sizing, Reserved Instances, Spot instances, unused resource cleanup, architectural optimization. Questions answered: "How can we reduce costs without impacting performance?" (3) Operate: continuous governance and improvement. Budgets, alerts, policies, automation, anomaly detection. Questions answered: "How do we maintain cost efficiency over time?" FinOps lifecycle: these pillars operate in a continuous cycle. You cannot optimize what you cannot see (Inform first), and optimizations must be maintained (Operate). FinOps is a cross-functional practice involving engineering, finance, and business stakeholders.',
    tags: ['finops', 'fundamentals', 'pillars', 'cloud-cost-management'],
  },
  {
    topicSlug: 'finops',
    difficulty: 'MEDIUM' as const,
    type: 'THEORY' as const,
    question: 'What is the difference between showback and chargeback in FinOps?',
    options: [
      'Showback reports costs to teams without billing them; chargeback actually transfers budget/costs to team budgets for accountability',
      'Showback and chargeback are the same',
      'Chargeback is only for external customers',
      'Showback requires no tagging while chargeback does',
    ],
    correctIndex: 0,
    explanation: 'Showback: (1) Reports cloud costs to teams/departments. (2) No actual budget transfer — informational only. (3) Teams see their spending but are not billed. (4) Lower friction to implement (no finance integration). (5) Use case: early FinOps maturity, driving awareness. Chargeback: (1) Actually transfers costs to team budgets. (2) Teams are financially accountable (affects P&L). (3) Requires finance integration and approval. (4) Higher friction but stronger accountability. (5) Use case: mature FinOps, department-level P&L ownership. Implementation path: (1) Start with showback to build visibility and tagging discipline. (2) Refine allocation rules (shared costs, untagged resources). (3) Graduate to chargeback when allocation is accurate and teams are ready. Both require tagging: you cannot attribute costs without knowing who owns what. Tags like Team, CostCenter, Application enable allocation. They are different (B). Chargeback is internal (C). Both need tagging (D).',
    tags: ['finops', 'showback', 'chargeback', 'cost-allocation', 'accountability'],
  },
  {
    topicSlug: 'finops',
    difficulty: 'MEDIUM' as const,
    type: 'SCENARIO' as const,
    question: 'Your team consistently under-utilizes their AWS Reserved Instances (40% utilization). What strategies can improve RI utilization?',
    options: [
      'Convert to Convertible RIs for flexibility, enable RI sharing across accounts in AWS Organizations, right-size before purchasing, and consider Savings Plans instead',
      'Buy more RIs to lower the unit cost',
      'RI utilization cannot be improved once purchased',
      'Convert all workloads to On-Demand to avoid waste',
    ],
    correctIndex: 0,
    explanation: 'Low RI utilization wastes the upfront commitment. Strategies: (1) Convertible RIs: can be exchanged for different instance types/families. If a workload shrinks, convert RI to match new needs. (2) RI sharing (AWS Organizations): unused RI capacity in one account can automatically apply to matching usage in other accounts. Enable "RI sharing" at organization level. (3) Right-size first: analyze actual usage before purchasing RIs. Buy RIs for baseline usage only, use On-Demand/Spot for variable load. (4) Savings Plans: more flexible than RIs. Compute Savings Plans apply to any instance family, size, region, OS. Easier to maintain utilization as workloads change. (5) Sell unused RIs: AWS Marketplace allows selling Standard RIs (not Convertible). (6) Normalize instances: if you have m5.xlarge RI but run m5.2xlarge, capacity is wasted. Standardize instance sizes. Prevention: (1) Buy RIs quarterly based on recent usage (not annual forecasts). (2) Start with 1-year terms, graduate to 3-year as confidence grows. Buying more RIs (B) worsens the problem. Utilization CAN be improved (C). On-Demand (D) wastes savings.',
    tags: ['finops', 'reserved-instances', 'utilization', 'optimization', 'savings-plans', 'aws'],
  },
  {
    topicSlug: 'finops',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What is Kubecost and why is it useful for Kubernetes cost management?',
    options: [
      'Kubecost provides real-time cost visibility for Kubernetes workloads, breaking down costs by namespace, deployment, pod, and label to enable accurate allocation and optimization',
      'Kubecost is a Kubernetes cluster management tool',
      'Kubecost replaces the Kubernetes scheduler',
      'Kubecost only works with GKE',
    ],
    correctIndex: 0,
    explanation: 'Kubecost solves Kubernetes cost visibility challenges: Problem: cloud bills show EC2/EKS costs at the node level, but you need costs per application, team, or microservice (namespace, deployment, pod). Kubecost provides: (1) Cost allocation: breaks down cluster costs by namespace, deployment, pod, label, or annotation. (2) Real-time visibility: dashboards showing cost trends, efficiency metrics. (3) Savings recommendations: identifies over-provisioned containers, suggests right-sizing. (4) Cost APIs: integrate with FinOps platforms or custom dashboards. (5) Alerts: notify when costs exceed thresholds. (6) Multi-cluster support: aggregate costs across clusters. How it works: (1) Runs as a deployment in your cluster. (2) Collects resource metrics (CPU, memory, storage, network). (3) Combines with cloud pricing (AWS, GCP, Azure). (4) Allocates costs to workloads based on actual resource usage. Alternatives: OpenCost (open-source, CNCF), native cloud tools (AWS Cost Explorer, GKE cost allocation). Kubecost is FinOps, not cluster management (B). It does not replace the scheduler (C). It works with EKS, AKS, GKE, and self-managed (D).',
    tags: ['finops', 'kubecost', 'kubernetes', 'cost-allocation', 'container-costs'],
  },
];
