export const iacQuestions = [
  // ─── EASY THEORY ───────────────────────────────────────────────────────────
  {
    topicSlug: 'iac-terraform',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What is Infrastructure as Code (IaC) and what are its main benefits?',
    options: [
      'IaC defines infrastructure using code files (version-controlled, repeatable); benefits include consistency, automation, version control, and disaster recovery',
      'IaC is only for cloud infrastructure, not on-premises',
      'IaC is slower than manual infrastructure provisioning',
      'IaC requires programming knowledge and is not suitable for operations teams',
    ],
    correctIndex: 0,
    explanation: 'Infrastructure as Code (IaC) is the practice of managing and provisioning infrastructure through machine-readable definition files rather than manual processes (clicking through consoles, running CLI commands). Benefits: (1) Version control: infrastructure code is stored in Git, providing history, diffs, and rollback. (2) Repeatability: create identical environments (dev, staging, prod) from the same code. (3) Automation: infrastructure changes are applied programmatically via CI/CD. (4) Documentation: code serves as living documentation of infrastructure. (5) Disaster recovery: recreate entire infrastructure from code after failure. (6) Collaboration: teams review infrastructure changes via pull requests. (7) Consistency: eliminate configuration drift caused by manual changes. IaC tools: Terraform (cloud-agnostic), CloudFormation (AWS), ARM templates (Azure), Pulumi (general-purpose programming languages). IaC works for on-premises, cloud, and hybrid (B is wrong). IaC is faster at scale than manual provisioning (C). Modern IaC tools use declarative DSLs, not complex programming (D).',
    tags: ['iac', 'terraform', 'infrastructure', 'automation', 'devops'],
  },
  {
    topicSlug: 'iac-terraform',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What is Terraform and how does it differ from CloudFormation?',
    options: [
      'Terraform is cloud-agnostic (supports AWS, Azure, GCP, etc.); CloudFormation is AWS-specific',
      'Terraform is for small projects; CloudFormation is for enterprise',
      'Terraform is free; CloudFormation is paid',
      'They are the same tool with different names',
    ],
    correctIndex: 0,
    explanation: 'Terraform (by HashiCorp) is a declarative, cloud-agnostic IaC tool. You define infrastructure in HCL (HashiCorp Configuration Language) and Terraform provisions it across multiple providers: AWS, Azure, GCP, Kubernetes, DataDog, PagerDuty, GitHub, etc. Terraform uses providers (plugins) to interact with APIs. CloudFormation is an AWS-native IaC service. You define infrastructure in YAML or JSON templates, and CloudFormation provisions AWS resources. CloudFormation is tightly integrated with AWS services and is free (you pay for resources, not the service). Terraform comparison: (1) Multi-cloud: Terraform works across clouds; CloudFormation is AWS-only. (2) State management: Terraform requires state files (local or remote); CloudFormation manages state internally. (3) Flexibility: Terraform supports custom providers; CloudFormation is limited to AWS. (4) Ecosystem: Terraform has a large module registry (Terraform Registry); CloudFormation uses AWS SAM/CDK. Neither is limited by project size (B). Both are free services (C) — you pay for infrastructure. They are different tools (D).',
    tags: ['iac', 'terraform', 'cloudformation', 'aws', 'multi-cloud'],
  },
  {
    topicSlug: 'iac-terraform',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What is the Terraform workflow (init, plan, apply)?',
    options: [
      'init: download providers; plan: preview changes; apply: execute changes',
      'init: create resources; plan: delete resources; apply: rollback',
      'init, plan, and apply all do the same thing',
      'init is optional; you can skip directly to apply',
    ],
    correctIndex: 0,
    explanation: 'Terraform workflow consists of three core commands: (1) terraform init: initializes a Terraform working directory. Downloads provider plugins (AWS, Azure, GCP providers) from the Terraform Registry, configures backend for state storage (S3, Terraform Cloud), and sets up modules. You run init once when starting a new project or when adding new providers/modules. (2) terraform plan: creates an execution plan showing what Terraform will do. Compares current state with desired state (defined in .tf files), shows resources to be created (+), modified (~), or destroyed (-), and does NOT make any changes (dry-run). Review plan output to catch mistakes before applying. (3) terraform apply: executes the planned changes. Prompts for confirmation (auto-approve flag skips this), provisions resources via provider APIs (AWS API, Azure Resource Manager), and updates state file with current resource IDs and attributes. Additional commands: terraform destroy (delete all resources), terraform validate (check syntax), terraform fmt (format code). Init is NOT optional (D) — it must be run first.',
    tags: ['terraform', 'iac', 'workflow', 'init', 'plan', 'apply'],
  },
  {
    topicSlug: 'iac-terraform',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What is a Terraform state file and why is it important?',
    options: [
      'The state file is a JSON file tracking the mapping between Terraform configuration and real-world resources; losing it means Terraform cannot manage existing infrastructure',
      'The state file is a backup of Terraform code',
      'The state file is optional and can be disabled',
      'The state file contains secrets and must be committed to Git',
    ],
    correctIndex: 0,
    explanation: 'The Terraform state file (terraform.tfstate) is a JSON file that stores: (1) Mapping between Terraform resources in code (aws_instance.web) and real resource IDs (i-0abcd1234). (2) Current attributes of resources (IP addresses, DNS names, etc.). (3) Dependency graph for proper resource ordering. When you run terraform plan, Terraform reads the state file to understand what infrastructure currently exists, compares it to your .tf files, and calculates required changes. Losing the state file is catastrophic — Terraform cannot manage existing infrastructure and may try to recreate everything, causing downtime and data loss. State file management: (1) Remote backend: store state in S3, Terraform Cloud, Azure Storage (never local files for teams). (2) State locking: use DynamoDB (with S3) or built-in locking to prevent concurrent modifications. (3) Encryption: enable encryption at rest (S3 encryption, Terraform Cloud). (4) Never commit state to Git: it contains sensitive data (passwords, keys). State is not a backup (B), not optional (C), and must NOT be in Git (D).',
    tags: ['terraform', 'state', 'state-file', 'iac', 'remote-backend'],
  },
  {
    topicSlug: 'iac-terraform',
    difficulty: 'EASY' as const,
    type: 'SCENARIO' as const,
    question: 'You run "terraform apply" and get an error: "Error: error creating EC2 Instance: UnauthorizedOperation". What is the likely cause?',
    options: [
      'The AWS IAM credentials used by Terraform lack the necessary permissions to create EC2 instances',
      'The Terraform syntax is invalid',
      'The EC2 service is down',
      'You need to run terraform init first',
    ],
    correctIndex: 0,
    explanation: `UnauthorizedOperation errors indicate IAM permission issues. Terraform authenticates to AWS using credentials from: (1) Environment variables (AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY), (2) Shared credentials file (~/.aws/credentials), (3) IAM role attached to EC2 instance or ECS task, (4) AWS profile (specified in provider block). The IAM user/role must have ec2:RunInstances permission (and related permissions: ec2:DescribeInstances, ec2:CreateTags, etc.). Troubleshooting: (1) Check IAM policy attached to the user/role. (2) Run 'aws sts get-caller-identity' to verify which identity Terraform is using. (3) Attach a policy like AmazonEC2FullAccess (for testing) or create a custom policy with least-privilege permissions. (4) Check for permission boundaries or SCPs that may restrict actions. Invalid syntax (B) causes different errors (syntax error, validation failed). EC2 outage (C) would show service errors, not UnauthorizedOperation. Running init (D) does not fix permission issues.`,
    tags: ['terraform', 'aws', 'iam', 'permissions', 'troubleshooting', 'unauthorized'],
  },
  {
    topicSlug: 'iac-terraform',
    difficulty: 'EASY' as const,
    type: 'SCENARIO' as const,
    question: 'You want to create multiple similar resources (e.g., 5 EC2 instances) without duplicating code. What Terraform feature should you use?',
    options: [
      'Use the "count" or "for_each" meta-argument to create multiple instances of a resource',
      'Copy-paste the resource block 5 times',
      'Terraform cannot create multiple resources',
      'Use modules only',
    ],
    correctIndex: 0,
    explanation: 'Terraform provides meta-arguments for creating multiple similar resources: (1) count: creates N identical resources with an index (0 to N-1). Example: resource "aws_instance" "web" { count = 5; ami = "ami-123"; ... } creates web[0], web[1], ..., web[4]. Access index via count.index. Use case: create a fixed number of identical resources. (2) for_each: creates resources based on a map or set. Example: for_each = toset(["dev", "staging", "prod"]) creates 3 instances with keys "dev", "staging", "prod". Access key via each.key, value via each.value. Use case: create resources with distinct attributes (different names, sizes, etc.). Best practice: use for_each over count — it is more robust when resources are added/removed (count changes indices, causing resource recreation). Copy-pasting (B) is unmaintainable and violates DRY principle. Terraform supports multiple resources (C). Modules (D) are for encapsulation, not iteration within a single resource.',
    tags: ['terraform', 'count', 'for-each', 'iteration', 'resource-management', 'iac'],
  },
  {
    topicSlug: 'iac-terraform',
    difficulty: 'EASY' as const,
    type: 'SCENARIO' as const,
    question: 'Your Terraform code creates an S3 bucket, but you accidentally deleted the bucket manually via AWS Console. What happens when you run "terraform apply"?',
    options: [
      'Terraform detects the bucket is missing (state file says it exists, AWS API says it does not) and recreates it',
      'Terraform fails permanently and cannot recover',
      'Terraform does nothing because the state file still shows the bucket exists',
      'You must manually update the state file before running apply',
    ],
    correctIndex: 0,
    explanation: `Terraform reconciles desired state (code) with actual state (real infrastructure). When you run 'terraform plan' or 'terraform apply', Terraform: (1) Reads the state file (expects bucket to exist with ID "my-bucket"). (2) Calls AWS API to check if the bucket actually exists. (3) Detects drift: state says bucket exists, but API returns 404 Not Found. (4) Terraform plan shows: bucket will be created (+). (5) Terraform apply recreates the bucket. This is one of Terraform's core strengths: drift detection and correction. If infrastructure is manually modified or deleted, Terraform brings it back to the desired state defined in code. You do NOT need to manually fix the state file (D). Terraform does NOT fail permanently (B) — it adapts. Terraform does NOT ignore drift (C) — it detects and corrects it. This behavior makes Terraform self-healing and is a key advantage over manual infrastructure management.`,
    tags: ['terraform', 'drift-detection', 'state', 'reconciliation', 'self-healing', 'iac'],
  },

  // ─── MEDIUM THEORY ─────────────────────────────────────────────────────────
  {
    topicSlug: 'iac-terraform',
    difficulty: 'MEDIUM' as const,
    type: 'THEORY' as const,
    question: 'What are Terraform modules and when should you use them?',
    options: [
      'Modules are reusable Terraform code packages; use them to encapsulate and standardize infrastructure patterns (e.g., VPC, EKS cluster, RDS database)',
      'Modules are only for large enterprises',
      'Modules make Terraform slower and should be avoided',
      'Modules are the same as providers',
    ],
    correctIndex: 0,
    explanation: 'Terraform modules are containers for multiple resources used together. A module is a directory containing .tf files. Modules enable: (1) Reusability: write a VPC module once, reuse it across projects with different inputs (CIDR block, region, tags). (2) Abstraction: hide complexity. Users call a module without understanding internal implementation. (3) Standardization: enforce organizational patterns (security groups, tagging, naming conventions). (4) Composition: build complex infrastructure from smaller modules (app module uses VPC module, RDS module, ALB module). Module structure: inputs (variables), outputs (exposed attributes), resources. Example: module "vpc" { source = "terraform-aws-modules/vpc/aws"; version = "5.0.0"; cidr = "10.0.0.0/16"; azs = ["us-east-1a", "us-east-1b"]; }. Terraform Registry hosts thousands of community modules. Modules are valuable for teams of all sizes (B). Modules improve maintainability, not slow down Terraform (C). Modules and providers are different (D) — providers are plugins for APIs, modules are reusable code.',
    tags: ['terraform', 'modules', 'reusability', 'abstraction', 'iac', 'terraform-registry'],
  },
  {
    topicSlug: 'iac-terraform',
    difficulty: 'MEDIUM' as const,
    type: 'THEORY' as const,
    question: 'What is Terraform remote state and why should you use it?',
    options: [
      'Remote state stores the state file in a shared backend (S3, Terraform Cloud) with locking, enabling team collaboration and preventing state corruption',
      'Remote state is for backing up Terraform code',
      'Remote state is slower than local state',
      'Remote state is only for CloudFormation',
    ],
    correctIndex: 0,
    explanation: `Local state (terraform.tfstate in the working directory) is problematic for teams: (1) Not shared: team members cannot see each other's changes. (2) No locking: concurrent runs corrupt the state. (3) Not backed up: accidental deletion loses state. (4) Secrets exposed: state contains sensitive data (passwords) in plaintext. Remote state solves these issues by storing state in a shared backend. Common backends: (1) S3 + DynamoDB (AWS): store state in S3 bucket (versioned, encrypted), use DynamoDB for locking. (2) Terraform Cloud/Enterprise: managed state, built-in locking, UI, RBAC. (3) Azure Storage, GCS (Google Cloud Storage), Consul. Benefits: (1) Team collaboration: shared state visible to all. (2) State locking: prevents concurrent modifications (DynamoDB lock table or backend-native locking). (3) Encryption: encrypt state at rest and in transit. (4) Versioning: S3 versioning enables rollback. (5) Audit: track who accessed state. Remote state is NOT for code backup (B). Performance difference is negligible (C). Remote state is Terraform-specific (D).`,
    tags: ['terraform', 'remote-state', 'state-locking', 's3', 'backend', 'collaboration'],
  },
  {
    topicSlug: 'iac-terraform',
    difficulty: 'MEDIUM' as const,
    type: 'THEORY' as const,
    question: 'What is the purpose of Terraform workspaces and when should you use them?',
    options: [
      'Workspaces allow multiple state files within the same configuration, typically used for managing separate environments (dev, staging, prod)',
      'Workspaces are for dividing large Terraform files into smaller files',
      'Workspaces are only available in Terraform Enterprise',
      'Workspaces replace modules',
    ],
    correctIndex: 0,
    explanation: 'Terraform workspaces allow you to maintain multiple state files for the same configuration. Commands: terraform workspace new dev, terraform workspace select prod, terraform workspace list. Each workspace has its own state file (terraform.tfstate.d/dev/, terraform.tfstate.d/prod/). Use case: manage multiple environments (dev, staging, prod) from a single codebase. You can use terraform.workspace variable in code to apply environment-specific logic (different instance sizes, replica counts). Alternative approach: separate directories per environment (environments/dev/, environments/staging/, environments/prod/). Pros of workspaces: single codebase, less duplication. Cons: easy to accidentally apply to wrong workspace, limited blast radius separation. Many teams prefer separate directories for production isolation. Workspaces do NOT divide files (B) — that is what modules do. Workspaces are in open-source Terraform (C). Workspaces do NOT replace modules (D) — they serve different purposes. Workspaces are a trade-off: convenient but risky if misused.',
    tags: ['terraform', 'workspaces', 'environments', 'state', 'multi-environment', 'iac'],
  },
  {
    topicSlug: 'iac-terraform',
    difficulty: 'MEDIUM' as const,
    type: 'THEORY' as const,
    question: 'What is the "terraform import" command and when would you use it?',
    options: [
      'Import brings existing infrastructure (created outside Terraform) under Terraform management by adding it to the state file',
      'Import downloads modules from the Terraform Registry',
      'Import copies Terraform state from one backend to another',
      'Import is used to merge multiple Terraform projects',
    ],
    correctIndex: 0,
    explanation: 'terraform import allows you to bring existing infrastructure (created manually or by other tools) under Terraform management. Process: (1) Write Terraform resource block matching the existing resource (empty or with basic config). (2) Run terraform import <resource_type>.<name> <resource_id>. Example: terraform import aws_instance.web i-0abc123. (3) Terraform fetches resource attributes from the provider API and adds them to the state file. (4) Run terraform plan — Terraform shows differences between code and actual resource (you must manually write the full configuration to match). (5) Run terraform apply after aligning code with reality. Import is tedious for large infrastructures but necessary for: (1) migrating legacy infrastructure to IaC, (2) adopting Terraform in existing environments, (3) recovering from state file loss. Limitations: import adds to state but does NOT generate code — you must write .tf files manually. Tools like terraformer and former2 can auto-generate code. Import does NOT download modules (B) or copy state (C).',
    tags: ['terraform', 'import', 'state', 'legacy-infrastructure', 'migration', 'iac'],
  },
  {
    topicSlug: 'iac-terraform',
    difficulty: 'MEDIUM' as const,
    type: 'SCENARIO' as const,
    question: 'Two team members run "terraform apply" simultaneously on the same infrastructure. What happens and how do you prevent state corruption?',
    options: [
      'Without state locking, both runs modify the state concurrently, causing corruption; enable remote backend with locking (S3 + DynamoDB, Terraform Cloud) to prevent this',
      'Terraform automatically handles concurrent runs',
      'The second apply is queued automatically',
      'Concurrent applies are safe and will not cause issues',
    ],
    correctIndex: 0,
    explanation: `Concurrent Terraform runs without state locking cause race conditions: (1) User A runs terraform apply, reads state file (version 1). (2) User B runs terraform apply simultaneously, also reads state file (version 1). (3) User A applies changes, writes state file (version 2). (4) User B applies changes based on stale state (version 1), writes state file (version 3, missing A's changes). Result: state corruption, lost changes, potential infrastructure damage. State locking prevents this: (1) S3 backend + DynamoDB: when Terraform starts, it acquires a lock in DynamoDB table. Other runs wait until the lock is released. (2) Terraform Cloud: built-in locking with run queue. (3) Other backends (Azure Storage, GCS, Consul) have native locking. If locking is not available, use manual coordination (team communication, CI/CD pipelines running sequentially). Terraform does NOT auto-handle concurrent runs without locking (B). Runs are NOT auto-queued without explicit locking (C). Concurrent applies are dangerous (D). Locking is critical for team collaboration.`,
    tags: ['terraform', 'state-locking', 'concurrency', 'dynamodb', 'remote-state', 'collaboration'],
  },
  {
    topicSlug: 'iac-terraform',
    difficulty: 'MEDIUM' as const,
    type: 'SCENARIO' as const,
    question: 'Your Terraform plan shows it will destroy and recreate an RDS database, causing data loss. How do you prevent this?',
    options: [
      'Use lifecycle block with "prevent_destroy = true" or "create_before_destroy = true", and review the plan to understand why recreation is triggered',
      'Terraform recreations cannot be prevented',
      'Delete the resource from Terraform code',
      'Run terraform apply --no-destroy flag',
    ],
    correctIndex: 0,
    explanation: 'Terraform recreates resources when certain attributes change that cannot be modified in-place. For RDS, changing engine, instance class (in some cases), or allocated_storage (downward) triggers recreation. Prevention strategies: (1) lifecycle { prevent_destroy = true }: prevents Terraform from destroying the resource. If a destroy is planned, Terraform errors and stops. Use for: critical databases, production infrastructure. (2) lifecycle { create_before_destroy = true }: creates the new resource before destroying the old one, reducing downtime. Use for: stateless resources (load balancers, app servers). (3) Review plan carefully: terraform plan shows why recreation is triggered (forces replacement). Modify attributes to avoid recreation if possible. (4) Use terraform state rm to remove resource from state (manual management) if unavoidable. (5) Take backups before applying risky changes. Recreations can be prevented (B). Deleting from code (C) still destroys the resource. --no-destroy flag does not exist (D). Lifecycle meta-arguments are critical safety mechanisms.',
    tags: ['terraform', 'lifecycle', 'prevent-destroy', 'database', 'safety', 'iac'],
  },
  {
    topicSlug: 'iac-terraform',
    difficulty: 'MEDIUM' as const,
    type: 'SCENARIO' as const,
    question: 'You need to deploy infrastructure to AWS accounts in multiple regions (us-east-1, eu-west-1, ap-southeast-1). How do you structure Terraform code?',
    options: [
      'Use multiple provider blocks with aliases, and pass the provider explicitly to resources/modules for each region',
      'Run terraform apply three times, changing the region in provider block each time',
      'Terraform cannot deploy to multiple regions',
      'Create separate Terraform projects for each region',
    ],
    correctIndex: 0,
    explanation: 'Terraform supports multiple providers using aliases. Example: provider "aws" { region = "us-east-1" } (default provider); provider "aws" { alias = "eu"; region = "eu-west-1" }; provider "aws" { alias = "ap"; region = "ap-southeast-1" }. Specify provider in resources: resource "aws_instance" "web_us" { provider = aws; ... } (uses default); resource "aws_instance" "web_eu" { provider = aws.eu; ... }. Pass provider to modules: module "vpc_us" { source = "./modules/vpc"; providers = { aws = aws } }; module "vpc_eu" { source = "./modules/vpc"; providers = { aws = aws.eu } }. This approach allows single terraform apply to deploy across regions. Alternative: separate directories per region (regions/us-east-1/, regions/eu-west-1/) for isolated state and blast radius. Manually changing region and re-running apply (B) is error-prone. Terraform supports multi-region (C). Separate projects (D) are valid but not required. Multi-provider setup is standard for global infrastructure.',
    tags: ['terraform', 'multi-region', 'provider', 'alias', 'global-infrastructure', 'iac'],
  },

  // ─── HARD THEORY ───────────────────────────────────────────────────────────
  {
    topicSlug: 'iac-terraform',
    difficulty: 'HARD' as const,
    type: 'THEORY' as const,
    question: 'What is Terraform state locking and how does it work with S3 and DynamoDB?',
    options: [
      'State locking uses DynamoDB to store a lock record with LockID; Terraform acquires the lock before modifying state and releases it afterward, preventing concurrent modifications',
      'DynamoDB stores the entire state file',
      'State locking is automatic with S3 alone',
      'State locking requires Terraform Enterprise',
    ],
    correctIndex: 0,
    explanation: 'When using S3 as a remote backend, state locking prevents concurrent modifications via DynamoDB. Backend configuration: backend "s3" { bucket = "my-tf-state"; key = "global/s3/terraform.tfstate"; region = "us-east-1"; dynamodb_table = "terraform-locks"; encrypt = true }. Locking workflow: (1) Terraform starts an operation (plan, apply, destroy). (2) Attempts to write a lock record to DynamoDB table with LockID (composite of bucket + key). (3) If lock record does not exist, Terraform acquires the lock and proceeds. (4) If lock record exists (another run is active), Terraform waits or fails after timeout. (5) After operation completes, Terraform deletes the lock record. DynamoDB table schema: LockID (partition key, string), Info (state lock metadata, string). If Terraform crashes, the lock remains — use terraform force-unlock <lock_id> carefully to remove stale locks. S3 alone does NOT provide locking (C) — you need DynamoDB. DynamoDB does NOT store state (B) — only the lock. Locking is available in open-source Terraform (D).',
    tags: ['terraform', 'state-locking', 's3', 'dynamodb', 'concurrency', 'remote-backend'],
  },
  {
    topicSlug: 'iac-terraform',
    difficulty: 'HARD' as const,
    type: 'THEORY' as const,
    question: 'What are Terraform provider version constraints and why are they critical for production?',
    options: [
      'Version constraints (e.g., ~> 5.0) pin provider versions to prevent breaking changes from automatic upgrades; critical for stability and reproducibility',
      'Version constraints are optional and can be omitted',
      'Version constraints slow down Terraform',
      'Version constraints are only for modules',
    ],
    correctIndex: 0,
    explanation: `Terraform providers are versioned independently of Terraform itself. Without version constraints, 'terraform init' downloads the latest provider version, which may introduce breaking changes. Version constraint syntax: (1) ~> 5.0: allows 5.x updates but not 6.0 (pessimistic constraint, recommended for stability). (2) >= 5.0, < 6.0: explicit range. (3) = 5.12.0: pin to exact version (too restrictive, blocks bug fixes). (4) No constraint: always use latest (dangerous for production). Example: terraform { required_providers { aws = { source = "hashicorp/aws"; version = "~> 5.0" } } }. Best practices: (1) Use ~> constraints for production to allow patch/minor updates but block major versions. (2) Lock provider versions in .terraform.lock.hcl (generated by terraform init) and commit to Git. (3) Test provider upgrades in non-production environments first. (4) Review provider changelogs before upgrading. Version constraints are critical (B) — omitting them causes non-reproducible infrastructure. Performance is unaffected (C). Constraints apply to providers and modules (D).`,
    tags: ['terraform', 'provider', 'version-constraints', 'lock-file', 'stability', 'reproducibility'],
  },
  {
    topicSlug: 'iac-terraform',
    difficulty: 'HARD' as const,
    type: 'THEORY' as const,
    question: `What is Terraform's "replace" (formerly "taint") command and when should you use it?`,
    options: [
      'Replace marks a resource for recreation on the next apply; use it to force replacement of unhealthy or misconfigured resources without changing code',
      'Replace permanently deletes a resource',
      'Replace is a deprecated command',
      'Replace is only for CloudFormation',
    ],
    correctIndex: 0,
    explanation: 'terraform apply -replace="aws_instance.web" marks a resource for forced replacement (destroy then create) on the next apply, even if no code changes were made. Use cases: (1) Resource is in a bad state (misconfigured, corrupted, unhealthy) and needs to be recreated. (2) Trigger recreation to test disaster recovery/auto-healing. (3) Force re-execution of provisioners (which only run during creation). (4) Rotate resources periodically (e.g., recreate instances to apply new AMI). Old command (Terraform <0.15.2): terraform taint aws_instance.web (marks resource as tainted in state file). New command (Terraform >=0.15.2): terraform apply -replace (stateless, does not modify state file). Replace does NOT permanently delete (B) — it recreates. Replace is NOT deprecated (C) — taint is deprecated in favor of -replace. Replace is Terraform-specific (D). This is useful for operational scenarios where code-driven changes are not feasible.',
    tags: ['terraform', 'replace', 'taint', 'resource-recreation', 'operations', 'iac'],
  },
  {
    topicSlug: 'iac-terraform',
    difficulty: 'HARD' as const,
    type: 'THEORY' as const,
    question: `What is Terraform's "moved" block and when would you use it?`,
    options: [
      'The "moved" block tracks resource refactoring (renaming, moving between modules) without destroying and recreating resources',
      'The "moved" block migrates state between backends',
      'The "moved" block is for database migrations',
      'The "moved" block copies resources across regions',
    ],
    correctIndex: 0,
    explanation: 'When you refactor Terraform code (rename a resource, move it to/from a module), Terraform sees it as: old resource deleted, new resource created. This causes resource recreation, leading to downtime and data loss. The moved block (Terraform 1.1+) tells Terraform that a resource was refactored, not replaced. Example: you renamed aws_instance.web to aws_instance.app. Without moved block, Terraform destroys web and creates app. With moved block: moved { from = aws_instance.web; to = aws_instance.app }. Terraform updates the state file (renames resource) without touching real infrastructure. Use cases: (1) Rename resources for clarity. (2) Reorganize code (move resources into/out of modules). (3) Consolidate or split resources. After applying the moved block, you can remove it — state is updated permanently. Before moved blocks, you had to use terraform state mv commands manually. Moved blocks do NOT migrate backends (B) — use terraform init -migrate-state. They are NOT for databases (C) or cross-region copies (D). Moved blocks are critical for safe refactoring.',
    tags: ['terraform', 'moved-block', 'refactoring', 'state', 'resource-renaming', 'iac'],
  },
  {
    topicSlug: 'iac-terraform',
    difficulty: 'HARD' as const,
    type: 'SCENARIO' as const,
    question: 'Your Terraform state file contains 500 resources and takes 10 minutes to refresh. How do you optimize Terraform performance?',
    options: [
      'Use -refresh=false to skip refresh during plan (when safe), split state into smaller workspaces/projects, use -target for specific resources, and parallelize with -parallelism',
      'Terraform performance cannot be optimized',
      'Delete unused resources from the state file manually',
      'Switch to CloudFormation',
    ],
    correctIndex: 0,
    explanation: 'Large Terraform states slow down operations because Terraform refreshes all resources (API calls to check current state) during plan/apply. Optimization strategies: (1) -refresh=false: skip refresh during plan (terraform plan -refresh=false). Use when you know state is current (risky for production — state may be stale). (2) Split state: divide large state into smaller isolated states (per team, per service, per environment). Each state manages fewer resources, refreshes faster. (3) -target: apply changes to specific resources only (terraform apply -target=aws_instance.web). Use sparingly — bypasses dependency graph. (4) -parallelism=N: increase parallel API requests (default 10). Example: terraform apply -parallelism=20. (5) Remove unused resources: if resources are no longer needed, destroy them (terraform destroy -target). (6) Optimize provider queries: some providers are slow (looking at you, Azure). State file size and complexity are primary bottlenecks. Manually editing state (C) is dangerous. CloudFormation has similar issues (D). Performance tuning is essential for large infrastructures.',
    tags: ['terraform', 'performance', 'optimization', 'state', 'refresh', 'parallelism'],
  },
  {
    topicSlug: 'iac-terraform',
    difficulty: 'HARD' as const,
    type: 'SCENARIO' as const,
    question: 'You need to deploy infrastructure to 10 AWS accounts (different teams, isolated billing). How do you structure Terraform to manage multi-account deployments?',
    options: [
      'Use multiple provider blocks with assume_role to different accounts, or use workspaces/directories per account with separate backend state files',
      'Terraform only supports single AWS account',
      'Create 10 separate Terraform installations',
      'Merge all accounts into one',
    ],
    correctIndex: 0,
    explanation: 'Multi-account AWS architecture is common for security, isolation, and billing separation. Terraform strategies: (1) Multiple providers with assume_role: provider "aws" { alias = "team_a"; assume_role { role_arn = "arn:aws:iam::111111111111:role/TerraformRole" } }; provider "aws" { alias = "team_b"; assume_role { role_arn = "arn:aws:iam::222222222222:role/TerraformRole" } }. Specify provider in resources: resource "aws_vpc" "team_a" { provider = aws.team_a; ... }. (2) Separate directories/workspaces per account: accounts/team-a/, accounts/team-b/. Each has its own backend config pointing to different S3 buckets/keys. Run terraform apply in each directory. (3) Terraform Cloud/Enterprise: use workspaces with different AWS credentials per workspace. (4) Terragrunt: DRY wrapper for Terraform, manages multi-account configurations elegantly. Best practice: separate state per account for blast radius isolation. Terraform supports multi-account (B). Multiple installations (C) are unnecessary. Merging accounts (D) defeats the purpose of isolation.',
    tags: ['terraform', 'multi-account', 'aws', 'assume-role', 'organizations', 'iac'],
  },
  {
    topicSlug: 'iac-terraform',
    difficulty: 'HARD' as const,
    type: 'SCENARIO' as const,
    question: 'Your team lost the Terraform state file for production infrastructure. How do you recover?',
    options: [
      'Recreate state by writing Terraform code matching production, then use "terraform import" for each resource to rebuild the state file',
      'Destroy all infrastructure and recreate from scratch',
      'State file loss is unrecoverable',
      'Manually write a new state file in JSON',
    ],
    correctIndex: 0,
    explanation: 'Losing the Terraform state file is a disaster but recoverable through painstaking import process: (1) Assess: List all production resources (AWS Console, CLI, CloudFormation exports, documentation). (2) Write code: Create .tf files for each resource based on current configuration. (3) Import resources: For each resource, run terraform import <resource_type>.<name> <resource_id>. Example: terraform import aws_instance.web i-0abc123, terraform import aws_security_group.app sg-0def456. (4) Align code with reality: After import, run terraform plan. Terraform shows differences between code and actual resources. Update .tf files to eliminate differences. (5) Validate: Once plan shows no changes, state is recovered. Prevention: (1) Use remote state with versioning (S3 versioned bucket). (2) Backup state regularly (automated S3 replication, Terraform Cloud backups). (3) Never delete state files. Destroying and recreating (B) causes massive downtime. State is recoverable (C) with effort. Manually writing state (D) is error-prone. Import is tedious but necessary. This is a top interview question for disaster recovery.',
    tags: ['terraform', 'state', 'disaster-recovery', 'import', 'state-loss', 'troubleshooting'],
  },
  {
    topicSlug: 'iac-terraform',
    difficulty: 'HARD' as const,
    type: 'SCENARIO' as const,
    question: 'You need to manage secrets (RDS password, API keys) in Terraform without hardcoding them. What is the best approach?',
    options: [
      'Use external secret management (AWS Secrets Manager, Vault) with data sources to fetch secrets at runtime, and mark outputs as sensitive',
      'Store secrets in Git with Terraform code',
      'Use environment variables only',
      'Secrets management is not possible in Terraform',
    ],
    correctIndex: 0,
    explanation: 'Hardcoding secrets in Terraform code is a critical security vulnerability. Best practices: (1) External secret management: store secrets in AWS Secrets Manager, HashiCorp Vault, Azure Key Vault, or GCP Secret Manager. Use data sources to fetch secrets at runtime: data "aws_secretsmanager_secret_version" "db_password" { secret_id = "prod/db/password" }. Reference: password = data.aws_secretsmanager_secret_version.db_password.secret_string. (2) Mark outputs as sensitive: output "db_password" { value = var.db_password; sensitive = true } prevents secrets from appearing in logs. (3) Environment variables: pass secrets via TF_VAR_* environment variables in CI/CD (do NOT commit to Git). (4) Terraform Cloud: store secrets in workspace variables (encrypted at rest). (5) Avoid state file secrets: use dynamic credentials or random_password resource. (6) State encryption: enable S3 encryption, Terraform Cloud encryption. Storing secrets in Git (B) is catastrophic. Environment variables alone (C) are insufficient without external management. Secrets management is critical in Terraform (D).',
    tags: ['terraform', 'secrets-management', 'security', 'aws-secrets-manager', 'vault', 'sensitive-data'],
  },

  // ─── ADDITIONAL IAC/TERRAFORM QUESTIONS ──────────────────────────────────────
  {
    topicSlug: 'iac-terraform',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What is the difference between Terraform variables and locals?',
    options: [
      'Variables are inputs from users/files/environment; locals are internal computed values within the configuration that cannot be set externally',
      'Variables and locals are the same thing',
      'Locals can be overridden by command-line flags',
      'Variables cannot have default values',
    ],
    correctIndex: 0,
    explanation: 'Variables (var.x): input values that can be set from multiple sources — terraform.tfvars, -var flag, TF_VAR_* environment variables, or default values. Used to parameterize configurations. Example: variable "instance_type" { default = "t3.micro" }. Locals (local.x): computed intermediate values used within the configuration. Cannot be set externally — they are internal helpers. Use for: (1) Reducing repetition. (2) Computing complex expressions once. (3) Building composite values. Example: locals { common_tags = { Environment = var.environment, Project = var.project } }. Key difference: variables are external inputs; locals are internal computations. Variables and locals serve different purposes (B). Locals cannot be overridden (C). Variables can have defaults (D).',
    tags: ['terraform', 'variables', 'locals', 'basics', 'configuration'],
  },
  {
    topicSlug: 'iac-terraform',
    difficulty: 'MEDIUM' as const,
    type: 'THEORY' as const,
    question: 'What is the purpose of terraform.lock.hcl and should it be committed to version control?',
    options: [
      'It locks provider versions to ensure consistent installations across team members and CI/CD; yes, it should be committed to Git',
      'It is a temporary cache file and should be gitignored',
      'It contains sensitive state information',
      'It is only used for Terraform Cloud',
    ],
    correctIndex: 0,
    explanation: 'terraform.lock.hcl (dependency lock file, introduced in Terraform 0.14): (1) Purpose: records the exact versions and checksums of providers selected for the project. (2) Ensures reproducibility: when another team member or CI/CD runs terraform init, they get the same provider versions. (3) Contains: provider version constraints resolved to specific versions, checksums for integrity verification (h1: and zh: hashes). (4) Should be committed: yes, commit .terraform.lock.hcl to version control. This ensures everyone uses identical provider versions. (5) Update with: terraform init -upgrade to get new versions matching version constraints. Without the lock file, different terraform init runs could resolve to different provider versions, causing inconsistent behavior. It is NOT temporary (B), NOT sensitive (C), and works with all Terraform configurations (D).',
    tags: ['terraform', 'lock-file', 'providers', 'version-control', 'reproducibility'],
  },
  {
    topicSlug: 'iac-terraform',
    difficulty: 'MEDIUM' as const,
    type: 'THEORY' as const,
    question: 'What is the difference between count and for_each in Terraform, and when should you use each?',
    options: [
      'count creates resources by index number; for_each creates resources with meaningful keys. Use for_each for resources that need stable identities when items are added/removed',
      'count and for_each are identical',
      'for_each only works with lists',
      'count is deprecated in favor of for_each',
    ],
    correctIndex: 0,
    explanation: 'count: creates N identical resources indexed by number (0, 1, 2...). Problem: if you remove an item from the middle, all subsequent resources are recreated due to index shift. Example: count = length(var.users) creates aws_iam_user.users[0], [1], [2]. If user 1 is removed, user 2 becomes [1] and is recreated. for_each: creates resources with string keys from a map or set. Keys are stable — removing an item does not affect others. Example: for_each = toset(var.users) creates aws_iam_user.users["alice"], ["bob"]. Removing "alice" does not affect "bob". When to use each: count: for truly identical, ordered resources (multiple identical EC2 instances). for_each: for resources with identities (users, S3 buckets, IAM policies) — almost always preferred. They are not identical (B). for_each works with maps and sets (C). count is not deprecated but for_each is preferred (D).',
    tags: ['terraform', 'count', 'for-each', 'iteration', 'best-practices'],
  },
  {
    topicSlug: 'iac-terraform',
    difficulty: 'MEDIUM' as const,
    type: 'SCENARIO' as const,
    question: 'You have a Terraform resource that Terraform wants to destroy and recreate (replace), but you cannot afford downtime. How do you handle this?',
    options: [
      'Use lifecycle { create_before_destroy = true } to create the replacement before destroying the old resource, minimizing downtime',
      'Terraform replacements always cause downtime',
      'Delete the resource from state before applying',
      'Disable the resource temporarily',
    ],
    correctIndex: 0,
    explanation: 'By default, Terraform destroys resources before creating replacements. This causes downtime. lifecycle { create_before_destroy = true } reverses the order: (1) Create new resource with temporary name. (2) Wait until new resource is healthy. (3) Update references to point to new resource. (4) Destroy old resource. Use cases: (1) EC2 instances behind a load balancer. (2) RDS instances (create replica, switch over, delete old). (3) Launch templates/configurations. Considerations: (1) Resource must support having two instances simultaneously (name conflicts, unique constraints). (2) May need to adjust names, use name_prefix instead of name. (3) Some resources (like aws_security_group) have default create-before-destroy behavior. Example: resource "aws_instance" "web" { lifecycle { create_before_destroy = true } }. Replacements do not always cause downtime (B). Deleting from state loses tracking (C). There is no "disable" concept (D).',
    tags: ['terraform', 'lifecycle', 'create-before-destroy', 'downtime', 'replacement'],
  },
  {
    topicSlug: 'iac-terraform',
    difficulty: 'HARD' as const,
    type: 'THEORY' as const,
    question: 'What is Terragrunt and what problems does it solve that Terraform alone cannot?',
    options: [
      'Terragrunt is a thin wrapper that provides DRY configurations, manages remote state setup, handles dependencies between modules, and enables multi-environment/multi-account patterns',
      'Terragrunt is a replacement for Terraform',
      'Terragrunt only works with AWS',
      'Terragrunt is deprecated',
    ],
    correctIndex: 0,
    explanation: 'Terragrunt (by Gruntwork) is a wrapper for Terraform that addresses common pain points: (1) DRY (Do Not Repeat Yourself): define backend configuration once, inherit in all modules. Define common variables once, override per environment. (2) Remote state management: automatically create S3 buckets, DynamoDB tables for state locking. Configure backend without repeating in every module. (3) Dependencies: explicitly define dependencies between modules. run_all apply applies modules in dependency order, run_all destroy destroys in reverse order. (4) Multi-environment: structure like envs/dev/, envs/prod/ with shared module code. (5) Hooks: run commands before/after terraform apply (e.g., generate tfvars, notify Slack). (6) Keep CLI DRY: pass common arguments automatically. Example structure: live/dev/vpc/terragrunt.hcl, live/prod/vpc/terragrunt.hcl, modules/vpc/main.tf. Terragrunt extends Terraform, does not replace it (B). It is cloud-agnostic (C). It is actively maintained (D). Used by many enterprises for large-scale Terraform management.',
    tags: ['terraform', 'terragrunt', 'dry', 'multi-environment', 'dependencies', 'gruntwork'],
  },
  {
    topicSlug: 'iac-terraform',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What is the purpose of the terraform validate command?',
    options: [
      'It checks whether the configuration is syntactically valid and internally consistent, without accessing remote state or provider APIs',
      'It checks if AWS resources exist',
      'It applies the configuration',
      'It destroys resources',
    ],
    correctIndex: 0,
    explanation: 'terraform validate checks your configuration for: (1) Syntax errors: missing braces, invalid HCL syntax. (2) Internal consistency: references to undefined resources, invalid attribute names, type mismatches. (3) Provider schema validation: checks resource attributes against provider schema. What it does NOT do: (1) Does not connect to remote state. (2) Does not make API calls to providers. (3) Does not check if resources exist. (4) Does not require credentials. Use in CI/CD: run terraform validate early in pipelines (before plan) to catch errors quickly without needing cloud credentials. Example: terraform validate returns exit code 0 if valid, non-zero with error messages if invalid. Combined with terraform fmt for code quality: terraform fmt -check -recursive && terraform validate. It does not check resource existence (B). It does not apply (C). It does not destroy (D).',
    tags: ['terraform', 'validate', 'syntax', 'ci-cd', 'linting'],
  },
  {
    topicSlug: 'iac-terraform',
    difficulty: 'HARD' as const,
    type: 'SCENARIO' as const,
    question: 'You need to refactor a monolithic Terraform configuration into reusable modules. What is the process for migrating existing resources to modules without destroying them?',
    options: [
      'Use terraform state mv to move resources from root to module addresses, keeping the same resource IDs in the state file',
      'Destroy all resources and recreate with modules',
      'Resources cannot be moved to modules',
      'Create modules and reimport all resources',
    ],
    correctIndex: 0,
    explanation: 'Migrating to modules requires moving resources in state without destroying them: (1) Create module structure: modules/vpc/main.tf, call from root: module "vpc" { source = "./modules/vpc" }. (2) Move resources in state: terraform state mv aws_vpc.main module.vpc.aws_vpc.main, terraform state mv aws_subnet.public module.vpc.aws_subnet.public. (3) Update code: remove resources from root, add to module. Ensure outputs and variables pass through correctly. (4) Verify: run terraform plan — should show no changes if state and code are aligned. Common moves: terraform state mv aws_instance.web[0] aws_instance.web_0 (rename), terraform state mv aws_s3_bucket.data module.storage.aws_s3_bucket.data (move to module). Caution: (1) Backup state before migration. (2) Some moves require module to be created first (terraform init). (3) Complex resources may need multiple moves. Destroying and recreating (B) causes downtime. Resources can be moved (C). Reimporting (D) is unnecessary and error-prone.',
    tags: ['terraform', 'modules', 'refactoring', 'state-mv', 'migration'],
  },
];
