export const kubernetesQuestions = [
  // ─── EASY THEORY ───────────────────────────────────────────────────────────
  {
    topicSlug: 'kubernetes',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What is a Kubernetes Pod and why is it the smallest deployable unit?',
    options: [
      'A Pod is a group of one or more containers that share network and storage; it is the smallest unit because Kubernetes manages Pods, not individual containers',
      'A Pod is a single container, and it is the smallest because you cannot split containers',
      'A Pod is a Kubernetes node where containers run',
      'A Pod is a namespace for isolating workloads',
    ],
    correctIndex: 0,
    explanation: 'A Pod is the fundamental building block in Kubernetes. It represents a group of one or more containers that are deployed together on the same node and share: (1) network namespace (same IP address, can communicate via localhost), (2) storage volumes, (3) lifecycle (all containers in a Pod are started, stopped, and restarted together). Most Pods contain a single container, but multi-container Pods are used for sidecar patterns (e.g., logging agent, service mesh proxy). Kubernetes schedules, scales, and manages Pods as atomic units — you cannot deploy a container without a Pod. Pods are ephemeral: they can be created, destroyed, and replaced at any time. Persistent data must be stored in Volumes outside the Pod. Each Pod gets a unique IP address in the cluster network. Pods are not nodes (C) — nodes are physical/virtual machines that run Pods. Pods are not namespaces (D) — namespaces are virtual clusters for resource isolation.',
    tags: ['kubernetes', 'pod', 'containers', 'fundamentals'],
  },
  {
    topicSlug: 'kubernetes',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What is the difference between a Kubernetes Deployment and a ReplicaSet?',
    options: [
      'A Deployment manages ReplicaSets and provides declarative updates and rollback capabilities; a ReplicaSet ensures a specified number of Pod replicas are running',
      'A Deployment is for stateful apps; ReplicaSet is for stateless apps',
      'A Deployment runs on master nodes; ReplicaSet runs on worker nodes',
      'They are the same thing with different names',
    ],
    correctIndex: 0,
    explanation: 'ReplicaSet is a lower-level Kubernetes resource that ensures a specified number of identical Pod replicas are running at all times. If a Pod crashes, the ReplicaSet controller creates a new one to maintain the desired count. However, ReplicaSets do not provide update or rollback capabilities — if you change the Pod template, existing Pods are not updated. Deployment is a higher-level abstraction that manages ReplicaSets. When you create a Deployment, Kubernetes automatically creates a ReplicaSet. When you update a Deployment (e.g., change the container image), Kubernetes creates a new ReplicaSet with the new Pod template and gradually scales it up while scaling down the old ReplicaSet (rolling update). You can also rollback to previous ReplicaSet versions with 'kubectl rollout undo'. Best practice: always use Deployments, not bare ReplicaSets or Pods, for managing application workloads. Neither is specific to stateful apps (B) — use StatefulSets for that. Both run on worker nodes (C).',
    tags: ['kubernetes', 'deployment', 'replicaset', 'rolling-update', 'workload-management'],
  },
  {
    topicSlug: 'kubernetes',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What are the different types of Kubernetes Services and when would you use each?',
    options: [
      'ClusterIP (internal cluster access), NodePort (expose on each node port), LoadBalancer (cloud provider LB), ExternalName (DNS alias)',
      'ClusterIP is for production; NodePort and LoadBalancer are for development only',
      'All service types provide the same functionality',
      'Services are only used for HTTP traffic',
    ],
    correctIndex: 0,
    explanation: 'Kubernetes Services provide stable networking for Pods, which have ephemeral IPs. Service types: (1) ClusterIP (default): assigns a virtual IP accessible only within the cluster. Use for: internal communication between microservices (backend API, database). (2) NodePort: exposes the Service on a static port (30000-32767) on every node. External traffic can reach the Service at <NodeIP>:<NodePort>. Use for: dev/test external access without a load balancer. (3) LoadBalancer: provisions a cloud load balancer (AWS ELB, GCP LB, Azure LB) with an external IP. Use for: production external access, automatically integrates with cloud infrastructure. (4) ExternalName: maps a Service to a DNS name (e.g., external database). Returns a CNAME record instead of proxying traffic. Services work for all protocols (TCP, UDP, HTTP) via selectors matching Pod labels. ClusterIP is not just for production (B) — it is the default for internal services. Service types are not functionally identical (C).',
    tags: ['kubernetes', 'service', 'networking', 'clusterip', 'nodeport', 'loadbalancer'],
  },
  {
    topicSlug: 'kubernetes',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What is the purpose of a Kubernetes ConfigMap and Secret?',
    options: [
      'ConfigMaps store non-sensitive configuration data (environment variables, config files); Secrets store sensitive data (passwords, tokens) in base64-encoded format',
      'ConfigMaps are for development; Secrets are for production',
      'ConfigMaps and Secrets are the same, just different names',
      'ConfigMaps are stored in etcd; Secrets are not',
    ],
    correctIndex: 0,
    explanation: 'ConfigMaps and Secrets decouple configuration from container images, enabling the same image to run in different environments (dev, staging, prod) with different configurations. ConfigMap stores key-value pairs or entire configuration files (e.g., nginx.conf, app.properties). Accessed by Pods as environment variables or mounted volumes. Use for: non-sensitive configuration (database host, feature flags, logging levels). Secrets store sensitive data (passwords, API keys, TLS certificates) in base64-encoded format (not encrypted by default — use encryption at rest in etcd). Accessed the same way as ConfigMaps but with additional security controls (RBAC, volume permissions). Use for: database passwords, OAuth tokens, private keys. Both are stored in etcd (D is wrong). ConfigMaps and Secrets are not environment-specific (B) — you create different ones per environment. They are not the same (C) — Secrets have additional security properties. Best practice: use external secret management (AWS Secrets Manager, HashiCorp Vault) with integrations like External Secrets Operator.',
    tags: ['kubernetes', 'configmap', 'secret', 'configuration', 'security'],
  },
  {
    topicSlug: 'kubernetes',
    difficulty: 'EASY' as const,
    type: 'SCENARIO' as const,
    question: 'Your Kubernetes Deployment shows "ImagePullBackOff" error. What are the most common causes?',
    options: [
      'The image does not exist, the image name/tag is incorrect, the registry requires authentication, or the node cannot reach the registry',
      'The Pod does not have enough CPU or memory',
      'The Deployment YAML syntax is invalid',
      'The Kubernetes version is too old',
    ],
    correctIndex: 0,
    explanation: 'ImagePullBackOff means Kubernetes failed to pull the container image and is backing off before retrying. Common causes: (1) Image does not exist: typo in image name or tag (myapp:latets instead of myapp:latest), or the image was deleted from the registry. (2) Private registry authentication: the image is in a private registry (Docker Hub private, ECR, GCR) but the Pod does not have credentials. Solution: create an imagePullSecret (kubectl create secret docker-registry) and reference it in the Pod spec. (3) Network issues: the node cannot reach the registry due to firewall rules, DNS issues, or lack of internet access. (4) Registry rate limits: Docker Hub has pull rate limits for anonymous users (100 pulls per 6 hours). Diagnosis: 'kubectl describe pod <pod_name>' shows detailed error messages. 'kubectl logs <pod_name>' will be empty (the container never started). CPU/memory issues (B) cause OOMKilled or CrashLoopBackOff, not ImagePullBackOff. Invalid YAML (C) prevents resource creation entirely.',
    tags: ['kubernetes', 'imagepullbackoff', 'troubleshooting', 'registry', 'container-image'],
  },
  {
    topicSlug: 'kubernetes',
    difficulty: 'EASY' as const,
    type: 'SCENARIO' as const,
    question: 'You want to run a one-time batch job in Kubernetes that processes data and exits. What resource type should you use?',
    options: [
      'Job (runs Pods until successful completion) or CronJob (runs Jobs on a schedule)',
      'Deployment (always keeps Pods running)',
      'DaemonSet (runs one Pod per node)',
      'StatefulSet (for stateful applications)',
    ],
    correctIndex: 0,
    explanation: 'Kubernetes Job creates one or more Pods and ensures they run to completion successfully. Once the task completes (exit code 0), the Job is considered complete and the Pods remain (in Completed state) for log inspection. Use Job for: data migration, batch processing, one-time scripts. You can configure parallelism (run N Pods in parallel) and completions (run N times total). CronJob is a higher-level resource that creates Jobs on a schedule (like cron syntax). Example: "0 2 * * *" runs a Job daily at 2 AM. Use CronJob for: scheduled backups, periodic data cleanup, daily report generation. Deployment (B) is for long-running applications — it continuously restarts Pods if they exit, which is not desired for batch jobs. DaemonSet (C) ensures one Pod runs on every node, used for cluster-wide services (logging agents, monitoring). StatefulSet (D) is for stateful apps requiring stable network identity and persistent storage (databases, Kafka). Understanding workload types is critical for Kubernetes interviews.',
    tags: ['kubernetes', 'job', 'cronjob', 'batch-processing', 'workload-types'],
  },
  {
    topicSlug: 'kubernetes',
    difficulty: 'EASY' as const,
    type: 'SCENARIO' as const,
    question: 'You deployed an application to Kubernetes, but when you curl the Service ClusterIP, you get "connection refused". What should you check?',
    options: [
      'Check if the Service selector matches the Pod labels, if Pods are running and ready, and if the containerPort matches the Service targetPort',
      'Check if the Kubernetes API server is running',
      'Restart the entire cluster',
      'Services do not work with curl; use a browser',
    ],
    correctIndex: 0,
    explanation: 'Service connection refused errors are usually due to misconfiguration between the Service and Pods. Troubleshooting steps: (1) Verify Service selector matches Pod labels: 'kubectl describe service <name>' shows the selector, 'kubectl get pods --show-labels' shows Pod labels. If they don\'t match, the Service has no endpoints. (2) Check if Pods are running and ready: 'kubectl get pods' — if Pods are CrashLoopBackOff or not Ready, the Service cannot route traffic. (3) Verify Endpoints: 'kubectl get endpoints <service-name>' shows the Pod IPs backing the Service. If empty, the selector is wrong. (4) Check port configuration: the Service port (what you connect to) must match the Service spec, and the targetPort must match the containerPort in the Pod spec. (5) Check firewall/network policies: NetworkPolicies may block traffic. The API server (B) being down would prevent kubectl commands entirely. Restarting the cluster (C) is drastic and does not fix configuration errors. Curl works with Services (D).',
    tags: ['kubernetes', 'service', 'networking', 'troubleshooting', 'endpoints'],
  },

  // ─── MEDIUM THEORY ─────────────────────────────────────────────────────────
  {
    topicSlug: 'kubernetes',
    difficulty: 'MEDIUM' as const,
    type: 'THEORY' as const,
    question: 'What is the purpose of Kubernetes resource requests and limits, and how do they affect scheduling?',
    options: [
      'Requests guarantee minimum resources for a Pod (used for scheduling); limits cap maximum resource usage (enforced by cgroups)',
      'Requests and limits are optional and have no effect on scheduling',
      'Requests are for CPU only; limits are for memory only',
      'Requests and limits are the same value and must be equal',
    ],
    correctIndex: 0,
    explanation: 'Kubernetes uses resource requests and limits to manage CPU and memory allocation. Requests specify the minimum guaranteed resources. The scheduler uses requests to find nodes with sufficient capacity. A Pod requesting 500m CPU and 1Gi memory will only be scheduled on nodes with at least that much available. Requests do not limit actual usage — a Pod can use more if available. Limits specify the maximum resources a Pod can consume. CPU limits throttle the Pod (via cgroups), memory limits trigger OOM killer if exceeded. Best practices: (1) Always set requests to match average usage for accurate scheduling. (2) Set limits higher than requests to allow bursts. (3) Avoid setting limits too low (causes throttling/OOMKills) or too high (allows resource hogging). (4) Use Vertical Pod Autoscaler (VPA) to recommend optimal values. Requests and limits are not optional (B) — without requests, Pods can be scheduled on overloaded nodes. Both apply to CPU and memory (C). Requests and limits can differ (D) — they often should.',
    tags: ['kubernetes', 'resource-requests', 'resource-limits', 'scheduling', 'performance'],
  },
  {
    topicSlug: 'kubernetes',
    difficulty: 'MEDIUM' as const,
    type: 'THEORY' as const,
    question: 'What is the difference between liveness and readiness probes in Kubernetes?',
    options: [
      'Liveness probes detect if a container is alive (restart if failing); readiness probes detect if a container is ready to serve traffic (remove from Service endpoints if failing)',
      'Liveness probes run before startup; readiness probes run after',
      'Liveness probes are for HTTP; readiness probes are for TCP',
      'They are the same and can be used interchangeably',
    ],
    correctIndex: 0,
    explanation: 'Kubernetes health checks ensure application reliability. Liveness probe checks if a container is running. If it fails, Kubernetes kills and restarts the container. Use for: detecting deadlocks, hung processes, infinite loops (application is alive but cannot make progress). Example: HTTP GET /healthz returning 200. Readiness probe checks if a container is ready to accept traffic. If it fails, Kubernetes removes the Pod from Service endpoints (no traffic routed to it), but does not restart the container. Use for: waiting for dependencies (database connection, cache warm-up), graceful startup/shutdown. Example: HTTP GET /ready returning 200 only after initialization completes. Startup probe (Kubernetes 1.20+) runs first, delays liveness/readiness until the application starts (useful for slow-starting apps). Probe types: HTTP GET, TCP socket, or exec (run command). Probes are not timing-based (B). Probes support multiple protocols (C). Liveness and readiness serve different purposes (D) — misconfiguring them causes cascading failures.',
    tags: ['kubernetes', 'liveness-probe', 'readiness-probe', 'health-checks', 'reliability'],
  },
  {
    topicSlug: 'kubernetes',
    difficulty: 'MEDIUM' as const,
    type: 'THEORY' as const,
    question: 'What is a Kubernetes Ingress and how does it differ from a LoadBalancer Service?',
    options: [
      'Ingress provides HTTP/HTTPS routing with path-based and host-based rules via a single load balancer; LoadBalancer Service creates one load balancer per Service',
      'Ingress is for internal traffic; LoadBalancer is for external traffic',
      'Ingress is only available in EKS; LoadBalancer works everywhere',
      'Ingress and LoadBalancer Service are the same',
    ],
    correctIndex: 0,
    explanation: 'LoadBalancer Service provisions one cloud load balancer (AWS ELB/ALB, GCP LB) per Service, which becomes expensive with many services. Ingress is a higher-level abstraction that provides HTTP/HTTPS routing to multiple Services through a single load balancer (Ingress Controller). Ingress features: (1) Host-based routing: route api.example.com to api-service, app.example.com to web-service. (2) Path-based routing: route /api/* to api-service, /images/* to cdn-service. (3) TLS termination: manage SSL certificates centrally. (4) URL rewrites, redirects, authentication. Popular Ingress Controllers: Nginx Ingress Controller, Traefik, HAProxy, AWS ALB Ingress Controller, Istio Gateway. Ingress requires an Ingress Controller to be installed in the cluster (not built into Kubernetes). Ingress is not limited to internal traffic (B). Ingress works on all Kubernetes platforms (C), though implementations vary. Ingress and LoadBalancer are complementary (D) — Ingress Controllers often use a LoadBalancer Service as the entry point.',
    tags: ['kubernetes', 'ingress', 'load-balancer', 'routing', 'http', 'networking'],
  },
  {
    topicSlug: 'kubernetes',
    difficulty: 'MEDIUM' as const,
    type: 'THEORY' as const,
    question: 'What is Kubernetes RBAC and how does it control access to cluster resources?',
    options: [
      'RBAC (Role-Based Access Control) uses Roles/ClusterRoles to define permissions and RoleBindings/ClusterRoleBindings to assign them to users/service accounts',
      'RBAC is a firewall for pod-to-pod communication',
      'RBAC is only for cluster administrators, not applications',
      'RBAC is disabled by default and must be manually enabled',
    ],
    correctIndex: 0,
    explanation: 'Kubernetes RBAC controls who can perform what actions on which resources. Components: (1) Role: defines permissions within a namespace (e.g., read pods, create services). (2) ClusterRole: defines permissions cluster-wide or across namespaces. (3) RoleBinding: grants a Role to users/groups/service accounts in a namespace. (4) ClusterRoleBinding: grants a ClusterRole cluster-wide. Permissions are additive (no deny rules). Example: Create a Role allowing read access to pods, bind it to a ServiceAccount, and pods running with that ServiceAccount can read other pods via the API. RBAC applies to: (1) Human users accessing kubectl/API. (2) ServiceAccounts used by pods to interact with the API. (3) External integrations (CI/CD, monitoring). RBAC is not for network traffic (B) — use NetworkPolicies for that. RBAC is critical for applications (C) — restrict pod permissions using ServiceAccounts. RBAC is enabled by default in modern Kubernetes (D). RBAC is a frequent interview topic because misconfigurations cause security vulnerabilities.',
    tags: ['kubernetes', 'rbac', 'security', 'authorization', 'service-account', 'access-control'],
  },
  {
    topicSlug: 'kubernetes',
    difficulty: 'MEDIUM' as const,
    type: 'SCENARIO' as const,
    question: 'Your application Pods are being evicted with "The node was low on resource: memory" errors. How do you prevent this?',
    options: [
      'Set appropriate resource requests and limits, use PodDisruptionBudgets to limit simultaneous evictions, add more nodes or scale existing nodes',
      'Disable eviction policies in Kubernetes',
      'Increase the Pod priority to prevent eviction',
      'Evictions are random and cannot be controlled',
    ],
    correctIndex: 0,
    explanation: 'Kubernetes evicts Pods when a node runs out of resources (memory, disk) to protect the node and other Pods. Eviction order: (1) BestEffort Pods (no requests/limits), (2) Burstable Pods (requests < limits), (3) Guaranteed Pods (requests = limits). Mitigation: (1) Set resource requests: Pods without requests are evicted first. (2) Set requests equal to limits (Guaranteed QoS) for critical workloads. (3) Use PodDisruptionBudgets (PDB) to limit simultaneous evictions (e.g., ensure at least 2 replicas remain during disruptions). (4) Add cluster capacity: add nodes or resize existing nodes to provide more memory. (5) Enable Cluster Autoscaler to automatically add nodes when resource pressure occurs. (6) Use priority classes: assign higher priority to critical Pods (lower priority Pods evicted first). Disabling eviction (B) is not possible — it is a core Kubernetes mechanism. Priority classes (C) help but do not prevent eviction entirely if the node is critically low. Eviction is deterministic, not random (D).',
    tags: ['kubernetes', 'eviction', 'resource-pressure', 'qos', 'pod-disruption-budget', 'troubleshooting'],
  },
  {
    topicSlug: 'kubernetes',
    difficulty: 'MEDIUM' as const,
    type: 'SCENARIO' as const,
    question: 'You need to update a Deployment with zero downtime. The application takes 30 seconds to start. What Kubernetes settings should you configure?',
    options: [
      'Use a rolling update strategy with appropriate readiness probes, set maxUnavailable=0 and maxSurge=1, and configure startupProbe or initialDelaySeconds',
      'Use a recreate strategy',
      'Scale down to 0 replicas, then scale back up',
      'Zero-downtime updates are not possible in Kubernetes',
    ],
    correctIndex: 0,
    explanation: 'Kubernetes Deployment supports two update strategies: Recreate (terminate all Pods, then create new ones — causes downtime) and RollingUpdate (default, gradually replace Pods). For zero-downtime rolling update: (1) Set maxUnavailable=0 to ensure no existing Pods are terminated until new Pods are ready. (2) Set maxSurge=1 (or higher) to allow extra Pods during the update (creates new Pod, waits for readiness, then terminates old Pod). (3) Configure readiness probe to accurately detect when the new Pod is ready to accept traffic (critical — if readiness probe passes too early, traffic is routed to not-yet-ready Pods). (4) Set initialDelaySeconds or use startupProbe to account for slow startup (prevent premature liveness probe failures that cause restart loops). (5) Ensure sufficient cluster capacity for maxSurge Pods. Recreate strategy (B) causes downtime. Scaling to 0 (C) causes total outage. Zero-downtime updates are standard practice (D). This pattern is tested extensively in production Kubernetes interviews.',
    tags: ['kubernetes', 'rolling-update', 'zero-downtime', 'deployment', 'readiness-probe', 'maxunavailable'],
  },
  {
    topicSlug: 'kubernetes',
    difficulty: 'MEDIUM' as const,
    type: 'SCENARIO' as const,
    question: 'Your StatefulSet requires 3 Pods to reach quorum, but only 2 Pods are starting successfully. How can you ensure minimum availability during updates?',
    options: [
      'Use PodDisruptionBudget (PDB) to specify minAvailable=2 or maxUnavailable=1, ensuring quorum is maintained during voluntary disruptions',
      'Increase replicas to 5 Pods',
      'Use a Deployment instead of StatefulSet',
      'StatefulSets cannot have minimum availability guarantees',
    ],
    correctIndex: 0,
    explanation: 'PodDisruptionBudgets (PDBs) protect availability during voluntary disruptions (node drains, cluster upgrades, Pod evictions). A PDB specifies either minAvailable (minimum number of Pods that must remain available) or maxUnavailable (maximum number that can be unavailable simultaneously). For a StatefulSet requiring quorum (e.g., etcd, ZooKeeper, Kafka): create a PDB with minAvailable=2. During a node drain or rolling update, Kubernetes will not evict Pods if doing so would violate the PDB. This prevents the cluster from losing quorum and becoming unavailable. Example: replicas=3, minAvailable=2. During update, only 1 Pod can be down at a time. PDBs do NOT prevent involuntary disruptions (node failures, out-of-memory kills). Increasing replicas (B) helps but does not enforce minimum availability during updates. Deployments (C) are for stateless apps; StatefulSets provide stable network identities for stateful apps. PDBs are critical for highly available stateful applications (D is wrong). This is a common topic in SRE interviews.',
    tags: ['kubernetes', 'poddisruptionbudget', 'statefulset', 'high-availability', 'quorum', 'voluntary-disruption'],
  },

  // ─── HARD THEORY ───────────────────────────────────────────────────────────
  {
    topicSlug: 'kubernetes',
    difficulty: 'HARD' as const,
    type: 'THEORY' as const,
    question: 'How does the Kubernetes scheduler decide which node to place a Pod on?',
    options: [
      'The scheduler filters nodes (predicates like resource capacity, taints/tolerations), then scores remaining nodes (priorities like spreading, affinity), and selects the highest-scoring node',
      'The scheduler randomly assigns Pods to nodes',
      'The scheduler always places Pods on the node with the most available resources',
      'The scheduler does not make decisions; users manually specify nodes',
    ],
    correctIndex: 0,
    explanation: 'The Kubernetes scheduler (kube-scheduler) assigns Pods to nodes in two phases: Filtering (Predicates) eliminates nodes that cannot run the Pod: (1) Insufficient resources (CPU, memory, GPU). (2) NodeSelector/NodeAffinity mismatch. (3) Taints without matching tolerations. (4) Pod anti-affinity rules. (5) Volume constraints (node must have access to required volumes). Scoring (Priorities) ranks remaining nodes: (1) LeastRequestedPriority: prefers nodes with lower resource utilization (spreading). (2) BalancedResourceAllocation: prefers balanced CPU/memory usage. (3) SelectorSpreadPriority: spreads Pods with the same labels across nodes. (4) NodeAffinityPriority: scores based on affinity preferences. (5) Custom scheduler extenders or scheduler plugins. The node with the highest score is selected. If multiple nodes tie, one is chosen randomly. Scheduling is deterministic based on rules, not random (B). The scheduler does not just pick the node with most resources (C) — it balances multiple factors. While users can specify nodeName, it bypasses the scheduler (D).',
    tags: ['kubernetes', 'scheduler', 'scheduling', 'predicates', 'priorities', 'node-selection'],
  },
  {
    topicSlug: 'kubernetes',
    difficulty: 'HARD' as const,
    type: 'THEORY' as const,
    question: 'What are Kubernetes admission controllers and how do they enforce policies?',
    options: [
      'Admission controllers intercept API requests after authentication/authorization but before persisting to etcd, and can mutate or validate objects (e.g., enforce security policies, inject sidecars)',
      'Admission controllers are plugins for kubectl',
      'Admission controllers monitor running Pods and restart them if they fail',
      'Admission controllers are only used for RBAC',
    ],
    correctIndex: 0,
    explanation: 'Admission controllers are plugins in the Kubernetes API server that intercept requests after authentication and authorization but before the object is persisted to etcd. Types: (1) Validating admission controllers: validate the request and accept or reject (e.g., deny privileged containers, enforce resource limits, require labels). (2) Mutating admission controllers: modify the request (e.g., inject environment variables, add default resource requests, inject sidecar containers like Istio proxy). Execution: mutating controllers run first, then validating controllers. If any controller rejects, the request fails. Common built-in controllers: NamespaceLifecycle (prevents creating resources in terminating namespaces), LimitRanger (enforces resource limits per namespace), PodSecurityAdmission (enforces Pod Security Standards). Custom controllers: ValidatingWebhookConfiguration and MutatingWebhookConfiguration allow external webhooks (OPA Gatekeeper, Kyverno) to enforce custom policies. Admission controllers are not kubectl plugins (B) or monitoring tools (C). They apply to all resource creation/updates, not just RBAC (D).',
    tags: ['kubernetes', 'admission-controllers', 'policy-enforcement', 'validation', 'mutation', 'webhooks'],
  },
  {
    topicSlug: 'kubernetes',
    difficulty: 'HARD' as const,
    type: 'THEORY' as const,
    question: 'What is the etcd database in Kubernetes and why is backing it up critical?',
    options: [
      'etcd is a distributed key-value store that holds all cluster state (resources, configuration); losing etcd means losing the entire cluster state, so backups are critical for disaster recovery',
      'etcd is a logging system for Kubernetes',
      'etcd is only used for storing Secrets',
      'etcd is automatically backed up by Kubernetes and does not require manual backups',
    ],
    correctIndex: 0,
    explanation: 'etcd is a strongly consistent, distributed key-value store that serves as Kubernetes' backing store for all cluster data: Pods, Services, ConfigMaps, Secrets, RBAC policies, custom resources, everything. The control plane (API server, scheduler, controller manager) reads and writes to etcd. If etcd data is lost or corrupted, the entire cluster state is lost — Kubernetes cannot recover Pods, Services, or any other resources. Disaster recovery requires etcd backups. Backup strategies: (1) Snapshot backups: use 'etcdctl snapshot save' to create point-in-time snapshots. (2) Continuous backups: tools like Velero back up Kubernetes resources to object storage. (3) etcd replication: run etcd as a cluster (3 or 5 members) for high availability. (4) External backup tools: managed Kubernetes services (EKS, GKE, AKS) often provide automated etcd backups. Restore: 'etcdctl snapshot restore' recreates the etcd data directory from a snapshot. etcd is not a logging system (B). It stores all resources, not just Secrets (C). Kubernetes does not auto-backup etcd (D) — you must implement backups.',
    tags: ['kubernetes', 'etcd', 'backup', 'disaster-recovery', 'state-management', 'cluster-data'],
  },
  {
    topicSlug: 'kubernetes',
    difficulty: 'HARD' as const,
    type: 'THEORY' as const,
    question: 'What is a Kubernetes Operator and how does it differ from a Helm chart?',
    options: [
      'An Operator is a Kubernetes-native application that uses custom resources and controllers to automate operational tasks (backups, upgrades, scaling); a Helm chart is a templating tool for packaging Kubernetes manifests',
      'An Operator is a deprecated feature replaced by Helm',
      'Operators and Helm charts are the same thing',
      'Operators are only for database management',
    ],
    correctIndex: 0,
    explanation: 'Helm charts are templates for deploying Kubernetes resources. They package YAML manifests with parameterization (values.yaml) and provide versioning, rollback, and lifecycle management. Helm is primarily a packaging and installation tool — it does not manage the runtime lifecycle of applications. Operators extend Kubernetes by encoding domain-specific operational knowledge into software. An Operator consists of: (1) Custom Resource Definition (CRD): defines a new API type (e.g., PostgresCluster). (2) Custom Controller: watches for custom resources and reconciles the desired state (e.g., create a PostgreSQL cluster, perform backups, handle failovers). Operators automate tasks like: database backups and restores, certificate renewal (cert-manager), application upgrades with custom logic, auto-scaling based on custom metrics. Operators can use Helm charts internally for deployment but add automation on top. Popular operators: Prometheus Operator, ArgoCD, Strimzi (Kafka), CloudNativePG (PostgreSQL). Operators are not deprecated (B). They are conceptually different from Helm (C). They are used for any complex stateful application, not just databases (D).',
    tags: ['kubernetes', 'operator', 'helm', 'crd', 'custom-controller', 'automation'],
  },
  {
    topicSlug: 'kubernetes',
    difficulty: 'HARD' as const,
    type: 'SCENARIO' as const,
    question: 'Your Kubernetes cluster is experiencing intermittent "too many open files" errors on nodes. What is the likely cause and solution?',
    options: [
      'The node is hitting the file descriptor limit due to too many Pods or file handles; increase fs.inotify.max_user_instances and fs.file-max kernel parameters, or reduce Pod density',
      'Kubernetes is misconfigured and needs to be reinstalled',
      'This is a Docker bug that cannot be fixed',
      'The node disk is full',
    ],
    correctIndex: 0,
    explanation: 'Linux systems have limits on the number of open file descriptors (files, sockets, pipes). Each Pod creates multiple file descriptors: (1) Container filesystem mounts (overlay, volumes). (2) inotify watches (kubelet watches container logs and filesystem changes). (3) Network sockets (container communication). (4) Device files (/dev/null, /dev/random). High-density nodes (many Pods per node) can exhaust file descriptor limits. Symptoms: "too many open files" errors, Pods failing to start, kubelet errors. Solutions: (1) Increase kernel limits: sysctl -w fs.inotify.max_user_instances=8192, fs.inotify.max_user_watches=524288, fs.file-max=2097152. (2) Reduce Pod density: schedule fewer Pods per node by adjusting resource requests or using node taints. (3) Optimize application: close file handles properly, avoid excessive log file handles. (4) Monitor file descriptor usage: lsof, /proc/<pid>/fd. This is a common production issue in large clusters. Reinstalling Kubernetes (B) does not fix kernel limits. This is not a Docker bug (C). Disk full (D) causes different errors.',
    tags: ['kubernetes', 'file-descriptors', 'ulimit', 'inotify', 'troubleshooting', 'node-limits'],
  },
  {
    topicSlug: 'kubernetes',
    difficulty: 'HARD' as const,
    type: 'SCENARIO' as const,
    question: 'You need to implement multi-tenancy in a Kubernetes cluster where different teams should not be able to see or access each other\'s resources. What approach should you take?',
    options: [
      'Use separate namespaces per team with RBAC policies restricting access, NetworkPolicies for network isolation, ResourceQuotas to limit resource usage, and PodSecurityStandards to enforce security',
      'Use separate clusters for each team',
      'Multi-tenancy is not possible in Kubernetes',
      'Just use RBAC alone without namespaces',
    ],
    correctIndex: 0,
    explanation: 'Multi-tenancy in Kubernetes requires isolation at multiple layers: (1) Namespace isolation: create a namespace per team. Namespaces provide logical grouping and RBAC boundaries. (2) RBAC: create Roles/RoleBindings scoped to each namespace, preventing cross-namespace access. Deny access to cluster-scoped resources (nodes, PVs) for non-admin users. (3) NetworkPolicies: enforce pod-to-pod network segmentation. Default deny all traffic, explicitly allow only necessary communication (e.g., team-a namespace cannot reach team-b pods). (4) ResourceQuotas: limit CPU, memory, and object counts per namespace to prevent resource hogging. (5) LimitRanges: enforce default/min/max resource requests per Pod to prevent denial-of-service. (6) PodSecurityStandards: enforce baseline or restricted security profiles (no privileged containers, no host access). (7) Admission controllers: use OPA Gatekeeper or Kyverno to enforce custom policies (e.g., mandatory labels, image registries). Separate clusters (B) provide stronger isolation but increase operational complexity. RBAC alone (D) is insufficient — network and resource isolation are also needed.',
    tags: ['kubernetes', 'multi-tenancy', 'rbac', 'network-policy', 'resource-quota', 'security', 'isolation'],
  },
  {
    topicSlug: 'kubernetes',
    difficulty: 'HARD' as const,
    type: 'SCENARIO' as const,
    question: 'Your Kubernetes cluster is running in AWS. During a node failure, Pods are stuck in Terminating state for 5 minutes before being rescheduled. How can you reduce this time?',
    options: [
      'Decrease node-monitor-grace-period and pod-eviction-timeout in kube-controller-manager, and use pod disruption budgets and preStop hooks for graceful shutdown',
      'Increase the number of nodes',
      'Kubernetes always takes 5 minutes and this cannot be changed',
      'Switch to a different cloud provider',
    ],
    correctIndex: 0,
    explanation: 'When a node fails, Kubernetes must detect the failure and reschedule Pods. Default timeline: (1) kubelet sends heartbeats to the control plane every 10s (node-status-update-frequency). (2) Control plane waits node-monitor-grace-period (default 40s) for heartbeats before marking the node NotReady. (3) Control plane waits pod-eviction-timeout (default 5 minutes) before evicting Pods from NotReady nodes. (4) Pods are marked Terminating and rescheduled on healthy nodes. This 5-minute delay causes downtime. Mitigation: (1) Reduce pod-eviction-timeout: set to 30s-1min in kube-controller-manager flags (trade-off: faster failover but more false positives during transient network issues). (2) Reduce node-monitor-grace-period: set to 20s (more aggressive node failure detection). (3) Use Pod preStop hooks to gracefully drain connections during termination. (4) Use PodDisruptionBudgets to ensure minimum replicas during disruptions. (5) Use liveness/readiness probes to detect Pod failures faster. Increasing nodes (B) does not reduce failover time. This is configurable (C). Cloud provider (D) does not affect Kubernetes behavior.',
    tags: ['kubernetes', 'node-failure', 'pod-eviction', 'high-availability', 'failover', 'tuning'],
  },
  {
    topicSlug: 'kubernetes',
    difficulty: 'HARD' as const,
    type: 'SCENARIO' as const,
    question: 'You deployed a custom controller that watches Pods and creates ConfigMaps. The controller is getting rate-limited by the API server with "429 Too Many Requests" errors. How do you fix this?',
    options: [
      'Implement client-side rate limiting, use informers with shared caches instead of direct LIST calls, and tune API server rate limit flags (--max-requests-inflight)',
      'Restart the API server',
      'Delete the controller and use built-in Kubernetes resources only',
      'Rate limiting cannot be configured in Kubernetes',
    ],
    correctIndex: 0,
    explanation: 'Kubernetes API server has rate limits to prevent overload. Custom controllers can easily overwhelm the API server with excessive LIST/WATCH requests. Best practices: (1) Use client-go informers: informers maintain a local cache synchronized with the API server via a single WATCH connection, dramatically reducing API calls. Controllers should query the cache instead of making repeated LIST calls. (2) Implement exponential backoff: when API calls fail, back off before retrying. (3) Use resource version: for WATCH requests, specify resourceVersion to receive only updates since the last known state. (4) Tune API server limits: increase --max-requests-inflight (default 400 for mutating requests, 800 for read-only). Monitor metrics: apiserver_request_total, apiserver_current_inflight_requests. (5) Use pagination for large LIST responses (--limit flag). Restarting the API server (B) does not fix the client behavior. Deleting the controller (C) is not a solution. Rate limiting is configurable (D is wrong). This is a common issue in custom operator development.',
    tags: ['kubernetes', 'api-server', 'rate-limiting', 'controllers', 'informers', 'performance', 'troubleshooting'],
  },
];
