export const linuxQuestions = [
  // ─── EASY THEORY ───────────────────────────────────────────────────────────
  {
    topicSlug: \'linux-shell\',
    difficulty: \'EASY\' as const,
    type: \'THEORY\' as const,
    question: \'What does the chmod 755 command do to a file?',
    options: [
      \'Gives the owner read/write/execute, group read/execute, others read/execute\',
      \'Gives everyone full read/write/execute permissions\',
      \'Removes all permissions from group and others\',
      \'Gives the owner read/write, group read, others no permission\',
    ],
    correctIndex: 0,
    explanation: \'chmod 755 uses octal notation where each digit represents permissions for owner, group, and others respectively. 7 = 4(read) + 2(write) + 1(execute) = rwx for owner. 5 = 4(read) + 0 + 1(execute) = r-x for group. 5 = r-x for others. This is the standard permission set for executables and directories that should be readable and executable by everyone but only writable by the owner. Common use cases: web server directories (/var/www/html), scripts that everyone should run but only root should modify. chmod 777 (option B) is a security anti-pattern. chmod 700 would remove group and others entirely. Understanding octal permissions is fundamental — every DevOps engineer is asked this in interviews.',
    tags: [\'linux\', \'permissions\', \'chmod\', \'security\'],
  },
  {
    topicSlug: \'linux-shell\',
    difficulty: \'EASY\' as const,
    type: \'THEORY\' as const,
    question: \'Which command shows all currently running processes with their CPU and memory usage?',
    options: [
      \'ps aux\',
      \'ls -la /proc\',
      \'jobs -l\',
      \'service --status-all\',
    ],
    correctIndex: 0,
    explanation: \'ps aux is the standard command for viewing all running processes. The flags mean: a = show processes for all users, u = display in user-oriented format (shows CPU%, MEM%, VSZ, RSS, TTY, STAT, START, TIME, COMMAND), x = include processes not attached to a terminal (daemons). The output columns include USER, PID, %CPU, %MEM, VSZ (virtual memory), RSS (resident set size — actual RAM used), TTY, STAT, START, TIME, and COMMAND. For a dynamic real-time view, top or htop is preferred. ls -la /proc (B) lists the proc filesystem directories but is not used for process viewing. jobs -l (C) shows jobs started by the current shell session only. service --status-all (D) shows systemd service status, not individual processes.',
    tags: [\'linux\', \'processes\', \'ps\', \'monitoring\'],
  },
  {
    topicSlug: \'linux-shell\',
    difficulty: \'EASY\' as const,
    type: \'THEORY\' as const,
    question: \'What is the purpose of a cron job and what does the expression "0 2 * * *" mean?',
    options: [
      \'A cron job is a scheduled task; "0 2 * * *" means run at 2:00 AM every day\',
      \'A cron job is a background daemon; "0 2 * * *" means run every 2 minutes\',
      \'A cron job is an alert; "0 2 * * *" means run at 2nd second of every minute\',
      \'A cron job is a log rotator; "0 2 * * *" means run twice a day at midnight and noon\',
    ],
    correctIndex: 0,
    explanation: \'Cron is a time-based job scheduler in Unix/Linux. The crontab syntax has five fields: minute (0-59), hour (0-23), day of month (1-31), month (1-12), day of week (0-7 where 0 and 7 are Sunday). So "0 2 * * *" breaks down as: 0 = at minute 0, 2 = at hour 2 (2 AM), * = every day of month, * = every month, * = every day of week. This runs exactly at 2:00 AM daily. Common patterns: "*/5 * * * *" = every 5 minutes, "0 0 * * 0" = every Sunday midnight, "0 9-17 * * 1-5" = every hour 9am-5pm weekdays. crontab -l lists current cron jobs, crontab -e edits them. Cron logs typically go to /var/log/syslog or /var/log/cron.',
    tags: [\'linux\', \'cron\', \'scheduling\', \'automation\'],
  },
  {
    topicSlug: \'linux-shell\',
    difficulty: \'EASY\' as const,
    type: \'THEORY\' as const,
    question: \'What is the difference between a hard link and a soft (symbolic) link in Linux?',
    options: [
      \'Hard links share the same inode and survive original file deletion; soft links are pointers that break if the original is deleted\',
      \'Hard links are for directories only; soft links are for files only\',
      \'Hard links work across filesystems; soft links do not\',
      \'There is no practical difference — they both point to the same data\',
    ],
    correctIndex: 0,
    explanation: \'This is a classic Linux interview question. A hard link creates a new directory entry pointing to the same inode (data blocks) as the original file. Since both names reference the same inode, deleting the original file does not remove the data — the data persists until all hard links are deleted. Hard links have important constraints: they cannot span different filesystems/partitions, and cannot link to directories (to prevent circular references). A symbolic (soft) link is a special file that contains the path to the target. It works like a Windows shortcut. Soft links CAN span filesystems and CAN link to directories. However, if the original file is deleted, the symlink becomes a "dangling" or "broken" link. Check with: ls -li (shows inodes), file (type), readlink (symlink target). Create: ln -s target linkname for symlinks.',
    tags: [\'linux\', \'filesystem\', \'inodes\', \'links\'],
  },
  {
    topicSlug: \'linux-shell\',
    difficulty: \'EASY\' as const,
    type: \'THEORY\' as const,
    question: \'What does the pipe operator "|" do in a Linux shell command?',
    options: [
      \'Sends the stdout of the left command as stdin to the right command\',
      \'Runs two commands simultaneously in parallel\',
      \'Redirects output to a file, appending to it\',
      \'Runs the right command only if the left command fails\',
    ],
    correctIndex: 0,
    explanation: \'The pipe operator | creates an inter-process communication channel — it connects the standard output (stdout, file descriptor 1) of the command on the left to the standard input (stdin, file descriptor 0) of the command on the right. This is one of the most powerful Unix philosophy concepts: small tools that do one thing well, composed together. Examples: cat /var/log/syslog | grep ERROR | tail -20 — reads the log, filters for ERROR lines, shows last 20. ps aux | grep nginx | awk "{print $2}" — finds nginx PIDs. The pipe does NOT run commands in parallel by default (though they may overlap in execution due to buffering). Option B describes & (background) or parallel. Option C describes >> (append redirect). Option D describes || (OR operator).',
    tags: [\'linux\', \'shell\', \'pipes\', \'stdin\', \'stdout\'],
  },
  {
    topicSlug: \'linux-shell\',
    difficulty: \'EASY\' as const,
    type: \'THEORY\' as const,
    question: \'How do you find all files larger than 100MB in the /var directory?',
    options: [
      \'find /var -type f -size +100M\',
      \'ls -lah /var | grep "100M"',
      \'du -sh /var/* | sort -h | tail -10\',
      \'locate /var -size 100MB\',
    ],
    correctIndex: 0,
    explanation: \'The find command is the correct tool for this. Breakdown: find = traverse directory tree, /var = starting directory, -type f = only files (not directories), -size +100M = larger than 100 megabytes (+ means greater than, M means megabytes, c=bytes, k=kilobytes, G=gigabytes). You can extend this: find /var -type f -size +100M -exec ls -lh {} ; to also show file details. Or add -mtime -7 to only show files modified in the last 7 days. ls -lah (B) lists the direct contents of /var but will not recurse or grep reliably for sizes. du -sh (C) shows directory usage summary but not individual files. locate (D) uses a database index but does not support size filtering and does not take a starting path like that.',
    tags: [\'linux\', \'find\', \'filesystem\', \'disk-management\'],
  },
  {
    topicSlug: \'linux-shell\',
    difficulty: \'EASY\' as const,
    type: \'SCENARIO\' as const,
    question: \'A web server process is consuming 100% CPU and you need to stop it immediately without rebooting. You know the process name is "nginx". What is the fastest sequence of commands?',
    options: [
      \'kill $(pgrep nginx) — sends SIGTERM to gracefully stop all nginx processes\',
      \'pkill -9 nginx — sends SIGKILL to forcefully terminate all nginx processes immediately\',
      \'service nginx stop — stops the nginx service through systemd\',
      \'renice -20 nginx — lowers the priority to free up CPU\',
    ],
    correctIndex: 1,
    explanation: \'In an emergency where a process is consuming 100% CPU and must be stopped immediately, pkill -9 nginx is the fastest option. Signal 9 (SIGKILL) cannot be caught, blocked, or ignored by the process — the kernel kills it unconditionally. pkill matches by name, so it kills all nginx processes at once. The -9 flag is critical here: SIGTERM (signal 15, the default) sends a polite termination request that the process CAN ignore or handle with cleanup code. A misbehaving process consuming 100% CPU may not respond to SIGTERM. However, best practice: try SIGTERM first (pkill nginx), wait 5 seconds, then use SIGKILL if unresponsive. kill $(pgrep nginx) uses SIGTERM — too polite for an emergency. service nginx stop (C) is fine for normal stops but goes through systemd which has timeouts. renice (D) changes priority but does NOT stop the process.',
    tags: [\'linux\', \'processes\', \'signals\', \'kill\', \'troubleshooting\'],
  },
  {
    topicSlug: \'linux-shell\',
    difficulty: \'EASY\' as const,
    type: \'THEORY\' as const,
    question: \'What is the /etc/passwd file and what does each field represent?',
    options: [
      \'User account information file with fields: username:password:UID:GID:comment:home:shell\',
      \'Password hash storage file with encrypted passwords for all users\',
      \'A configuration file that maps usernames to IP addresses for authentication\',
      \'A read-only file managed by the kernel containing active login sessions\',
    ],
    correctIndex: 0,
    explanation: '/etc/passwd is a plain text file that stores essential user account information. Each line represents one user with seven colon-separated fields: (1) username — the login name, (2) password — historically stored here but now replaced with "x" indicating the actual hash is in /etc/shadow for security, (3) UID — User ID (0=root, 1-999=system accounts, 1000+=regular users), (4) GID — primary group ID, (5) GECOS/comment — full name or description, (6) home directory — default location after login, (7) login shell — the program run at login (/bin/bash, /bin/sh, /sbin/nologin for service accounts). The file is world-readable (chmod 644) so programs can look up usernames. /etc/shadow stores the actual password hashes and is only readable by root. This separation is a security improvement introduced in the 1980s.',
    tags: [\'linux\', \'users\', \'security\', \'system-administration\'],
  },

  // ─── MEDIUM THEORY ─────────────────────────────────────────────────────────
  {
    topicSlug: \'linux-shell\',
    difficulty: \'MEDIUM\' as const,
    type: \'THEORY\' as const,
    question: \'What is the difference between a process and a thread in Linux, and how does the kernel handle context switching?',
    options: [
      \'Processes have separate memory spaces; threads share memory within a process. Context switching saves/restores CPU registers, stack pointer, and page tables\',
      \'Processes and threads are identical in Linux — both use the same task_struct\',
      \'Threads are faster than processes because they skip the kernel entirely and run in user space\',
      \'Context switching only occurs between processes, never between threads of the same process\',
    ],
    correctIndex: 0,
    explanation: \'In Linux, the distinction is crucial for DevOps performance tuning. A process is an independent execution unit with its own virtual address space, file descriptors, and resources. A thread (also called a Light Weight Process in Linux) shares the address space, file descriptors, and heap with other threads in the same process but has its own stack, registers, and thread-local storage. The kernel uses the same task_struct internally for both, but threads share the mm_struct (memory descriptor). Context switching involves: (1) saving the current process CPU registers to its kernel stack, (2) switching page tables (expensive — requires TLB flush for full process switch), (3) restoring the next process registers. Thread context switches within the same process are cheaper because page tables don\\'t need switching. Excessive context switching (visible via vmstat, cs column) degrades performance. Tools to observe: /proc/[pid]/status shows Threads count, perf stat shows context-switches.',
    tags: [\'linux\', \'processes\', \'threads\', \'kernel\', \'performance\'],
  },
  {
    topicSlug: \'linux-shell\',
    difficulty: \'MEDIUM\' as const,
    type: \'THEORY\' as const,
    question: \'Explain what file descriptors 0, 1, and 2 are and how you would redirect stderr to a file while keeping stdout going to the terminal.',
    options: [
      \'FD 0=stdin, 1=stdout, 2=stderr. Redirect with: command 2>error.log\',
      \'FD 0=stdout, 1=stdin, 2=stderr. Redirect with: command 1>error.log\',
      \'FD 0=stdin, 1=stdout, 2=stderr. Redirect with: command >error.log\',
      \'FD 0=stderr, 1=stdout, 2=stdin. Redirect with: command 2>>error.log\',
    ],
    correctIndex: 0,
    explanation: \'File descriptors are the foundation of Unix I/O. Every process inherits three standard file descriptors: FD 0 (stdin) — standard input, defaults to keyboard. FD 1 (stdout) — standard output, defaults to terminal. FD 2 (stderr) — standard error, defaults to terminal. The redirection operator 2>error.log redirects FD 2 (stderr) to the file error.log, while FD 1 (stdout) continues to the terminal. Common patterns: command > out.log 2>&1 redirects both stdout and stderr to the same file (2>&1 means "redirect FD 2 to wherever FD 1 currently points"). command 2>/dev/null discards all error output. command 1>out.log 2>err.log sends each stream to different files. command &>all.log is bash shorthand for redirecting both streams. In scripts, you can create custom FDs: exec 3>debug.log and then echo "debug" >&3. Understanding FDs is essential for writing robust shell scripts.',
    tags: [\'linux\', \'shell\', \'file-descriptors\', \'redirection\', \'io\'],
  },
  {
    topicSlug: \'linux-shell\',
    difficulty: \'MEDIUM\' as const,
    type: \'THEORY\' as const,
    question: \'What is systemd and how does it differ from the traditional SysV init system?',
    options: [
      \'systemd is a modern init system (PID 1) with parallel service startup, socket activation, journald logging, and declarative unit files, unlike SysV\\'s sequential shell scripts\',
      \'systemd is a security daemon that monitors system calls — SysV init is the actual process manager\',
      \'systemd and SysV init are equivalent; systemd is just a renamed version for newer kernels\',
      \'systemd only manages network interfaces; SysV init handles all other services\',
    ],
    correctIndex: 0,
    explanation: \'systemd replaced SysV init as the standard init system (PID 1) on most modern Linux distros. Key differences: (1) Startup: SysV uses sequential shell scripts in /etc/init.d/ (S01script, S02script order). systemd starts services in parallel where dependencies allow, dramatically reducing boot time. (2) Configuration: SysV uses bash scripts; systemd uses declarative .unit files (e.g., /etc/systemd/system/nginx.service) with [Unit], [Service], [Install] sections. (3) Logging: SysV uses syslog; systemd includes journald (journalctl -u nginx -f for logs). (4) Socket activation: systemd can start services on-demand when a connection arrives. (5) Cgroups integration: systemd tracks processes in cgroups for reliable service management. Key commands: systemctl start/stop/restart/enable/disable/status, journalctl -xe for logs. systemctl list-units --failed shows broken services. Understanding systemd is essential for troubleshooting production Linux servers.',
    tags: [\'linux\', \'systemd\', \'init\', \'services\', \'system-administration\'],
  },
  {
    topicSlug: \'linux-shell\',
    difficulty: \'MEDIUM\' as const,
    type: \'THEORY\' as const,
    question: \'In a shell script, what is the difference between $(), backticks, and '${}` for variable expansion?',
    options: [
      '$() is command substitution (preferred, nestable); backticks are older command substitution (not nestable); ${} is variable expansion with optional modifiers\',
      '$() runs commands in a subshell; backticks run in the current shell; ${} is arithmetic expansion\',
      \'All three are identical in bash — they exist only for historical compatibility\',
      '$() is for arrays; backticks are for strings; ${} is for integers only\',
    ],
    correctIndex: 0,
    explanation: \'These are three distinct mechanisms: $() is modern command substitution — it captures the stdout of a command: VERSION=$(cat /etc/os-release | grep VERSION_ID). It is nestable: INNER=$(echo $(date +%Y)). This is the preferred form in modern scripts. Backticks (`command\') are the legacy form of command substitution from original Bourne shell. They work identically to $() but cannot be nested cleanly: OLD=\'cat /etc/hostname`. Avoid in new scripts. ${} is variable expansion — it evaluates a variable and allows modifiers: ${VAR:-default} (use default if unset), ${VAR:?error} (fail with error if unset), ${VAR#prefix} (remove prefix), ${VAR%suffix} (remove suffix), ${#VAR} (string length), ${VAR/old/new} (substitution). Example: FILE=config.tar.gz; echo ${FILE%.gz} outputs config.tar. Mastering these is key to writing robust DevOps automation scripts.',
    tags: [\'linux\', \'shell\', \'scripting\', \'bash\', \'variables\'],
  },
  {
    topicSlug: \'linux-shell\',
    difficulty: \'MEDIUM\' as const,
    type: \'SCENARIO\' as const,
    question: \'Your application logs are filling up disk space at /var/log/app.log (currently 50GB). The app is still running and writing to this file. You need to free space without restarting the app. What is the correct approach?',
    options: [
      \'Run "rm /var/log/app.log" — the disk space will be freed immediately\',
      \'Run "> /var/log/app.log" or "truncate -s 0 /var/log/app.log" — zeros out the file while keeping the file descriptor open so the app keeps writing\',
      \'Run "mv /var/log/app.log /tmp/" — moving frees the space in /var/log immediately\',
      \'Run "gzip /var/log/app.log" — compresses the file in place to free space\',
    ],
    correctIndex: 1,
    explanation: \'This is a critical operational scenario. When a running process has a file open (via a file descriptor), deleting or moving the file does NOT free disk space — the kernel keeps the data on disk until all file descriptors referencing the inode are closed. So rm /var/log/app.log (A) removes the directory entry but the space is NOT freed while the app is running. mv (C) has the same problem — the inode persists. gzip (D) requires reading then writing, creating a new file, and the original stays open. The correct solution is to TRUNCATE the file: > /var/log/app.log (shell redirection) or truncate -s 0 /var/log/app.log. This zeroes the file contents while preserving the inode and the open file descriptor. The app continues writing from position 0. Verify with: lsof | grep app.log to see open FDs. Long-term solution: configure logrotate with copytruncate option for this app.',
    tags: [\'linux\', \'filesystem\', \'disk-management\', \'troubleshooting\', \'logrotate\'],
  },
  {
    topicSlug: \'linux-shell\',
    difficulty: \'MEDIUM\' as const,
    type: \'THEORY\' as const,
    question: \'What does "sed -i \'s/old/new/g\' file.txt" do, and what does the -i flag mean?',
    options: [
      \'It replaces all occurrences of "old" with "new" in file.txt in-place (editing the file directly), where -i means in-place editing\',
      \'It creates an interactive sed session where you can type replacements manually, -i means interactive\',
      \'It replaces only the first occurrence of "old" with "new", -i ignores case during matching\',
      \'It replaces "old" with "new" and prints to stdout, -i means invert the match\',
    ],
    correctIndex: 0,
    explanation: \'sed (stream editor) is a powerful text transformation tool. Breakdown: -i = in-place (edit the file directly rather than printing to stdout). On macOS, -i requires an extension argument: -i ''. s/old/new/g = substitute command: s = substitute, /old/ = pattern to match (regex), /new/ = replacement, /g = global flag (replace ALL occurrences on each line, not just the first). Without g, only the first match per line is replaced. Examples: sed -i \'s/localhost/0.0.0.0/g\' config.ini — change all hostnames. sed -i '/^#/d\' file.txt — delete all comment lines. sed -i \'3d\' file.txt — delete line 3. sed -i \'s/\\bfoo\\b/bar/g\' — whole word replacement. Always back up before sed -i in production: sed -i.bak \'s/old/new/g\' file creates file.bak first. Pair with grep -n to find lines before editing.',
    tags: [\'linux\', \'sed\', \'text-processing\', \'shell-scripting\'],
  },

  // ─── HARD THEORY ───────────────────────────────────────────────────────────
  {
    topicSlug: \'linux-shell\',
    difficulty: \'HARD\' as const,
    type: \'THEORY\' as const,
    question: \'Explain Linux kernel parameters tunable via sysctl that are critical for high-performance network servers, specifically around TCP stack optimization.',
    options: [
      \'net.core.somaxconn (listen backlog), net.ipv4.tcp_tw_reuse (TIME_WAIT reuse), net.ipv4.ip_local_port_range (ephemeral ports), net.core.rmem_max/wmem_max (socket buffers)',
      \'net.ipv4.tcp_fast_open only — all other TCP parameters are hardcoded in the kernel\',
      \'Only /proc/sys/fs/file-max matters — all network performance is determined by file descriptor limits\',
      \'kernel.pid_max and vm.swappiness are the only meaningful parameters for network servers\',
    ],
    correctIndex: 0,
    explanation: \'TCP stack tuning is essential for high-traffic servers. Critical parameters: (1) net.core.somaxconn — maximum listen backlog (pending connections). Default 128 is far too low for production. Set to 65535. Pair with net.ipv4.tcp_max_syn_backlog. (2) net.ipv4.tcp_tw_reuse=1 — allows reusing TIME_WAIT sockets for new connections to the same remote endpoint. Essential for servers making many outbound connections. (3) net.ipv4.ip_local_port_range="1024 65535" — increases the ephemeral port range for outbound connections, preventing port exhaustion. (4) net.core.rmem_max/wmem_max — maximum receive/send socket buffer sizes. For high-bandwidth connections set to 134217728 (128MB). (5) net.ipv4.tcp_keepalive_time=300 — reduces keepalive probe frequency. (6) fs.file-max — system-wide file descriptor limit. Apply permanently in /etc/sysctl.conf or /etc/sysctl.d/99-custom.conf, then run sysctl -p.',
    tags: [\'linux\', \'kernel\', \'sysctl\', \'tcp\', \'performance\', \'networking\'],
  },
  {
    topicSlug: \'linux-shell\',
    difficulty: \'HARD\' as const,
    type: \'THEORY\' as const,
    question: \'How do you use strace to diagnose a mysterious application crash, and what are the key system calls to look for?',
    options: [
      \'strace -p PID attaches to a running process; look for SIGSEGV in signal delivery, ENOENT in open() calls, EACCES in permission errors, and futex() for deadlocks\',
      \'strace only works on new processes, not running ones, and only shows memory allocation calls\',
      \'strace is deprecated — use gdb instead for all production diagnostics\',
      \'strace shows kernel logs only; for user-space crashes use dmesg exclusively\',
    ],
    correctIndex: 0,
    explanation: \'strace is invaluable for black-box debugging. Key usage patterns: strace -p [PID] attaches to a running process. strace -f follows forked child processes. strace -e trace=open,read,write,socket filters to specific syscalls. strace -c shows syscall counts and time (performance profiling). strace -T shows time spent in each syscall. What to look for when diagnosing crashes: (1) open()/openat() returning ENOENT — missing config files or libraries. (2) open() returning EACCES — permission denied on a resource. (3) mmap()/brk() failures — memory allocation issues. (4) futex(FUTEX_WAIT) that never returns — deadlock. (5) connect() returning ECONNREFUSED — dependency service down. (6) Signal delivery (--- SIGSEGV ---) shows the crash point. Real scenario: strace -p 1234 2>&1 | tail -20 just before a crash shows the last syscalls executed. Combine with ltrace for library calls.',
    tags: [\'linux\', \'strace\', \'debugging\', \'syscalls\', \'troubleshooting\'],
  },
  {
    topicSlug: \'linux-shell\',
    difficulty: \'HARD\' as const,
    type: \'SCENARIO\' as const,
    question: \'A production server has the following symptoms: load average is 40 (on an 8-core machine), top shows very little CPU usage in user/system space, but iowait is at 85%. No single process shows high CPU. What is happening and how do you diagnose it?',
    options: [
      \'High iowait with high load but low CPU means processes are blocked waiting for I/O (disk/network). Diagnose with: iostat -xz 1, iotop, lsof, and check for SSD/disk saturation\',
      \'Load average of 40 on 8 cores means 40 processes are running — this is normal for busy servers\',
      \'High iowait is always caused by network issues — check netstat and firewall rules first\',
      \'This indicates a kernel bug — reboot the server immediately and apply kernel patches\',
    ],
    correctIndex: 0,
    explanation: \'This describes classic I/O bound performance degradation. Load average counts BOTH running processes AND processes in uninterruptible sleep (D state — waiting for I/O). A load of 40 on 8 cores means ~32 extra processes stuck waiting for I/O. High iowait (85%) in CPU breakdown confirms: CPUs are idle but processes can\\'t proceed because they\\'re waiting for disk. Diagnosis steps: (1) iostat -xz 1 — shows per-disk utilization, await (avg wait time), %util. If a disk shows 100% util and high await (>20ms for SSD, >50ms for HDD) it\\'s saturated. (2) iotop -o — shows real-time per-process I/O. Find the culprit. (3) lsof +D /path — see what files a path has open. (4) cat /proc/[pid]/io — process I/O counters. (5) vmstat 1 — check bi (blocks in) and bo (blocks out). Solutions: upgrade disk tier (HDD→SSD→NVMe), add caching (Redis/Varnish), tune application buffering, check for log storms or backup jobs running.',
    tags: [\'linux\', \'performance\', \'io\', \'troubleshooting\', \'iostat\', \'iotop\'],
  },
  {
    topicSlug: \'linux-shell\',
    difficulty: \'HARD\' as const,
    type: \'THEORY\' as const,
    question: \'What are Linux namespaces and cgroups, and how do they form the foundation of container technology?',
    options: [
      \'Namespaces provide process isolation (PID, network, mount, UTS, IPC, user namespaces); cgroups limit and account for resource usage (CPU, memory, I/O). Together they create isolated, resource-constrained environments — the basis of Docker containers\',
      \'Namespaces are kernel modules for filesystem isolation only; cgroups are a userspace scheduling mechanism\',
      \'Both namespaces and cgroups are Docker-specific implementations not available in the base kernel\',
      \'Namespaces handle CPU allocation; cgroups handle memory isolation\',
    ],
    correctIndex: 0,
    explanation: \'This is the foundational question for understanding containers at the kernel level. Linux Namespaces provide isolation by giving processes a "view" that looks like an entire system: PID namespace — processes have their own PID 1 (think init inside container). Network namespace — separate network interfaces, routing tables, iptables rules, and sockets. Mount namespace — different filesystem mount points visible. UTS namespace — separate hostname and domain name. IPC namespace — separate message queues and semaphores. User namespace — map container UID/GID to host UID/GID (rootless containers). cgroups (Control Groups) v1 and v2 provide resource control: cpu — CPU time limits and shares. memory — hard memory limits, OOM killer. blkio/io — disk I/O limits. pids — limit number of processes. devices — control device access. Docker/containerd/runc use: unshare() syscall to create new namespaces, clone() with namespace flags, cgroupfs or systemd-cgroup to apply limits. kubectl describe pod shows resource limits which translate to cgroup entries at /sys/fs/cgroup/.',
    tags: [\'linux\', \'containers\', \'namespaces\', \'cgroups\', \'docker\', \'kernel\'],
  },
  {
    topicSlug: \'linux-shell\',
    difficulty: \'HARD\' as const,
    type: \'SCENARIO\' as const,
    question: \'You need to write a bash script that monitors a directory for new files and processes each one exactly once, even if the script is restarted. The script must be idempotent. What is the robust approach?',
    options: [
      \'Use inotifywait for real-time events, maintain a processed-files log, use file locking (flock) to prevent parallel processing, and use atomic mv for "processed" marking\',
      \'Use a simple while loop with ls and sleep 5, checking if files exist each iteration\',
      \'Use cron every minute to run a script that processes all files — cron handles deduplication automatically\',
      \'Use find with -newer flag to find recently modified files and process them\',
    ],
    correctIndex: 0,
    explanation: \'Building a robust file processor requires several Linux primitives: (1) inotifywait (from inotify-tools) — event-driven, zero polling overhead: inotifywait -m -e close_write /watch/dir. Triggers on file creation/modification, no busy-waiting. (2) Idempotency via a processed log: PROCESSED_LOG=/var/lib/processor/done.log. Before processing, check if filename is in log. After success, append to log. (3) flock for exclusion: exec 200>/var/lock/processor.lock; flock -x 200 prevents two script instances running concurrently (important for restarts). (4) Atomic operations: mv source dest within the same filesystem is atomic — use mv to a "processing" directory, then to "done" on success. This prevents partial processing. (5) Signal handling: trap \'cleanup\' SIGTERM SIGINT to handle graceful shutdown. The naive ls+sleep approach (B) misses files created and deleted quickly. cron (C) doesn\\'t deduplicate. find -newer (D) has race conditions. Production file processors often use this pattern for ETL pipelines.',
    tags: [\'linux\', \'shell-scripting\', \'inotify\', \'automation\', \'idempotency\'],
  },
  {
    topicSlug: \'linux-shell\',
    difficulty: \'MEDIUM\' as const,
    type: \'SCENARIO\' as const,
    question: \'You need to extract the 5th column from a CSV file where columns are separated by commas, and print only unique values sorted alphabetically. Which command pipeline achieves this?',
    options: [
      \'awk -F\',' '{print $5}' file.csv | sort | uniq\',
      \'cut -d\',' -f5 file.csv | sort -u\',
      \'Both A and B are correct — cut is simpler but awk handles edge cases better\',
      \'grep -o '[^,]*,[^,]*,[^,]*,[^,]*,\\([^,]*\\)' file.csv | sort | uniq\',
    ],
    correctIndex: 2,
    explanation: \'Both options A and B produce the correct result but have different strengths. cut -d\',' -f5 — uses comma as delimiter (-d\',') and extracts field 5 (-f5). sort -u combines sorting and deduplication in one step. This is simpler and faster for straightforward CSVs. awk -F\',' '{print $5}' — sets field separator to comma and prints column 5. sort | uniq is the traditional deduplication pipeline. awk is more powerful because: it handles quoted fields with commas (though not by default), you can add conditions (NR>1 to skip headers), apply transformations before printing. For production: if the CSV has a header row, skip it with: awk -F\',' \'NR>1{print $5}' file.csv | sort -u. If values may contain quoted commas, use a proper CSV parser like python -c "import csv,sys; ..." instead. The sort | uniq pattern is so common in Linux it\\'s considered idiomatic.',
    tags: [\'linux\', \'awk\', \'cut\', \'text-processing\', \'shell-scripting\'],
  },
  {
    topicSlug: \'linux-shell\',
    difficulty: \'EASY\' as const,
    type: \'THEORY\' as const,
    question: \'What is the purpose of the /etc/hosts file and when would you use it in a DevOps context?',
    options: [
      \'Maps hostnames to IP addresses locally, bypassing DNS. Used for local development, testing DNS changes, container networking, and emergency DNS overrides\',
      \'Stores the list of all allowed SSH hosts for the server — only IPs listed here can connect\',
      \'A backup DNS server list used only when the primary DNS is unreachable\',
      \'Manages firewall rules for hostname-based access control\',
    ],
    correctIndex: 0,
    explanation: '/etc/hosts is a local hostname resolution file that takes precedence over DNS (by default — controlled by /etc/nsswitch.conf "hosts: files dns" ordering). Format: IP_ADDRESS HOSTNAME ALIAS. DevOps use cases: (1) Local development — map app.local to 127.0.0.1 so developers can test with production-like URLs. (2) Testing DNS changes — before propagating a DNS change, test by adding the new IP in /etc/hosts. (3) Container networking — Docker containers\' /etc/hosts is automatically populated with container names and service aliases. (4) Emergency override — during a DNS outage, temporarily hardcode critical service IPs. (5) Kubernetes CoreDDS — pods get cluster service names resolved via /etc/hosts injection. (6) Block domains — map ad/tracking domains to 0.0.0.0. Important: changes take effect immediately (no reload needed) but only on that host. For Kubernetes pods, use hostAliases in pod spec instead.',
    tags: [\'linux\', \'networking\', \'dns\', \'hosts\', \'devops\'],
  },
  {
    topicSlug: \'linux-shell\',
    difficulty: \'MEDIUM\' as const,
    type: \'THEORY\' as const,
    question: \'What is the difference between "source script.sh", "./script.sh", and "bash script.sh" when running a shell script?',
    options: [
      \'source runs in the CURRENT shell (variable changes persist); ./script.sh and bash script.sh both run in a SUBSHELL (changes are lost after exit)',
      \'All three are identical — the shell creates a new process regardless of how you call the script\',
      \'source and bash script.sh create a subshell; ./script.sh runs in the current shell\',
      './script.sh requires the file to be owned by root; the others work for any file owner\',
    ],
    correctIndex: 0,
    explanation: \'This distinction is critical for shell scripting: source script.sh (or . script.sh) — executes the script in the CURRENT shell process. All variable assignments, function definitions, and directory changes (cd) persist after the script finishes. This is how .bashrc and .bash_profile work — they are sourced, not executed. Use when the script needs to modify the current environment (set environment variables, define functions). ./script.sh — executes in a subshell (child process). The script must have execute permission (chmod +x). Changes to variables and directory do NOT affect the parent shell. The script can use any interpreter specified in the shebang line (#!/bin/bash, #!/usr/bin/python3). bash script.sh — explicitly runs with bash in a subshell. Does NOT require execute permission. Ignores the shebang line (always uses bash). Practical example: An environment setup script should be sourced: source setup_env.sh. A deployment script should be executed: ./deploy.sh.',
    tags: [\'linux\', \'shell\', \'scripting\', \'bash\', \'subshell\'],
  },
  {
    topicSlug: \'linux-shell\',
    difficulty: \'HARD\' as const,
    type: \'THEORY\' as const,
    question: \'Explain Linux memory management concepts: virtual memory, the page cache, dirty pages, and when the OOM killer fires.',
    options: [
      \'Virtual memory provides each process a private address space. Page cache stores recently used disk data in RAM. Dirty pages are modified cache entries not yet written to disk. OOM killer fires when the kernel cannot allocate memory after exhausting swap\',
      \'Virtual memory is only used when RAM is full. Page cache is a Redis-like key-value store in the kernel. OOM killer runs every 5 minutes to free unused memory\',
      \'Linux does not have virtual memory — all processes share the same physical address space managed by the MMU\',
      \'Page cache and swap are the same concept. OOM killer fires when CPU usage exceeds 95%',
    ],
    correctIndex: 0,
    explanation: \'Linux memory management is deep but essential for performance tuning: Virtual Memory — each process sees a contiguous 64-bit address space (on x86_64) via page tables. Physical pages are mapped on-demand (lazy allocation). Pages may be shared (copy-on-write for fork). Page Cache — Linux aggressively uses free RAM as a cache for filesystem data. free -h shows "buff/cache" column. This is NOT wasted memory — it speeds up repeated disk reads dramatically. vm.dirty_ratio and vm.dirty_background_ratio control when dirty pages are flushed. Dirty Pages — pages in the page cache that have been modified but not yet written to disk. sync forces a flush. Excessive dirty data delays I/O (check /proc/meminfo: Dirty). OOM Killer — fires when the kernel tries to allocate memory (page fault) and both RAM and swap are exhausted. It uses an OOM score (/proc/[pid]/oom_score) to select the process to kill. Prevent OOM kills with: /proc/[pid]/oom_score_adj = -1000 (never kill). vm.overcommit_memory=2 prevents over-allocation. Monitor: dmesg | grep -i oom.',
    tags: [\'linux\', \'memory\', \'kernel\', \'oom\', \'performance\', \'page-cache\'],
  },
  {
    topicSlug: \'linux-shell\',
    difficulty: \'EASY\' as const,
    type: \'THEORY\' as const,
    question: \'What does "grep -r ERROR /var/log/ 2>/dev/null | wc -l" do?',
    options: [
      \'Recursively searches all files in /var/log/ for the word ERROR, suppresses permission errors, and counts the number of matching lines\',
      \'Searches /var/log/ for files named ERROR and counts how many files exist\',
      \'Counts the number of files in /var/log/ that are larger than ERROR size\',
      \'Searches for ERROR in /var/log/ and writes the count to file descriptor 2\',
    ],
    correctIndex: 0,
    explanation: \'Breaking down this pipeline: grep — the pattern matching tool. -r — recursive: search all files in the directory tree. ERROR — the literal string to search for (case-sensitive by default; use -i for case-insensitive). /var/log/ — the starting directory. 2>/dev/null — redirect stderr (FD 2) to /dev/null, discarding permission denied errors for files grep cannot read (e.g., /var/log/auth.log owned by root). | wc -l — pipe to word count, -l flag counts newlines (lines). Result: the total number of log lines across all files in /var/log/ that contain the word "ERROR". Common variations: grep -rl ERROR /var/log/ lists only filenames. grep -c ERROR file counts matches per file. grep -n ERROR file shows line numbers. grep -A 3 ERROR file shows 3 lines after each match (context). This exact pattern is used in monitoring scripts, incident triage, and CI/CD pipeline checks.',
    tags: [\'linux\', \'grep\', \'text-processing\', \'shell\', \'logging\'],
  },
  {
    topicSlug: \'linux-shell\',
    difficulty: \'MEDIUM\' as const,
    type: \'SCENARIO\' as const,
    question: \'A developer reports "too many open files" errors on a production server. How do you investigate and permanently fix this?',
    options: [
      \'Check with ulimit -n and lsof | wc -l; raise limits in /etc/security/limits.conf and /etc/sysctl.conf (fs.file-max); also check per-service systemd LimitNOFILE\',
      \'Restart the server — open file limits reset on reboot automatically\',
      \'Delete files in /tmp to free up file descriptors\',
      \'Reduce the number of running processes to stay within the 1024 file limit\',
    ],
    correctIndex: 0,
    explanation: \'File descriptor exhaustion is a common production issue. Diagnosis: ulimit -n — shows per-process FD limit for the current shell (default 1024). cat /proc/[pid]/limits — shows limits for a specific process. lsof -p [pid] | wc -l — counts open FDs for a process. lsof | wc -l — total system FDs. cat /proc/sys/fs/file-max — system-wide hard limit. cat /proc/sys/fs/file-nr — currently open / free / max. Fix hierarchy: (1) Per-user limits: /etc/security/limits.conf add: appuser soft nofile 65536 and appuser hard nofile 65536. (2) System-wide: /etc/sysctl.conf add fs.file-max = 2097152, run sysctl -p. (3) systemd services: In the .service unit file, add LimitNOFILE=65536 under [Service]. This overrides limits.conf for service processes. (4) For Docker containers: use --ulimit nofile=65536:65536. Verify after fix: cat /proc/[pid]/limits | grep "open files". The default 1024 limit is ancient and inappropriate for modern applications.',
    tags: [\'linux\', \'ulimit\', \'file-descriptors\', \'troubleshooting\', \'performance\'],
  },
  {
    topicSlug: \'linux-shell\',
    difficulty: \'HARD\' as const,
    type: \'SCENARIO\' as const,
    question: \'You need to analyze a performance issue on a production server with restricted tooling (no perf, no strace, no htop). Only basic tools available. The server shows high load. What is your systematic investigation approach using only /proc, ps, vmstat, and netstat?',
    options: [
      \'Check /proc/loadavg for load breakdown, vmstat 1 for CPU/IO/memory trends, ps aux --sort=-%cpu for process ranking, netstat -an | grep ESTABLISHED for connection states, /proc/[pid]/status for individual process details\',
      \'Without proper tools, you cannot diagnose performance issues — escalate immediately and request rebooting the server\',
      \'Check /var/log/messages only — all performance issues are logged there automatically\',
      \'Run df -h to check disk, ping to check network latency — these two checks cover 95% of all performance issues\',
    ],
    correctIndex: 0,
    explanation: \'This tests depth of knowledge with fundamental Unix tools. Systematic approach: (1) /proc/loadavg — format: "1min 5min 15min running/total_threads last_pid". High load with declining trend (15min > 5min > 1min) means problem is resolving. Opposite means worsening. (2) vmstat 1 5 — columns: r (runnable), b (blocked on I/O), swpd (swap used), us/sy/id/wa (CPU breakdown), bi/bo (block I/O). High wa = I/O bound. High sy = kernel overhead. High r with low id = CPU bound. (3) ps aux --sort=-%mem or --sort=-%cpu — sort by resource usage. Check STAT column: D = uninterruptible sleep (I/O wait), Z = zombie, R = running, S = sleeping. (4) /proc/meminfo — MemAvailable, SwapUsed, Dirty, Writeback tell the memory story. (5) /proc/net/tcp — socket states in hex. (6) /proc/[pid]/fd/ — count open FDs. (7) netstat -s — TCP retransmit counters indicate network issues. This disciplined approach works even on severely restricted systems and shows deep Linux knowledge.',
    tags: [\'linux\', \'performance\', \'proc\', \'vmstat\', \'troubleshooting`, \'investigation\'],
  },
];
