export const networkingQuestions = [
  // ─── EASY THEORY ───────────────────────────────────────────────────────────
  {
    topicSlug: 'networking',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What are the 7 layers of the OSI model and what does each layer do?',
    options: [
      'Physical, Data Link, Network, Transport, Session, Presentation, Application — each layer provides services to the layer above it',
      'Application, Presentation, Session, Transport, Network, Data Link, Physical — read top to bottom for data flow',
      'Hardware, Driver, Protocol, Socket, Service, API, User — a Linux-specific networking stack',
      'Layer 1-4 are network layers; Layer 5-7 are application layers with no meaningful distinction between them',
    ],
    correctIndex: 0,
    explanation: 'The OSI model is a conceptual framework for understanding network communication. Layer 1 (Physical) — bits on the wire: cables, switches, electrical/optical signals, Wi-Fi radio. Layer 2 (Data Link) — frames between adjacent nodes: MAC addresses, Ethernet, switches, VLANs, ARP. Layer 3 (Network) — packets between networks: IP addresses, routing, IPv4/IPv6, ICMP. Layer 4 (Transport) — end-to-end communication: TCP (reliable, connection-oriented), UDP (unreliable, connectionless), ports. Layer 5 (Session) — managing sessions: session establishment, maintenance, termination (rarely referenced in practice). Layer 6 (Presentation) — data format: encryption (TLS), encoding (ASCII/UTF-8), compression. Layer 7 (Application) — user-facing protocols: HTTP, DNS, SMTP, SSH, FTP. DevOps relevance: Load balancers work at L4 (TCP) or L7 (HTTP). Firewalls operate at L3/L4. Service meshes operate at L7. WAFs operate at L7. The mnemonic: "Please Do Not Throw Sausage Pizza Away" (Physical, Data Link, Network, Transport, Session, Presentation, Application).',
    tags: ['networking', 'osi', 'fundamentals', 'protocols'],
  },
  {
    topicSlug: 'networking',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What is the difference between TCP and UDP? When would you choose each in a DevOps/cloud context?',
    options: [
      'TCP is connection-oriented with guaranteed delivery and ordering (HTTP, SSH, databases). UDP is connectionless, lower latency, no guarantees (DNS queries, monitoring metrics, video streaming)',
      'TCP is faster than UDP for all workloads — UDP is only used when TCP is unavailable',
      'UDP provides encryption while TCP does not — use UDP for sensitive data and TCP for public data',
      'There is no functional difference — TCP and UDP both guarantee delivery, TCP is just older',
    ],
    correctIndex: 0,
    explanation: 'TCP (Transmission Control Protocol) establishes a connection via the 3-way handshake (SYN → SYN-ACK → ACK), guarantees reliable delivery with acknowledgments and retransmission, maintains packet ordering with sequence numbers, and implements flow control and congestion control. Overhead: ~20 byte header. Use cases: HTTP/HTTPS, SSH, database connections, file transfers — anything where data integrity matters. UDP (User Datagram Protocol) is connectionless — just sends datagrams with no handshake, no acknowledgments, no retransmission, no ordering guarantee. Header: ~8 bytes. Use cases: DNS queries (single request/response, fast), DHCP, monitoring (Prometheus, StatsD — occasional metric loss is acceptable), video/VoIP (retransmission would cause worse artifacts than loss), gaming. QUIC (HTTP/3) is built on UDP with application-layer reliability. In cloud contexts: Security Groups/NACLs distinguish TCP and UDP. Load balancers have TCP and HTTP listeners. Knowing this distinction is tested in every cloud/networking interview.',
    tags: ['networking', 'tcp', 'udp', 'protocols', 'fundamentals'],
  },
  {
    topicSlug: 'networking',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'How does DNS resolution work when you type "www.google.com" into your browser?',
    options: [
      'Browser cache → OS cache → /etc/hosts → Recursive resolver → Root nameserver → TLD nameserver (.com) → Authoritative nameserver → IP returned',
      `Browser directly queries Google's DNS server, then connects to the IP address`,
      'OS sends the hostname to a DHCP server which returns the IP address',
      'Browser uses ARP to broadcast the hostname and the server responds with its IP address',
    ],
    correctIndex: 0,
    explanation: 'DNS resolution is a hierarchical lookup process: (1) Browser DNS cache — checked first (chrome://net-internals/#dns). (2) OS DNS cache — checked next (nscd, systemd-resolved). (3) /etc/hosts — local overrides. (4) Recursive Resolver — your ISP or configured DNS server (8.8.8.8, 1.1.1.1). This resolver does the heavy lifting. If it has a cached answer, it returns immediately. (5) Root Nameservers — there are 13 root server clusters worldwide (a.root-servers.net through m.root-servers.net). The recursive resolver asks: "who handles .com?" (6) TLD Nameserver — the .com registry (Verisign) responds: "google.com is managed by ns1.google.com" (the authoritative nameserver). (7) Authoritative Nameserver — the actual DNS server for google.com returns the A record (IPv4) or AAAA record (IPv6) for www. Each step has a TTL (Time To Live) — the duration the answer can be cached. Low TTL = faster propagation but more DNS load. High TTL = faster resolution but slower changes. dig +trace www.google.com shows every step of this process.',
    tags: ['networking', 'dns', 'fundamentals', 'resolution'],
  },
  {
    topicSlug: 'networking',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What is the difference between HTTP and HTTPS, and what does an SSL/TLS certificate actually do?',
    options: [
      'HTTP is plaintext; HTTPS encrypts traffic with TLS. A certificate binds a public key to a domain name, enabling encryption and verifying server identity',
      'HTTPS is faster than HTTP because it uses compression by default',
      'An SSL certificate is a firewall rule that blocks non-encrypted traffic',
      'HTTPS is only required for login pages — other pages are safe with HTTP',
    ],
    correctIndex: 0,
    explanation: `HTTP (HyperText Transfer Protocol) transmits data in plaintext — anyone on the network path (ISP, coffee shop Wi-Fi, man-in-the-middle) can read credentials, session tokens, and personal data. HTTPS = HTTP over TLS (Transport Layer Security). TLS provides: (1) Encryption — data is encrypted in transit using symmetric encryption (AES) negotiated via asymmetric cryptography (RSA/ECDHE). (2) Authentication — the server's TLS certificate proves it really is the server you intended to reach, preventing impersonation. (3) Integrity — HMAC ensures data isn't tampered with in transit. An SSL/TLS certificate contains: the domain name (Common Name / Subject Alternative Names), the server's public key, certificate validity period, the Certificate Authority (CA) signature. When your browser connects, it verifies the certificate was signed by a trusted CA (DigiCert, Let's Encrypt, etc.) and matches the domain. DevOps context: Let's Encrypt provides free automated certificates. cert-manager in Kubernetes automates TLS. ACM (AWS Certificate Manager) handles certs for AWS services. HTTPS is now mandatory — browsers warn on HTTP.`,
    tags: ['networking', 'http', 'https', 'tls', 'ssl', 'security'],
  },
  {
    topicSlug: 'networking',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What are well-known port numbers for SSH, HTTP, HTTPS, DNS, and PostgreSQL?',
    options: [
      'SSH: 22, HTTP: 80, HTTPS: 443, DNS: 53, PostgreSQL: 5432',
      'SSH: 21, HTTP: 8080, HTTPS: 8443, DNS: 53, PostgreSQL: 3306',
      'SSH: 22, HTTP: 80, HTTPS: 8443, DNS: 123, PostgreSQL: 5432',
      'SSH: 2222, HTTP: 80, HTTPS: 443, DNS: 53, PostgreSQL: 5433',
    ],
    correctIndex: 0,
    explanation: 'Port numbers are fundamental networking knowledge every DevOps engineer must know: SSH 22 — Secure Shell for remote access and SFTP. HTTP 80 — unencrypted web traffic. HTTPS 443 — encrypted web traffic (TLS). DNS 53 — domain name resolution (both UDP and TCP; TCP for zone transfers and large responses). PostgreSQL 5432 — default database port. Additional important ports: FTP 21 (control), 20 (data). MySQL/MariaDB 3306. Redis 6379. MongoDB 27017. Elasticsearch 9200 (HTTP), 9300 (transport). Kafka 9092. RabbitMQ 5672, 15672 (management). Prometheus 9090. Grafana 3000. Kubernetes API 6443. etcd 2379/2380. Docker registry 5000. Understanding ports is critical for security group rules, firewall configuration, network policies in Kubernetes (NetworkPolicy), and troubleshooting connectivity. Test port connectivity: nc -zv hostname port or telnet hostname port or nmap -p port hostname.',
    tags: ['networking', 'ports', 'fundamentals', 'protocols'],
  },
  {
    topicSlug: 'networking',
    difficulty: 'EASY' as const,
    type: 'SCENARIO' as const,
    question: 'A developer reports they cannot connect to a service running on port 8080 of a remote server. You can SSH to the server successfully. What are your systematic troubleshooting steps?',
    options: [
      'Verify the service is listening (ss -tlnp | grep 8080), check firewall rules (iptables -L or ufw status), test local connectivity (curl localhost:8080), then test from client network',
      'Immediately restart the service — most connectivity issues resolve with a restart',
      'Check DNS first — the service is probably not resolving to the right IP',
      'Ping the server — if ping works, port 8080 must also work',
    ],
    correctIndex: 0,
    explanation: `Systematic network troubleshooting follows the OSI model bottom-up. Since SSH works, L1/L2/L3 are fine. Focus on L4 and above: Step 1 — Is the service listening? ss -tlnp | grep 8080 (or netstat -tlnp | grep 8080). Look for LISTEN state. 0.0.0.0:8080 = listening on all interfaces (accessible externally). 127.0.0.1:8080 = listening on localhost ONLY (not accessible externally — common mistake!). Step 2 — Test locally on the server: curl -v localhost:8080. If this fails, the service itself is the problem. Step 3 — Check firewall: iptables -L -n (iptables), ufw status (Ubuntu UFW), firewall-cmd --list-all (firewalld/CentOS). Is there a REJECT or DROP rule for port 8080? Step 4 — If cloud server: Check security group rules in AWS/GCP/Azure console. Inbound rule for port 8080 must allow the client IP. Step 5 — Test from client: nc -zv server_ip 8080 or telnet server_ip 8080. If ss shows LISTEN and firewall is open but still can't connect, check if there's a proxy or load balancer in between.`,
    tags: ['networking', 'troubleshooting', 'connectivity', 'firewall', 'ports'],
  },
  {
    topicSlug: 'networking',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What is a CIDR notation and what does "10.0.0.0/24" mean?',
    options: [
      'CIDR specifies an IP range; 10.0.0.0/24 means the network 10.0.0.0 with a 24-bit subnet mask, giving 254 usable host addresses (10.0.0.1 to 10.0.0.254)',
      'CIDR is a DNS record type; 10.0.0.0/24 means the DNS zone for the 10.0.0.0 domain',
      '10.0.0.0/24 means 24 separate networks in the 10.0.0.0 range',
      'The /24 in CIDR notation means the network can only have 24 devices connected simultaneously',
    ],
    correctIndex: 0,
    explanation: 'CIDR (Classless Inter-Domain Routing) notation compactly represents IP address ranges. Format: IP_address/prefix_length. The prefix length (/24) indicates how many bits of the address are the network portion. 10.0.0.0/24: Network bits: first 24 bits = 10.0.0 (fixed). Host bits: last 8 bits = 0-255 (variable). Total addresses: 2^8 = 256. Usable hosts: 256 - 2 = 254 (subtract network address 10.0.0.0 and broadcast 10.0.0.255). Common CIDR blocks in DevOps: /32 = single IP (e.g., security group rule for your IP). /24 = 256 addresses, standard subnet. /16 = 65,536 addresses (common VPC size: 10.0.0.0/16). /8 = 16,777,216 addresses. AWS VPC design: typically use 10.0.0.0/16 for the VPC, then carve out /24 subnets per AZ. Kubernetes pod CIDR: typically 10.244.0.0/16. Calculate subnets: ipcalc 10.0.0.0/24 or use online tools. Understanding CIDR is essential for VPC design, security groups, Kubernetes networking, and firewall rules.',
    tags: ['networking', 'cidr', 'subnets', 'ip-addressing', 'vpc'],
  },

  // ─── MEDIUM THEORY ─────────────────────────────────────────────────────────
  {
    topicSlug: 'networking',
    difficulty: 'MEDIUM' as const,
    type: 'THEORY' as const,
    question: 'Compare the load balancing algorithms: Round Robin, Least Connections, IP Hash, and Weighted Round Robin. When would you use each?',
    options: [
      'Round Robin: equal distribution for stateless apps; Least Connections: dynamic load for varied request durations; IP Hash: session affinity by client IP; Weighted Round Robin: proportional distribution for heterogeneous backends',
      'Round Robin is always the best algorithm — the others exist only for legacy compatibility',
      'IP Hash is required for all HTTPS traffic; the other algorithms only work with HTTP',
      'Least Connections works only with TCP load balancers; Round Robin only with HTTP',
    ],
    correctIndex: 0,
    explanation: 'Load balancing algorithms determine how requests are distributed: Round Robin — each backend receives requests in rotation (1→2→3→1→2→3). Simple, zero state. Best for: stateless applications where all backends are identical in capacity and request processing time. Limitation: if one request takes 10x longer, that backend gets overloaded. Least Connections — new requests go to the backend with the fewest active connections. Best for: applications with variable request duration (e.g., WebSockets, long-polling, mixed workloads). More complex — requires tracking connection state. IP Hash — client IP is hashed to determine backend. The same client always goes to the same server. Best for: session-based applications where session state is local to the server (though stateless design is preferred). Warning: uneven distribution if clients share a NAT IP. Weighted Round Robin — backends get requests proportional to their weight (e.g., 8-core server gets 4x traffic of a 2-core server). Best for: heterogeneous fleet with different capacity servers. In AWS: ALB uses round-robin by default, with least-outstanding-requests option. NLB uses flow hash. In Kubernetes, services default to round-robin via kube-proxy iptables rules.',
    tags: ['networking', 'load-balancing', 'algorithms', 'infrastructure'],
  },
  {
    topicSlug: 'networking',
    difficulty: 'MEDIUM' as const,
    type: 'THEORY' as const,
    question: 'What happens during a TLS 1.3 handshake and why is it faster than TLS 1.2?',
    options: [
      'TLS 1.3 completes in 1 RTT (vs 2 RTT for TLS 1.2) by combining key exchange and cipher negotiation. It supports 0-RTT session resumption. It removed weak cipher suites (RSA key exchange, RC4, 3DES)',
      'TLS 1.3 is faster because it eliminates all encryption, relying instead on certificate authentication only',
      'TLS 1.3 uses UDP instead of TCP, reducing handshake overhead',
      'TLS 1.3 and TLS 1.2 have identical handshake speeds — 1.3 only improves cipher strength',
    ],
    correctIndex: 0,
    explanation: `TLS 1.2 handshake (2 RTTs): Client→Server: ClientHello (supported ciphers, TLS version). Server→Client: ServerHello (chosen cipher), Certificate, ServerHelloDone. Client→Server: ClientKeyExchange (encrypts pre-master secret with server's public key). Server→Client: Finished. Only after this can data flow. TLS 1.3 handshake (1 RTT): Client→Server: ClientHello WITH key_share (the client sends its Diffie-Hellman public key immediately). Server→Client: ServerHello, encrypted Certificate, encrypted Finished — ALL in one response. Data can flow immediately after. Key improvements: (1) Forward Secrecy mandatory — DHE/ECDHE key exchange means past sessions can't be decrypted even if the private key is later compromised. (2) Removed deprecated algorithms: RSA key exchange, DH < 1024 bits, RC4, 3DES, MD5, SHA-1. (3) 0-RTT resumption for returning clients (though has replay attack considerations). Performance impact: for microservices making thousands of connections per second, the RTT reduction is significant. Configure in nginx: ssl_protocols TLSv1.2 TLSv1.3; Always test with: openssl s_client -connect host:443 -tls1_3.`,
    tags: ['networking', 'tls', 'ssl', 'security', 'performance', 'https'],
  },
  {
    topicSlug: 'networking',
    difficulty: 'MEDIUM' as const,
    type: 'THEORY' as const,
    question: 'What is iptables and what are the differences between the PREROUTING, INPUT, FORWARD, OUTPUT, and POSTROUTING chains?',
    options: [
      'iptables is the Linux kernel firewall. PREROUTING handles incoming packets before routing; INPUT handles packets destined for the host; FORWARD handles routed packets; OUTPUT handles locally-generated packets; POSTROUTING handles packets after routing',
      'iptables is a userspace firewall that works independently of the kernel, similar to Windows Firewall',
      'All five chains are identical — the names are just labels for organization',
      'PREROUTING and POSTROUTING are for NAT only; INPUT and OUTPUT handle all filtering',
    ],
    correctIndex: 0,
    explanation: `iptables is a userspace utility that configures the Linux kernel's Netfilter framework. Packet flow through chains: PREROUTING — first chain hit by incoming packets (before routing decision). Used for DNAT (redirect incoming traffic to different IP/port). Example: port forwarding 80→8080. Routing Decision — kernel decides: is this packet for me (→INPUT) or should I forward it (→FORWARD)? INPUT — packets destined for the local machine. This is where you accept/reject SSH, HTTP, etc. FORWARD — packets passing THROUGH the machine (the host is acting as a router). Used in container networking and VPNs. OUTPUT — packets generated by local processes leaving the machine. POSTROUTING — after routing, before sending. Used for SNAT/MASQUERADE (hide container IPs behind host IP). Tables: filter (default: INPUT/FORWARD/OUTPUT rules), nat (PREROUTING/POSTROUTING for address translation), mangle (packet modification). Modern replacement: nftables (same concept, better syntax). In Docker/Kubernetes: rules are automatically added to DOCKER-USER and KUBE-* chains. iptables-save shows all rules; iptables-restore loads them.`,
    tags: ['networking', 'iptables', 'firewall', 'linux', 'nat', 'security'],
  },
  {
    topicSlug: 'networking',
    difficulty: 'MEDIUM' as const,
    type: 'SCENARIO' as const,
    question: 'Your monitoring shows intermittent 5-second spikes in API response times. The application, database, and load balancer all report normal. You suspect a DNS issue. How do you confirm and fix it?',
    options: [
      'Use dig/nslookup to measure DNS resolution time, check local resolver config (/etc/resolv.conf), verify TTL values, and consider switching to a local DNS cache (dnsmasq) or using IP addresses directly',
      'DNS issues always cause 100% failure, not intermittent spikes — rule out DNS and focus on application profiling',
      'Increase the HTTP timeout to 30 seconds to absorb DNS delays',
      'DNS resolution is cached indefinitely in Linux — no DNS issues are possible after the first request',
    ],
    correctIndex: 0,
    explanation: `DNS resolution spikes are a real and common source of latency issues in microservices. Diagnosis: (1) time dig service-name measures DNS resolution time. If you see 5+ second results intermittently, DNS is the culprit. (2) cat /etc/resolv.conf — check nameserver IPs and options. Default: 5-second timeout with 2 retries = 15-second worst case. (3) Check ndots setting — options ndots:5 (Kubernetes default) means names with fewer than 5 dots get multiple search domain appended queries, multiplying DNS traffic. (4) tcpdump -i any port 53 — capture DNS traffic to see failed queries. Solutions: (1) Local DNS cache — run dnsmasq or nscd locally. Kubernetes pods should use node-local-dns daemonset. (2) Reduce ndots in Kubernetes: dnsConfig.options [{name: "ndots", value: "1"}]. (3) Use fully-qualified domain names (trailing dot): svc.namespace.svc.cluster.local. (4) Configure resolv.conf timeout/attempts: options timeout:2 attempts:1. (5) AWS: use Amazon Route 53 Resolver (169.254.169.253) — it's local per AZ. A 5-second spike matching DNS timeout is a classic pattern that trips up engineers who don't think to check DNS.`,
    tags: ['networking', 'dns', 'troubleshooting', 'performance', 'latency'],
  },
  {
    topicSlug: 'networking',
    difficulty: 'MEDIUM' as const,
    type: 'THEORY' as const,
    question: 'What is BGP (Border Gateway Protocol) and why is it relevant to cloud engineers managing multi-region infrastructure?',
    options: [
      'BGP is the routing protocol that runs the internet — it exchanges reachability information between autonomous systems. Cloud engineers encounter it with Direct Connect, Transit Gateway, and anycast routing',
      'BGP is a load balancing protocol used only inside private data centers, not relevant to cloud environments',
      'BGP is a deprecated protocol replaced by OSPF in all modern cloud networks',
      'BGP is only relevant to ISPs — cloud engineers never need to configure or understand BGP',
    ],
    correctIndex: 0,
    explanation: `BGP (Border Gateway Protocol, RFC 4271) is THE routing protocol of the internet — it's how autonomous systems (ASes) exchange routing information. Every ISP, cloud provider, and large enterprise has an AS number (ASN). BGP relevance for cloud engineers: (1) AWS Direct Connect — when you connect your data center to AWS via dedicated fiber, you run BGP to exchange routes between your on-premises ASN and AWS's ASN. You advertise your IP ranges to AWS and AWS advertises VPC CIDRs to you. (2) AWS Transit Gateway — connect multiple VPCs and on-premises networks. BGP is used for dynamic route propagation. (3) VPN connections — both AWS Site-to-Site VPN and Direct Connect use BGP for dynamic routing (alternative: static routes). (4) Anycast — multiple servers worldwide share the same IP address, and BGP routing directs users to the nearest one. CloudFront, Route 53, and DDoS protection services use anycast. (5) eBGP vs iBGP — external BGP (between different ASes) vs internal BGP (within the same AS). Key BGP attributes affecting path selection: AS_PATH, LOCAL_PREF, MED, NEXT_HOP.`,
    tags: ['networking', 'bgp', 'routing', 'cloud', 'aws', 'direct-connect'],
  },
  {
    topicSlug: 'networking',
    difficulty: 'MEDIUM' as const,
    type: 'THEORY' as const,
    question: 'What is the difference between a VPN (IPsec/OpenVPN) and a Direct Connect or Dedicated Interconnect link to a cloud provider?',
    options: [
      'VPN runs over the public internet with encryption (lower cost, variable latency). Direct Connect is a dedicated physical connection bypassing the internet (consistent latency, higher bandwidth, higher cost)',
      'VPN and Direct Connect are identical technologies — Direct Connect just adds extra encryption layers',
      'Direct Connect is a software-defined virtual connection; VPN requires physical hardware at both ends',
      'VPN is more secure than Direct Connect because it adds a second encryption layer on the dedicated link',
    ],
    correctIndex: 0,
    explanation: `This is a critical architecture decision in enterprise cloud adoption: Site-to-Site VPN (AWS or equivalent): Travels over the public internet. Uses IPsec encryption. Setup: minutes. Cost: ~$36/month per connection + data transfer. Bandwidth: typically up to 1.25 Gbps. Latency: variable (internet path). High availability: dual tunnels per connection. Best for: smaller workloads, backup connectivity, dev/test environments. AWS Direct Connect (Azure ExpressRoute / GCP Dedicated Interconnect): Dedicated physical fiber between your data center and the cloud provider's edge. Does NOT traverse the public internet — private, consistent path. Setup: weeks to months (physical provisioning). Cost: port fee ($220-$5000/month) + data transfer (cheaper per GB). Bandwidth: 1 Gbps to 100 Gbps ports. Latency: consistent, low (predictable SLA). Security: traffic is private but NOT encrypted by default — often add VPN over Direct Connect for defense in depth. Best for: high-bandwidth workloads (petabyte migrations), latency-sensitive applications, regulatory compliance requiring private connectivity. Architecture: many enterprises use Direct Connect as primary + VPN as failover.`,
    tags: ['networking', 'vpn', 'direct-connect', 'aws', 'hybrid-cloud', 'connectivity'],
  },

  // ─── HARD ──────────────────────────────────────────────────────────────────
  {
    topicSlug: 'networking',
    difficulty: 'HARD' as const,
    type: 'THEORY' as const,
    question: 'Explain TCP connection states and why TIME_WAIT accumulation is problematic at scale. How do you diagnose and resolve it?',
    options: [
      'TIME_WAIT holds closed connections for 2*MSL (typically 60s) to prevent delayed packets from corrupting new connections. High accumulation exhausts ephemeral ports. Fix: net.ipv4.tcp_tw_reuse=1, increase port range, or use connection pooling',
      'TIME_WAIT is a kernel bug — patch the kernel to version 5.15+ to eliminate it',
      'TIME_WAIT sockets use no system resources — they can accumulate indefinitely without impact',
      'TIME_WAIT only occurs on servers, never on clients making HTTP requests',
    ],
    correctIndex: 0,
    explanation: 'TCP connection lifecycle and TIME_WAIT: after the 4-way FIN handshake, the side that initiated the close enters TIME_WAIT for 2*MSL (Maximum Segment Lifetime, typically 60 seconds total on Linux). Why it exists: ensures the final ACK was received. Prevents delayed duplicate segments from a previous connection from being misinterpreted by a new connection using the same 4-tuple (src IP, src port, dst IP, dst port). The problem at scale: Each TIME_WAIT socket consumes a (src port, dst IP, dst port) 3-tuple. A service making many short-lived HTTP requests to the same upstream can exhaust the ephemeral port range (typically 32,768-60,999 = ~28,000 ports). Symptom: "Cannot assign requested address" connection errors. Diagnosis: ss -s shows TIME_WAIT count. ss -ant | grep TIME_WAIT | wc -l. /proc/sys/net/ipv4/tcp_tw_buckets shows current count. Solutions: (1) net.ipv4.tcp_tw_reuse=1 — allows reusing TIME_WAIT sockets for new connections to the same endpoint (safe with timestamps). (2) Increase port range: net.ipv4.ip_local_port_range="1024 65535". (3) Connection pooling/keep-alive — fewer connections = fewer TIME_WAITs. (4) net.ipv4.tcp_fin_timeout=30 — reduces TIME_WAIT duration. DO NOT use tcp_tw_recycle — removed in Linux 4.12 due to bugs behind NAT.',
    tags: ['networking', 'tcp', 'time-wait', 'performance', 'troubleshooting', 'scaling'],
  },
  {
    topicSlug: 'networking',
    difficulty: 'HARD' as const,
    type: 'THEORY' as const,
    question: 'What is MTU and MSS, and how can MTU misconfiguration cause mysterious packet loss that only affects large transfers?',
    options: [
      'MTU (Max Transmission Unit) is the largest frame a link can carry (Ethernet default 1500 bytes). MSS (Max Segment Size) is the largest TCP payload. PMTUD blackholes occur when intermediate routers drop oversized packets without sending ICMP "fragmentation needed" messages',
      'MTU and MSS are the same concept — MTU is the Linux term, MSS is the Windows term for the same limit',
      'MTU issues only affect UDP traffic — TCP handles fragmentation automatically with no configuration needed',
      'MTU of 9000 (jumbo frames) is always better than 1500 and should be configured on all modern networks',
    ],
    correctIndex: 0,
    explanation: 'MTU/MSS is a tricky networking concept that causes real production incidents: MTU (Maximum Transmission Unit) — largest payload a network link can carry. Ethernet standard: 1500 bytes. With 802.1Q VLAN tag: 1496 bytes. Jumbo frames: 9000 bytes (requires end-to-end support). MSS (Maximum Segment Size) — largest TCP segment DATA payload (excludes IP header 20B + TCP header 20B): MSS = MTU - 40 = 1460 bytes for standard Ethernet. TCP negotiates MSS during handshake via SYN packet. PMTUD (Path MTU Discovery) problem: If an intermediate link has a smaller MTU (e.g., VPN tunnel: 1500-50bytes overhead = 1450), routers should send ICMP "Type 3, Code 4 - Fragmentation Needed" back to the sender. If those ICMP packets are blocked by a firewall (ICMP black hole), PMTUD breaks. Symptoms: Small requests/responses (SSH keystrokes, HTTP headers) work fine. Large file transfers hang or fail mysteriously. HTTPS works for small pages but hangs on large downloads. Diagnosis: ping -M do -s 1472 remote_host (DF bit set, 1472+28 headers = 1500). Decrease size until it works. Fix: set MSS clamping on VPN/tunnel interfaces: ip tcp_metrics, or iptables -t mangle -A FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu.',
    tags: ['networking', 'mtu', 'mss', 'pmtud', 'troubleshooting', 'tcp'],
  },
  {
    topicSlug: 'networking',
    difficulty: 'HARD' as const,
    type: 'SCENARIO' as const,
    question: 'Your company runs a global API service. Users in Asia-Pacific report 300ms higher latency than users in the US. The application is only deployed in us-east-1. What is the architectural solution and how does anycast help?',
    options: [
      'Deploy multi-region with CloudFront or similar CDN for static content; deploy application replicas in ap-southeast-1 and ap-northeast-1; use Route 53 latency-based routing or anycast to direct users to nearest region',
      'Increase server CPU and memory in us-east-1 — latency is always caused by server processing time',
      'Switch from HTTPS to HTTP to eliminate TLS handshake overhead for APAC users',
      'Add more EC2 instances behind the load balancer in us-east-1 — more servers means lower latency for all regions',
    ],
    correctIndex: 0,
    explanation: `This is a fundamental distributed systems architecture problem. Physics imposes a speed-of-light limit: light travels ~200km/ms in fiber (with refraction). US-East to Singapore: ~16,000 km = ~80ms one-way, ~160ms round-trip minimum. The 300ms gap suggests additional routing hops and TCP handshakes on top of propagation delay. Solutions: (1) Multi-region deployment: Deploy application in ap-southeast-1 (Singapore) and ap-northeast-1 (Tokyo). Use RDS read replicas or DynamoDB global tables for data locality. (2) Route 53 Latency-Based Routing: Route each user to the AWS region with lowest measured latency from their location. (3) CloudFront for static/cacheable content: 400+ PoPs worldwide. TLS termination at the nearest edge eliminates the 3-RTT TLS handshake penalty across the ocean. (4) Anycast: Multiple servers worldwide share the same IP. BGP routing automatically directs each user's packets to the topologically nearest server. AWS Global Accelerator uses anycast with AWS backbone routing instead of public internet. (5) TCP connection optimization: CloudFront keeps persistent connections to origins, pooling the long-haul latency. Result: APAC users connect to Singapore PoP (10ms), Singapore PoP fetches from origin over AWS backbone. Latency reduces from 300ms to ~15ms for cached content.`,
    tags: ['networking', 'latency', 'anycast', 'cdn', 'multi-region', 'global-architecture'],
  },
  {
    topicSlug: 'networking',
    difficulty: 'HARD' as const,
    type: 'THEORY' as const,
    question: 'Explain what happens at the packet level during a TCP three-way handshake, and how a SYN flood DDoS attack exploits this mechanism.',
    options: [
      'Handshake: Client SYN → Server SYN-ACK (allocates half-open connection) → Client ACK. SYN flood: attacker sends millions of SYN packets with spoofed IPs, filling the backlog queue with half-open connections that never complete, exhausting server resources',
      'SYN flood works by sending valid complete handshakes faster than the server can process — the solution is to add more servers',
      'The three-way handshake is immune to attack because TCP validates sequence numbers, preventing any spoofing',
      'SYN flood attacks are blocked automatically by all modern operating systems without any configuration',
    ],
    correctIndex: 0,
    explanation: `The TCP three-way handshake creates a vulnerability: (1) Client→Server: SYN (synchronize) — contains client's Initial Sequence Number (ISN), client capabilities. (2) Server→Client: SYN-ACK — server allocates a Transmission Control Block (TCB) in the SYN backlog (half-open connections table), responds with server ISN + client ISN+1. (3) Client→Server: ACK — connection moves from SYN backlog to accept queue, becomes ESTABLISHED. SYN flood attack: Attacker sends millions of SYN packets per second with spoofed source IPs. Server responds to each with SYN-ACK but never receives ACK (spoofed IP). Server holds half-open TCBs in memory (net.ipv4.tcp_max_syn_backlog entries) until they time out (tcp_synack_retries × timeout). When backlog fills, new legitimate connections are dropped. Defenses: (1) SYN Cookies (net.ipv4.tcp_syncookies=1) — server encodes connection state in the sequence number, doesn't allocate TCB until ACK received. This is the primary defense. (2) Rate limiting: iptables -A INPUT -p tcp --syn -m limit --limit 10/s -j ACCEPT. (3) Increase backlog: net.ipv4.tcp_max_syn_backlog=65536. (4) AWS Shield/CloudFlare absorb at the network edge. (5) Reduce tcp_synack_retries from default 5 to 2.`,
    tags: ['networking', 'tcp', 'security', 'ddos', 'syn-flood', 'kernel'],
  },
  {
    topicSlug: 'networking',
    difficulty: 'MEDIUM' as const,
    type: 'SCENARIO' as const,
    question: 'You are setting up a new AWS VPC for a production application. You need public subnets (for load balancers), private subnets (for application servers), and isolated subnets (for databases). What is the correct network architecture?',
    options: [
      'VPC with /16 CIDR; public subnets with Internet Gateway and route 0.0.0.0/0→IGW; private subnets with NAT Gateway for outbound-only internet; isolated subnets with no internet route; security groups restrict traffic between tiers',
      'Use a single subnet for all resources — security groups alone provide sufficient isolation in AWS',
      'Public subnets for everything — use network ACLs to restrict database access instead of multiple subnet tiers',
      'Each subnet needs its own Internet Gateway — one IGW per subnet is the AWS best practice',
    ],
    correctIndex: 0,
    explanation: 'This is the standard three-tier VPC architecture, a must-know for any cloud engineer. Architecture breakdown: VPC: 10.0.0.0/16 (65,536 IPs — room to grow). Public Subnets (one per AZ): e.g., 10.0.1.0/24, 10.0.2.0/24, 10.0.3.0/24. Attached to route table with route: 0.0.0.0/0 → Internet Gateway (IGW). Hosts: Application Load Balancer, NAT Gateway, bastion hosts. Instances need public IPs or Elastic IPs. Private Subnets (one per AZ): e.g., 10.0.11.0/24, 10.0.12.0/24, 10.0.13.0/24. Route: 0.0.0.0/0 → NAT Gateway (in public subnet). Hosts: EC2 application servers, EKS nodes. Can reach internet for updates, but not directly reachable from internet. Isolated Subnets (one per AZ): e.g., 10.0.21.0/24, 10.0.22.0/24, 10.0.23.0/24. No internet route (no 0.0.0.0/0 entry). Only accessible from private subnets via security groups. Hosts: RDS, ElastiCache, Redshift. Security Groups: ALB SG accepts 80/443 from 0.0.0.0/0. App SG accepts traffic from ALB SG only. DB SG accepts 5432 from App SG only. This defense-in-depth model ensures database servers are never directly reachable from the internet, even if security groups are misconfigured.',
    tags: ['networking', 'vpc', 'aws', 'subnets', 'architecture', 'security'],
  },
  {
    topicSlug: 'networking',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What does the traceroute command do and how do you interpret its output?',
    options: [
      'traceroute shows each hop (router) a packet traverses to reach a destination, using ICMP/UDP with incrementing TTL values. Each line shows hop number, IP, and round-trip time',
      'traceroute measures the bandwidth available between your machine and the destination server',
      'traceroute shows all established TCP connections from your machine to a destination',
      'traceroute tests if a specific port is open on a destination server, similar to telnet',
    ],
    correctIndex: 0,
    explanation: `traceroute works by exploiting TTL (Time To Live) in IP packets. TTL is decremented by 1 at each router. When TTL reaches 0, the router sends back an ICMP "Time Exceeded" message — which reveals its IP address. traceroute sends probes with TTL=1, 2, 3, ... incrementing until the destination is reached. Each row shows: hop number, three RTT measurements (ms), and IP/hostname of that router. Reading output: * * * means that router doesn't respond to probes (firewall drops TTL exceeded ICMP). High RTT at a specific hop indicates a slow link. RTT that stays constant after a certain hop means the latency was introduced at that point. Asymmetric routes are common — return path may differ. DevOps use cases: Diagnose routing issues (traffic going wrong path). Identify slow network hops. Verify Direct Connect / VPN routing. traceroute6 for IPv6. mtr (Matt's Traceroute) combines ping + traceroute continuously, better for intermittent issues. In AWS: You can't traceroute through the AWS backbone from EC2 by default (ICMP is filtered), but you can use VPC Reachability Analyzer for logical path analysis.`,
    tags: ['networking', 'traceroute', 'troubleshooting', 'routing', 'diagnostics'],
  },
  {
    topicSlug: 'networking',
    difficulty: 'MEDIUM' as const,
    type: 'THEORY' as const,
    question: 'What is the difference between a Layer 4 (TCP) load balancer and a Layer 7 (HTTP) load balancer? When would you use each?',
    options: [
      'L4 LB routes based on IP/port with lower latency and no HTTP awareness. L7 LB inspects HTTP headers/URL for advanced routing, SSL termination, and health checks — but adds processing overhead',
      'L4 LB supports HTTPS; L7 LB only supports HTTP. Use L4 for all production traffic',
      'L7 LB is always faster than L4 because it maintains fewer connections',
      'L4 and L7 refer to OSI layers but perform identical functions in practice',
    ],
    correctIndex: 0,
    explanation: 'Layer 4 Load Balancers (e.g., AWS NLB, HAProxy TCP mode): Route based on IP address and TCP/UDP port only. Do NOT inspect application-level content. Ultra-low latency (no payload parsing). Supports any TCP/UDP protocol (databases, SMTP, MQTT, game servers). Static IP support. Preserves client IP (important for logging). TLS passthrough (backend handles TLS). Use cases: Non-HTTP protocols, extremely low latency requirements, when clients need static IPs, preserving source IP. Layer 7 Load Balancers (e.g., AWS ALB, nginx, Traefik): Terminates TCP connection, inspects HTTP. Content-based routing: route /api/* to one target group, /static/* to another. Host-based routing: api.example.com → backend-api, www.example.com → frontend. Header-based routing: A/B testing by User-Agent or custom headers. SSL/TLS termination (offloads encryption from backends). HTTP health checks (check actual 200 response, not just TCP connect). WebSocket support. HTTP/2 support. Use cases: Web applications, microservices, need URL-based routing, SSL termination, WAF integration. In Kubernetes: Ingress controllers are L7 LBs; Service type:LoadBalancer is typically L4.',
    tags: ['networking', 'load-balancing', 'l4', 'l7', 'alb', 'nlb', 'aws'],
  },

  // ─── ADDITIONAL NETWORKING QUESTIONS ─────────────────────────────────────────
  {
    topicSlug: 'networking',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What is the difference between TCP and UDP?',
    options: [
      'TCP is connection-oriented with guaranteed delivery and ordering; UDP is connectionless with no delivery guarantee but lower latency',
      'TCP and UDP are identical protocols',
      'UDP is more reliable than TCP',
      'TCP is used only for web traffic; UDP is used only for DNS',
    ],
    correctIndex: 0,
    explanation: 'TCP (Transmission Control Protocol): (1) Connection-oriented: three-way handshake before data transfer. (2) Reliable: guarantees delivery, retransmits lost packets. (3) Ordered: packets delivered in sequence. (4) Flow control: adjusts speed based on receiver capacity. (5) Congestion control: adjusts speed based on network conditions. (6) Overhead: headers, acknowledgments, retransmissions. Use cases: HTTP/HTTPS, SSH, FTP, email, database connections. UDP (User Datagram Protocol): (1) Connectionless: no handshake, just send. (2) Unreliable: no delivery guarantee, no retransmission. (3) Unordered: packets may arrive out of order. (4) Low latency: minimal overhead. (5) Simple: 8-byte header vs TCP 20-byte minimum. Use cases: DNS (quick queries), video streaming (latency > reliability), gaming (real-time), VoIP. Both can carry various traffic types (D). UDP is not more reliable (C). They are different (B).',
    tags: ['networking', 'tcp', 'udp', 'protocols', 'fundamentals'],
  },
  {
    topicSlug: 'networking',
    difficulty: 'MEDIUM' as const,
    type: 'THEORY' as const,
    question: 'What is CIDR notation and how do you calculate the number of hosts in a CIDR block?',
    options: [
      'CIDR notation (e.g., /24) indicates network prefix length; hosts = 2^(32-prefix) - 2 for IPv4 (minus network and broadcast addresses)',
      'CIDR notation indicates the number of hosts directly',
      '/24 means 24 hosts are available',
      'CIDR is only used for IPv6 addressing',
    ],
    correctIndex: 0,
    explanation: 'CIDR (Classless Inter-Domain Routing) notation: /prefix indicates how many bits are the network portion. IPv4 has 32 bits total. Formula: Hosts = 2^(32 - prefix) - 2. The -2 accounts for network address (all host bits 0) and broadcast address (all host bits 1). Examples: /32: 2^0 - 2 = -1 (single host, no network/broadcast). /30: 2^2 - 2 = 2 hosts (point-to-point links). /28: 2^4 - 2 = 14 hosts. /24: 2^8 - 2 = 254 hosts (common subnet size). /16: 2^16 - 2 = 65,534 hosts. /8: 2^24 - 2 = 16,777,214 hosts. AWS VPC: supports /16 to /28. AWS subnets reserve 5 IPs (network, VPC router, DNS, future use, broadcast), so a /24 gives 251 usable. Quick mental math: /24 = 256 addresses - 2 = 254 hosts. Each bit down doubles: /23 = 510, /22 = 1022. Each bit up halves: /25 = 126, /26 = 62. CIDR applies to both IPv4 and IPv6 (D).',
    tags: ['networking', 'cidr', 'subnetting', 'ipv4', 'addressing'],
  },
  {
    topicSlug: 'networking',
    difficulty: 'MEDIUM' as const,
    type: 'SCENARIO' as const,
    question: 'Your application is experiencing SSL/TLS certificate errors when connecting to an internal service. How do you troubleshoot this?',
    options: [
      'Use openssl s_client -connect host:port to inspect the certificate chain, check expiration dates, verify CN/SAN matches the hostname, and ensure CA certificates are trusted',
      'Disable SSL verification to fix the error',
      'Certificate errors are always server-side issues',
      'Restart the client application to refresh certificates',
    ],
    correctIndex: 0,
    explanation: 'SSL/TLS troubleshooting with openssl: Command: openssl s_client -connect hostname:443 -servername hostname. What to check: (1) Certificate chain: verify all intermediate certificates are present. (2) Expiration: look for "Not Before" and "Not After" dates. (3) Subject/SAN: CN (Common Name) or SAN (Subject Alternative Names) must match the hostname. (4) Issuer: identify the CA. Is it trusted by your system? (5) Verify return code: 0 = ok, 10 = certificate expired, 18 = self-signed, 19 = self-signed in chain, 21 = unable to verify. Common issues: (1) Expired certificate: renew with Let\'s Encrypt or CA. (2) Missing intermediate: server must send full chain. (3) Wrong hostname: CN/SAN mismatch. (4) Untrusted CA: add CA to trust store (/etc/ssl/certs/). (5) Self-signed: add to trust store or use --cacert flag. Additional tools: curl -v for verbose SSL output, openssl x509 -text to decode certificate. Disabling SSL (B) is insecure. Client issues are possible (C). Restarting rarely helps (D).',
    tags: ['networking', 'ssl', 'tls', 'certificates', 'troubleshooting', 'openssl'],
  },
  {
    topicSlug: 'networking',
    difficulty: 'HARD' as const,
    type: 'THEORY' as const,
    question: 'What is BGP (Border Gateway Protocol) and why is it important for internet routing?',
    options: [
      'BGP is the routing protocol that exchanges routes between autonomous systems, determining how traffic flows across the internet; it uses path attributes to select best routes',
      'BGP is used only within local area networks',
      'BGP is a firewall protocol',
      'BGP has been replaced by OSPF for internet routing',
    ],
    correctIndex: 0,
    explanation: 'BGP (Border Gateway Protocol) is the routing protocol of the internet. Autonomous Systems (AS): networks under a single administrative control (ISPs, enterprises, cloud providers). Each AS has a unique ASN (e.g., AWS is AS16509, Google is AS15169). BGP function: (1) Exchanges routing information between ASes (eBGP). (2) Propagates routes within an AS (iBGP). (3) Determines best path to destinations. Path selection criteria: (1) Shortest AS_PATH (fewest AS hops). (2) Local preference (configured priority). (3) Origin type (IGP > EGP > incomplete). (4) MED (Multi-Exit Discriminator). DevOps relevance: (1) AWS Direct Connect uses BGP to advertise routes between your datacenter and AWS. (2) Multi-region/multi-cloud requires understanding BGP peering. (3) Route leaks and BGP hijacking can cause outages (see Cloudflare, YouTube incidents). (4) anycast (same IP from multiple locations) relies on BGP. BGP is not for LANs (B, use OSPF/EIGRP). BGP is not a firewall (C). BGP is THE internet routing protocol (D).',
    tags: ['networking', 'bgp', 'routing', 'internet', 'autonomous-systems'],
  },
  {
    topicSlug: 'networking',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What is a reverse proxy and how does it differ from a forward proxy?',
    options: [
      'A reverse proxy sits in front of servers, handling client requests on their behalf (load balancing, SSL termination); a forward proxy sits in front of clients, handling their outbound requests',
      'Reverse and forward proxies are identical',
      'Reverse proxies are used for caching only',
      'Forward proxies are always faster than reverse proxies',
    ],
    correctIndex: 0,
    explanation: 'Forward proxy: (1) Sits in front of clients. (2) Client configures browser/system to use the proxy. (3) Use cases: corporate internet access control, content filtering, anonymity (hiding client IP), caching (Squid proxy). (4) Client knows it is using a proxy. Reverse proxy: (1) Sits in front of servers. (2) Clients connect to the proxy, thinking it is the server. (3) Use cases: load balancing (nginx, HAProxy), SSL termination, caching (CDN), security (WAF), compression, routing (microservices). (4) Clients usually do not know there is a proxy. Examples: nginx: reverse proxy for web apps. CloudFlare: reverse proxy CDN. Squid: forward proxy for corporate networks. AWS ALB: reverse proxy load balancer. Key difference: forward proxy protects/serves clients; reverse proxy protects/serves servers. They are different (B). Reverse proxies do more than caching (C). Performance depends on configuration (D).',
    tags: ['networking', 'proxy', 'reverse-proxy', 'load-balancing', 'nginx'],
  },
  {
    topicSlug: 'networking',
    difficulty: 'MEDIUM' as const,
    type: 'SCENARIO' as const,
    question: 'You need to allow your Kubernetes pods to access an external API that only allows specific IP addresses. Your pods run on nodes with dynamic IPs. How do you solve this?',
    options: [
      'Route outbound traffic through a NAT Gateway with a static Elastic IP, and whitelist that EIP with the external API provider',
      'Ask the API provider to allow all AWS IP ranges',
      'Assign public IPs to each pod',
      'External APIs cannot be accessed from Kubernetes',
    ],
    correctIndex: 0,
    explanation: 'IP whitelisting with dynamic infrastructure requires a stable egress IP. Solution: NAT Gateway with Elastic IP. Architecture: (1) Pods in private subnet. (2) NAT Gateway in public subnet with Elastic IP attached. (3) Private subnet route table: 0.0.0.0/0 → NAT Gateway. (4) All outbound traffic appears to come from the NAT Gateway EIP. (5) Whitelist the EIP with the external API. Alternatives: (1) AWS PrivateLink: if the API supports it, no public internet. (2) VPN tunnel: dedicated connection to API provider. (3) Dedicated proxy: run a proxy (Squid) on an EC2 with EIP, route specific traffic through it. Multi-AZ consideration: each AZ needs its own NAT Gateway. Use different EIPs or a transit gateway for a single egress IP. Kubernetes specifics: for finer control, use egress gateways (Istio) or network policies to route specific traffic through a dedicated path. Whitelisting all AWS IPs (B) is insecure and impractical. Pods typically do not have public IPs (C). External access is common (D).',
    tags: ['networking', 'kubernetes', 'nat-gateway', 'egress', 'ip-whitelisting', 'aws'],
  },
];
