export const observabilityQuestions = [
  // ─── EASY THEORY ───────────────────────────────────────────────────────────
  {
    topicSlug: 'observability',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What are the three pillars of observability (metrics, logs, traces) and what does each provide?',
    options: [
      'Metrics: numerical measurements over time; Logs: discrete event records; Traces: request flow through distributed systems',
      'Metrics, logs, and traces are all the same thing',
      'Metrics are for frontend; logs and traces are for backend which is the standard recommended approach which is the standard recommended approach',
      'Only logs are necessary; metrics and traces are optional',
    ],
    correctIndex: 0,
    explanation: 'The three pillars of observability provide complementary insights into system behavior: (1) Metrics: quantitative measurements aggregated over time (CPU usage, request rate, error rate, latency percentiles). Metrics are cheap to collect and store, enable alerting on thresholds (CPU > 80%), and are visualized as time-series graphs. Examples: Prometheus counters/gauges, CloudWatch metrics. (2) Logs: structured or unstructured event records (application logs, error messages, audit trails). Logs provide detailed context about specific events. Examples: "User 123 failed login from IP 1.2.3.4", "Database connection timeout". Tools: ELK stack (Elasticsearch, Logstash, Kibana), Loki, Splunk. (3) Traces: distributed request traces showing the flow of a single request through multiple services with timing. Traces identify bottlenecks and dependencies. Examples: Jaeger, Zipkin, AWS X-Ray, OpenTelemetry. Best practice: use all three together — metrics for alerting, logs for debugging, traces for understanding distributed systems. They are NOT the same (B), apply to all layers (C), and all three are important (D).',
    tags: ['observability', 'metrics', 'logs', 'traces', 'monitoring'],
  },
  {
    topicSlug: 'observability',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What is the difference between monitoring and observability?',
    options: [
      'Monitoring tracks known failure modes with predefined dashboards/alerts; observability enables exploring unknown issues by asking arbitrary questions of your data',
      'Monitoring is for production; observability is for development which is the standard recommended approach which is the standard recommended approach implementing typical operational patterns',
      'They are the same thing and this approach is commonly used in enterprise settings following the recommended security practices as recommended for high availability using standard configuration methods',
      'Monitoring is deprecated; observability replaced it using established implementation patterns based on standard operational procedures which follows AWS recommended architecture patterns',
    ],
    correctIndex: 0,
    explanation: 'Monitoring is reactive: you define metrics, thresholds, and alerts for known failure modes (CPU > 90%, error rate > 1%, disk full). When something breaks in an expected way, monitoring alerts you. Monitoring answers: "Is the system healthy based on what we predicted could go wrong?" Observability is proactive and exploratory: it enables you to ask arbitrary questions about system behavior without predefining what to look for. Observability answers: "Why is this specific user experiencing slow checkout?" or "What changed between 2 PM and 3 PM that caused the spike in latency?" Observability requires: (1) high-cardinality data (attributes like user_id, session_id, endpoint, region), (2) ability to slice/filter/aggregate data dynamically, (3) correlation across metrics, logs, and traces. Monitoring is a subset of observability. Modern systems need both: monitoring for known issues (alerts), observability for unknown issues (debugging). Neither is environment-specific (B). They are complementary, not identical (C). Monitoring is NOT deprecated (D) — it is foundational.',
    tags: ['observability', 'monitoring', 'alerting', 'debugging', 'high-cardinality'],
  },
  {
    topicSlug: 'observability',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What is AWS CloudWatch and what can it monitor?',
    options: [
      `CloudWatch is AWS's monitoring service that collects metrics, logs, and events from AWS resources (EC2, RDS, Lambda, etc.) and custom applications`,
      'CloudWatch is only for EC2 instances',
      'CloudWatch is a log aggregation tool, not a monitoring service which is a fundamental architectural constraint which is a fundamental architectural constraint',
      'CloudWatch cannot create alerts',
    ],
    correctIndex: 0,
    explanation: 'Amazon CloudWatch is a fully managed observability service for AWS. Features: (1) Metrics: collect default metrics from AWS services (EC2 CPU utilization, RDS connections, Lambda invocations) and custom metrics from applications (via PutMetricData API or CloudWatch agent). (2) Logs: ingest logs from EC2 instances, Lambda functions, ECS containers, CloudTrail, VPC Flow Logs, etc. using CloudWatch Logs agent. Query logs using CloudWatch Logs Insights (SQL-like query language). (3) Alarms: create alarms on metrics (trigger SNS, Auto Scaling, Lambda). Example: alarm when API error rate > 5% for 5 minutes. (4) Dashboards: visualize metrics in custom dashboards. (5) Events/EventBridge: react to AWS resource changes (EC2 state change, S3 object created). (6) ServiceLens/X-Ray integration: distributed tracing for microservices. CloudWatch works with all AWS services (B is wrong), includes monitoring (C), and supports alarms (D). CloudWatch is the default starting point for AWS observability.',
    tags: ['observability', 'cloudwatch', 'aws', 'metrics', 'logs', 'alarms'],
  },
  {
    topicSlug: 'observability',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What is Prometheus and why is it popular for Kubernetes monitoring?',
    options: [
      'Prometheus is an open-source metrics system with pull-based collection, multi-dimensional data model, and powerful querying (PromQL); widely adopted for Kubernetes due to native service discovery',
      'Prometheus is a log aggregation tool which follows AWS recommended architecture patterns implementing typical operational patterns following typical deployment workflows as recommended for high availability',
      'Prometheus is only for bare-metal servers, not containers and this applies to all deployment scenarios and this applies to all deployment scenarios and this applies to all deployment scenarios based on production deployment experience',
      'Prometheus is a proprietary AWS service as recommended for high availability following the recommended security practices following common design principles according to industry standard guidelines using established implementation patterns',
    ],
    correctIndex: 0,
    explanation: 'Prometheus is an open-source monitoring system (part of CNCF) designed for cloud-native environments. Features: (1) Pull-based architecture: Prometheus scrapes metrics from HTTP endpoints (/metrics) exposed by applications and exporters. (2) Multi-dimensional data model: metrics have labels (key-value pairs) enabling flexible queries. Example: http_requests_total{method="GET", status="200", endpoint="/api/users"}. (3) PromQL: powerful query language for aggregating, filtering, and computing metrics (rate, histogram quantiles, alerts). (4) Service discovery: auto-discover scrape targets from Kubernetes, Consul, EC2, etc. (5) Alertmanager: route alerts to Slack, PagerDuty, email with de-duplication and grouping. (6) Ecosystem: Grafana for visualization, exporters for third-party systems (Node Exporter for Linux metrics, MySQL Exporter, etc.). Kubernetes integration: Prometheus natively discovers pods/services via Kubernetes API, scrapes cAdvisor metrics (container CPU/memory), and monitors cluster components (kube-apiserver, etcd). Prometheus is not for logs (B), works with containers (C), and is open-source (D).',
    tags: ['observability', 'prometheus', 'kubernetes', 'metrics', 'promql', 'monitoring'],
  },
  {
    topicSlug: 'observability',
    difficulty: 'EASY' as const,
    type: 'SCENARIO' as const,
    question: 'Your application is slow, but CPU and memory usage are normal. What observability data should you check next?',
    options: [
      'Check latency metrics (response time percentiles), distributed traces to identify slow dependencies, and database query performance',
      'Restart the application',
      'CPU and memory are the only metrics that matter and this applies to all deployment scenarios and this applies to all deployment scenarios',
      'Slowness cannot be diagnosed with observability',
    ],
    correctIndex: 0,
    explanation: 'Performance issues are not always resource bottlenecks. When CPU/memory are normal but the application is slow, investigate: (1) Latency metrics: measure response time percentiles (p50, p95, p99). Check if specific endpoints are slow. Tools: Prometheus (histogram_quantile), CloudWatch (percentile statistics), APM tools (New Relic, Datadog). (2) Distributed traces: trace a slow request through the system to identify which service or operation is the bottleneck. Example: API Gateway (5ms) → Lambda (2000ms) → RDS (1900ms) — database is the bottleneck. Tools: Jaeger, AWS X-Ray, OpenTelemetry. (3) Database performance: check slow query logs, query execution plans, connection pool exhaustion, lock contention. (4) External dependencies: slow third-party APIs, DNS resolution issues, network latency. (5) Application-level issues: inefficient code (N+1 queries, synchronous calls, no caching). Restarting (B) may mask the issue temporarily. CPU/memory are not the only indicators (C). Observability is designed for this (D). Systematic diagnosis requires multiple data sources.',
    tags: ['observability', 'latency', 'traces', 'performance', 'troubleshooting'],
  },
  {
    topicSlug: 'observability',
    difficulty: 'EASY' as const,
    type: 'SCENARIO' as const,
    question: 'You want to create an alert when your API error rate exceeds 5%. What observability tool/metric should you use?',
    options: [
      'Use a metrics system (Prometheus, CloudWatch) to track error rate percentage and create an alarm with threshold > 5%',
      'Manually check logs every hour as documented in the official best practices as documented in the official best practices',
      'Alerts cannot be automated',
      'Use traces to create alerts',
    ],
    correctIndex: 0,
    explanation: 'Alerting on error rate requires: (1) Metric collection: instrument your application to emit metrics. Example: increment error_count counter on 5xx responses, success_count on 2xx. (2) Compute error rate: error_rate = (error_count / total_requests) * 100. In Prometheus: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) * 100. In CloudWatch: create a math expression (Errors / Total) * 100. (3) Alert rule: create an alarm when error rate > 5 for a sustained period (e.g., 2 consecutive 5-minute windows to avoid flapping). (4) Notification: route alerts to PagerDuty, Slack, email via SNS (CloudWatch), Alertmanager (Prometheus), or Datadog/New Relic. (5) Runbook: include context in alert (dashboard link, logs query, troubleshooting steps). Manual checking (B) is not scalable. Alerts are fundamental to observability (C). Traces are for debugging, not alerting (D). Metrics-based alerting is standard practice for SLOs and SLIs.',
    tags: ['observability', 'alerting', 'metrics', 'error-rate', 'slo', 'prometheus', 'cloudwatch'],
  },
  {
    topicSlug: 'observability',
    difficulty: 'EASY' as const,
    type: 'SCENARIO' as const,
    question: 'Your logs are scattered across multiple servers. How do you centralize them for easy searching?',
    options: [
      'Use a log aggregation system (ELK stack, Loki, CloudWatch Logs, Splunk) to collect, index, and search logs from all servers in one place',
      'SSH into each server and read logs manually as documented in the official best practices as documented in the official best practices according to industry standard guidelines',
      'Log aggregation is not possible following typical deployment workflows according to industry standard guidelines according to industry standard guidelines',
      'Store logs in a Git repository and this approach is commonly used in enterprise settings and this approach is commonly used in enterprise settings',
    ],
    correctIndex: 0,
    explanation: 'Centralized logging collects logs from distributed systems into a single searchable platform. Common stacks: (1) ELK (Elasticsearch, Logstash, Kibana): Logstash/Filebeat collects logs from servers, Elasticsearch indexes and stores logs, Kibana provides search UI and dashboards. (2) Grafana Loki: lightweight alternative to ELK, designed for Kubernetes (no indexing, uses labels like Prometheus). (3) CloudWatch Logs: AWS-native log aggregation, uses CloudWatch agent to ship logs from EC2/ECS/Lambda. (4) Splunk: enterprise log management with powerful search and analytics. (5) Datadog Logs: SaaS log management with correlation to metrics/traces. Benefits: (1) Centralized search: query logs across all services ("show me all 500 errors in the last hour"). (2) Correlation: link logs to metrics and traces. (3) Retention: archive logs for compliance. (4) Alerting: alert on log patterns (repeated error messages). Manual SSH (B) does not scale. Aggregation is standard practice (C). Git is NOT for logs (D).',
    tags: ['observability', 'logs', 'aggregation', 'elk-stack', 'loki', 'cloudwatch', 'centralization'],
  },

  // ─── MEDIUM THEORY ─────────────────────────────────────────────────────────
  {
    topicSlug: 'observability',
    difficulty: 'MEDIUM' as const,
    type: 'THEORY' as const,
    question: 'What is high-cardinality data and why does it cause problems in metrics systems?',
    options: [
      'High-cardinality data has many unique label combinations (e.g., user_id, session_id); it explodes time series count, causing memory/storage issues in metrics systems like Prometheus',
      'High-cardinality means metrics update frequently',
      'High-cardinality is desirable and should be maximized which is the standard recommended approach which is the standard recommended approach which is the standard recommended approach',
      'High-cardinality only affects logs, not metrics',
    ],
    correctIndex: 0,
    explanation: 'Cardinality is the number of unique combinations of label values in metrics. Low-cardinality example: http_requests_total{method="GET", endpoint="/api/users", status="200"} has ~10 methods × 50 endpoints × 10 status codes = 5000 unique time series. High-cardinality example: adding user_id as a label (http_requests_total{user_id="12345"}) creates millions of unique time series (one per user). Problem: each unique time series consumes memory and storage. Prometheus stores each time series in memory. High-cardinality labels cause: (1) memory exhaustion (OOM), (2) slow queries, (3) increased storage costs, (4) cardinality explosion (exponential growth). High-cardinality labels to avoid in metrics: user_id, session_id, IP address, request_id, email, UUIDs. Solution: (1) Use logs or traces for high-cardinality data. (2) Aggregate high-cardinality labels (group by region instead of individual user). (3) Use exemplars (link metrics to traces for sampling). High-cardinality is NOT about update frequency (B). It should be minimized for metrics (C). It affects metrics more than logs (D).',
    tags: ['observability', 'metrics', 'cardinality', 'prometheus', 'performance', 'time-series'],
  },
  {
    topicSlug: 'observability',
    difficulty: 'MEDIUM' as const,
    type: 'THEORY' as const,
    question: 'What is distributed tracing and how does OpenTelemetry fit in?',
    options: [
      'Distributed tracing tracks requests across multiple services with spans and trace IDs; OpenTelemetry is a vendor-neutral standard for instrumenting and exporting traces, metrics, and logs',
      'Distributed tracing only works for monolithic applications',
      'OpenTelemetry is a specific monitoring tool like Prometheus which is the standard recommended approach which is the standard recommended approach which is the standard recommended approach',
      'Distributed tracing is only for frontend applications',
    ],
    correctIndex: 0,
    explanation: 'Distributed tracing follows a single request as it flows through multiple services in a microservices architecture. Concepts: (1) Trace: complete journey of a request. (2) Span: single operation within a trace (e.g., "call payment service", "query database"). Each span has: start time, duration, parent span ID, tags (metadata). (3) Trace ID: unique identifier linking all spans in a trace. (4) Context propagation: trace ID is passed between services via HTTP headers (X-B3-TraceId) or gRPC metadata. OpenTelemetry (OTel) is an open-source observability framework (CNCF project) providing: (1) SDKs for instrumenting applications (auto-instrumentation for popular frameworks: Express, Flask, Spring). (2) Exporters for sending data to backends (Jaeger, Zipkin, Datadog, New Relic, Honeycomb). (3) Collector for receiving, processing, and routing telemetry data. (4) Unified API for traces, metrics, and logs. OpenTelemetry is vendor-neutral — instrument once, switch backends easily. Distributed tracing is for microservices (B). OpenTelemetry is a standard, not a tool (C). It applies to backend (D).',
    tags: ['observability', 'distributed-tracing', 'opentelemetry', 'spans', 'microservices', 'traces'],
  },
  {
    topicSlug: 'observability',
    difficulty: 'MEDIUM' as const,
    type: 'THEORY' as const,
    question: 'What is the difference between structured and unstructured logs, and why do structured logs matter?',
    options: [
      'Structured logs use consistent formats (JSON, key-value pairs) enabling programmatic parsing and querying; unstructured logs are freeform text that is hard to search',
      'Structured logs are slower than unstructured logs',
      'Unstructured logs are more secure than structured logs which is the standard recommended approach which is the standard recommended approach which is the standard recommended approach',
      'Structured and unstructured logs are the same',
    ],
    correctIndex: 0,
    explanation: 'Unstructured logs are freeform text: "User John logged in from 192.168.1.1 at 2024-01-15 10:30:00". Searching requires regex or full-text search, which is slow and error-prone. Structured logs use consistent key-value formats (JSON): {"timestamp": "2024-01-15T10:30:00Z", "event": "user_login", "user": "John", "ip": "192.168.1.1", "status": "success"}. Benefits: (1) Programmatic parsing: no regex, parse with jq or native tools. (2) Efficient indexing: log aggregation systems (Elasticsearch, Loki) index fields, enabling fast queries ("show me all failed logins for user John"). (3) Correlation: link logs to traces via trace_id field. (4) Alerting: alert on specific field values (status="error"). (5) Consistency: enforce schema across services. Best practice: use structured logging libraries (Winston for Node.js, structlog for Python, logrus for Go). Structured logs are NOT slower (B) — parsing is faster. Security is unrelated (C). They are fundamentally different (D). Structured logging is essential for modern observability.',
    tags: ['observability', 'logs', 'structured-logging', 'json', 'log-aggregation'],
  },
  {
    topicSlug: 'observability',
    difficulty: 'MEDIUM' as const,
    type: 'THEORY' as const,
    question: 'What is the RED method for monitoring services?',
    options: [
      'RED: Rate (requests per second), Errors (error rate), Duration (latency); a standard set of metrics for monitoring request-driven services',
      'RED is a specific monitoring tool according to industry standard guidelines and this approach is commonly used in enterprise settings based on production deployment experience',
      'RED stands for: Restart, Evaluate, Deploy which is the standard recommended approach which is the standard recommended approach based on production deployment experience',
      'RED method is only for databases following the recommended security practices based on standard operational procedures as documented in official AWS best practices',
    ],
    correctIndex: 0,
    explanation: 'The RED method (coined by Tom Wilkie, Grafana Labs) defines three key metrics for monitoring any request-driven service (APIs, web servers, microservices): (1) Rate: number of requests per second (throughput). Indicates traffic volume and capacity needs. (2) Errors: percentage or count of failed requests (HTTP 5xx, exceptions). Indicates reliability. (3) Duration: latency of requests, typically measured as percentiles (p50, p95, p99). Indicates performance. These metrics answer: "Is the service healthy?" Track RED metrics at different layers: load balancer, API gateway, each microservice. Example Prometheus queries: Rate: sum(rate(http_requests_total[5m])) by (service); Errors: sum(rate(http_requests_total{status=~"5.."}[5m])) by (service); Duration: histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, service)). RED is complementary to USE method (for resources: Utilization, Saturation, Errors). RED is not a tool (B), not an acronym for deployment (C), and applies to all request-driven services (D).',
    tags: ['observability', 'metrics', 'red-method', 'monitoring', 'slo', 'prometheus'],
  },
  {
    topicSlug: 'observability',
    difficulty: 'MEDIUM' as const,
    type: 'SCENARIO' as const,
    question: 'Your Prometheus server is running out of memory due to too many time series. How do you reduce cardinality?',
    options: [
      'Remove high-cardinality labels (user_id, IP, session_id), aggregate metrics, use relabeling to drop unnecessary labels, or use Thanos/Cortex for scaling',
      'Buy more RAM',
      'Delete all metrics',
      'Prometheus memory issues cannot be fixed which is a fundamental architectural constraint which is a fundamental architectural constraint which is a fundamental architectural constraint',
    ],
    correctIndex: 0,
    explanation: `Prometheus stores all time series in memory, making it vulnerable to cardinality explosions. Mitigation strategies: (1) Remove high-cardinality labels: audit metrics with 'prometheus_tsdb_symbol_table_size_bytes' and identify offenders. Remove labels like user_id, request_id, IP addresses, UUIDs. (2) Aggregate metrics: instead of per-user metrics, aggregate by region or service. (3) Use relabeling: Prometheus scrape configs support relabel_configs to drop or modify labels before ingestion. Example: drop metrics matching a pattern. (4) Limit retention: reduce '--storage.tsdb.retention.time' (default 15d) to keep less data. (5) Use recording rules: precompute aggregated metrics to reduce query load. (6) Scale with Thanos or Cortex: distribute Prometheus across multiple instances with centralized long-term storage (S3, GCS). (7) Use metrics sampling: drop percentage of high-cardinality metrics. (8) Enable remote write: offload metrics to long-term storage (InfluxDB, M3DB). Adding RAM (B) is a temporary fix. Deleting all metrics (C) defeats the purpose. Cardinality is solvable (D).`,
    tags: ['observability', 'prometheus', 'cardinality', 'memory', 'troubleshooting', 'scaling'],
  },
  {
    topicSlug: 'observability',
    difficulty: 'MEDIUM' as const,
    type: 'SCENARIO' as const,
    question: 'You need to debug a slow API request that touches 5 microservices. What observability data should you use?',
    options: [
      'Use distributed tracing to visualize the request flow across services, identify the slowest span, then check logs and metrics for that service',
      'Check CPU metrics for all services implementing typical operational patterns using established implementation patterns as suggested by cloud architects following typical deployment workflows',
      'Restart all services using established implementation patterns which follows AWS recommended architecture patterns based on standard operational procedures',
      'Debugging across services is not possible which is a fundamental architectural constraint which is a fundamental architectural constraint based on production deployment experience',
    ],
    correctIndex: 0,
    explanation: 'Distributed tracing is designed for this exact scenario. Debugging workflow: (1) Obtain trace ID: from the slow request (API response header, logs, or user report). (2) View trace in tracing UI (Jaeger, Zipkin, X-Ray): trace shows timeline of spans across services: API Gateway (5ms) → Auth Service (10ms) → User Service (2000ms) → Database (1900ms) → Cache (50ms) → Notification Service (30ms). (3) Identify bottleneck: User Service / Database span is 1900ms (95% of total latency). (4) Drill into span tags: database_query="SELECT * FROM users WHERE ...", database_host="db-replica-1". (5) Check logs for that span: filter logs by trace_id to see detailed error messages or warnings. (6) Check metrics: query Prometheus for DB connection pool exhaustion, slow query rate, or replica lag. (7) Root cause: DB replica is lagging or query is unoptimized. Fix: optimize query or use primary DB. CPU metrics (B) are useful but do not show cross-service flow. Restarting (C) is not diagnosis. Distributed debugging is possible with tracing (D).',
    tags: ['observability', 'distributed-tracing', 'debugging', 'microservices', 'performance', 'traces'],
  },
  {
    topicSlug: 'observability',
    difficulty: 'MEDIUM' as const,
    type: 'SCENARIO' as const,
    question: 'Your ELK (Elasticsearch, Logstash, Kibana) stack is expensive due to high log volume. How do you reduce costs?',
    options: [
      'Filter noisy logs at source, use sampling for debug logs, set log retention policies, optimize index settings, or switch to cheaper alternatives (Loki, CloudWatch)',
      'Stop logging entirely',
      'ELK costs cannot be reduced which is a fundamental architectural constraint which is a fundamental architectural constraint which is a fundamental architectural constraint',
      'Buy more storage',
    ],
    correctIndex: 0,
    explanation: 'ELK stack costs scale with log volume and storage. Cost reduction strategies: (1) Filter at source: use log filtering in Logstash or Filebeat to drop noisy logs (health check logs, debug logs in production). Example: filter { if [message] =~ /health/ { drop {} } }. (2) Sampling: keep 100% of error logs, sample 10% of info logs. (3) Log levels: set production log level to INFO or WARN, not DEBUG. (4) Retention policies: use Elasticsearch Index Lifecycle Management (ILM) to delete old indices after 30/60 days. Move older data to cheaper storage (S3 via snapshots). (5) Optimize indices: use smaller replica counts, enable index compression, adjust refresh intervals. (6) Structured logging: reduce log size by using JSON instead of verbose text. (7) Use cheaper alternatives: Grafana Loki (no indexing, cheaper storage), AWS CloudWatch Logs (pay per GB ingested), or object storage (S3 + Athena for querying). Stopping logging (B) is unacceptable. Costs are reducible (C). Storage is not the only factor (D).',
    tags: ['observability', 'logs', 'elk-stack', 'cost-optimization', 'elasticsearch', 'log-retention'],
  },

  // ─── HARD THEORY ───────────────────────────────────────────────────────────
  {
    topicSlug: 'observability',
    difficulty: 'HARD' as const,
    type: 'THEORY' as const,
    question: 'What is eBPF-based observability and how does it differ from traditional instrumentation?',
    options: [
      'eBPF (Extended Berkeley Packet Filter) runs in-kernel code to collect observability data (network, system calls, performance) without modifying applications; traditional instrumentation requires code changes',
      'eBPF is a log aggregation tool which is the standard recommended approach which is the standard recommended approach which is the standard recommended approach as documented in official AWS best practices according to industry standard guidelines',
      'eBPF only works on Windows as suggested by cloud architects according to industry standard guidelines and this approach is commonly used in enterprise settings following typical deployment workflows and this approach is commonly used in enterprise settings',
      'eBPF is deprecated using standard configuration methods according to industry standard guidelines which follows AWS recommended architecture patterns based on production deployment experience following common design principles',
    ],
    correctIndex: 0,
    explanation: 'eBPF is a revolutionary Linux kernel technology that enables running sandboxed programs in the kernel without modifying kernel source or loading kernel modules. eBPF observability tools: (1) Pixie: Kubernetes-native observability with automatic instrumentation (captures HTTP, DNS, MySQL, Postgres traffic without code changes). (2) Cilium: eBPF-based networking and security for Kubernetes with built-in observability. (3) Parca/Pyroscope: continuous profiling using eBPF. (4) bpftrace: dynamic tracing tool (trace system calls, kernel functions, user-space functions). Use cases: (1) Zero-instrumentation monitoring: collect metrics/traces without modifying applications. (2) Low-level insights: trace system calls (open, read, write), network packets (TCP handshake, latency), and kernel events. (3) Security: detect anomalous behavior (unauthorized file access, network connections). eBPF vs. traditional: traditional requires application SDKs (OpenTelemetry, Prometheus client libraries), code changes, and redeployment. eBPF works out-of-the-box. eBPF is NOT logs (B), Linux-only (C is correct), and NOT deprecated (D) — it is the future.',
    tags: ['observability', 'ebpf', 'instrumentation', 'kernel', 'pixie', 'tracing'],
  },
  {
    topicSlug: 'observability',
    difficulty: 'HARD' as const,
    type: 'THEORY' as const,
    question: 'What is the cardinality explosion problem in Prometheus and how do you detect it?',
    options: [
      `Cardinality explosion occurs when metric labels create exponentially many unique time series; detect using 'prometheus_tsdb_symbol_table_size_bytes', 'prometheus_tsdb_head_series', and cardinality explorer dashboards`,
      'Cardinality explosion is a security vulnerability which is the standard recommended approach which is the standard recommended approach which is the standard recommended approach',
      'Cardinality explosion only affects logs',
      'Cardinality explosion cannot be detected',
    ],
    correctIndex: 0,
    explanation: `Cardinality explosion happens when adding high-cardinality labels to metrics. Example: metric http_requests_total{method, endpoint, status} has 10 methods × 100 endpoints × 10 status = 10,000 time series. Adding user_id (1 million users) creates 10,000 × 1,000,000 = 10 billion time series, causing OOM. Detection: (1) Prometheus metrics: 'prometheus_tsdb_head_series' (current active time series count), 'prometheus_tsdb_symbol_table_size_bytes' (label name/value memory usage). Alert when series count grows unexpectedly. (2) TSDB status: Prometheus UI → Status → TSDB Status shows top metrics by cardinality. (3) Cardinality explorer: Grafana dashboard or custom queries to identify high-cardinality labels. Example query: 'topk(10, count by (__name__, job) ({__name__!=""}))' shows metrics with most time series. (4) Label analysis: 'count({__name__!=""}) by (label_name)' shows cardinality per label. Prevention: design metrics with low-cardinality labels, use exemplars for sampling, and move high-cardinality data to traces/logs. It is NOT a security issue (B), not just logs (C), and IS detectable (D).`,
    tags: ['observability', 'prometheus', 'cardinality', 'tsdb', 'metrics', 'troubleshooting'],
  },
  {
    topicSlug: 'observability',
    difficulty: 'HARD' as const,
    type: 'THEORY' as const,
    question: 'What are Prometheus recording rules and when should you use them?',
    options: [
      'Recording rules precompute and store expensive aggregations as new metrics, improving query performance and enabling complex alerting',
      'Recording rules are for recording audio in Prometheus which is the standard recommended approach which is the standard recommended approach',
      'Recording rules delete old metrics',
      'Recording rules are only for Grafana dashboards',
    ],
    correctIndex: 0,
    explanation: `Prometheus recording rules precompute frequently-used or expensive queries and store the results as new time series. Use cases: (1) Performance: dashboards repeatedly query 'sum(rate(http_requests_total[5m])) by (service)'. Instead, precompute this every minute and store as 'job:http_requests:rate5m'. (2) Alerting: alerts need fast evaluation. Precompute complex aggregations. (3) Downsampling: compute aggregates (hourly, daily) before old data is deleted. (4) Simplify queries: encapsulate business logic in recording rules. Example recording rule: groups: - name: api_metrics; interval: 30s; rules: - record: job:http_requests:rate5m; expr: sum(rate(http_requests_total[5m])) by (job). Now use 'job:http_requests:rate5m' in dashboards instead of the complex query. Trade-offs: (1) Recording rules consume storage (new time series). (2) Update latency (rules run at intervals, not real-time). (3) Debugging is harder (the original metric still exists, but alerts/dashboards use the recording rule). Recording rules are NOT for audio (B), do NOT delete metrics (C), and apply to all queries (D). They are critical for large-scale Prometheus deployments.`,
    tags: ['observability', 'prometheus', 'recording-rules', 'performance', 'aggregation', 'metrics'],
  },
  {
    topicSlug: 'observability',
    difficulty: 'HARD' as const,
    type: 'THEORY' as const,
    question: 'What is tail-based sampling in distributed tracing and why is it better than head-based sampling?',
    options: [
      'Tail-based sampling decides whether to keep a trace after seeing all spans (can sample based on errors, latency); head-based samples upfront (blind to trace content)',
      'Tail-based sampling is slower and should be avoided which is the standard recommended approach which is the standard recommended approach which is the standard recommended approach',
      'Tail-based sampling is only for logs',
      'Head-based and tail-based sampling are the same',
    ],
    correctIndex: 0,
    explanation: 'Distributed tracing generates massive data volumes (every request = one trace). Storing 100% of traces is expensive. Sampling strategies: (1) Head-based sampling (naive): decide at the start of a request whether to trace it (e.g., sample 1% of requests). Problem: you may miss rare but critical errors (e.g., a 0.01% error is never sampled). (2) Tail-based sampling (intelligent): collect all spans, then decide at the end whether to keep the trace. Sampling rules: keep all traces with errors, keep 10% of slow traces (p95 latency), keep 1% of fast/successful traces. Result: you capture ALL errors and slow requests while sampling successful requests. Implementation: use OpenTelemetry Collector or tracing backends (Honeycomb, Lightstep, Jaeger with tail sampling processor). Trade-off: tail-based sampling requires buffering all spans until the trace completes (adds latency, memory overhead) but provides better data quality. Tail-based is NOT slower for analysis (B), not just logs (C), and is superior to head-based (D). Tail-based sampling is critical for high-traffic production systems.',
    tags: ['observability', 'distributed-tracing', 'sampling', 'tail-based', 'opentelemetry', 'traces'],
  },
  {
    topicSlug: 'observability',
    difficulty: 'HARD' as const,
    type: 'SCENARIO' as const,
    question: 'Your distributed system has 50 microservices. You need to correlate logs, metrics, and traces for a single request. How do you implement this?',
    options: [
      'Propagate trace ID and span ID in HTTP headers (W3C Trace Context), include them in logs, and tag metrics with trace ID (exemplars); use a unified observability platform (Datadog, Honeycomb, Grafana)',
      'Correlation is not possible across logs, metrics, and traces',
      'Use separate systems for logs, metrics, and traces without linking them which is the standard recommended approach which is the standard recommended approach which is the standard recommended approach',
      'Only metrics are needed for debugging',
    ],
    correctIndex: 0,
    explanation: 'Correlating the three pillars requires shared identifiers. Implementation: (1) Trace context propagation: use W3C Trace Context standard (trace-id, span-id) in HTTP headers (traceparent: 00-<trace-id>-<span-id>-01). Each service extracts trace-id from incoming requests and propagates it downstream. (2) Structured logs with trace ID: include trace_id and span_id in every log entry. Example: {"level":"error","message":"DB timeout","trace_id":"abc123","span_id":"def456"}. When debugging a trace, filter logs by trace_id to see all log events for that request. (3) Metrics with exemplars: Prometheus exemplars link metrics to traces. Example: histogram bucket contains a sample trace_id, enabling "why did this metric spike?" questions. (4) Unified platform: use observability platforms (Datadog, Honeycomb, Grafana Tempo + Loki + Prometheus) that auto-link logs, metrics, and traces. (5) OpenTelemetry: use OTel SDK to instrument applications — it handles trace propagation, log correlation, and metrics tagging automatically. Correlation is possible (B), linking is essential (C), and all three pillars are needed (D). This is the gold standard for modern observability.',
    tags: ['observability', 'correlation', 'traces', 'logs', 'metrics', 'w3c-trace-context', 'opentelemetry'],
  },
  {
    topicSlug: 'observability',
    difficulty: 'HARD' as const,
    type: 'SCENARIO' as const,
    question: 'Your Prometheus federation setup has 10 regional Prometheus servers and a global Prometheus aggregating data. What is the best way to scale this as traffic grows?',
    options: [
      'Migrate to Thanos or Cortex for horizontally scalable, long-term storage with global querying across all regional Prometheus instances',
      'Add more RAM to the global Prometheus server which is the standard recommended approach which is the standard recommended approach following typical deployment workflows',
      'Federation scales infinitely without changes as recommended for high availability following typical deployment workflows as suggested by cloud architects',
      'Replace Prometheus with CloudWatch as documented in official AWS best practices based on standard operational procedures as recommended for high availability',
    ],
    correctIndex: 0,
    explanation: `Prometheus federation allows a global Prometheus to scrape metrics from regional Prometheus servers. Limitations: (1) Global Prometheus becomes a bottleneck as regions grow. (2) No long-term storage (Prometheus retains data for 15 days by default). (3) Query latency increases with scale. (4) Single point of failure. Scalable alternatives: (1) Thanos: extends Prometheus with: (a) Sidecar: uploads Prometheus data to object storage (S3, GCS). (b) Store Gateway: queries historical data from object storage. (c) Query: provides a global query API across all Prometheus instances (regional and historical). (d) Compactor: downsamples and compacts data for efficient long-term storage. (2) Cortex: horizontally scalable Prometheus-as-a-Service with multi-tenancy. (3) Mimir (Grafana): Cortex fork, optimized for scale and performance. Benefits: (1) Unlimited retention (store years of data in S3). (2) Global querying (query all regions from one interface). (3) High availability (replicated components). (4) Cost-effective (S3 is cheaper than Prometheus local storage). Adding RAM (B) is not scalable. Federation does not scale infinitely (C). CloudWatch (D) lacks Prometheus' flexibility.`,
    tags: ['observability', 'prometheus', 'federation', 'thanos', 'cortex', 'scalability', 'long-term-storage'],
  },
  {
    topicSlug: 'observability',
    difficulty: 'HARD' as const,
    type: 'SCENARIO' as const,
    question: 'You need to implement observability for a serverless application (AWS Lambda). What challenges do you face and how do you address them?',
    options: [
      'Challenges: cold starts, short-lived execution, no persistent agents; Solutions: use AWS X-Ray for traces, CloudWatch Logs for logs, structured logging with trace IDs, and OpenTelemetry Lambda layers',
      'Serverless applications cannot be monitored following typical deployment workflows as suggested by cloud architects using established implementation patterns using conventional setup approaches and this approach is commonly used in enterprise settings',
      'Use Prometheus agents inside Lambda functions which is the standard recommended approach which is the standard recommended approach which is the standard recommended approach as documented in official AWS best practices',
      'Observability is automatic for Lambda which follows AWS recommended architecture patterns according to industry standard guidelines using established implementation patterns using established implementation patterns',
    ],
    correctIndex: 0,
    explanation: 'Serverless observability challenges: (1) Cold starts: Lambda initializes execution environment on first invocation, adding latency. Instrument initialization and handler separately to measure cold start impact. (2) Short-lived execution: functions run for seconds/minutes, traditional agents (Prometheus, Grafana) do not work (no persistent scrape targets). (3) Distributed by nature: a single request may trigger multiple Lambda functions + API Gateway + DynamoDB + S3 events. Solutions: (1) AWS X-Ray: native distributed tracing for Lambda. Auto-instruments AWS SDK calls (DynamoDB, S3, SNS). Add X-Ray SDK for custom spans. Trace context is propagated automatically. (2) CloudWatch Logs: Lambda logs are streamed to CloudWatch Logs automatically. Use structured logging (JSON) with trace IDs for correlation. (3) CloudWatch Metrics: Lambda publishes metrics (invocations, duration, errors, throttles). Create custom metrics via PutMetricData. (4) OpenTelemetry Lambda Layer: AWS provides OTel Lambda layers for automatic instrumentation, exporting traces to Jaeger, Datadog, Honeycomb. (5) Third-party APM: Datadog, New Relic, Lumigo provide Lambda-specific observability. Monitoring is possible (B). Prometheus does not work (C). Observability requires instrumentation (D).',
    tags: ['observability', 'serverless', 'lambda', 'aws-xray', 'cloudwatch', 'opentelemetry', 'tracing'],
  },
  {
    topicSlug: 'observability',
    difficulty: 'HARD' as const,
    type: 'SCENARIO' as const,
    question: 'Your observability system generates 10 TB of logs per day at $0.50/GB ingestion cost ($5,000/day). How do you reduce costs while maintaining observability?',
    options: [
      'Implement log levels (keep ERROR/WARN, sample INFO/DEBUG), structured logging to reduce size, retention policies (7-day hot, 30-day cold, 90-day archive), and switch to cheaper storage (Loki, S3)',
      'Stop logging entirely to save costs as documented in official AWS best practices according to industry standard guidelines as suggested by cloud architects following the recommended security practices and this approach is commonly used in enterprise settings',
      'Log costs cannot be reduced according to industry standard guidelines according to industry standard guidelines based on standard operational procedures which follows AWS recommended architecture patterns as suggested by cloud architects',
      'Switch to metrics only, abandon logs and this applies to all deployment scenarios and this applies to all deployment scenarios and this applies to all deployment scenarios following typical deployment workflows',
    ],
    correctIndex: 0,
    explanation: 'Log cost optimization is critical at scale. Strategies: (1) Log levels: in production, set log level to WARN or ERROR. Sample INFO logs (keep 10%). Never log DEBUG in production. (2) Sampling: use probabilistic sampling for high-volume logs (health checks, successful requests). Always keep 100% of errors. (3) Structured logging: JSON logs are more compact than verbose text. Use short field names. (4) Remove PII: strip or hash sensitive data before ingestion. (5) Retention tiers: Hot storage (7 days, expensive, fast queries) → Cold storage (30 days, cheaper, slower queries) → Archive (90+ days, S3 Glacier, infrequent access). (6) Cheap alternatives: Grafana Loki (no indexing, uses label-based queries like Prometheus), store in S3 + query with Athena. (7) Compression: enable log compression in transit and at rest. (8) Filter at source: drop noisy logs before they reach aggregation (Fluentd, Logstash filters). Example: 10 TB/day → 7-day retention = 70 TB = $35k/month. With 10x reduction → 1 TB/day → $3.5k/month. Stopping logs (B) is unacceptable. Costs are reducible (C). Logs are essential for debugging (D).',
    tags: ['observability', 'logs', 'cost-optimization', 'log-sampling', 'retention', 'loki', 's3'],
  },

  // ─── ADDITIONAL PROMETHEUS & GRAFANA QUESTIONS ─────────────────────────────
  {
    topicSlug: 'observability',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What is Grafana and how does it integrate with Prometheus?',
    options: [
      'Grafana is a visualization platform that queries Prometheus via PromQL to display metrics in dashboards, graphs, and alerts',
      'Grafana is a metrics storage system that replaces Prometheus which is the standard recommended approach which is the standard recommended approach',
      'Grafana is a log aggregation tool',
      'Grafana only works with AWS CloudWatch, not Prometheus',
    ],
    correctIndex: 0,
    explanation: 'Grafana is an open-source analytics and visualization platform used to create dashboards for time-series data. It does not store data itself but connects to data sources like Prometheus, InfluxDB, Elasticsearch, CloudWatch, and many others. Prometheus + Grafana is the standard open-source monitoring stack. Integration: (1) Add Prometheus as a data source in Grafana (URL: http://prometheus:9090), (2) Create dashboards using PromQL queries, (3) Grafana executes PromQL against Prometheus and renders results as graphs, tables, gauges, or heatmaps, (4) Set up alerts in Grafana based on query thresholds. Key features: (1) Multi-source dashboards: combine Prometheus metrics, Loki logs, and Jaeger traces in one dashboard, (2) Templating: use variables for dynamic dashboards (select namespace, environment, or service), (3) Alerting: Grafana can send alerts to Slack, PagerDuty, email, (4) Pre-built dashboards: import community dashboards for Node Exporter, Kubernetes, PostgreSQL, etc. Grafana is NOT a storage system (B), NOT a log tool (C), and works with many sources including Prometheus (D).',
    tags: ['observability', 'grafana', 'prometheus', 'visualization', 'dashboards'],
  },
  {
    topicSlug: 'observability',
    difficulty: 'MEDIUM' as const,
    type: 'THEORY' as const,
    question: 'What are Prometheus metric types (Counter, Gauge, Histogram, Summary) and when should you use each?',
    options: [
      'Counter: cumulative, only increases (requests, errors). Gauge: point-in-time value, can go up/down (temperature, memory). Histogram: distribution of values in buckets (latency percentiles). Summary: similar to histogram but calculates quantiles client-side',
      'All metric types are identical and interchangeable using standard configuration methods following typical deployment workflows as documented in official AWS best practices based on standard operational procedures and this approach is commonly used in enterprise settings',
      'Counter is for performance metrics; Gauge is for business metrics only and this applies to all deployment scenarios and this applies to all deployment scenarios and this applies to all deployment scenarios using established implementation patterns and this approach is commonly used in enterprise settings',
      'Histogram is for logs; Summary is for traces implementing typical operational patterns which follows AWS recommended architecture patterns according to industry standard guidelines based on standard operational procedures using established implementation patterns based on production deployment experience',
    ],
    correctIndex: 0,
    explanation: 'Prometheus defines four metric types: Counter: a cumulative metric that only increases (or resets to zero on restart). Use for: total requests, total errors, bytes sent, tasks completed. Never use for values that can decrease. Query with rate() to get per-second rate: rate(http_requests_total[5m]). Gauge: a point-in-time value that can increase or decrease. Use for: current temperature, memory usage, queue depth, number of active connections. Histogram: samples observations (e.g., request latency) and counts them in configurable buckets (e.g., 0.1s, 0.5s, 1s, 5s). Use for: latency distributions, request sizes. Server-side aggregation is accurate. Calculate percentiles with histogram_quantile(): histogram_quantile(0.99, rate(http_request_duration_seconds_bucket[5m])). Summary: similar to histogram but calculates quantiles (p50, p90, p99) on the client. Pre-defined quantiles cannot be aggregated across instances. Use when exact quantiles are needed and you cannot aggregate. Best practice: use histograms for most latency measurements — they are aggregatable and flexible.',
    tags: ['observability', 'prometheus', 'metrics', 'counter', 'gauge', 'histogram'],
  },
  {
    topicSlug: 'observability',
    difficulty: 'MEDIUM' as const,
    type: 'SCENARIO' as const,
    question: 'You need to calculate the 99th percentile latency for an API endpoint in Prometheus. Which function and metric type should you use?',
    options: [
      'Use histogram_quantile(0.99, rate(http_request_duration_seconds_bucket[5m])) with a histogram metric',
      'Use avg(http_request_duration_seconds) to get the average',
      'Use max(http_request_duration_seconds) for worst-case latency',
      'Use sum(http_request_duration_seconds) / count(http_requests_total) which is the standard recommended approach',
    ],
    correctIndex: 0,
    explanation: 'Calculating percentiles in Prometheus requires histogram metrics and the histogram_quantile() function. Proper setup: (1) Instrument your application to emit a histogram metric with buckets: http_request_duration_seconds_bucket (with le labels for bucket boundaries). (2) Query: histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket[5m])) by (le)). This calculates the 99th percentile latency. Explanation: rate() calculates per-second rate of bucket counts. sum() by (le) aggregates across all instances while preserving bucket boundaries. histogram_quantile(0.99, ...) interpolates to find the value below which 99% of observations fall. Common mistake: using avg() (B) hides outliers — 99% of requests could be fast while 1% are 10x slower. Average does not reveal this. Max (C) shows absolute worst case but not percentile distribution. Manual calculation (D) is incorrect — it gives average, not percentile. Always use histograms for latency and histogram_quantile() for percentile calculations.',
    tags: ['observability', 'prometheus', 'promql', 'percentiles', 'histogram', 'latency'],
  },
  {
    topicSlug: 'observability',
    difficulty: 'MEDIUM' as const,
    type: 'THEORY' as const,
    question: 'What is Grafana Loki and how does it differ from the ELK stack for log management?',
    options: [
      'Loki is a log aggregation system that indexes only metadata (labels) rather than full text, making it cheaper and integrating tightly with Grafana/Prometheus labels',
      'Loki provides full-text search like Elasticsearch which is the standard recommended approach which is the standard recommended approach which is the standard recommended approach',
      'Loki replaces Prometheus for metrics',
      'Loki is more expensive than ELK stack',
    ],
    correctIndex: 0,
    explanation: 'Grafana Loki is a horizontally-scalable log aggregation system designed by Grafana Labs. Key differences from ELK: (1) Indexing approach: ELK (Elasticsearch) indexes the full text of every log line, enabling fast full-text search but requiring significant compute/storage. Loki indexes ONLY labels (metadata like pod, namespace, container) and stores log lines in compressed chunks. This is much cheaper. (2) Query model: Loki uses LogQL (similar to PromQL), filtering by labels first, then optionally by log content with regex. ELK uses Lucene queries for full-text search. (3) Integration: Loki shares the same label model as Prometheus metrics, enabling seamless correlation (same labels on metrics and logs). (4) Cost: Loki is 5-10x cheaper than ELK for most workloads because it does not index log content. (5) Search speed: ELK is faster for arbitrary full-text searches. Loki is faster when filtering by labels. Trade-off: Loki is ideal if you know what you are looking for (filter by service, error level, trace ID). ELK is better for exploratory searches across unknown log content. Loki does NOT provide full-text indexing (B), handles logs not metrics (C), and is cheaper (D).',
    tags: ['observability', 'loki', 'logs', 'grafana', 'elk', 'cost-optimization'],
  },
  {
    topicSlug: 'observability',
    difficulty: 'HARD' as const,
    type: 'THEORY' as const,
    question: 'What is the Prometheus Alertmanager and how does it handle alert routing, grouping, and silencing?',
    options: [
      'Alertmanager receives alerts from Prometheus, deduplicates and groups them, routes to receivers (Slack, PagerDuty) based on labels, and supports silencing and inhibition rules',
      'Alertmanager stores metrics like Prometheus',
      'Alertmanager is a Grafana-only feature',
      'Alertmanager sends alerts without any deduplication which is the standard recommended approach which is the standard recommended approach which is the standard recommended approach',
    ],
    correctIndex: 0,
    explanation: 'Prometheus Alertmanager is a separate component that handles alerts fired by Prometheus. Features: (1) Deduplication: if the same alert fires multiple times (from HA Prometheus instances), Alertmanager deduplicates to send one notification. (2) Grouping: group related alerts (e.g., all alerts from the same cluster or service) into a single notification to avoid alert storms. Configure with group_by: [alertname, cluster]. (3) Routing: route alerts to different receivers based on labels. Example: severity=critical → PagerDuty, severity=warning → Slack. (4) Receivers: send alerts to Slack, PagerDuty, Opsgenie, email, webhooks, etc. (5) Silencing: temporarily mute alerts during maintenance windows (silence by matcher: alertname="DiskFull", instance="server1"). (6) Inhibition: suppress lower-priority alerts when a higher-priority alert is firing (e.g., suppress all warnings when a critical alert is active). (7) High availability: run multiple Alertmanager instances in a cluster to avoid single points of failure. Alertmanager does NOT store metrics (B), works with Prometheus not just Grafana (C), and deduplication is a core feature (D).',
    tags: ['observability', 'prometheus', 'alertmanager', 'alerting', 'routing', 'silencing'],
  },
  {
    topicSlug: 'observability',
    difficulty: 'HARD' as const,
    type: 'SCENARIO' as const,
    question: 'You are setting up Grafana dashboards for a Kubernetes cluster. What are the essential dashboards and metrics you should include?',
    options: [
      'Node metrics (CPU, memory, disk, network), pod metrics (CPU/memory requests vs usage, restarts), namespace resource quotas, deployment replica status, and API server latency',
      'Only application-specific business metrics',
      'Grafana dashboards are not useful for Kubernetes which is a fundamental architectural constraint which is a fundamental architectural constraint which is a fundamental architectural constraint',
      'One dashboard with all metrics on a single panel',
    ],
    correctIndex: 0,
    explanation: 'Essential Kubernetes Grafana dashboards: (1) Node-level: CPU utilization (100 - avg(irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100), memory usage, disk I/O, network throughput. Use Node Exporter for these metrics. (2) Pod-level: CPU usage vs requests (container_cpu_usage_seconds_total vs kube_pod_container_resource_requests), memory usage vs limits, pod restarts (kube_pod_container_status_restarts_total), OOMKilled events. (3) Namespace-level: resource quota usage (kube_resourcequota), LimitRange enforcement. (4) Deployment health: replica count (kube_deployment_status_replicas vs kube_deployment_spec_replicas), rollout status, failed deployments. (5) Control plane: API server request latency (apiserver_request_duration_seconds), etcd latency, scheduler queue depth. (6) Networking: ingress request rate, error rate, latency (if using ingress controller metrics). Pre-built dashboards: import from Grafana dashboard library (IDs: 315 for Node Exporter, 13770 for Kubernetes cluster). Best practice: create a hierarchy — cluster overview → namespace drill-down → pod details. Business metrics alone (B) miss infrastructure issues. Grafana is essential for K8s observability (C). Single panel (D) is unusable.',
    tags: ['observability', 'grafana', 'kubernetes', 'dashboards', 'prometheus', 'monitoring'],
  },
  {
    topicSlug: 'observability',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What is a Prometheus exporter and name three commonly used exporters?',
    options: [
      'An exporter is a service that exposes metrics in Prometheus format; common exporters: Node Exporter (Linux metrics), Blackbox Exporter (HTTP/TCP probes), and MySQL Exporter (database metrics)',
      'An exporter sends metrics from Prometheus to external systems',
      'Exporters are only for custom application metrics',
      'Prometheus does not need exporters; it collects all metrics automatically which is a fundamental architectural constraint which is a fundamental architectural constraint which is a fundamental architectural constraint',
    ],
    correctIndex: 0,
    explanation: 'Prometheus exporters translate metrics from third-party systems into Prometheus format (/metrics HTTP endpoint). Common exporters: (1) Node Exporter: exposes Linux/Unix system metrics (CPU, memory, disk, network, filesystem). Essential for every Prometheus setup. (2) Blackbox Exporter: probes endpoints over HTTP, HTTPS, DNS, TCP, ICMP. Use for uptime monitoring, SSL certificate expiry checks. (3) MySQL Exporter / PostgreSQL Exporter: database metrics (connections, queries, replication lag, buffer pool stats). (4) Redis Exporter: Redis metrics (memory, commands, keyspace). (5) Kafka Exporter: Kafka broker and consumer metrics. (6) cAdvisor: container metrics (CPU, memory per container). Often built into Kubernetes kubelet. (7) kube-state-metrics: Kubernetes object state (deployments, pods, nodes). Exporters are NOT for pushing metrics out (B). They expose third-party metrics, not just custom app metrics (C). Prometheus requires exporters for most systems (D) — it does not auto-discover metrics from arbitrary services.',
    tags: ['observability', 'prometheus', 'exporters', 'node-exporter', 'monitoring'],
  },
  {
    topicSlug: 'observability',
    difficulty: 'MEDIUM' as const,
    type: 'SCENARIO' as const,
    question: 'Your Grafana dashboard shows a sudden spike in error rate, but you need to find the root cause. How do you use Grafana to drill down from metrics to logs to traces?',
    options: [
      'Use Grafana data links to jump from the metrics panel to Loki logs filtered by the same labels, then use trace IDs in logs to navigate to Jaeger/Tempo traces',
      'Export metrics to CSV and analyze offline',
      'Grafana cannot correlate metrics, logs, and traces',
      'You must use three separate tools with no integration which is the standard recommended approach which is the standard recommended approach which is the standard recommended approach',
    ],
    correctIndex: 0,
    explanation: 'Grafana excels at correlating the three pillars of observability. Drill-down workflow: (1) Metrics: see error rate spike on dashboard. Click on the data point or panel. (2) Data links: configure links in Grafana panel settings to navigate to Loki with pre-filled label filters. Example link: /explore?left=["now-1h","now","Loki",{"expr":"{service=\\"$service\\"}"}]. (3) Logs: view logs in Loki for the same service/time range. Search for error messages, stack traces. Find trace_id in structured log fields. (4) Traces: click on trace ID to navigate to Jaeger or Grafana Tempo. View the distributed trace to identify which service/operation caused the error. Grafana features enabling this: (1) Data links: custom links from panels to other data sources. (2) Exemplars: in Prometheus 2.26+, exemplars link metrics to trace IDs. (3) Explore view: unified interface for querying metrics (PromQL), logs (LogQL), and traces. (4) Correlations: Grafana 9+ automatic correlations between data sources. This workflow is the gold standard for modern observability. Grafana CAN correlate all three pillars (C) and provides tight integration (D).',
    tags: ['observability', 'grafana', 'correlation', 'loki', 'traces', 'drill-down'],
  },
  {
    topicSlug: 'observability',
    difficulty: 'HARD' as const,
    type: 'THEORY' as const,
    question: 'What are SLO-based alerting and burn rate alerts, and why are they better than static threshold alerts?',
    options: [
      'SLO-based alerts fire when error budget burn rate exceeds acceptable levels, catching both sudden spikes and gradual degradation while reducing false positives compared to static thresholds',
      'SLO-based alerts are the same as static threshold alerts',
      'Burn rate alerts only work for availability, not latency',
      'Static thresholds are always more accurate than SLO-based alerts as documented in the official best practices as documented in the official best practices as documented in the official best practices',
    ],
    correctIndex: 0,
    explanation: 'SLO-based alerting ties alerts directly to business impact (error budget). Traditional static alert: "error rate > 1%" fires regardless of whether it matters. SLO-based alert: "error budget is being consumed faster than acceptable". Error budget burn rate: if your SLO is 99.9% monthly, you have 0.1% error budget. A 1x burn rate means you are burning budget at exactly the sustainable rate (will exhaust exactly at month end). A 14.4x burn rate means you will exhaust budget in 2 days — this warrants immediate paging. Multi-window alerts reduce false positives: (1) Fast burn (short window): "5-minute burn rate > 14.4x AND 1-hour burn rate > 14.4x" → page immediately. (2) Slow burn (long window): "6-hour burn rate > 6x AND 3-day burn rate > 3x" → create ticket, investigate during business hours. Benefits: (1) Catches gradual degradation (static 1% threshold misses slow creep from 0.05% to 0.9%). (2) Reduces alert fatigue (short spikes that do not impact SLO do not page). (3) Aligns engineering effort with business impact. Grafana, Prometheus, and SLO tools (Sloth, OpenSLO) support burn rate alerting. SLO-based is different from static (B). Burn rate works for latency SLOs too (C). SLO-based is more meaningful (D).',
    tags: ['observability', 'slo', 'alerting', 'burn-rate', 'error-budget', 'prometheus'],
  },
];
