export const securityQuestions = [
  // ─── EASY THEORY ───────────────────────────────────────────────────────────
  {
    topicSlug: 'security',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What is the principle of least privilege and why is it important for security?',
    options: [
      'Least privilege means granting users/services only the minimum permissions needed to perform their tasks, reducing the blast radius of security breaches',
      'Least privilege means never granting any permissions',
      'Least privilege only applies to human users, not services',
      'Least privilege is outdated and not used in modern systems',
    ],
    correctIndex: 0,
    explanation: 'The principle of least privilege (PoLP) is a foundational security concept: grant the minimum permissions necessary, nothing more. Benefits: (1) Limits blast radius: if credentials are compromised, the attacker has limited access (cannot delete databases, access other systems). (2) Reduces insider threat: employees cannot accidentally or maliciously access sensitive data outside their role. (3) Compliance: many regulations (SOC 2, HIPAA, PCI-DSS) require least privilege. (4) Audit trail: narrow permissions make it easier to track who did what. Examples: (1) IAM policies: instead of granting s3:*, grant only s3:GetObject for specific buckets. (2) Database access: app user has SELECT/INSERT/UPDATE, not DROP TABLE. (3) Kubernetes RBAC: pod can read ConfigMaps in its namespace, not cluster-wide secrets. Least privilege does NOT mean no permissions (B). It applies to all principals: users, services, roles, applications (C). Least privilege is fundamental to modern zero-trust security (D). Implementing PoLP requires careful IAM design and regular access reviews.',
    tags: ['security', 'least-privilege', 'iam', 'access-control', 'zero-trust'],
  },
  {
    topicSlug: 'security',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What is the difference between authentication and authorization?',
    options: [
      'Authentication verifies identity (who you are); authorization determines permissions (what you can do)',
      'Authentication and authorization are the same',
      'Authentication is for users; authorization is for services',
      'Authorization comes before authentication',
    ],
    correctIndex: 0,
    explanation: 'Authentication (AuthN) and authorization (AuthZ) are distinct security concepts. Authentication: verifying identity. Examples: (1) Username + password. (2) Multi-factor authentication (MFA): password + OTP. (3) OAuth/OIDC: verify identity via third-party provider (Google, GitHub). (4) Mutual TLS: verify both client and server identity via certificates. Authentication answers: "Are you who you say you are?" Authorization: determining permissions based on identity. Examples: (1) RBAC (Role-Based Access Control): admin role can delete users, viewer role cannot. (2) ABAC (Attribute-Based Access Control): users in engineering department can access prod, users in sales cannot. (3) IAM policies: verified AWS user has s3:PutObject permission. Authorization answers: "What are you allowed to do?" Flow: (1) Authenticate: user logs in with credentials. (2) Authorize: check user permissions for the requested action. They are NOT the same (B). Both apply to users and services (C). Authentication ALWAYS comes before authorization (D). Modern systems use both: OAuth for authN, JWT claims/RBAC for authZ.',
    tags: ['security', 'authentication', 'authorization', 'access-control', 'rbac'],
  },
  {
    topicSlug: 'security',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What is Multi-Factor Authentication (MFA) and why is it more secure than passwords alone?',
    options: [
      'MFA requires multiple forms of verification (password + OTP/biometric/hardware key); even if password is stolen, attacker cannot access account without second factor',
      'MFA means using two different passwords',
      'MFA is only for high-security government systems',
      'MFA makes systems less secure due to complexity',
    ],
    correctIndex: 0,
    explanation: 'Multi-Factor Authentication (MFA) requires two or more factors from different categories: (1) Something you know: password, PIN. (2) Something you have: OTP app (Google Authenticator, Authy), SMS code, hardware token (YubiKey, RSA SecurID). (3) Something you are: biometric (fingerprint, face recognition, iris scan). MFA security: if an attacker steals your password (phishing, data breach, keylogger), they still cannot log in without the second factor (OTP, hardware key). Benefits: (1) Phishing resistance: hardware keys (FIDO2/WebAuthn) are immune to phishing. (2) Credential stuffing defense: stolen passwords from other breaches are useless without MFA. (3) Compliance: PCI-DSS, SOC 2, HIPAA require MFA for privileged access. MFA is NOT two passwords (B) — factors must be from different categories. MFA is standard for all systems (C) — AWS, GitHub, Google all support MFA. MFA significantly improves security (D). Best practice: use hardware keys (YubiKey) > authenticator apps > SMS (SMS is vulnerable to SIM swapping). Enable MFA for root accounts, privileged users, and production access.',
    tags: ['security', 'mfa', 'multi-factor-authentication', 'authentication', 'phishing'],
  },
  {
    topicSlug: 'security',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What are AWS security groups and how do they differ from Network ACLs (NACLs)?',
    options: [
      'Security groups are stateful firewalls at the instance level (allow rules only); NACLs are stateless firewalls at the subnet level (allow + deny rules)',
      'Security groups and NACLs are the same',
      'Security groups are for EC2 only; NACLs are for all AWS services',
      'NACLs are more secure than security groups',
    ],
    correctIndex: 0,
    explanation: 'AWS provides two firewall mechanisms: Security Groups (SG): (1) Stateful: if you allow inbound traffic, return traffic is automatically allowed (no need for explicit outbound rule). (2) Instance-level: attached to ENIs (elastic network interfaces) of EC2, RDS, Lambda, ELB. (3) Allow rules only: you specify what traffic to allow, everything else is implicitly denied. (4) Default deny: no inbound traffic allowed by default. Network ACLs (NACLs): (1) Stateless: inbound and outbound rules are independent. If you allow inbound HTTP (port 80), you must also allow outbound ephemeral ports (1024-65535) for return traffic. (2) Subnet-level: applied to all instances in a subnet. (3) Allow + deny rules: you can explicitly deny traffic (useful for blocking specific IPs). (4) Default allow: default NACL allows all traffic. Rule evaluation: SG rules are evaluated as a whole (if any rule matches, allow); NACL rules are evaluated in order by rule number (lowest first). Best practice: use security groups for instance-level control (allow SSH from bastion, allow HTTPS from ALB); use NACLs for subnet-level defense (block known malicious IPs). They are NOT the same (B). SGs apply to multiple services (C). Neither is inherently more secure (D) — they serve different purposes.',
    tags: ['security', 'aws', 'security-groups', 'nacl', 'firewall', 'networking'],
  },
  {
    topicSlug: 'security',
    difficulty: 'EASY' as const,
    type: 'SCENARIO' as const,
    question: 'You accidentally committed AWS access keys to a public GitHub repository. What should you do immediately?',
    options: [
      'Rotate (delete and recreate) the access keys immediately in AWS IAM, review CloudTrail logs for unauthorized usage, and enable secret scanning on the repo',
      'Delete the commit from GitHub history',
      'Ignore it if no one has noticed',
      'Change the AWS account password',
    ],
    correctIndex: 0,
    explanation: 'Exposed credentials in public repos are scanned by bots within minutes and used for crypto mining, data exfiltration, or resource abuse. Immediate actions: (1) Rotate credentials: in AWS IAM, delete the exposed access key and create a new one. Update applications with the new key. (2) Check for unauthorized activity: review CloudTrail logs for API calls made with the exposed key (EC2 launches, S3 access, IAM changes). Check AWS Trusted Advisor and GuardDuty for security findings. (3) Check AWS bill: look for unexpected charges (EC2 instances in unfamiliar regions, high data transfer). (4) Enable AWS GuardDuty: monitors for credential compromise and anomalous behavior. (5) Enable secret scanning: GitHub secret scanning (free for public repos) detects and alerts on exposed secrets. (6) Educate team: use pre-commit hooks (git-secrets, detect-secrets) to prevent future leaks. Deleting the commit (B) is insufficient — the key is already in Git history and may be cached/mirrored. Ignoring it (C) is catastrophic. Changing account password (D) does not affect programmatic access keys. Exposed credentials are a top cause of AWS account compromises.',
    tags: ['security', 'aws', 'credentials', 'secrets', 'incident-response', 'github'],
  },
  {
    topicSlug: 'security',
    difficulty: 'EASY' as const,
    type: 'SCENARIO' as const,
    question: 'Your web application has user login functionality. What security best practices should you follow for password storage?',
    options: [
      'Hash passwords with a strong algorithm (bcrypt, Argon2, scrypt) with salt; never store plaintext passwords or use weak hashing (MD5, SHA1)',
      'Store passwords in plaintext in the database',
      'Encrypt passwords with AES',
      'Hashing is outdated; use SHA1',
    ],
    correctIndex: 0,
    explanation: 'Password storage is critical for protecting user accounts. Best practices: (1) Use a password hashing algorithm designed for passwords: bcrypt (industry standard, configurable work factor), Argon2 (modern, winner of Password Hashing Competition), scrypt (memory-hard, resistant to hardware attacks). (2) Automatic salting: bcrypt and Argon2 generate unique salts per password, preventing rainbow table attacks. (3) Work factor / cost: bcrypt cost factor (rounds) makes hashing slower (10-12 is standard), protecting against brute-force attacks. (4) Never store plaintext (B): if database is breached, all passwords are exposed. (5) Do NOT use fast hashes (MD5, SHA1, SHA256) — they are designed for speed, making brute-force trivial. (6) Do NOT use encryption (C): encryption is reversible (if key is stolen, all passwords are decrypted); hashing is one-way. Hashing is NOT outdated (D) — it is fundamental. Additional security: (1) Enforce strong password policies (length, complexity, no common passwords). (2) Use MFA. (3) Implement rate limiting on login endpoints (prevent brute-force). (4) Check passwords against breach databases (Have I Been Pwned API). This is a top interview question for application security.',
    tags: ['security', 'passwords', 'hashing', 'bcrypt', 'authentication', 'best-practices'],
  },
  {
    topicSlug: 'security',
    difficulty: 'EASY' as const,
    type: 'SCENARIO' as const,
    question: 'You need to grant an EC2 instance access to an S3 bucket. What is the most secure method?',
    options: [
      'Attach an IAM role to the EC2 instance via an instance profile, granting only the necessary S3 permissions',
      'Hardcode AWS access keys in the application code',
      'Store access keys in the EC2 user data',
      'Use the root account credentials',
    ],
    correctIndex: 0,
    explanation: 'EC2 instances should use IAM roles, not hardcoded credentials. Implementation: (1) Create IAM role with S3 permissions (e.g., s3:GetObject, s3:PutObject for specific buckets). (2) Attach role to EC2 instance via instance profile. (3) Application code uses AWS SDK to access S3 — SDK automatically retrieves temporary credentials from instance metadata service (IMDS) at http://169.254.169.254. (4) Credentials rotate automatically every few hours (no manual rotation needed). Benefits: (1) No long-lived credentials (access keys cannot be stolen from code/config). (2) Automatic rotation (temporary credentials expire and refresh). (3) Least privilege (grant only necessary permissions). (4) Audit trail (CloudTrail logs show which role performed actions). Hardcoding keys (B) is a critical security vulnerability — keys can be leaked in logs, committed to Git, or stolen from memory. Storing keys in user data (C) is equally insecure — user data is readable by anyone with DescribeInstanceAttribute permission. Using root credentials (D) violates least privilege and is forbidden. IAM roles are the gold standard for AWS service-to-service authentication.',
    tags: ['security', 'aws', 'iam-roles', 'ec2', 's3', 'least-privilege', 'credentials'],
  },

  // ─── MEDIUM THEORY ─────────────────────────────────────────────────────────
  {
    topicSlug: 'security',
    difficulty: 'MEDIUM' as const,
    type: 'THEORY' as const,
    question: 'What is zero-trust security and how does it differ from traditional perimeter-based security?',
    options: [
      'Zero-trust assumes no user or device is trusted by default, even inside the network; verify identity and enforce least privilege for every request',
      'Zero-trust means trusting no one and blocking all traffic',
      'Zero-trust is only for on-premises networks',
      'Zero-trust is the same as using a firewall',
    ],
    correctIndex: 0,
    explanation: 'Traditional perimeter security (castle-and-moat): trust everything inside the network, distrust everything outside. Once an attacker breaches the perimeter (phishing, VPN compromise), they have broad access. Zero-trust security: never trust, always verify. Principles: (1) Verify explicitly: authenticate and authorize every request (user, device, location, context). (2) Least privilege access: grant minimum necessary permissions, time-bound access. (3) Assume breach: segment networks, limit lateral movement, monitor continuously. Implementation: (1) Identity-based access: users/services authenticated via SSO (Okta, Azure AD) with MFA. (2) Micro-segmentation: use network policies (AWS Security Groups, Kubernetes NetworkPolicies) to isolate workloads. (3) Device trust: enforce device compliance (corporate-managed, patched, encrypted). (4) Contextual access: allow access based on user location, device health, time of day (IP allowlists, conditional access policies). Zero-trust does NOT block all traffic (B) — it verifies and allows legitimate access. Zero-trust applies to cloud and on-prem (C). Firewalls are perimeter-based, not zero-trust (D). Modern frameworks: Google BeyondCorp, AWS Zero Trust, NIST 800-207.',
    tags: ['security', 'zero-trust', 'identity', 'least-privilege', 'network-segmentation'],
  },
  {
    topicSlug: 'security',
    difficulty: 'MEDIUM' as const,
    type: 'THEORY' as const,
    question: 'What are SAST, DAST, and SCA in application security, and when should each be used?',
    options: [
      'SAST: static code analysis (pre-deployment); DAST: runtime security testing (post-deployment); SCA: dependency vulnerability scanning',
      'SAST, DAST, and SCA are the same thing',
      'SAST is for frontend; DAST is for backend',
      'Security scanning is only needed for production',
    ],
    correctIndex: 0,
    explanation: 'Application security testing types: SAST (Static Application Security Testing): analyzes source code, bytecode, or binaries without executing the program. Detects: SQL injection, XSS, hardcoded secrets, insecure crypto, buffer overflows. Tools: SonarQube, Checkmarx, Semgrep, CodeQL. When: during development and CI/CD (before deployment). Pros: fast, finds issues early. Cons: false positives, cannot detect runtime issues. DAST (Dynamic Application Security Testing): tests running applications by simulating attacks (black-box testing). Detects: auth bypasses, API vulnerabilities, misconfigured CORS, injection attacks. Tools: OWASP ZAP, Burp Suite, Acunetix. When: against deployed test/staging environments. Pros: fewer false positives, detects runtime issues. Cons: slower, requires deployed app. SCA (Software Composition Analysis): scans dependencies (npm packages, Maven jars, Docker base images) for known vulnerabilities (CVEs). Tools: Snyk, Dependabot, Trivy, WhiteSource. When: during build and continuously (new CVEs are published daily). Pros: protects against supply chain attacks. Cons: relies on public CVE databases. Best practice: use all three (defense in depth). They are NOT the same (B). They apply to all layers (C). Security scanning is needed throughout SDLC (D).',
    tags: ['security', 'sast', 'dast', 'sca', 'vulnerability-scanning', 'devsecops'],
  },
  {
    topicSlug: 'security',
    difficulty: 'MEDIUM' as const,
    type: 'THEORY' as const,
    question: 'What is the OWASP Top 10 and why is it important?',
    options: [
      'OWASP Top 10 is a list of the most critical web application security risks (injection, broken auth, XSS, etc.); it guides developers and security teams on priorities',
      'OWASP Top 10 is a list of security tools',
      'OWASP Top 10 is only relevant for startups',
      'OWASP Top 10 is outdated',
    ],
    correctIndex: 0,
    explanation: 'OWASP (Open Web Application Security Project) Top 10 is a standard awareness document representing the most critical web security risks. Updated periodically (latest: 2021). Top 10 (2021): (1) Broken Access Control: missing authorization checks, allowing users to access unauthorized resources. (2) Cryptographic Failures: weak encryption, plaintext data transmission, exposed secrets. (3) Injection: SQL injection, command injection, LDAP injection. (4) Insecure Design: flawed architecture, missing security requirements in design phase. (5) Security Misconfiguration: default passwords, exposed admin interfaces, verbose error messages. (6) Vulnerable and Outdated Components: using dependencies with known CVEs. (7) Identification and Authentication Failures: weak passwords, no MFA, session fixation. (8) Software and Data Integrity Failures: unsigned updates, insecure deserialization, CI/CD compromise. (9) Security Logging and Monitoring Failures: insufficient logging, not detecting breaches. (10) Server-Side Request Forgery (SSRF): attacker tricks server into making requests to internal resources. Importance: provides a framework for secure development, testing, and audits. OWASP is NOT tools (B). It applies to all organizations (C). It is regularly updated (D). Every developer and DevOps engineer should know OWASP Top 10.',
    tags: ['security', 'owasp', 'web-security', 'vulnerabilities', 'application-security'],
  },
  {
    topicSlug: 'security',
    difficulty: 'MEDIUM' as const,
    type: 'THEORY' as const,
    question: 'What is secrets management and why should secrets not be hardcoded in code or config files?',
    options: [
      'Secrets management centralizes storage of sensitive data (passwords, API keys) with encryption, access control, and rotation; hardcoding exposes secrets in version control and logs',
      'Secrets management is only for large enterprises',
      'Hardcoding secrets is acceptable if the repo is private',
      'Secrets management is too complex and not worth it',
    ],
    correctIndex: 0,
    explanation: 'Secrets (passwords, API keys, certificates, tokens) should never be hardcoded in code or committed to Git. Risks: (1) Git history: even if you delete the secret later, it remains in Git history forever. (2) Accidental exposure: private repos can become public, developers can fork repos, CI logs may expose secrets. (3) No rotation: hardcoded secrets are rarely rotated, increasing compromise risk. (4) No audit trail: cannot track who accessed secrets. Secrets management solutions: (1) AWS Secrets Manager: encrypted storage, automatic rotation, IAM access control, audit logging. (2) HashiCorp Vault: centralized secret storage, dynamic credentials (short-lived tokens), encryption as a service. (3) Azure Key Vault, GCP Secret Manager: cloud-native secret storage. (4) Kubernetes Secrets: base64-encoded (not encrypted by default — use encryption at rest). Best practices: (1) Store secrets in a secret manager. (2) Fetch secrets at runtime (via SDK or environment variables injected by platform). (3) Use short-lived credentials (IAM roles, OAuth tokens). (4) Rotate secrets regularly (automated rotation). Secrets management is critical for all organizations (B). Private repos are NOT safe (C). Secrets management is essential (D).',
    tags: ['security', 'secrets-management', 'aws-secrets-manager', 'vault', 'credentials'],
  },
  {
    topicSlug: 'security',
    difficulty: 'MEDIUM' as const,
    type: 'SCENARIO' as const,
    question: 'Your application is vulnerable to SQL injection. An attacker can input "admin' OR '1'='1" to bypass authentication. How do you fix this?',
    options: [
      'Use parameterized queries (prepared statements) or ORM frameworks that automatically escape user input; never concatenate user input directly into SQL',
      'Add input validation to block single quotes',
      'Use stored procedures',
      'SQL injection cannot be fixed',
    ],
    correctIndex: 0,
    explanation: 'SQL injection occurs when user input is concatenated directly into SQL queries. Example: query = "SELECT * FROM users WHERE username = '" + userInput + "'"; If userInput = "admin' OR '1'='1", the query becomes SELECT * FROM users WHERE username = 'admin' OR '1'='1', returning all users. Fix: use parameterized queries (prepared statements). Parameterized query: query = "SELECT * FROM users WHERE username = ?"; execute(query, [userInput]). The database driver automatically escapes userInput, treating it as a literal string (not executable code). ORMs (Sequelize, TypeORM, Prisma, SQLAlchemy) use parameterized queries by default. Input validation (B) is insufficient — blacklists (', ", ;, --) can be bypassed (encoding, Unicode). Stored procedures (C) help but are not a complete solution (they can still be vulnerable if they concatenate input). SQL injection CAN be fixed (D) with proper coding practices. Additional defenses: (1) Least privilege: app database user should not have DROP, ALTER permissions. (2) WAF (Web Application Firewall): block common SQL injection patterns. (3) Security scanning: use SAST/DAST to detect injection vulnerabilities. SQL injection is #3 in OWASP Top 10 and a top interview topic.',
    tags: ['security', 'sql-injection', 'owasp', 'parameterized-queries', 'web-security'],
  },
  {
    topicSlug: 'security',
    difficulty: 'MEDIUM' as const,
    type: 'SCENARIO' as const,
    question: 'Your Docker images are being scanned for vulnerabilities. A critical CVE is found in a base image layer. What should you do?',
    options: [
      'Update the base image to a patched version, rebuild the image, rescan to verify the fix, and deploy the new image',
      'Ignore the CVE if the application is not using the vulnerable component',
      'Wait for the CVE to be auto-fixed',
      'Vulnerability scanning is unnecessary',
    ],
    correctIndex: 0,
    explanation: 'Container image vulnerabilities are common because images include OS packages and libraries. Remediation process: (1) Identify vulnerability: scanning tools (Trivy, Snyk, Aqua, AWS ECR scanning, Docker Scout) report CVE, affected package, and severity. (2) Assess risk: is the vulnerability exploitable in your context? Tools like VEX (Vulnerability Exploitability eXchange) help determine if the vulnerable code path is reachable. (3) Update base image: change FROM debian:10 to FROM debian:11 or FROM alpine:3.18 to FROM alpine:3.19. (4) Rebuild image: docker build -t myapp:v2 . (5) Rescan: verify CVE is resolved. (6) Deploy: push to registry, update Kubernetes Deployment or ECS task definition. (7) Monitor: continuously scan images (new CVEs are published daily). Ignoring CVEs (B) is risky — even if you think the vulnerable code is unused, attackers may find creative ways to exploit it. CVEs are NOT auto-fixed (C) — you must rebuild images. Vulnerability scanning is critical (D) for supply chain security and compliance (SOC 2, PCI-DSS require it). Automate scanning in CI/CD and block deployments of images with critical vulnerabilities.',
    tags: ['security', 'docker', 'vulnerabilities', 'cve', 'container-scanning', 'trivy'],
  },
  {
    topicSlug: 'security',
    difficulty: 'MEDIUM' as const,
    type: 'SCENARIO' as const,
    question: 'Your Kubernetes cluster allows pods to access the Kubernetes API with default ServiceAccount. What is the security risk and how do you mitigate it?',
    options: [
      'Pods can query/modify cluster resources (list secrets, create pods); mitigate by disabling automountServiceAccountToken, using RBAC to restrict permissions, or using dedicated ServiceAccounts',
      'There is no security risk',
      'All pods need cluster-admin access',
      'ServiceAccounts cannot be restricted',
    ],
    correctIndex: 0,
    explanation: 'By default, every Kubernetes pod has a ServiceAccount token mounted at /var/run/secrets/kubernetes.io/serviceaccount/token, allowing it to authenticate to the Kubernetes API. Risk: if a pod is compromised (RCE vulnerability, container escape), the attacker can use the ServiceAccount token to interact with the API. Default ServiceAccount has limited permissions but can still list resources in its namespace. Worse: if RBAC is misconfigured, the ServiceAccount may have elevated permissions (list secrets, create pods for privilege escalation). Mitigation: (1) Disable auto-mounting: set automountServiceAccountToken: false in pod spec or ServiceAccount (opt-in only for pods that need API access). (2) Use dedicated ServiceAccounts: create specific ServiceAccounts per application with RBAC policies granting only necessary permissions. (3) Restrict permissions: use Roles/RoleBindings to enforce least privilege (e.g., allow reading ConfigMaps but not Secrets). (4) Admission controllers: use OPA Gatekeeper or Kyverno to enforce policies (block pods without explicit ServiceAccount, block privilege escalation). There IS a risk (B). Pods should NOT have cluster-admin (C). ServiceAccounts CAN be restricted via RBAC (D). This is a common Kubernetes security misconfiguration.',
    tags: ['security', 'kubernetes', 'serviceaccount', 'rbac', 'least-privilege', 'api-access'],
  },

  // ─── HARD THEORY ───────────────────────────────────────────────────────────
  {
    topicSlug: 'security',
    difficulty: 'HARD' as const,
    type: 'THEORY' as const,
    question: 'What is a side-channel attack and how does it differ from traditional exploits?',
    options: [
      'Side-channel attacks exploit information leaked through physical implementation (timing, power consumption, electromagnetic radiation) rather than logical vulnerabilities',
      'Side-channel attacks are network-based attacks',
      'Side-channel attacks only target hardware',
      'Side-channel attacks are theoretical and not exploited in practice',
    ],
    correctIndex: 0,
    explanation: 'Side-channel attacks exploit physical characteristics of system implementation rather than algorithmic weaknesses. Types: (1) Timing attacks: measure execution time to infer secrets. Example: password comparison using strcmp() — if it fails fast on the first character, attacker knows the first character is wrong; if it takes longer, the first character is correct. (2) Cache timing attacks: measure CPU cache behavior to infer memory access patterns. Examples: Spectre, Meltdown (exploit speculative execution to leak kernel memory). (3) Power analysis: measure power consumption during cryptographic operations to extract keys. (4) Electromagnetic emissions: measure EM radiation to infer computations. (5) Acoustic cryptanalysis: extract keys from sounds (RSA key extraction from laptop fan noise). Defenses: (1) Constant-time algorithms: ensure execution time is independent of input (critical for crypto). (2) Blinding: add random noise to computations. (3) Hardware defenses: CPU mitigations (Spectre/Meltdown patches), secure enclaves (Intel SGX). Side-channel attacks are NOT network-based (B). They target software and hardware (C). They are actively exploited (D) — Spectre/Meltdown affected billions of CPUs. Side-channel security is critical for cryptographic implementations.',
    tags: ['security', 'side-channel', 'timing-attack', 'spectre', 'meltdown', 'cryptography'],
  },
  {
    topicSlug: 'security',
    difficulty: 'HARD' as const,
    type: 'THEORY' as const,
    question: 'What is certificate pinning and when should it be used?',
    options: [
      'Certificate pinning hardcodes expected SSL/TLS certificate (or public key) in the application, preventing man-in-the-middle attacks even if attacker has a valid CA-signed certificate',
      'Certificate pinning is a method to create self-signed certificates',
      'Certificate pinning is deprecated',
      'Certificate pinning is only for mobile apps',
    ],
    correctIndex: 0,
    explanation: 'Certificate pinning strengthens TLS/SSL security by pinning (hardcoding) the expected certificate or public key in the application. Normal TLS: client trusts any certificate signed by a trusted CA (100+ CAs in most trust stores). Risk: if a CA is compromised or issues a fraudulent certificate, attacker can perform MITM. Certificate pinning: application is hardcoded to accept only specific certificate(s). Types: (1) Certificate pinning: pin the exact certificate (must update app when certificate rotates). (2) Public key pinning: pin the public key (survives certificate rotation if key is reused). (3) CA pinning: pin the issuing CA (less strict than key pinning). Use cases: (1) Mobile apps communicating with backend API (prevent MITM on compromised networks). (2) High-security applications (banking, healthcare). (3) Protecting against rogue CAs. Risks: (1) Certificate rotation requires app update (operational overhead). (2) Emergency revocation is complex (if pinned cert is compromised, app cannot connect until updated). Best practice: pin multiple certificates (current + backup) and have an emergency pin update mechanism. Pinning is NOT for creating certificates (B). It is NOT deprecated (C). It applies to all applications (D), though most common in mobile. HTTP Public Key Pinning (HPKP) was deprecated for web browsers but still used in apps.',
    tags: ['security', 'certificate-pinning', 'tls', 'ssl', 'mitm', 'mobile-security'],
  },
  {
    topicSlug: 'security',
    difficulty: 'HARD' as const,
    type: 'THEORY' as const,
    question: 'What is a supply chain attack and how can organizations defend against it?',
    options: [
      'Supply chain attacks compromise software dependencies (npm packages, Docker images, build tools) to inject malicious code; defend with SCA, code signing, SBOMs, and vendor security reviews',
      'Supply chain attacks only target physical goods',
      'Supply chain attacks cannot be prevented',
      'Supply chain attacks are not relevant to software',
    ],
    correctIndex: 0,
    explanation: 'Supply chain attacks target the software supply chain (dependencies, build tools, infrastructure) to inject malicious code that propagates to downstream users. Examples: (1) SolarWinds (2020): attackers compromised build system, injecting backdoor into Orion software, affecting 18,000+ customers including US government agencies. (2) npm package attacks: attackers publish malicious packages or compromise existing popular packages (eslint-scope, event-stream). (3) Codecov (2021): attackers modified Codecov bash uploader script, stealing credentials from CI environments. (4) Dependency confusion: attackers publish malicious packages with internal package names to public registries, exploiting misconfigured dependency resolution. Defenses: (1) Software Composition Analysis (SCA): scan dependencies for known vulnerabilities (Snyk, Dependabot). (2) Code signing: verify signatures of packages, Docker images, binaries (Docker Content Trust, GPG signing). (3) SBOM (Software Bill of Materials): maintain inventory of all components, enabling rapid response to newly disclosed vulnerabilities. (4) Dependency pinning: lock dependency versions (package-lock.json, Pipfile.lock) to prevent automatic upgrades. (5) Private registries: mirror dependencies in private registry with security scanning. Supply chain attacks target software (D). They CAN be mitigated (C) with layered defenses. This is a top security concern in 2024+.',
    tags: ['security', 'supply-chain', 'dependencies', 'sbom', 'code-signing', 'sca'],
  },
  {
    topicSlug: 'security',
    difficulty: 'HARD' as const,
    type: 'THEORY' as const,
    question: 'What is privilege escalation and how can it be exploited in cloud environments?',
    options: [
      'Privilege escalation is gaining higher permissions than intended; in cloud, attackers exploit misconfigurations (overly permissive IAM policies, assume-role chains) to access admin privileges',
      'Privilege escalation only affects on-premises systems',
      'Privilege escalation is a hardware vulnerability',
      'Privilege escalation cannot occur in cloud environments',
    ],
    correctIndex: 0,
    explanation: 'Privilege escalation is when an attacker gains permissions beyond what they should have. Vertical escalation: user gains admin/root. Horizontal escalation: user accesses another user\'s resources. Cloud privilege escalation techniques: (1) IAM policy misconfiguration: user has iam:PutUserPolicy (can grant themselves admin permissions). (2) Assume-role chains: user can assume Role A, Role A can assume Role B (admin role). (3) Lambda/EC2 role hijacking: compromise a service with attached IAM role, use role credentials to escalate. (4) Metadata service exploitation: SSRF vulnerability allows attacker to query IMDS and steal instance IAM credentials. (5) Kubernetes RBAC bypass: compromised pod uses overly permissive ServiceAccount to create privileged pods or access secrets. (6) Pass-role vulnerability: user has iam:PassRole for admin role, creates Lambda function with that role, executes code as admin. Defenses: (1) Least privilege IAM policies. (2) Permission boundaries (limit maximum permissions). (3) SCPs (Service Control Policies) to restrict actions at organization level. (4) IAM Access Analyzer to detect overly permissive policies. (5) Continuous monitoring (CloudTrail, GuardDuty). Privilege escalation is critical in cloud (D). It is a configuration issue (C).',
    tags: ['security', 'privilege-escalation', 'iam', 'cloud-security', 'aws', 'kubernetes'],
  },
  {
    topicSlug: 'security',
    difficulty: 'HARD' as const,
    type: 'SCENARIO' as const,
    question: 'Your AWS account is compromised. An attacker created IAM users, launched EC2 instances for crypto mining, and accessed S3 buckets. What is your incident response plan?',
    options: [
      'Contain: rotate credentials, delete attacker-created resources, revoke sessions; Investigate: review CloudTrail logs; Recover: restore from backups; Postmortem: identify root cause and implement preventive controls',
      'Delete the AWS account',
      'Ignore it if the bill is not too high',
      'Change the root password only',
    ],
    correctIndex: 0,
    explanation: 'AWS account compromise incident response (based on AWS Security Incident Response Guide): Phase 1 - Contain: (1) Rotate compromised credentials (access keys, passwords). (2) Delete attacker-created resources (IAM users, roles, EC2 instances, S3 buckets). Use AWS CLI to list resources created within the attack window. (3) Revoke active sessions (AWS STS sessions, IAM user sessions). (4) Apply restrictive SCPs temporarily to limit blast radius. (5) Enable MFA on root account and privileged users. Phase 2 - Investigate: (1) Review CloudTrail logs: identify initial access vector (stolen access key, compromised IAM user). (2) Analyze AWS Config history to see resource changes. (3) Check AWS GuardDuty findings for anomalies. (4) Review IAM Access Analyzer for overly permissive policies. (5) Check billing for unauthorized charges. Phase 3 - Recover: (1) Restore deleted S3 objects from versioning or backups. (2) Relaunch terminated EC2 instances from AMIs. Phase 4 - Postmortem: (1) Root cause: how did attacker gain access? (exposed access key, phishing, weak password). (2) Preventive controls: enable GuardDuty, CloudTrail, AWS Config, SCPs, MFA enforcement, secret scanning. Deleting the account (B) is extreme. Ignoring it (C) is negligent. Root password alone (D) does not address programmatic access.',
    tags: ['security', 'aws', 'incident-response', 'compromise', 'cloudtrail', 'containment'],
  },
  {
    topicSlug: 'security',
    difficulty: 'HARD' as const,
    type: 'SCENARIO' as const,
    question: 'Your Kubernetes cluster is running workloads with privileged containers and hostNetwork enabled. What are the security risks?',
    options: [
      'Privileged containers have root access to the host, can escape to the node, and access all node resources; hostNetwork allows sniffing network traffic; mitigate with PodSecurityStandards and admission controllers',
      'Privileged containers are more secure',
      'There are no risks',
      'Kubernetes prevents privilege escalation automatically',
    ],
    correctIndex: 0,
    explanation: 'Privileged containers are a major security risk. Risks: (1) Container escape: privileged containers run as root on the host, can mount host filesystem, load kernel modules, and escape containment. (2) Host access: can read/write host files (/etc/passwd, /etc/shadow), access other containers' filesystems. (3) Kernel exploits: can exploit kernel vulnerabilities to compromise the entire node. (4) hostNetwork: pod shares the host network namespace, can bind to privileged ports (< 1024), sniff network traffic, and impersonate other pods. Use cases for privileged containers: monitoring agents (Datadog, New Relic), CNI plugins (Cilium, Calico), DaemonSets that need host access (log collectors). Mitigation: (1) PodSecurityStandards: enforce baseline/restricted policies (block privileged containers, hostNetwork, hostPath, host PID/IPC). (2) Admission controllers: use OPA Gatekeeper or Kyverno to block privileged pods. (3) Seccomp/AppArmor: limit system calls allowed by containers. (4) RuntimeClass: use gVisor or Kata Containers for stronger isolation. (5) Audit: regularly audit privileged workloads and justify their necessity. Privileged containers are NOT more secure (B). There ARE risks (C). Kubernetes does NOT prevent this automatically (D) — you must configure policies.',
    tags: ['security', 'kubernetes', 'privileged-containers', 'container-escape', 'podsecurity', 'rbac'],
  },
  {
    topicSlug: 'security',
    difficulty: 'HARD' as const,
    type: 'SCENARIO' as const,
    question: 'Your application uses OAuth 2.0 for authentication. An attacker intercepts the authorization code and exchanges it for an access token. How do you prevent this?',
    options: [
      'Use PKCE (Proof Key for Code Exchange) to bind the authorization code to the client; the attacker cannot exchange the code without the code verifier',
      'OAuth cannot be secured',
      'Use longer authorization codes',
      'Disable OAuth',
    ],
    correctIndex: 0,
    explanation: 'This describes an authorization code interception attack. OAuth 2.0 flow (without PKCE): (1) Client redirects user to authorization server. (2) User authorizes, authorization server redirects to client with authorization code. (3) Client exchanges code for access token. Vulnerability: if attacker intercepts the redirect (malicious app on mobile, compromised network), they can steal the authorization code and exchange it for an access token (code is valid for 60 seconds). PKCE (RFC 7636) prevents this: (1) Client generates code_verifier (random string) and code_challenge (SHA256 hash of verifier). (2) Client sends code_challenge in authorization request. (3) Authorization server stores code_challenge with the authorization code. (4) Client exchanges authorization code + code_verifier for access token. (5) Authorization server verifies SHA256(code_verifier) == code_challenge. (6) If attacker steals authorization code but not code_verifier, they cannot exchange it. PKCE is mandatory for public clients (mobile apps, SPAs) and recommended for all clients. OAuth CAN be secured (B) with PKCE. Longer codes do not help (C) — the code itself is stolen. Disabling OAuth (D) is impractical. This tests deep understanding of OAuth security (RFC 6749 + 7636).',
    tags: ['security', 'oauth', 'pkce', 'authentication', 'authorization', 'mobile-security'],
  },
  {
    topicSlug: 'security',
    difficulty: 'HARD' as const,
    type: 'SCENARIO' as const,
    question: 'You need to implement encryption at rest for sensitive data in your database. What AWS service should you use and what are the trade-offs?',
    options: [
      'Use AWS KMS (Key Management Service) with customer-managed keys (CMK) for encryption; trade-off: additional latency for decryption, cost per API call, and key rotation complexity',
      'Store encryption keys in the database',
      'Encryption at rest is not necessary',
      'Use hardcoded encryption keys',
    ],
    correctIndex: 0,
    explanation: 'Encryption at rest protects data if storage media is stolen or accessed without authorization. AWS options: (1) AWS-managed keys (default): AWS manages encryption keys transparently (RDS, S3, EBS). Easy but less control. (2) Customer-managed keys (CMK) via AWS KMS: you control key lifecycle (rotation, deletion, access policies). Provides audit trail (CloudTrail logs key usage). Encryption process: (1) Application requests data encryption. (2) Database/service calls KMS to generate data encryption key (DEK). (3) KMS returns plaintext DEK + encrypted DEK. (4) Service encrypts data with plaintext DEK, stores encrypted DEK alongside data, discards plaintext DEK. (5) Decryption: service calls KMS to decrypt DEK, uses it to decrypt data. Trade-offs: (1) Latency: KMS API calls add 5-20ms latency. Mitigate with caching (data key caching). (2) Cost: $1/month per CMK + $0.03 per 10,000 API requests. (3) Complexity: key rotation, access policies, disaster recovery (backing up keys). (4) Compliance: many regulations require customer-managed keys (HIPAA, PCI-DSS). Storing keys in the database (B) defeats the purpose (if DB is compromised, keys are too). Encryption is critical for compliance (C). Hardcoded keys (D) are insecure.',
    tags: ['security', 'encryption', 'kms', 'aws', 'encryption-at-rest', 'data-protection'],
  },
];
