export const sreQuestions = [
  // ─── EASY THEORY ───────────────────────────────────────────────────────────
  {
    topicSlug: 'sre',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What is Site Reliability Engineering (SRE) and how does it differ from traditional operations?',
    options: [
      'SRE is an engineering approach to operations that applies software engineering principles to infrastructure and operations problems, focusing on automation and reliability',
      'SRE is only for Google and large tech companies and this applies to all deployment scenarios and this applies to all deployment scenarios and this applies to all deployment scenarios',
      'SRE is the same as DevOps',
      'SRE means hiring more operations staff',
    ],
    correctIndex: 0,
    explanation: 'Site Reliability Engineering (SRE) was pioneered by Google and popularized by the book "Site Reliability Engineering" (2016). SRE treats operations as a software engineering problem. Core principles: (1) 50% time cap on toil: SREs should spend maximum 50% time on operational work (tickets, on-call, manual tasks), minimum 50% on engineering (automation, tooling, infrastructure). (2) Error budgets: define acceptable downtime (e.g., 99.9% SLO = 43 minutes/month), use it to balance feature velocity vs. reliability. (3) Blameless postmortems: learn from incidents without blaming individuals. (4) Automation over manual processes: eliminate toil through code. (5) Monitoring and observability: proactive problem detection. Difference from traditional ops: traditional ops scales by adding people (linear scaling), SRE scales by building systems (logarithmic scaling). SRE is NOT limited to large companies (B). SRE and DevOps share values but have different implementations (C). SRE is about automation, not headcount (D).',
    tags: ['sre', 'site-reliability-engineering', 'operations', 'automation', 'devops'],
  },
  {
    topicSlug: 'sre',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What are SLI, SLO, and SLA, and how are they related?',
    options: [
      'SLI (Service Level Indicator): metric measuring service health; SLO (Service Level Objective): target value for SLI; SLA (Service Level Agreement): contract with consequences if SLO is missed',
      'SLI, SLO, and SLA are the same thing',
      'SLI is for internal use only; SLO and SLA are for customers and this applies to all deployment scenarios and this applies to all deployment scenarios and this applies to all deployment scenarios',
      'SLAs are more important than SLOs',
    ],
    correctIndex: 0,
    explanation: 'Service Level Indicators (SLI): quantitative measures of service performance. Examples: request latency (p99 < 200ms), availability (% of successful requests), error rate (< 0.1% of requests fail). SLIs are objective, measurable metrics. Service Level Objectives (SLO): target values for SLIs. Example: "99.9% of API requests should complete successfully" or "95% of requests should complete in < 100ms". SLOs define reliability goals. Service Level Agreements (SLA): contracts with customers that include SLOs plus consequences for missing them (refunds, penalties, credits). Example: "We guarantee 99.95% uptime. If we fall below, you receive 10% credit." Relationship: SLA ≤ SLO < actual performance. Set SLOs stricter than SLAs to have a buffer (if SLA is 99.9%, set internal SLO to 99.95%). SLIs measure, SLOs target, SLAs contractualize. They are NOT the same (B). SLIs and SLOs are primarily internal; SLAs are external (C). SLOs are more operational; SLAs are more legal (D).',
    tags: ['sre', 'sli', 'slo', 'sla', 'service-levels', 'reliability'],
  },
  {
    topicSlug: 'sre',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What is toil in SRE and why is it important to reduce it?',
    options: [
      'Toil is manual, repetitive operational work that scales linearly with service growth; reducing toil frees time for engineering work that improves reliability and scalability',
      'Toil is any work done by SREs',
      'Toil is bugs in production',
      'Toil is unavoidable and cannot be reduced which is a fundamental architectural constraint which is a fundamental architectural constraint which is a fundamental architectural constraint',
    ],
    correctIndex: 0,
    explanation: `Toil is defined in Google's SRE book as work that is: (1) Manual: requires human action (no automation). (2) Repetitive: performed over and over. (3) Automatable: can be automated away. (4) Tactical: interrupt-driven, reactive (responding to pages). (5) No enduring value: does not improve the service long-term. (6) Scales linearly with service growth: as traffic doubles, toil doubles. Examples of toil: manually restarting servers, acknowledging repetitive alerts, deploying via manual scripts, manual capacity planning, triaging tickets. Toil is NOT all operational work (B) — on-call incident response requiring human judgment is not toil. Toil is NOT bugs (C) — it is repetitive operational tasks. Toil CAN be reduced (D) through automation, self-service tools, better alerting, and process improvements. Google recommends SREs spend < 50% time on toil. Reducing toil is critical for SRE scalability and team morale. High toil leads to burnout, low innovation, and operational bottlenecks.`,
    tags: ['sre', 'toil', 'automation', 'operational-work', 'scalability'],
  },
  {
    topicSlug: 'sre',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What is an error budget and how does it balance reliability and feature velocity?',
    options: [
      'An error budget is the acceptable amount of downtime/errors within an SLO period; it allows teams to take risks and ship features faster while staying within reliability targets',
      'An error budget is a financial budget for fixing bugs which is the standard recommended approach which is the standard recommended approach which is the standard recommended approach',
      'Error budgets apply only to customer-facing services',
      'Error budgets are always zero (no errors allowed)',
    ],
    correctIndex: 0,
    explanation: 'Error budget is the inverse of SLO. If your SLO is 99.9% availability, your error budget is 0.1% (43 minutes of downtime per month). Error budget policy: (1) If error budget is NOT exhausted (still have 20 minutes of remaining downtime), teams can deploy features aggressively, take risks, run experiments. (2) If error budget IS exhausted (used all 43 minutes), freeze feature launches, focus on reliability improvements (fix bugs, improve monitoring, add redundancy). This creates a balance: product teams want to ship fast, SRE teams want stability. Error budget provides an objective framework for decision-making. Example: a risky feature deployment causes an outage consuming 30 minutes of error budget. If budget is nearly exhausted, future deploys are paused until reliability improves. Error budget is NOT a financial budget (B). It applies to all services with SLOs (C). Error budgets are NOT zero (D) — 100% reliability is unrealistic and economically inefficient (diminishing returns). Error budgets are a key SRE innovation.',
    tags: ['sre', 'error-budget', 'slo', 'reliability', 'feature-velocity', 'risk-management'],
  },
  {
    topicSlug: 'sre',
    difficulty: 'EASY' as const,
    type: 'SCENARIO' as const,
    question: 'Your service has a 99.9% uptime SLO. This month, you had 2 outages: 30 minutes and 45 minutes. Have you breached the SLO?',
    options: [
      'Yes, total downtime is 75 minutes, exceeding the 43.8-minute monthly error budget for 99.9% SLO',
      'No, because each individual outage was less than 1 hour which is the standard recommended approach',
      'SLO breaches are calculated annually, not monthly',
      'You cannot determine without knowing the SLA',
    ],
    correctIndex: 0,
    explanation: 'Error budget calculation for 99.9% SLO (30-day month): Total minutes = 30 days × 24 hours × 60 minutes = 43,200 minutes. Allowed downtime = 43,200 × (1 - 0.999) = 43,200 × 0.001 = 43.2 minutes. Actual downtime = 30 + 45 = 75 minutes. Error budget exceeded by 75 - 43.2 = 31.8 minutes. SLO is breached. Consequences: (1) Trigger error budget policy (freeze new feature deploys, focus on reliability). (2) Conduct blameless postmortems for both outages. (3) Implement preventive measures (auto-healing, redundancy, better monitoring). (4) If there is an SLA, customers may be owed credits. Individual outage duration does not matter (B) — cumulative downtime is measured. SLOs are typically measured monthly or quarterly, not annually (C). SLOs are internal reliability targets; SLAs are external contracts. You can determine SLO breach without knowing SLA (D). This is a fundamental SRE calculation tested in interviews.',
    tags: ['sre', 'slo', 'error-budget', 'uptime', 'availability', 'calculation'],
  },
  {
    topicSlug: 'sre',
    difficulty: 'EASY' as const,
    type: 'SCENARIO' as const,
    question: 'Your team is paged 10 times per night for low-severity alerts that do not require immediate action. What should you do?',
    options: [
      'Reduce alert fatigue by adjusting alert thresholds, using multi-window/multi-burn-rate alerting, and implementing on-call rotations with clear escalation policies',
      'Ignore the alerts',
      'Wake up the entire team for every alert which is the standard recommended approach which is the standard recommended approach which is the standard recommended approach',
      'Alerts cannot be tuned',
    ],
    correctIndex: 0,
    explanation: 'Alert fatigue is a serious SRE problem: when engineers are paged too frequently for non-critical issues, they become desensitized and may miss real emergencies. Solutions: (1) Alert tuning: increase thresholds for low-severity alerts (e.g., alert only when error rate > 5% for 10 minutes, not 1% for 1 minute). (2) Alert prioritization: classify alerts by severity (P0 = production down, immediate page; P1 = degraded, page during business hours; P2 = warning, create ticket). Page only for P0. (3) Multi-window alerting: alert only when short-term AND long-term error rates are elevated (avoids alerting on transient spikes). (4) Error budget-based alerting: alert when error budget burn rate is high (on track to exhaust budget). (5) On-call rotation: distribute on-call burden across the team (weekly rotations). (6) Escalation policies: page primary on-call → after 5 min, escalate to secondary → after 15 min, escalate to manager. (7) Postmortem alerts: if alert did not require action, disable or tune it. Ignoring alerts (B) is dangerous. Waking everyone (C) is unsustainable. Alert tuning is essential (D).',
    tags: ['sre', 'on-call', 'alerting', 'alert-fatigue', 'incident-management'],
  },
  {
    topicSlug: 'sre',
    difficulty: 'EASY' as const,
    type: 'SCENARIO' as const,
    question: 'Your service depends on 5 microservices, each with 99% availability. What is the overall availability assuming all dependencies are critical (serial)?',
    options: [
      'Approximately 95% (0.99^5 = 0.95), because availability multiplies for serial dependencies',
      '99% because dependencies do not affect availability which is a fundamental architectural constraint',
      '100% because microservices are inherently reliable',
      'Availability cannot be calculated for microservices',
    ],
    correctIndex: 0,
    explanation: 'When services depend on each other serially (A calls B, B calls C, etc.), overall availability is the product of individual availabilities. Formula: Overall availability = A₁ × A₂ × A₃ × A₄ × A₅ = 0.99 × 0.99 × 0.99 × 0.99 × 0.99 = 0.99^5 ≈ 0.951 = 95.1%. This is the "weakest link" problem. Example: if any of the 5 services is down (5% chance per service), your service is down. Implications: (1) Dependencies reduce reliability: more dependencies = lower overall availability. (2) Redundancy helps: if services have fallbacks (cache, retries, circuit breakers), effective availability improves. (3) High dependency SLOs: if your service needs 99.9% SLO, dependencies must have 99.98% or higher. (4) Parallel dependencies: if A can function with either B or C (not both), availability is 1 - (1 - Aв)(1 - Ac) (better than serial). Dependencies DO affect availability (B). Microservices are not inherently 100% available (C). Availability is calculable (D). Understanding dependency math is critical for SRE architecture.',
    tags: ['sre', 'availability', 'dependencies', 'microservices', 'reliability', 'slo'],
  },

  // ─── MEDIUM THEORY ─────────────────────────────────────────────────────────
  {
    topicSlug: 'sre',
    difficulty: 'MEDIUM' as const,
    type: 'THEORY' as const,
    question: 'What is a blameless postmortem and why is it important for SRE culture?',
    options: [
      'A blameless postmortem focuses on understanding what went wrong (systems, processes) without blaming individuals, fostering psychological safety and continuous learning',
      'A blameless postmortem means no one is held accountable',
      'Postmortems are only conducted for customer-impacting incidents and this applies to all deployment scenarios and this applies to all deployment scenarios',
      'Blameless postmortems are optional',
    ],
    correctIndex: 0,
    explanation: `Blameless postmortem is a structured incident review that focuses on improving systems and processes, not punishing people. Principles: (1) Assume good intent: engineers made decisions with the information available at the time. (2) Focus on systems: "Why did the system allow this to happen?" not "Who caused this?" (3) Psychological safety: engineers should feel safe admitting mistakes and sharing learnings. (4) Learning culture: incidents are opportunities to improve, not failures. Postmortem structure: (1) Incident summary (what, when, duration, impact). (2) Timeline (sequence of events). (3) Root cause analysis (5 Whys, fishbone diagram). (4) Contributing factors (what made this possible?). (5) Action items (preventive measures, owner, deadline). (6) Lessons learned. Blameless does NOT mean no accountability (B) — action items have owners. Postmortems apply to all significant incidents (C), not just customer-facing. Postmortems are NOT optional (D) — they are mandatory in SRE culture. Blameless postmortems are key to Google's SRE philosophy.`,
    tags: ['sre', 'postmortem', 'blameless', 'incident-management', 'culture', 'learning'],
  },
  {
    topicSlug: 'sre',
    difficulty: 'MEDIUM' as const,
    type: 'THEORY' as const,
    question: 'What are multi-window, multi-burn-rate alerts and why are they better than static threshold alerts?',
    options: [
      'Multi-window alerts check error rate over multiple time windows (1h, 6h) and burn rates (how fast error budget is consumed), reducing false positives while catching real incidents early',
      'Multi-window alerts are more complex and should be avoided which is the standard recommended approach which is the standard recommended approach which is the standard recommended approach',
      'Multi-window alerts are only for large companies',
      'Static threshold alerts are always better',
    ],
    correctIndex: 0,
    explanation: `Static threshold alerts ("error rate > 5%") are noisy and slow to detect issues. Problems: (1) False positives: transient spikes (brief traffic surge, network blip) trigger alerts that self-resolve. (2) Slow detection: gradual degradation (error rate slowly rising from 1% to 4.9%) is not detected until it crosses threshold. Multi-window, multi-burn-rate alerting (introduced in Google's SRE Workbook) is more sophisticated. Concepts: (1) Error budget burn rate: how fast are you consuming error budget? 1x = burning at exactly SLO rate (will exhaust budget in 30 days). 10x = will exhaust budget in 3 days. (2) Multiple time windows: check burn rate over short window (1 hour) AND long window (6 hours). Alert if BOTH are elevated (reduces false positives from transient spikes). Example alert: "1-hour burn rate > 14.4x AND 6-hour burn rate > 6x" → page immediately. "6-hour burn rate > 3x AND 3-day burn rate > 1x" → ticket, no page. Multi-window alerts are NOT overly complex (B) — they are standard in modern SRE. They apply to all scales (C). Static alerts are inferior (D).`,
    tags: ['sre', 'alerting', 'burn-rate', 'multi-window', 'error-budget', 'slo'],
  },
  {
    topicSlug: 'sre',
    difficulty: 'MEDIUM' as const,
    type: 'THEORY' as const,
    question: 'What is chaos engineering and how does it improve reliability?',
    options: [
      'Chaos engineering is the practice of intentionally injecting failures (server crashes, network partitions) into production to test resilience and discover weaknesses before real incidents',
      'Chaos engineering is breaking production systems randomly which is the standard recommended approach which is the standard recommended approach which is the standard recommended approach',
      'Chaos engineering is only for testing environments',
      'Chaos engineering is deprecated and no longer used',
    ],
    correctIndex: 0,
    explanation: 'Chaos engineering (pioneered by Netflix with Chaos Monkey) validates system resilience by proactively introducing controlled failures. Principles: (1) Hypothesize steady state: define normal system behavior (SLIs within SLO range). (2) Vary real-world events: inject failures that could realistically occur (instance termination, network latency, dependency unavailability). (3) Run experiments in production: staging does not reflect prod traffic/complexity. (4) Minimize blast radius: start small (single instance, single region), expand gradually. (5) Automate experiments: run continuously, not one-off. Common experiments: (1) Chaos Monkey: randomly terminates instances. (2) Latency injection: add network delays to dependencies. (3) Failure injection: make dependencies return errors. (4) Resource exhaustion: limit CPU, memory, or disk. (5) Region failures: simulate entire AZ or region unavailability. Benefits: (1) Discover weaknesses before customers do. (2) Validate auto-healing, failover, retry logic. (3) Build confidence in resilience. Chaos is NOT random (B) — it is controlled. Chaos belongs in production (C) — that is the point. Chaos is actively used (D) by Netflix, Amazon, Google.',
    tags: ['sre', 'chaos-engineering', 'resilience', 'testing', 'chaos-monkey', 'reliability'],
  },
  {
    topicSlug: 'sre',
    difficulty: 'MEDIUM' as const,
    type: 'THEORY' as const,
    question: 'What is the incident management lifecycle (detection, triage, mitigation, resolution, postmortem)?',
    options: [
      'Detection: identify issue; Triage: assess severity; Mitigation: reduce impact; Resolution: fix root cause; Postmortem: learn and prevent recurrence',
      'Incident management is only about fixing bugs',
      'Detection and mitigation are the same',
      'Postmortems are optional if the incident was small as documented in the official best practices as documented in the official best practices',
    ],
    correctIndex: 0,
    explanation: 'SRE incident management follows a structured lifecycle: (1) Detection: monitoring/alerting identifies an anomaly (latency spike, error rate increase, customer reports). (2) Triage: on-call engineer assesses severity (P0 = production down, P1 = degraded, P2 = minor). Declares incident if severe. (3) Mitigation: reduce blast radius and restore service (not necessarily fixing root cause). Actions: roll back deployment, scale up resources, failover to backup, disable problematic feature. Goal: stop the bleeding. (4) Resolution: identify and fix root cause (bugfix, infrastructure change, configuration update). (5) Postmortem (follow-up): conduct blameless review, document timeline, identify contributing factors, create action items to prevent recurrence. Key roles during incident: (1) Incident Commander (IC): coordinates response, makes decisions. (2) Communications Lead: updates stakeholders, status page. (3) Operations Lead: executes mitigation/resolution. Incident management is NOT just bugfixes (B) — it includes operational issues. Detection ≠ mitigation (C). Postmortems are mandatory (D) for significant incidents.',
    tags: ['sre', 'incident-management', 'on-call', 'mitigation', 'postmortem', 'triage'],
  },
  {
    topicSlug: 'sre',
    difficulty: 'MEDIUM' as const,
    type: 'SCENARIO' as const,
    question: 'Your service has a 99.5% SLO (3.6 hours downtime/month). You are considering a risky feature that may cause 2 hours of downtime. Should you deploy it?',
    options: [
      'Check error budget: if > 2 hours remain, deploy; if < 2 hours, defer until budget resets or improve reliability first',
      'Always deploy immediately; features are more important than reliability as documented in the official best practices',
      'Never deploy risky features',
      'SLOs do not influence deployment decisions',
    ],
    correctIndex: 0,
    explanation: 'This scenario illustrates error budget-driven decision making. Analysis: Monthly error budget = 30 days × 24 hours = 720 hours × (1 - 0.995) = 720 × 0.005 = 3.6 hours. Risky feature may consume 2 hours (55% of budget). Decision framework: (1) Check current error budget: used 0.5 hours so far → 3.1 hours remaining. Deploying risks 2 hours → 1.1 hours would remain. Decision: deploy (within budget). (2) If budget already used 2 hours → only 1.6 hours remaining. Deploying risks 2 hours → would exceed budget. Decision: defer feature until next month or improve reliability first (fix bugs, add redundancy) to earn back budget. (3) Mitigation: use progressive rollout (canary deployment) to limit blast radius. Roll out to 5% → monitor → roll out to 100%. If issues arise, revert with minimal downtime. Deploying everything immediately (B) ignores reliability. Never deploying risky features (C) stagnates innovation. SLOs SHOULD drive decisions (D). Error budgets provide objective framework for risk/reward trade-offs.',
    tags: ['sre', 'error-budget', 'slo', 'risk-management', 'deployment', 'decision-making'],
  },
  {
    topicSlug: 'sre',
    difficulty: 'MEDIUM' as const,
    type: 'SCENARIO' as const,
    question: 'Your on-call engineer is paged at 3 AM for an incident. The service is degraded but not fully down. What is the first action?',
    options: [
      'Assess severity, declare incident if P0/P1, form incident response team (IC, comms, ops), prioritize mitigation over root cause analysis',
      'Immediately start debugging to find root cause',
      'Ignore it until morning if customers are not complaining which is a fundamental architectural constraint which is a fundamental architectural constraint',
      'Restart all servers',
    ],
    correctIndex: 0,
    explanation: 'Incident response follows a structured process. First actions: (1) Assess severity: check dashboards (error rate, latency, traffic). Is it P0 (production down), P1 (degraded, customer impact), or P2 (minor)? (2) Declare incident: if P0/P1, formally declare incident (Slack incident channel, PagerDuty incident, status page). (3) Form incident team: Page Incident Commander (coordinates), Communications Lead (updates stakeholders), Operations Lead (executes fixes). (4) Initial communication: notify stakeholders (engineering leadership, customer support, product managers). Update status page if customer-facing. (5) Triage: gather facts (what broke? when? what changed?). Check recent deployments, infrastructure changes. (6) Mitigation first, root cause later: prioritize restoring service (rollback, failover, scale up). Do NOT spend hours debugging root cause while customers are impacted. (7) Document timeline: record actions in incident log (for postmortem). Immediate debugging (B) delays mitigation. Ignoring degradation (C) violates SLOs. Restarting servers (D) may worsen issues without understanding cause.',
    tags: ['sre', 'incident-management', 'on-call', 'mitigation', 'incident-commander', 'response'],
  },
  {
    topicSlug: 'sre',
    difficulty: 'MEDIUM' as const,
    type: 'SCENARIO' as const,
    question: 'Your SLO is 99.9% success rate. You measure 99.95% actual success rate. Should you improve reliability further?',
    options: [
      'Not necessarily — exceeding SLO may mean over-investing in reliability; consider whether resources are better spent on features or other improvements',
      'Yes, always aim for 100% reliability',
      'No, never improve beyond SLO',
      'SLO performance does not influence investment decisions which is a fundamental architectural constraint which is a fundamental architectural constraint',
    ],
    correctIndex: 0,
    explanation: 'This is a critical SRE question about reliability investment trade-offs. Analysis: You are exceeding SLO (99.95% vs. 99.9% target). Considerations: (1) Opportunity cost: achieving 99.95% → 99.99% (4 nines) requires exponentially more effort (redundancy, complexity, cost) with diminishing returns. That effort could be spent on features, new products, or infrastructure scalability. (2) SLO calibration: if you consistently exceed SLO, your SLO may be too loose. Consider tightening it (99.9% → 99.95%) to reflect actual performance. (3) Customer expectations: are customers happy with 99.9%? If not, improving reliability (and adjusting SLO) may be justified. (4) Error budget: if you consistently have unused error budget, you can take more risks (faster deployments, experiments) without harming reliability. 100% reliability (B) is impossible and economically irrational. Not improving beyond SLO (C) is a dogmatic rule — context matters. SLO performance SHOULD influence investment (D). SRE is about balancing reliability and velocity, not maximizing reliability at all costs.',
    tags: ['sre', 'slo', 'reliability', 'investment', 'opportunity-cost', 'trade-offs'],
  },

  // ─── HARD THEORY ───────────────────────────────────────────────────────────
  {
    topicSlug: 'sre',
    difficulty: 'HARD' as const,
    type: 'THEORY' as const,
    question: 'What is cascading failure and how do you prevent it in distributed systems?',
    options: [
      'Cascading failure occurs when one component failure triggers failures in dependent components, spreading system-wide; prevent with circuit breakers, timeouts, rate limiting, and graceful degradation',
      'Cascading failures are inevitable and cannot be prevented which is a fundamental architectural constraint which is a fundamental architectural constraint which is a fundamental architectural constraint',
      'Cascading failures only happen in monolithic systems',
      'Cascading failures are caused by hardware, not software',
    ],
    correctIndex: 0,
    explanation: 'Cascading failure is a chain reaction where one failure triggers subsequent failures. Example: (1) Database becomes slow. (2) API requests to DB time out. (3) API servers hold connections waiting for DB, exhausting connection pools. (4) API servers become unresponsive, unable to handle new requests. (5) Load balancer marks API servers unhealthy, routes all traffic to remaining servers. (6) Remaining servers overload and crash. (7) Entire system is down. Prevention mechanisms: (1) Circuit breakers: detect failures in dependencies, stop calling them temporarily (fail fast), retry after cooldown. (2) Timeouts: enforce strict timeouts on all network calls (prevent waiting indefinitely). (3) Bulkheads: isolate resources (separate thread pools for different operations) so one failure does not exhaust all resources. (4) Rate limiting: throttle traffic during overload to prevent collapse. (5) Load shedding: reject low-priority requests during overload to preserve capacity for critical requests. (6) Graceful degradation: return cached/default responses when dependencies fail. Cascading failures CAN be prevented (B). They are more common in distributed systems (C). Software architecture is the primary cause (D).',
    tags: ['sre', 'cascading-failure', 'circuit-breaker', 'resilience', 'distributed-systems', 'reliability'],
  },
  {
    topicSlug: 'sre',
    difficulty: 'HARD' as const,
    type: 'THEORY' as const,
    question: 'What is the SRE Golden Signals framework and how does it differ from RED method?',
    options: [
      'Golden Signals: Latency, Traffic, Errors, Saturation (focuses on resource exhaustion); RED: Rate, Errors, Duration (focuses on request-driven services)',
      'Golden Signals and RED are the same',
      'Golden Signals is outdated',
      'RED is a replacement for Golden Signals which is the standard recommended approach which is the standard recommended approach which is the standard recommended approach',
    ],
    correctIndex: 0,
    explanation: `Google's SRE book introduced Golden Signals as four key metrics for monitoring: (1) Latency: time to service requests (p50, p95, p99). Distinguish successful vs. failed request latency (failed requests may be fast due to immediate rejection). (2) Traffic: measure of demand (requests/sec, transactions/sec, bandwidth). (3) Errors: rate of failed requests (HTTP 5xx, exceptions, incorrect responses). (4) Saturation: utilization of constrained resources (CPU, memory, disk, connections). Indicates impending failure (near capacity). When saturation is high, performance degrades. RED method (Rate, Errors, Duration) is a subset focused on request-driven services. Comparison: RED Rate = Golden Traffic; RED Errors = Golden Errors; RED Duration = Golden Latency. Golden Signals add Saturation, which is critical for capacity planning and predicting failures before they occur. Golden Signals are NOT the same as RED (B). Golden Signals are NOT outdated (C) — they are fundamental. RED does NOT replace Golden Signals (D) — it is complementary. Use Golden Signals for comprehensive monitoring, RED for request-driven service dashboards.`,
    tags: ['sre', 'golden-signals', 'red-method', 'monitoring', 'metrics', 'observability'],
  },
  {
    topicSlug: 'sre',
    difficulty: 'HARD' as const,
    type: 'THEORY' as const,
    question: 'What is the SRE "production readiness review" and what does it assess?',
    options: [
      'A production readiness review assesses whether a service is ready for production based on SLOs, monitoring, incident response, capacity planning, and operational maturity',
      'Production readiness review is a code review',
      'Production readiness review is only for new services and this applies to all deployment scenarios and this applies to all deployment scenarios and this applies to all deployment scenarios',
      'Production readiness review is a one-time checklist',
    ],
    correctIndex: 0,
    explanation: 'Production readiness review (PRR) is a structured assessment before launching a service or after significant changes. SRE teams evaluate: (1) Architecture: redundancy, fault tolerance, dependency management. (2) SLIs/SLOs: defined, measurable, realistic. (3) Monitoring: comprehensive metrics, logs, traces; dashboards covering Golden Signals. (4) Alerting: actionable alerts tied to SLOs; alert escalation policies. (5) Incident response: on-call rotation, runbooks, postmortem process. (6) Capacity planning: traffic forecasts, load testing results, auto-scaling configuration. (7) Disaster recovery: backups, recovery procedures, RTO/RPO defined. (8) Dependencies: resilience patterns (circuit breakers, timeouts, retries). (9) Security: authentication, authorization, secrets management, compliance. (10) Documentation: architecture diagrams, operational runbooks, troubleshooting guides. PRR is NOT a code review (B) — it is operational readiness. PRR applies to new AND existing services undergoing major changes (C). PRR is NOT one-time (D) — it should be revisited periodically. PRR ensures SRE teams can support services they inherit.',
    tags: ['sre', 'production-readiness', 'operational-maturity', 'launch', 'slo', 'monitoring'],
  },
  {
    topicSlug: 'sre',
    difficulty: 'HARD' as const,
    type: 'THEORY' as const,
    question: 'What is the difference between RTO (Recovery Time Objective) and RPO (Recovery Point Objective) in disaster recovery?',
    options: [
      'RTO: maximum acceptable downtime after a disaster; RPO: maximum acceptable data loss measured in time (e.g., last backup)',
      'RTO and RPO are the same thing',
      'RTO is for networks; RPO is for databases which is the standard recommended approach which is the standard recommended approach',
      'RTO is always longer than RPO',
    ],
    correctIndex: 0,
    explanation: 'RTO and RPO are critical disaster recovery metrics. Recovery Time Objective (RTO): maximum time to restore service after a failure. Example: "We must restore the database within 4 hours of a failure." RTO defines downtime tolerance. Lower RTO requires: active-active failover, hot standby replicas, automated recovery. Recovery Point Objective (RPO): maximum acceptable data loss measured in time. Example: "We can tolerate losing up to 1 hour of data." RPO defines backup frequency. RPO of 1 hour requires: backups every hour, continuous replication, transaction logs. Example scenario: Database crashes at 3 PM. Last backup was 2 PM. Recovery takes 3 hours (restored at 6 PM). RPO = 1 hour (lost data from 2 PM to 3 PM). RTO = 3 hours (downtime from 3 PM to 6 PM). Trade-offs: (1) RTO = 0, RPO = 0 (zero data loss, zero downtime) requires synchronous multi-region replication (expensive). (2) RTO = 24 hours, RPO = 24 hours (daily backups, manual restore) is cheap but high risk. RTO ≠ RPO (B). Both apply to all systems (C). RTO and RPO are independent (D).',
    tags: ['sre', 'rto', 'rpo', 'disaster-recovery', 'backup', 'business-continuity'],
  },
  {
    topicSlug: 'sre',
    difficulty: 'HARD' as const,
    type: 'SCENARIO' as const,
    question: 'Your service has three dependencies: A (99.9% SLO), B (99.5% SLO), C (99% SLO). You need 99.9% overall SLO. How do you achieve this?',
    options: [
      'Implement resilience patterns: retries, circuit breakers, fallbacks, caching; or remove hard dependencies (make B and C optional with graceful degradation)',
      'Replace B and C with higher-SLO services',
      'It is impossible to achieve 99.9% with those dependencies which is the standard recommended approach which is the standard recommended approach',
      'Ignore dependency SLOs',
    ],
    correctIndex: 0,
    explanation: 'Naive calculation: serial dependencies → overall SLO = 0.999 × 0.995 × 0.99 = 0.984 = 98.4% (does NOT meet 99.9% target). To achieve higher availability than dependencies, implement resilience patterns: (1) Retries with exponential backoff: transient failures become successes (improves effective SLO). (2) Circuit breakers: fail fast during dependency outage, prevent cascading failure (isolates failure domain). (3) Fallbacks: return cached/default data when dependency fails. Example: if recommendation service (C) fails, return generic recommendations. (4) Graceful degradation: make dependencies optional. Core functionality works without B and C (reduced features but not failure). (5) Redundancy: if dependency C has two implementations (C1, C2), parallel call both, use first response (increases availability). (6) Caching: reduce dependency calls (cached responses have 100% availability). (7) Request hedging: send request to multiple backends, use fastest response. Replacing dependencies (B) may not be feasible. Achieving higher availability than dependencies IS possible with resilience patterns (C). Dependency SLOs matter (D). This tests deep understanding of reliability engineering.',
    tags: ['sre', 'dependencies', 'resilience', 'circuit-breaker', 'graceful-degradation', 'slo'],
  },
  {
    topicSlug: 'sre',
    difficulty: 'HARD' as const,
    type: 'SCENARIO' as const,
    question: 'During a major incident, your Incident Commander is overwhelmed and making slow decisions. What SRE principle applies here?',
    options: [
      'Incident Commander should delegate responsibilities (ops, comms, scribe) and focus on coordination, not hands-on mitigation; or hand off IC role if overwhelmed',
      'The IC should handle everything alone',
      'Cancel the incident response',
      'Incident Commander is not an SRE concept which is a fundamental architectural constraint which is a fundamental architectural constraint which is a fundamental architectural constraint',
    ],
    correctIndex: 0,
    explanation: `This scenario tests understanding of incident command structure (based on Incident Command System used by firefighters, adapted for SRE). Key principle: Incident Commander (IC) coordinates but does NOT execute. IC responsibilities: (1) Assess situation, declare incident severity. (2) Assign roles: Operations Lead (executes mitigation), Communications Lead (stakeholder updates), Scribe (documents timeline). (3) Make strategic decisions (rollback vs. forward fix, escalate vs. resolve). (4) Ensure information flows (status updates, handoffs). (5) Call for additional resources (page more engineers, loop in experts). IC should NOT: (1) Debug code or run commands (that is Ops Lead's job). (2) Write status updates (that is Comms Lead's job). (3) Take notes (that is Scribe's job). If IC is overwhelmed: (1) Explicitly hand off IC role to another engineer. (2) IC becomes Ops Lead or steps back entirely. Anti-pattern: single engineer as IC + Ops + Comms → context switching, slow decisions, missed updates. IC should NOT work alone (B). Canceling response (C) is absurd. IC is a core SRE concept (D) from Google's incident management framework.`,
    tags: ['sre', 'incident-commander', 'incident-management', 'coordination', 'delegation', 'on-call'],
  },
  {
    topicSlug: 'sre',
    difficulty: 'HARD' as const,
    type: 'SCENARIO' as const,
    question: 'Your error budget policy states: "If error budget is exhausted, freeze all feature launches until budget resets." Product team wants to ship a critical revenue-generating feature mid-month after budget is exhausted. What do you do?',
    options: [
      'Hold firm on error budget policy (it exists for this reason), or negotiate: ship feature with strict rollback plan and reduced blast radius (canary), accepting the risk',
      'Always follow the product team; error budget is just a guideline as documented in the official best practices as documented in the official best practices',
      'Refuse the feature launch without exception',
      'Error budget policies are not enforceable',
    ],
    correctIndex: 0,
    explanation: `This scenario tests error budget governance. Error budget policy is an agreement between SRE and product teams, negotiated upfront. It should be followed consistently to maintain trust and balance reliability/velocity. Options: (1) Hold the line: "We agreed on the error budget policy. We exhausted the budget due to recent outages. We need to focus on reliability before launching new features." This is the correct default response. (2) Negotiate exception: if the feature is genuinely critical (major revenue impact, contractual obligation), discuss risk mitigation: (a) Progressive rollout (canary 1% → 5% → 10%, monitor closely, instant rollback). (b) Feature flags (enable for limited users, quick disable if issues). (c) Dedicated on-call resources during rollout. (d) Incident budget: accept that this launch may consume additional error budget, pushing next month's budget into deficit. (3) Escalate: involve leadership (VP Engineering, CTO) to make the final call, documenting the risk. Always following product (B) makes error budget meaningless. Never allowing exceptions (C) is too rigid. Error budget policies ARE enforceable (D) — that is their purpose. This tests real-world SRE leadership and negotiation.`,
    tags: ['sre', 'error-budget', 'policy', 'governance', 'negotiation', 'feature-launch', 'trade-offs'],
  },
  {
    topicSlug: 'sre',
    difficulty: 'HARD' as const,
    type: 'SCENARIO' as const,
    question: 'Your postmortem reveals that an incident was caused by a bad deployment. The action item is "implement canary deployments." Who owns this action item: SRE or product team?',
    options: [
      'It depends on team structure and toil budget; typically SRE builds tooling/process, product team adopts it; ownership should be explicit with deadline',
      'Always SRE',
      'Always product team',
      'Action items do not need owners which is a fundamental architectural constraint which is a fundamental architectural constraint which is a fundamental architectural constraint',
    ],
    correctIndex: 0,
    explanation: 'This tests understanding of SRE ownership boundaries. Action item ownership depends on: (1) SRE toil budget: if SRE is at 50% toil, they cannot take on large projects. Action item may be assigned to platform engineering or product team. (2) Skill set: implementing canary deployments requires CI/CD expertise. If SRE has strong CI/CD skills, they own it. If product team owns their deployment pipeline, they own it. (3) Scope: "build a generic canary framework" is SRE platform work. "Adopt existing canary framework for this service" is product team work. Best practice: (1) Explicitly assign owner in postmortem (no ambiguity). (2) Set deadline (within 1 month, 1 quarter). (3) Track action items in a centralized system (Jira, Asana). (4) Review action item completion in postmortem follow-ups. Anti-pattern: action items with no owner or deadline → nothing gets done → same incident recurs. SRE does NOT automatically own all operational improvements (B). Product teams own their services and should implement reliability improvements (C). Action items MUST have owners (D) — accountability is critical. This tests practical incident follow-through.',
    tags: ['sre', 'postmortem', 'action-items', 'ownership', 'accountability', 'canary-deployment'],
  },

  // ─── ADDITIONAL SRE QUESTIONS ────────────────────────────────────────────────
  {
    topicSlug: 'sre',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What is the difference between SLI, SLO, and SLA?',
    options: [
      'SLI is the metric (latency, availability), SLO is the internal target (99.9%), SLA is the external contract with customers that includes consequences for breach',
      'They are all the same thing',
      'SLA is an internal metric while SLO is external which is the standard recommended approach which is the standard recommended approach which is the standard recommended approach',
      'SLI is only for backend services',
    ],
    correctIndex: 0,
    explanation: 'SLI (Service Level Indicator): the actual measurement of a service property. Examples: latency (p99 response time), availability (% of successful requests), throughput (requests per second), error rate. SLO (Service Level Objective): internal target for an SLI. Example: "99.9% of requests should complete in under 200ms." SLOs balance reliability with feature velocity. Not externally promised. SLA (Service Level Agreement): external contract with customers that specifies service levels and consequences (refunds, credits) for breaches. SLAs should be less strict than SLOs (buffer for safety). Example: SLA promises 99.9% availability; SLO targets 99.95% to maintain buffer. Relationship: SLI measures → SLO targets → SLA promises. SRE uses SLIs and SLOs for internal reliability management. SLAs are business/legal commitments. They are different (B). SLO is internal, SLA is external (C). SLIs apply to any measurable service property (D).',
    tags: ['sre', 'sli', 'slo', 'sla', 'reliability', 'metrics'],
  },
  {
    topicSlug: 'sre',
    difficulty: 'MEDIUM' as const,
    type: 'THEORY' as const,
    question: 'What is toil in SRE and why is reducing it important?',
    options: [
      'Toil is manual, repetitive operational work that scales with service size and provides no lasting value; reducing toil frees SREs for engineering work that improves reliability',
      'Toil is any work that SREs do',
      'Toil elimination is not a priority',
      'Toil always requires human intervention as documented in the official best practices as documented in the official best practices as documented in the official best practices',
    ],
    correctIndex: 0,
    explanation: 'Toil (Google SRE definition): work that is (1) Manual: requires human intervention. (2) Repetitive: done repeatedly, not one-time. (3) Automatable: could be scripted or eliminated. (4) Reactive: interrupt-driven, not proactive. (5) No enduring value: fixing symptoms, not root causes. (6) Scales with service: more traffic = more toil. Examples of toil: (1) Manually restarting crashed services. (2) Copying logs from servers for debugging. (3) Responding to identical alerts repeatedly. (4) Manual deployments. (5) Provisioning resources by hand. Google SRE target: keep toil below 50% of SRE time. The other 50%+ should be engineering: automation, tooling, reliability improvements. Why reduce toil: (1) Burnout: repetitive work is demoralizing. (2) Scalability: toil does not scale; engineering does. (3) Career growth: SREs should be engineers, not operators. Automation strategies: (1) Self-healing systems. (2) CI/CD automation. (3) Alert tuning (fewer false positives). Not all work is toil (B). Toil reduction is core SRE (C). Toil CAN be automated (D).',
    tags: ['sre', 'toil', 'automation', 'engineering', 'operational-work'],
  },
  {
    topicSlug: 'sre',
    difficulty: 'MEDIUM' as const,
    type: 'SCENARIO' as const,
    question: 'You receive an alert at 3 AM that says "Disk usage above 80%." After investigation, you find the disk has been at 81% for weeks and will not fill for months. What is wrong with this alert?',
    options: [
      'The alert threshold is too sensitive; it should alert on rate of change or time-to-exhaustion rather than a static threshold, and it should be actionable',
      'Nothing is wrong; 80% is a good threshold which is a fundamental architectural constraint which is a fundamental architectural constraint which is a fundamental architectural constraint',
      'Alerts should never fire at night',
      'Disk alerts are not important',
    ],
    correctIndex: 0,
    explanation: 'This is a classic example of a non-actionable alert causing alert fatigue. Problems: (1) Static threshold: 80% might be normal for months-old data. (2) No urgency: disk will not fill for months, but engineer was woken at 3 AM. (3) Not actionable: what can the engineer do at 3 AM? Nothing urgent. Good alerting principles: (1) Alert on symptoms, not causes: "disk will be full in 4 hours" vs "disk is 80% full." (2) Predict exhaustion: alert when time-to-exhaustion < 4 hours (linear extrapolation). (3) Two-tier alerts: warning at 7 days (ticket), page at 4 hours (wake someone). (4) Actionable: every page should require immediate human action. (5) Low false positive rate: if alert fires and no action is needed, fix the alert. Alert fatigue consequence: if on-call engineers receive many non-urgent alerts, they start ignoring alerts, missing real incidents. 80% is arbitrary (B). Night alerts should be reserved for emergencies (C). Disk alerts matter when disk will actually fill soon (D).',
    tags: ['sre', 'alerting', 'alert-fatigue', 'monitoring', 'on-call', 'actionable-alerts'],
  },
  {
    topicSlug: 'sre',
    difficulty: 'HARD' as const,
    type: 'THEORY' as const,
    question: 'What is chaos engineering and how does it differ from traditional testing?',
    options: [
      'Chaos engineering proactively injects failures in production or production-like environments to discover weaknesses before they cause outages; traditional testing validates known requirements',
      'Chaos engineering is uncontrolled system destruction which is the standard recommended approach which is the standard recommended approach which is the standard recommended approach',
      'Chaos engineering replaces unit tests',
      'Chaos engineering is only for Netflix',
    ],
    correctIndex: 0,
    explanation: 'Chaos engineering (pioneered by Netflix Chaos Monkey): the discipline of experimenting on systems to build confidence in their ability to withstand turbulent conditions. Traditional testing: validates known requirements against expected behavior. "Does feature X work as specified?" You know what you are testing. Chaos engineering: explores unknown failure modes. "What happens when service Y becomes slow?" You discover what breaks. Principles: (1) Start with a hypothesis: "If we kill 10% of API pods, latency should remain below 200ms due to autoscaling." (2) Minimize blast radius: start small (single instance, low traffic), expand gradually. (3) Run in production (or production-like): staging environments hide real-world complexity. (4) Automate: continuous chaos experiments (not just one-off tests). Tools: (1) Chaos Monkey: randomly terminates instances. (2) Litmus Chaos: Kubernetes-native chaos experiments. (3) Gremlin: commercial chaos platform. (4) AWS Fault Injection Simulator: inject faults in AWS resources. Chaos engineering is controlled experimentation (B). It complements unit tests (C). It is industry-wide now (D).',
    tags: ['sre', 'chaos-engineering', 'resilience', 'testing', 'fault-injection', 'netflix'],
  },
  {
    topicSlug: 'sre',
    difficulty: 'MEDIUM' as const,
    type: 'THEORY' as const,
    question: 'What is a runbook and what should it contain?',
    options: [
      'A runbook is a documented procedure for handling operational tasks or incidents, containing steps to diagnose, mitigate, and resolve issues with clear decision trees',
      'Runbooks are only for new engineers and this applies to all deployment scenarios and this applies to all deployment scenarios and this applies to all deployment scenarios',
      'Runbooks should contain code only',
      'Runbooks are obsolete in modern SRE',
    ],
    correctIndex: 0,
    explanation: 'Runbooks are operational documentation for handling alerts, incidents, and routine tasks. Contents: (1) Purpose: what this runbook addresses (alert name, symptom). (2) Severity assessment: how to determine impact and urgency. (3) Diagnostic steps: commands to run, logs to check, metrics to review. (4) Mitigation steps: how to restore service (restart, rollback, scale up, failover). (5) Decision trees: if X, do Y; if not, do Z. (6) Escalation: when to page additional help, who to contact. (7) Post-incident: cleanup steps, follow-up actions. (8) Links: dashboards, related runbooks, architecture diagrams. Best practices: (1) Keep runbooks in version control (Git). (2) Link runbooks to alerts (alert annotation includes runbook URL). (3) Update after incidents (if runbook was incomplete, improve it). (4) Automate where possible (runbook becomes automation script). Runbooks are for everyone, especially during 3 AM incidents (B). They contain procedures, not just code (C). Runbooks remain essential (D) — even with automation, humans need context.',
    tags: ['sre', 'runbook', 'documentation', 'incident-response', 'on-call', 'operations'],
  },
  {
    topicSlug: 'sre',
    difficulty: 'EASY' as const,
    type: 'THEORY' as const,
    question: 'What is the purpose of a blameless postmortem?',
    options: [
      'To understand what happened and prevent recurrence without assigning personal blame, focusing on systemic improvements rather than individual fault',
      'To identify and punish the person who caused the incident which is the standard recommended approach which is the standard recommended approach',
      'Postmortems are optional after incidents',
      'Blameless means no action items are assigned',
    ],
    correctIndex: 0,
    explanation: 'Blameless postmortems (root cause analysis): Principle: humans make mistakes; systems should prevent those mistakes from causing outages. Focus on WHY the system allowed the failure, not WHO made the error. Goals: (1) Understand the incident timeline (what happened, when). (2) Identify root causes (not just symptoms). (3) Develop action items to prevent recurrence. (4) Share learnings across the organization. Why blameless matters: (1) Psychological safety: engineers report issues honestly without fear of punishment. (2) Root cause discovery: if engineers hide details to avoid blame, you cannot find true causes. (3) Culture: blame culture leads to cover-ups and repeated incidents. Postmortem contents: (1) Summary. (2) Impact (duration, affected users, revenue impact). (3) Timeline (minute-by-minute events). (4) Root cause analysis (contributing factors). (5) What went well (detection, response). (6) What went poorly. (7) Action items (with owners and deadlines). Punishing individuals (B) is counterproductive. Postmortems are essential (C). Blameless still has action items (D).',
    tags: ['sre', 'postmortem', 'blameless', 'incident-response', 'root-cause', 'culture'],
  },
];
