export const topics = [
  {
    slug: \'linux-shell\',
    title: \'Linux & Shell Scripting\',
    description: \'Master Linux fundamentals, shell scripting, process management, and system administration skills essential for any DevOps role.',
    icon: '🐧',
    category: \'DEVOPS\' as const,
  },
  {
    slug: \'networking\',
    title: \'Networking Fundamentals\',
    description: \'Deep dive into OSI model, TCP/IP, DNS, load balancing, VPNs, and network troubleshooting at scale.',
    icon: '🌐',
    category: \'DEVOPS\' as const,
  },
  {
    slug: \'aws-core\',
    title: \'AWS Core Services\',
    description: \'Comprehensive coverage of EC2, S3, VPC, and IAM — the four pillars of AWS infrastructure.',
    icon: '☁️',
    category: \'AWS\' as const,
  },
  {
    slug: \'aws-advanced\',
    title: \'AWS Advanced Services\',
    description: \'Advanced AWS services including RDS, EKS, Lambda, and CloudFront for production workloads.',
    icon: '⚡',
    category: \'AWS\' as const,
  },
  {
    slug: \'docker\',
    title: \'Docker & Containerization\',
    description: \'Everything from Dockerfile best practices to container runtime internals, namespaces, and cgroups.',
    icon: '🐳',
    category: \'CONTAINERS\' as const,
  },
  {
    slug: \'kubernetes\',
    title: \'Kubernetes\',
    description: \'From pods and deployments to custom operators, admission webhooks, and multi-cluster federation.',
    icon: '☸️',
    category: \'CONTAINERS\' as const,
  },
  {
    slug: \'cicd\',
    title: \'CI/CD Pipelines\',
    description: \'Git branching strategies, GitHub Actions, blue-green deployments, GitOps, and compliance gates.',
    icon: '🔄',
    category: \'CICD\' as const,
  },
  {
    slug: \'iac-terraform\',
    title: \'Infrastructure as Code (Terraform)',
    description: \'Terraform from basics to advanced module composition, state management, and provider development.',
    icon: '🏗️',
    category: \'IaC\' as const,
  },
  {
    slug: \'observability\',
    title: \'Observability & Monitoring\',
    description: \'Metrics, logs, traces — Prometheus, Grafana, ELK, distributed tracing, and OpenTelemetry.',
    icon: '📡',
    category: \'OBSERVABILITY\' as const,
  },
  {
    slug: \'sre\',
    title: \'Site Reliability Engineering\',
    description: \'SLIs, SLOs, error budgets, incident management, blameless postmortems, and chaos engineering.',
    icon: '🔧',
    category: \'SRE\' as const,
  },
  {
    slug: \'security\',
    title: \'Security & Compliance\',
    description: \'Least privilege, GuardDuty, secrets management, zero-trust networking, and container runtime security.',
    icon: '🔒',
    category: \'DEVOPS\' as const,
  },
  {
    slug: \'finops\',
    title: \'Cost Optimization & FinOps\',
    description: \'Right-sizing, Savings Plans, spot fleets, tagging strategies, and multi-account FinOps at scale.',
    icon: '💰',
    category: \'AWS\' as const,
  },
];
